from pathlib import Path
from collections import defaultdict, Counter
from datetime import datetime, timezone
import json, re, hashlib

W=Path(__file__).parent
ROOT=W.parents[3]
BASE=ROOT/'_commentary/v16/out/s107/images.r13.map3.nohft.tool.tool/images.md'
OUT=ROOT/'enrichment/v1/out/107/107_enriched.md'
matrix=json.loads((W/'evidence_matrix.json').read_text())
assert matrix['stage']=='substantive_evidence_matrix_complete_before_composition'
assert matrix['annotations_composed'] is False
assert hashlib.sha256((W/'evidence_matrix.json').read_bytes()).hexdigest()==(W/'evidence_matrix.precomposition.sha256').read_text().strip()
slots=defaultdict(list)
enums=set('type tradition role relation status confidence historicity hadith_grade connection classical_attestation priority audience canonical'.split())
core='TAB107|KATH107|SUY107|KASH107|RAZI107|BAY107|BIQ107|QURT107'
corpus='Taberî, İbn Kesîr, Süyûtî, Zemahşerî, Beyzâvî, Bikâî, Kurtubî: 107:1–7 sayfalarında görüntülenen bütün açıklama gövdeleri ve bu sayfalardaki sûre girişleri; Râzî: 107:1 mesele 1–4, 107:2–3 yetim/teşvik açıklamaları, 107:4–5 aynı üç meselelik gövde, 107:6 riya açıklaması, 107:7 maûn vecihleri. Boş/tekrarlı gövdeler ayrıca kaydedildi; bütün ciltler taranmadı.'

def add(b,key,t,prose,source,ayah='107:1-7',tradition='project',role='clarification',relation='methodological',status='interpretive',priority='extended',audience='advanced',**kw):
    d=dict(id='S107-'+key,type=t,tradition=tradition,ayah=ayah,role=role,relation=relation,status=status,priority=priority,audience=audience,prose=prose,source=source)
    d.update(kw)
    assert '\n' not in prose
    slots[b].append(d)

novelty_map=[]
def nov(b,n,prose,attest,extra,source,covered,ayah='107:1-7',relation='lexical'):
    key=f'NOV-{n:03}'
    add(b,key,'novelty',prose,core+('|' + source if source else ''),ayah=ayah,role='novelty_assessment',relation=relation,classical_attestation=attest,checked_sources=corpus+' Ayrıca gerçekten incelenen pasajlar: '+extra,confidence='medium',priority='research',audience='research',connection='resonant')
    novelty_map.append(dict(id='S107-'+key,base_blocks=covered,classical_attestation=attest,checked_corpus=corpus,additional_checked_passages=extra,scope_limit='Only the listed displayed passages/root entries; not exhaustive entire works.'))

# Opening, interpretation, historical uncertainty and verified reading.
add(2,'TAF-001','tafsir','Zemahşerî bu soruyu dinini yalanlayanın işini hayretle önümüze koyan bir çağrı olarak okur. Râzî, hitabın Peygambere veya böyle bir kişiyi görebilecek her akıllı insana yönelmesi ihtimallerini ayırır. Bikâî ise söylenmemiş ikinci nesneyi, o kişinin nasıl bir karşılık göreceğini düşündüren bir soru olarak açıklar. Dolayısıyla bakış, gözün gördüğünü saymakla kalmaz; davranışın neyi gösterdiğini kavramaya çağırır. Bu, klasik açıklamadır; sonraki ayna ağı ayrıca bir yorum katmanıdır.','KASH107|RAZI107|BIQ107',ayah='107:1',tradition='dirayet',role='anchor',relation='direct_tafsir',status='explicit',priority='core',audience='general',source_ref='Zemahşerî 107:1; Râzî 107:1 ikinci mesele; Bikâî 107:1 iki meful açıklaması')
add(2,'TAF-002','tafsir','Başlangıçtaki dîn için tek bir klasik açıklama yoktur. Taberî kendi açıklamasında yapılanların karşılığını ve bu karşılıktan doğan emir-yasak yükümlülüğünü öne çıkarır; İbn Abbas’tan Allahın hükmü, İbn Cüreyc’den hesap anlamını aktarır. İbn Kesîr diriliş ve karşılık der. Râzî ve Beyzâvî, İslâm/din anlamını da mümkün saymakla birlikte hesap-karşılık yönünü korur. Aşağıdaki borç ve boyun eğiş imgeleri bu aralığa bağlanabilir; ayetteki kelimeyi yalnız parasal borca çeviremez.','TAB107|KATH107|RAZI107|BAY107',ayah='107:1',tradition='rivayet',role='semantic_range',relation='direct_tafsir',status='reported',priority='core',audience='general',transmitter='İbn Abbas; İbn Cüreyc',source_ref='Taberî 107:1; İbn Kesîr 107:1; Râzî 107:1 dördüncü mesele; Beyzâvî 107:1')
add(2,'REV-001','revelation_history','Sûrenin Mekkî veya Medenî sayılması üzerinde aktarımlar ayrılır. Kurtubî, Mekkî diyenler yanında İbn Abbas’a nispet edilen ikinci görüşü ve Katâde’nin Medenî görüşünü kaydeder. Âlûsî, Mekkî görüşün çoğunluğa ait olduğunu söyler; ayrıca yarısının Mekke’de Âs b. Vâil, yarısının Medine’de Abdullah b. Übey hakkında indiği iddiasını Hibetu’llah’a nispet eder. İncelenen bu pasaj, yarıları belirli ayet numaralarıyla ayırmaz. İki toplumsal sahne bulunduğundan kesin bir ilk üç/son dört ayet kronolojisi veya mutlak nüzul tarihi çıkarılmadı.','QURT107|ALUS107|KATH107|SUY107',tradition='historical',role='chronology',relation='historical',status='disputed',historicity='contested',priority='core',audience='general',source_ref='Kurtubî 107:1 sûre girişi; Âlûsî 107:1 sûre girişi; İbn Kesîr/Süyûtî 107:1 girişleri')
add(2,'ASB-001','asbab','Vâhidî, ilk ayetler için Mukātil ve Kelbî’den Âs b. Vâil adını aktarır; İbn Cüreyc’den ise Ebû Süfyân’ın yemek isteyen yetimi sopayla itmesi anlatısını verir. Kurtubî, Râzî ve Beyzâvî başka isimler de kaydeder: Ebû Cehil, Velîd b. Muğîre ve bir münafık ihtimalleri aynı değildir. Bunlar tek olayın bağımsız tanıkları gibi birleştirilemez. Özellikle adlandırılan kişiler ve olay ayrıntıları için ayrı isnad incelemesi yapılmadığından, metnin genel davranış tipini bu isimlerden birine kesinlikle kapatmak doğru değildir.','WAH107|QURT107|RAZI107|BAY107',ayah='107:1-3',tradition='rivayet',role='asbab_context',relation='asbab',status='reported',historicity='uncertain',hadith_grade='not_assessed',priority='extended',audience='general',source_ref='Vâhidî 107:1–2; Râzî 107:1 üçüncü mesele; Kurtubî 107:1–2; Beyzâvî 107:2')
add(2,'SRC-001','source_note','Ebû Süfyân anlatısının ayrıntıları bile aynı biçimde korunmamıştır: Vâhidî’nin görüntülenen pasajında haftalık iki deve, Kurtubî’nin ilk ayet açıklamasında bir deve geçer. Bu farkı çözmeden kesilen hayvan sayısını tarihî veri olarak kullanmadım. Süyûtî’nin İbn Merdûye’den aktardığı Mekkîlik haberleri de özgün İbn Merdûye nüshasıyla kontrol edilmiş bağımsız deliller değildir. Nüzul yeri, ayetin hedeflediği insan tipi ve rivayet edilen özel sebep ayrı sorulardır.','WAH107|QURT107|SUY107',ayah='107:1-3',role='source_criticism',relation='historical',status='disputed',historicity='uncertain',priority='research',audience='research')
add(2,'QIR-001','qiraat','Başlangıçtaki eraeyte’nin kök hemzesini düşürme yalnız kaynağı belirsiz bir okuma notu değildir. Ebû Şâme’nin Şâtıbiyye’nin 638. beytine açıklaması, soru hemzesinden sonra gelen bu kalıpta Kisâî’nin kök hemzesini düşürdüğünü, Nâfiʿ’in ise kolaylaştırdığını açıkça kaydeder; Âlûsî de 107:1 için Kisâî’yi adlandırır. Buradaki değişiklik görme/haber sorma işlevini değiştirmez. Zemahşerî’nin dil bakımından tercih etmediği hemze düşürme ile kanonik okuyucunun aktarımı aynı değerlendirme değildir.','SHAMA638|ALUS107|KASH107',ayah='107:1',tradition='dirayet',role='clarification',relation='grammatical',status='explicit',canonical='true',priority='research',audience='research',source_ref='Ebû Şâme, İbrâz, Şâtıbiyye 638 beytinin açıklaması; Âlûsî/Zemahşerî 107:1')
add(2,'RDR-001','reader_note','Bu metinde ana paragrafların sözlük imgeleri korunuyor. Ek katmanlarda ayetin bağlamdaki anlamı, tefsirde aktarılan alternatif, hadisle kurulan tema, sözlük ailesinin imgesi ve projenin bunları birleştiren yorumu ayrı işaretleniyor. Bir imgeyi okurken ilk soru şudur: Bu kelimenin burada söylediği mi, aynı ailedeki başka kullanımdan duyulan bir benzerlik mi? İkisi değerli olabilir; delil dereceleri aynı değildir.','PACK107|MAQ|TAB107',role='reader_orientation',priority='core',audience='general')
add(3,'TAF-003','tafsir','Karşılıklı gösterişin klasik bir öncülü vardır. Zemahşerî, müfâale kalıbını şöyle açıklar: kişi amelini gösterir; bakanlar da beğenilerini ve övgülerini ona gösterir. Râzî, Beyzâvî ve Bikâî bu karşılıklı alışverişi sürdürür. Taberî’nin rivayet ağırlıklı açıklaması ise insanlara İslâm görünüşü sunup içte onu taşımayan münafıklara odaklanır. Ayna kelimesi ayette bulunmaz; karşılıklı gösterme/övgü yorumu ise yalnız projenin bulduğu bir bağ değildir.','KASH107|RAZI107|BAY107|BIQ107|TAB107',ayah='107:6',tradition='dirayet',role='early_attestation',relation='direct_tafsir',status='explicit',priority='core',audience='general',source_ref='Zemahşerî/Râzî/Beyzâvî/Bikâî 107:6; Taberî 107:6')
add(3,'HAD-001','hadith','Müslim’de Ebû Hüreyre’den gelen kudsî hadiste Allah, kendisiyle birlikte başkasının payı gözetilerek yapılan ameli bırakacağını bildirir. Bu sahih rivayet 107:6’nın açık bir açıklaması olarak sunulmaz; amelin kime yöneltildiğini sınayan güçlü bir tematik delildir. Bakışın başka gözlere çevrilmesi imgesini, yalnız görünüşün hoş olmasına değil amelin maksadına bağlar.','MUS2985',ayah='107:6',tradition='hadith',role='corroboration',relation='thematic',status='explicit',hadith_grade='sahih',connection='strong',priority='core',audience='general',transmitter='Ebû Hüreyre',source_ref='Sahîh Muslim 2985')
add(3,'HAD-002','hadith','Müslim’in İbn Abbas rivayeti, kendini duyurmak ve gösteriş yapmak isteyenin Allah tarafından açığa çıkarılacağını söyler. Burada göstermek fiili ile karşılığının birlikte dönmesi, sûredeki seyirci arama temasını aydınlatır. Hadis, ayna veya sûrenin ilk kelimesiyle sonu arasında kurulmuş bir yapı bildirmez; ayetin doğrudan tefsiri olarak değil aynı ahlâkî yönün sahih tanığı olarak kullanılıyor.','MUS2986',ayah='107:6',tradition='hadith',role='corroboration',relation='thematic',status='explicit',hadith_grade='sahih',connection='strong',priority='extended',audience='general',transmitter='İbn Abbas',source_ref='Sahîh Muslim 2986')
add(3,'MTH-001','method_note','Sûrenin “kapandığı” cümlesindeki 107:6, kullanılan yedi ayetlik metnin son ayeti değildir: son söz 107:7’de maûnu esirgemedir. Bu nedenle görme-yuraun bağı bir çerçeve önerisi olarak okunabilir; son ayetin küçük yardımı fiilen kapatması da çerçevede kalmalıdır. Ana cümle değiştirilmedi; lafız ile bu anlatım arasındaki fark burada açık tutuluyor.','QURAN|TAB107|BIQ107',ayah='107:6-7',role='constraint',relation='structural',status='explicit',priority='core',audience='general')
add(4,'MTH-002','method_note','Kök akrabalığı ile bağlamdaki anlam arasında basamak vardır. Meselâ aynı sözlük maddesinde ayna bulunması, yuraunun ayna demek olduğunu göstermez. Daha kuvvetlisi, Maqāyîs bazen aynı harfler altında iki ayrı asıl yahut asıl dışı bir dal verir. Aşağıda ateş/namaz ve sehve/sahunun örneklerinde bu kayıtlar ayrıca belirtiliyor. İmge, köken hakkında kesin hüküm veya ayetin saklı sözlük çevirisi hâline gelmemelidir.','MAQ|RAGHIB|PACK107',role='methodological_note',relation='lexical',status='explicit',priority='core',audience='general')
nov(5,1,'Görmeye çağıran açılış ile görünmek isteyen kişiyi karşılaştırmanın parçaları eskidir: eraeytenin dikkat/hayret işlevi, riya kalıbındaki karşılıklı övgü ve sözlükte ayna. Bikâî ayrıca sonun başa dönmesini açıkça söyler. Fakat gerçek bakış/aranan bakış/ayna biçimindeki bu tam çerçeve, burada adı ve kapsamı verilen bölümlerde açık kurulmuş olarak bulunmadı. Eski yapıtaşları ve kısmî nazm öncülüyle hazırlanmış proje sentezidir; bütün klasik literatürde yokluk hükmü değildir.','partial','Maqāyîs رأي bütün madde; Râgıb رأي görüntülenen bütün madde; Bikâî 107:7 sonun başa dönmesi paragrafı.','MAQ|RAGHIB',[2,3,4,5],relation='structural')
add(6,'NZM-001','nazm','Yetimden namaza geçişin ahlâkî mantığını Râzî önceden kurar: ilk iki sosyal fiil, yaratılmışlara merhametin eksikliğini; sonraki namaz tavrı, Yaratana yönelişin bozulmasını gösterir. 107:3’te kötü işi yapmak ile iyiye yöneltmeyi bırakmak da ayrılır. Bikâî’nin fe açıklaması gizli inkârın bu işlerle açığa çıkmasını vurgular. Böylece görünen işlerden birbirine geçiş salt kelime avı değil, klasik nazmın tanıdığı bir düşünce sırasıdır.','RAZI107|BIQ107',ayah='107:2-7',tradition='nazm',role='nazm',relation='structural',status='explicit',priority='core',audience='general',source_ref='Râzî 107:3 birinci mesele, 107:4–5 birinci mesele; Bikâî 107:2–4')
nov(6,2,'Yetimin kapısından namazın seyircisine ve esirgenen nesneye ilerleyen göz güzergâhı projenin mekânsal anlatımıdır. Fe ile inkârın görünür davranışa bağlanması, yaratılmış/Yaratan hakları sırası ve yapılmayan kolay teşvikin önemi incelenen Râzî/Bikâî pasajlarında açık öncüllere sahiptir. Bu yüzden sıra bütünüyle yeni sayılmadı; sırayı bakışın bir evde dolaşması olarak somutlaştıran bölüm, klasik ahlâkî nazmın üzerine eklenen kısım olarak ayrıldı.','partial','Râzî 107:3 birinci mesele ve 107:4–5 birinci mesele; Bikâî 107:2 fe ve 107:3 teşvik/ihtibak açıklamaları.','',[6],relation='structural')
add(7,'CQ-001','cross_quran','Bu karşılaştırmada dayanakların kuvveti farklıdır. Nisâ 4:142 namazdaki riya ve az zikirle doğrudan yakınlık kurar; 4:38 malın gösteriş için verilmesini ekler. İnsan 76:8–10, yetim ve yoksulu doyurmayı karşılık ve teşekkür istememeyle bağlar. Alak 96:6–14 ise kendini ihtiyaçsız gören, namazı engelleyen ve Allahın gördüğünü hesaba katmayan kişinin sahnesidir. Şuarâ’daki görülme Peygambere yöneliktir. Bunların hepsi aynı olay değil; sûrenin gösteriş/hesap eksenini sınayan karşı sahnelerdir.','QURAN',ayah='107:1-7',tradition='edebi',role='intertext',relation='comparative',status='interpretive',connection='strong',priority='extended',audience='general',source_ref='4:38/142; 26:218–219; 76:8–10; 92:19–20; 96:6–14')
nov(7,3,'İlâhî bakış, başka insanların bakışı ve teşekkür beklemeden verme, anılan ayetlerde metin düzeyinde açık yapıtaşlarıdır. İncelenen 107 açıklamaları riya-niyet ve toplumsal zarar bağını zaten kurar. Buna karşılık Şuarâ, Alak, Nisâ, İnsan ve Leyl sahnelerini tek görme ekseninde böyle sıralayan toplam ağ bu sınırlı taramada açık bulunmadı. Bu bölümün özgün payı ayetleri yeniden söylemek değil, farklı konuşanlara ait sahneleri işaretlenen tema altında birlikte okutmasıdır.','building_blocks_only','Kur’an 4:38/142,26:218–219,76:8–10,92:19–20,96:6–14 metinleri ve yakın bağlamları.','QURAN',[7],relation='comparative')

# Cloth, stopped motion, prayer neglect and meaningful competing reports.
add(10,'SEM-001','semantic_history','Râgıb’ın k-z-b maddesi doğruluk/yanlışlık ayrımını sözlerle sınırlamaz; niyet ve fiilin iddiayla uyuşmasını da ele alır. Aynı maddede boyayla süslenmiş kumaşın nakışlı görünmesi örneği bulunur. Kurtubî’nin 107:6 açıklaması ise gösterişin giysiyle zahit görünme biçimine uzanabileceğini söyler. Bunlar gerçek eski öncüllerdir. Ancak biri genel sözlük örneği, diğeri riya türüdür; ikisi de 107:1’deki tekzib kelimesinin doğrudan kumaş anlamına geldiğini söylemez.','RAGHIB|QURT107',ayah='107:1|107:6',tradition='edebi',role='early_attestation',relation='lexical',status='explicit',priority='extended',audience='general',source_ref='Râgıb كذب bütün madde; Kurtubî 107:6 giysiyle riya paragrafı')
nov(10,4,'Yalancı kumaş, Râgıb’daki boyalı süs örneğine dayanır; giysiyle dindar görünme de Kurtubî’de vardır. Bu iki öncül, kumaş/görünüş ilişkisini salt yeni bir buluş saymayı önler. Fakat ipliğe işlememiş boyayı tekzibden şeklen namaza, oradan sahte sürekliliğe taşıyan bütün anlatım incelenen ayet açıklamalarında açık bulunmadı. Özellikle boya-alt dokuma ayrıntıları ayetin anlamı veya kaynakların verdiği bir dokuma tarihi değil, bu eski örnekten geliştirilen proje imgesidir.','partial','Râgıb كذب boyalı kumaş ve söz/fiil doğruluğu bölümü; Kurtubî 107:6 giysiyle riya; Maqāyîs كذب bütün madde.','RAGHIB|MAQ',[10])
add(11,'MTH-003','method_note','Maqāyîs, hücumda geri durma kullanımı ile doğruluk karşıtlığı arasında kıyas kurar; deve sütünün kesilmesine dair kullanımda ise ayrıca ihtiyat gösterir. Râgıb da süt ve hücum örneklerini kaydeder; رأي maddesinde gebeliğin görünmesi vardır. Bunlar bağlamsal fiil anlamına eşit değildir. Sûredeki yalanlama, hesaba/dine karşı tutumdur; hayvanın hamileliği veya saldırısının kesilmesi bu tutumun sözlük ailesinden gelen benzetmeleridir. Paketteki her alt rivayetin ilk sözlük nüshası ayrıca kollasyon edilmedi.','MAQ|RAGHIB|PACK107',ayah='107:1|107:5-6',role='constraint',relation='lexical',status='explicit',priority='extended',audience='advanced')
nov(11,5,'Yarıda kalan hücum, kesilen süt ve belli olan gebelik eski sözlük yapıtaşlarıdır. İncelenen 107 açıklamalarında bu hayvan sahnelerini tekzib-riya-sehv hattında aynı biyografiye birleştiren açık bir anlatım bulunmadı. Bu yüzden bu ağ yapıtaşları düzeyinde attested sayıldı. Maqāyîs’in ihtiyatı ve paketteki bazı özel nakillerin bağımsız ilk kaynakla kontrol edilmemiş olması, sentezin köken bilgisi veya güçlü bağlamsal tefsir diye sunulmasını ayrıca sınırlar.','building_blocks_only','Maqāyîs كذب bütün madde; Râgıb كذب süt/hücum bölümleri ve رأي gebeliğin görünmesi cümlesi; özgün paket B004–B007 atıfları.','MAQ|RAGHIB|PACK107',[11])
add(12,'SRC-002','source_note','D-y-n ailesindeki özel hukuk deyimlerinin denetimi kısmen tamamlandı. Sıhâh’ta kişiyi kendi dinine bırakma sözü, Muhkem’de yargıda ve kişi ile Allah arasında onu doğrulama kullanımı görüldü. Buna karşılık ana metindeki yemin edenin niyetine bırakılması alıntısının bağımsız Tehzîb nüshasıyla kontrolü tamamlanmadı; onun ilk kaynak kontrolü not_checked kalıyor. Bu özel kullanım, 107:1’de dînin mutlaka gizli niyeti inceleyen bir mahkeme hükmü olduğu sonucunu tek başına taşımaz.','SIHAH|MUHKAM|PACK107|TAB107|RAZI107',ayah='107:1',role='source_criticism',relation='lexical',status='not_assessed',priority='research',audience='research',source_ref='Sıhâh دين; Muhkem دين; proje d-y-n B007; ilk Tehzîb kaynağı bağımsız kontrol edilmedi')
nov(12,6,'İnkârı görünür fiille tanıma ve riyada maksadı sorgulama klasik öncüllerdir. Kişiyi kendi dinine bırakma gibi hukuk kullanımları da eski sözlüklerde vardır. Fakat “boyanın altına bakan hüküm” biçimindeki hukuk-kumaş-niyet birleşimi incelenen 107 açıklamalarında açık bulunmadı. Yemin niyeti alıntısının ilk kaynak kontrolü eksik olduğundan o özel yapıtaşının kaynağı ayrıca not_checked’tır; bir hukuk deyiminden bütün ayetin tek anlamı çıkarılmadı.','building_blocks_only','Sıhâh دين bütün madde; Muhkem دين bütün madde; Esâs دين bütün madde; Râzî 107:1–3; B007 paket alıntısı incelendi fakat bağımsız Tehzîb pasajı kontrol edilmedi.','SIHAH|MUHKAM|ASAS|PACK107',[12])
add(13,'SEM-005','semantic_history','Taberî’nin 107:5 derlemesi üç ana tavrı bir arada tutar: namazı vaktinden kaçırmak, insanların yanında kılıp yalnızken bırakmak, kılıp kılmadığına aldırmamak. Sonunda bunları namaza karşı kayıtsızlığın farklı biçimleri olarak genişçe birleştirir. İbn Kesîr zaman, şartlar ve huşû ihmali arasında dereceler sayar. Zemahşerî de savsaklama, aceleyle kılma ve kalbin eğilmemesini ele alır. “Namazın dışı” imgesi bu açıklamaları düşündürebilir; yalnız mekân anlamına indirgeyip erken rivayetlerden dirayet açıklamalarına süren klasik aralığı kapatmamalıdır.','TAB107|KATH107|KASH107',ayah='107:4-5',tradition='rivayet',role='historical_development',relation='direct_tafsir',status='reported',priority='core',audience='general',source_ref='Taberî 107:5 rivayet grupları ve sonuç; İbn Kesîr 107:5; Zemahşerî 107:5')
add(13,'TAF-005','tafsir','An/fî ayrımı eski bir tefsir gözlemidir. Zemahşerî, namazdan gafil olmakla namazın içinde insanın elinde olmadan yanılmasını ayırır; Kurtubî’nin İbnü’l-Arabî’den aktarımı bunun herkesin, Peygamberin de başına gelebileceğini söyler. Râzî, sehvi yalnız namazı tümüyle bırakmaya bağlamayı, kişilere musallîn denmesi nedeniyle başlangıçta zayıf bulur; ardından şeklen namaz ile anlamca Allahı hatırlama ayrımı üzerinden bu itiraza cevap kurulabileceğini gösterir. Önce itirazın, sonra ayrımın varlığı birlikte korunmalıdır. An, bedenen namazın dışında bulunmak veya bütün iç dalgınlıkların aynı ahlâkî kusur olması demek değildir.','KASH107|QURT107|RAZI107',ayah='107:5',tradition='dirayet',role='early_attestation',relation='grammatical',status='explicit',priority='core',audience='general',source_ref='Zemahşerî 107:5 an/fî sorusu; Kurtubî 107:5; Râzî 107:4–5 ikinci/üçüncü mesele')
add(13,'TAF-006','tafsir','Süyûtî’nin derlemesinde Ebü’l-Âliye sehv örneklerini namazda rekatın tek/çift olduğundan şaşırma gibi verir; Hasan bu açıklamayı reddedip vaktin geçirilmesini öne çıkarır. Bu, ana metnin kullandığı unutma yapıtaşının klasik kaynakta görünmesiyle birlikte bağlamsal tefsir olarak reddedildiği önemli bir karşı örnektir. Sözcükte unutma bulunması, buradaki tehditte her olağan unutmanın kastedildiğini göstermez. Taberî’nin geniş sonucu da namazı önemsememe tavrını korur.','SUY107|TAB107',ayah='107:5',tradition='rivayet',role='disagreement',relation='direct_tafsir',status='disputed',priority='extended',audience='advanced',transmitter='Ebü’l-Âliye; Hasan',source_ref='Süyûtî 107:5 rekatlarda sehv ve Hasan’ın itirazı; Taberî 107:5 sonuç')
add(13,'HAD-003','hadith','Buhârî’nin Abdullah b. Buhayne rivayetinde Peygamber namazda iki rekattan sonra oturmadan kalkar; sonunda selamdan önce iki sehiv secdesi yapar. Bu sahih karşı sahne, ibadeti terk etmeyen insanda unutmanın olabileceğini somutlaştırır. 107:5’in doğrudan tefsiri değildir; namazı önemsemeyen yerleşik tutumla ibadet içinde düzeltilen insani yanılmayı ayırmaya yardım eder.','BUK1224',ayah='107:5',tradition='hadith',role='contrast',relation='thematic',status='explicit',hadith_grade='sahih',connection='strong',priority='core',audience='general',transmitter='Abdullah b. Buhayne',source_ref='Sahîh Bukhârî 1224')
add(13,'HAD-004','hadith','Müslim’de Enes’in aktardığı namaz tasvirinde kişi güneşi bekler; vakit daralınca dört rekatı aceleyle kılar ve Allahı pek az anar. Hadis bu tavrı münafığın namazı olarak adlandırır. Geç kalma, bedensel acele ve az zikrin birlikte görünmesi, sûredeki sehv/riya ağına güçlü bir tematik karşılıktır. Sırf her gecikme veya tek dalgınlık için kişinin iç inkârını kesinleştiren bir teşhis aracı değildir.','MUS622',ayah='107:4-6',tradition='hadith',role='corroboration',relation='thematic',status='explicit',hadith_grade='sahih',connection='strong',priority='extended',audience='general',transmitter='Enes b. Mâlik',source_ref='Sahîh Muslim 622')
add(13,'SRC-003','source_note','Bu ayete doğrudan bağlanan her merfû aktarım sahih değildir. İbn Kesîr, Ebû Berze’ye nispet edilen açıklamanın Câbir el-Cuʿfî ve adı verilmeyen kişi üzerinden geldiğini söyleyerek zayıflığını belirtir. Saʿd’ın namazı vaktinden geçirmek açıklamasında ise merfû biçimi zayıf bulup sahâbî sözü olan mevkuf biçimin tercih edildiğini aktarır; Süyûtî de Beyhakī/Hâkim’in bu değerlendirmesini nakleder. Özgün hadis-tenkit eserleri ayrıca incelenmedi: burada doğrulanan, bu müfessirlerin açık tenkitleridir. Bu haberler sahih doğrudan Peygamber tefsiri olarak kullanılmadı.','KATH107|SUY107|TAB107',ayah='107:5',role='source_criticism',relation='direct_tafsir',status='weak',hadith_grade='not_assessed',priority='research',audience='research',source_ref='İbn Kesîr 107:6 sonunda Ebû Berze/Saʿd tenkidi; Süyûtî 107:5; Taberî 107:5 merfû aktarımları')
add(13,'QIR-002','qiraat','İbn Mesʿûd’a nispet edilen okuma notları tefsirin anlam aralığını gösterir: Taberî 107:1’de tekzib fiilinden sonra bâ olmadan dîni okuma haberini; Zemahşerî/Râzî eraeytaka biçimini; Süyûtî 107:5’te sahun yerine lâhun aktarımını verir. Lâhun, oyalanma/kayıtsızlık yönünü güçlendirir. Bu aktarımların isnadı ve kıraat tasnifi bağımsız kıraat kitabında kontrol edilmedi; kanonik metin varyantı diye sunulmuyor ve burada canonical hükmü verilmiyor.','TAB107|KASH107|RAZI107|SUY107',ayah='107:1|107:5',tradition='rivayet',role='semantic_range',relation='grammatical',status='reported',priority='research',audience='research',transmitter='İbn Mesʿûd’a nispet edilen okumalar',source_ref='Taberî 107:1; Zemahşerî/Râzî 107:1; Süyûtî 107:5')
nov(13,7,'Namazdan gaflet ile namaz içindeki yanılma ayrımı ve şekil/hatırlama karşıtlığı klasik kaynaklarda açıktır; yalnız projeye mal edilemez. İpliğe girmeyen boya, durup seyirci arayan hayvan ve yetim kelimesindeki gecikmeyi bu ayırımlara bağlama ise incelenen pasajlarda tam bir ağ olarak bulunmadı. Bu nedenle kısmî klasik öncüllü sentez sayıldı. Olağan rekat şaşırmasını bağlamsal anlam sayıp reddeden Hasan’ın itirazı da, unutma yapıtaşının varlığıyla birlikte korunuyor.','partial','Zemahşerî 107:5 an/fî; Kurtubî 107:5 İbnü’l-Arabî; Râzî 107:4–5 ikinci/üçüncü mesele; Süyûtî 107:5 Hasan/Ebü’l-Âliye; Maqāyîs سهو; Lisan يتم.','MAQ|LISAN',[13],ayah='107:2|107:4-6')
add(14,'MTH-004','method_note','Bakara 2:177, iyiliği yalnız yüzün belli yöne çevrilmesine kapatmayı önler; aynı ayet namazı ve malı paylaşmayı olumlu bütünün içinde sayar. Bu yüzden “boyasız kumaş” ile kıbleyi veya namazın şekil şartlarını değersizleştirmek aynı şey değildir. 63:4’teki kütük ve 2:264’teki kaya kendi bağlamında açık benzetmelerdir; bunları kumaşın parçası olarak okumak ayrıca edebî karşılaştırmadır.','QURAN',ayah='107:1|107:4-7',role='constraint',relation='comparative',status='explicit',priority='extended',audience='general')
nov(14,8,'Kayanın toprak görüntüsü, desteklenmiş kütükler, kıbleyi aşan iyilik ve az verip kesme ayetlerin açık malzemesidir. Fakat bunların aynı boyalı kumaşın çeşitli yüzleri gibi bir araya gelmesi, incelenen 107 tefsir gövdelerinde açık bir yapı olarak bulunmadı. Eski Kur’an sahneleri bu yorumun yapıtaşlarıdır; özel birleştirme ve “boyasız kumaş” adı projenindir. Karşılaştırma, her ayetin konuşanını ve kendi bağlamındaki maksadını koruduğu ölçüde çalışır.','building_blocks_only','Kur’an 2:177/264,63:4,53:33–34,70:23/34,98:5; Râgıb كذب kumaş örneği.','QURAN|RAGHIB',[14],relation='comparative')

# Neglect, weak visibility and the hands around the vulnerable.
add(17,'SEM-002','semantic_history','Yetim için ihmal ve gecikme açıklamaları uydurulmuş değildir: Lisân, Mufaddal’ın ihmal kökenini, Ebû Amr’ın gecikme açıklamasını kaydeder. Bunlar tek bir tartışmasız türeyiş değildir. Maqāyîs ana ekseni ayrılma/yalnızlaşma olarak kurup insanda babanın, hayvanda annenin ölümü ayrımını verir. Tek inci mecazı da yalnızlık kolundadır. Bu nedenle baba kaybı, ihmal edilmişlik ve gecikme aynı tanımın eşanlamlı parçaları değil; sözlük geleneğinin ayrı açıklama ve kullanımlarıdır.','LISAN|MAQ|RAGHIB',ayah='107:2',tradition='edebi',role='semantic_range',relation='lexical',status='explicit',priority='extended',audience='general',source_ref='Lisân يتم bütün madde; Maqāyîs يتم; Râgıb يتم')
add(18,'MTH-005','method_note','Suhâ ile gözden kaçma bağı için Maqāyîs’in kesinlik derecesi önemlidir. İbn Fâris, yıldızın adını zor görüldüğü için aynı anlama bağlamanın mümkün olduğunu söyler; bunu kesin bir türeyiş olarak vermez. Dostun kusurunu görmezden gelme ise farklı ahlâkî sonuç doğuran kullanım olarak aynı maddede yer alır. Bu malzeme ihmal edilen çocuğa dikkat çeken bir imgeyi besleyebilir; 107:5’in bir yıldızdan söz ettiği veya sahunun astronomik tanımı olduğu sonucunu vermez.','MAQ|PACK107',ayah='107:2|107:5-6',role='constraint',relation='lexical',status='explicit',priority='core',audience='general',source_ref='Maqāyîs سهو: Suhâ için محتمل kaydı, müsâhât ve asıl açıklaması')
nov(18,9,'Suhâ, yalnız inci, ihmal/gecikme ve dostun kusurunu örtme eski sözlük dallarıdır. İncelenen tefsirlerde namazı önemsememeyle yetime zarar verme de birlikte ele alınır. Buna karşılık görülmesi zor yıldız ile toplumun görmediği çocuk ve kendini görünür kılan kişi arasındaki bu tam üçlü ağ, adı verilen ayet açıklamalarında açık bulunmadı. Burada yapıtaşları düzeyinde klasik tanıklık var; birleşim projenindir. Suhâ etimolojisinin kaynakta yalnız ihtimal sayılması da birleşimin delil sınırına dahildir.','building_blocks_only','Maqāyîs سهو ve يتم; Lisân يتم ihmal/gecikme görüşleri; Râgıb يتم yalnız inci; 107:2/5/6 gösteriş-gaflet açıklamaları.','MAQ|LISAN|RAGHIB',[17,18,19],ayah='107:2-6')
add(19,'TAF-007','tafsir','Taberî, yetimi itmenin hakkını engellemek ve ona zulmetmek olduğunu açıklar; Mücâhid’den itip doyurmamayı da aktarır. İbn Kesîr buna yiyecek vermeme ve iyi davranmama yönünü ekler. 107:3’teyse doğrudan kendi vermemesi değil, yoksulun doyurulmasını başkasına da öğütlememesi açıkça belirtilir. Râzî’nin dikkat çektiği fark, kötü bir işi yapmakla kolay bir iyiliğe yöneltmeyi dahi terk etmek arasındadır. Bu, çocuğun iç dünyasını tahmin etmekten önce somut hak ve davranışa bakan bir okumadır.','TAB107|KATH107|RAZI107',ayah='107:2-3',tradition='rivayet',role='anchor',relation='direct_tafsir',status='reported',priority='core',audience='general',source_ref='Taberî 107:2–3; İbn Kesîr 107:2–3; Râzî 107:3 birinci mesele')
add(19,'MTH-006','method_note','Ana paragraftaki “Üçüncü ayette yoksulun yemeği hiç anılmaz” ifadesi lafızla uyuşmuyor: 107:3 açıkça taʿâmi’l-miskîn, yoksulun yemeği der. Eksik olan yemek kelimesi değil, onu doyurmaya teşvik eden davranıştır. Râzî ve Bikâî’nin açıklamaları bu yapılmayan teşvikin önemini artırır. Özgün cümle korunuyor; okurun bu cümleyi ayet alıntısı veya lafız tespiti sanmaması için çatışma burada belirtiliyor.','QURAN|RAZI107|BIQ107',ayah='107:3',role='constraint',relation='methodological',status='explicit',priority='core',audience='general')
add(19,'HAD-005','hadith','Buhârî’de Sehl b. Saʿd’ın rivayeti, yetime bakım sağlayanın cennette Peygambere yakınlığını iki parmağı göstererek anlatır. Bu sahih hadis sûrenin nüzul olayı veya doğrudan tefsiri değildir. İtişe karşı bir elin ne yapabileceğini somutlaştıran olumlu tematik sahnedir: uzaktan acıma yerine devam eden bakım. Yetime bakmakla yetimin her zaman malı olmayan biri olduğunu varsaymak da ayrı şeylerdir.','BUK6005',ayah='107:2',tradition='hadith',role='contrast',relation='thematic',status='explicit',hadith_grade='sahih',connection='strong',priority='extended',audience='general',transmitter='Sehl b. Saʿd',source_ref='Sahîh Bukhârî 6005')
add(20,'CQ-002','cross_quran','Zâriyât 51:10–14’te ghamra, doğru hesaptan uzaklaştıran yanılma/şüphe ve gaflet bağlamındadır; ardından din günü sorulur ve ateş sahnesi gelir. Taberî, İbn Zeyd’in suyun içinde kalmış bir nesne benzetmesini de aktarır. Dolayısıyla suya gömülme imgesinin eski bir öncülü vardır; “gaflet seli” ayetin doğrudan akarsu tasviri değildir. Duhâ 93:6–10 barındırma ile yetimi ezmeme emrini bağlar. Tevbe 9:67’de Allahın onları unutması da karşılıklı bilgi kaybı değil, münafıkların unutmasına karşı terk edilme dili içinde okunmalıdır.','QURAN|TAB5111',ayah='107:1-7',tradition='rivayet',role='intertext',relation='comparative',status='interpretive',connection='resonant',priority='extended',audience='advanced',source_ref='Taberî 51:11 ghmra açıklaması ve İbn Zeyd su benzetmesi; Kur’an 51:10–14,93:6–10,9:67')
nov(20,10,'Gafleti suda kalmaya benzetmek için yalnız yeni bir kök çağrışımı yoktur: Taberî 51:11’de İbn Zeyd’in açık su benzetmesi incelendi. Bu nedenle su/gaflet yapıtaşı eski sayıldı. Ancak onu Suhâ, barındırılan yetim ve 107’nin aranan bakışıyla aynı görünmezlik ağına bağlayan tam düzen incelenen bölümlerde bulunmadı. Eski benzetmeyi kaydetmek, “sel” kelimesinin ayetin bağlamsal anlamı olduğunu veya 107:5’in suyla açıklanmış doğrudan bir rivayete sahip olduğunu söylemek değildir.','building_blocks_only','Taberî 51:11 bütün görüntülenen açıklama ve İbn Zeyd su içinde kalma benzetmesi; Kur’an 51:10–14,93:6–10,9:67; Maqāyîs سهو.','TAB5111|QURAN|MAQ',[20],relation='comparative')
add(23,'MTH-007','method_note','Maqāyîs’in d-ʿ-ʿ maddesi şiddetli itişi temel alır ve kabı sallayıp doldurma kullanımını ona bağlar. Fakat düşene söylenen kalk sesi gibi kullanımlarda seslerin düzenli kıyasının güç olduğunu ayrıca belirtir. Lisân küçük çocuklar ve farklı seslenişler için başka şahitler de verir. Bu nedenle aşağı iten el ile ayağa çağıran sesi karşılaştırmak mümkündür; ayetteki yadʿuyu yardım ederek kaldırmak diye çevirmek yahut tüm sesleri tek düzenli etimoloji saymak doğru değildir.','MAQ|LISAN',ayah='107:2',role='constraint',relation='lexical',status='explicit',priority='extended',audience='advanced',source_ref='Maqāyîs دع asıl ve seslerin kıyas sınırı; Lisân دع')
add(24,'MTH-008','method_note','Maqāyîs h-d-d maddesinde teşvik ile düşük/çukur yer için iki asıl ayırır. Halîl’den aktardığı ayrım, bu teşvik fiilinin yürüme ve sürü sürmede kullanılmadığını açıkça söyler. Dolayısıyla “hayra doğru sürmek” bir Türkçe imgedir; yetimi sert itmekle teşvik etmeyi aynı fiziksel zorlamaya eşitlemez. Çukurda duranın yanına inme sahnesi de ikinci sözlük aslından kurulan benzetmedir. Ayetin doğrudan fiili yoksulun doyurulmasına yöneltmektir.','MAQ|RAZI107',ayah='107:3',role='constraint',relation='lexical',status='explicit',priority='core',audience='general',source_ref='Maqāyîs حض iki asıl ve Halîl tanımı; Râzî 107:3 teşvikin kendisine/başkasına yönelmesi')
add(25,'HIS-001','historical_context','Kurtubî yetimi ezmeyi malını ve hakkını engelleme yönüyle açıklar; çocukların ve kadınların mirasta dışlanması örneğini de verir. Bu aktarımı bütün kabilelerin tüm zamanlardaki düzeni diye genellemedim. Kur’an 4:2 ve 4:6, yetimlerin korunacak malları olabileceğini; 4:7 miras payı hakkını açıkça gösterir. Baba kaybı ağır bir korunma ihtiyacı doğurabilir, ama her yetimin mutlaka malsız, yoksul veya bütün yakınlarından yoksun olduğu sonucunu vermez.','QURT107|QURAN',ayah='107:2-3',tradition='historical',role='historical_context',relation='historical',status='reported',historicity='uncertain',priority='extended',audience='general',source_ref='Kurtubî 107:2 hak/mal/miras açıklaması; Kur’an 4:2/6/7')
add(25,'HAD-006','hadith','Buhârî’nin Ebû Hüreyre rivayeti, miskîni kapı kapı dolaşırken bir lokmayla dönen kişiyle sınırlamaz; ihtiyacı karşılanmayan, fark edilip yardım edilmeyen ve dilenmeyen kişiyi de görünür kılar. Bu sahih tematik delil, sûredeki kolayca gözden kaçan ihtiyaçla iyi buluşur. Buna karşılık miskîni tanım gereği bedeni hareketsiz, evi bulunmayan veya başkasından mutlaka yemek isteyen biri saymayı sınırlar. Kökten gelen durgunluk imgesi sosyal durumun tamamı değildir.','BUK1479|SIHAH',ayah='107:3',tradition='hadith',role='clarification',relation='thematic',status='explicit',hadith_grade='sahih',connection='strong',priority='core',audience='general',transmitter='Ebû Hüreyre',source_ref='Sahîh Bukhârî 1479; Sıhâh سكن miskin açıklaması')
add(26,'TAF-008','tafsir','Alışkanlık ve kolay teşvikin terk edilmesi için güçlü klasik dayanak vardır. Râzî muzari anlatımı yerleşmiş tavır olarak okur; Bikâî, bir söz bile harcamayanın mal harcamasının daha da uzak oluşunu vurgular. Ama Râzî aynı yerde her teşvik etmeyişin günah olmadığını da söyler: başkaları zaten doyuruyorsa, söz etkisizse veya söyleyene zarar getirecekse durum ayrıdır. Ayetin hedefi ihtiyaç karşısında katılaşan tavırdır; her sessizliği aynı ahlâkî teşhise dönüştürmez.','RAZI107|BIQ107',ayah='107:2-3',tradition='dirayet',role='constraint',relation='direct_tafsir',status='explicit',priority='core',audience='general',source_ref='Râzî 107:3 muzari/şiddet ve teşvik etmemenin şartları; Bikâî 107:3')
add(26,'TAF-009','tafsir','Yoksulun yemeği tamlamasını Râzî ve Bikâî hak yönüyle de duyar: mal sahibinin keyfî iyiliği saydığı şey, muhtacın gözetilecek payıdır. Bu, yoksulun bedeni hakkındaki durgunluk imgesinden daha doğrudan bir ahlâkî noktadır. Kişinin kendi yemesi veya yalnız bir kez sadaka vermesi değil, ihtiyaç sahibinin hakkına yer açan ve başkasını da buna yönelten tavır öne çıkar. Hak vurgusu, daha sonra görülecek zekât ve maûn tartışmasının da eski yapıtaşıdır.','RAZI107|BIQ107',ayah='107:3|107:7',tradition='dirayet',role='early_attestation',relation='direct_tafsir',status='explicit',priority='extended',audience='general',source_ref='Râzî 107:3 taʿam-miskin izafeti; Bikâî 107:3 izafet/hak açıklaması')
nov(26,11,'İtiş ile teşviksizlik, yapılan kötülük ile terk edilen iyilik, alışkanlık ve az sözün esirgenmesi klasik kaynaklarda açıktır. Tûr’daki itiliş bağı da Râzî/Kurtubî’de eski bir karşılaştırmadır. Kaldırma sesi, düşük yer, durgun beden, koruyucu çevre ve diğer ayetlerdeki elleri aynı elin hareketleri olarak kuran tam ağ ise incelenen 107 pasajlarında bulunmadı. Bu sentezin kısmî öncülü kuvvetlidir; seslerin kıyaslanmaması ve teşvik/dip yerin iki asıl olması sınırlarıdır. Baba kaybından her korumanın kaybını, miskinden her zaman hareketsiz beden çıkarmak desteklenmedi.','partial','Maqāyîs دع/حض/سكن/منع; Lisân دع; Sıhâh سكن; Râzî107:3 ve Bikâî107:3; Kurtubî107:2 Tûr bağlantısı; Kur’an4:2/6/7/37–38,52:13,89:17–18,93:9–10,68:17–24,90:15–17.','MAQ|LISAN|SIHAH|QURAN',[23,24,25,26,27],ayah='107:2-3|107:7')
add(27,'CQ-003','cross_quran','Tûr 52:13’e bağlanma klasik öncüllüdür: Râzî ve Kurtubî, yetimi itme fiilini cehenneme şiddetle itilme lafzıyla karşılaştırır. Fecr 89:17–18 yetimi gözetmeme ile karşılıklı teşvik etmeyişi, Duhâ 93:9–10 yetimi ezmeme ile isteyeni azarlamamayı yan yana getirir. Kalem’in bahçe sahipleri anlatısı 68:17–24, yoksulu içeri almama niyetini ayrıca görünür kılar. Bunlar birbirini aydınlatan ahlâkî sahnelerdir; aynı şahıs veya aynı nüzul olayı değildir.','RAZI107|QURT107|QURAN',ayah='107:2-3|107:7',tradition='dirayet',role='intertext',relation='comparative',status='explicit',connection='strong',priority='extended',audience='general',source_ref='Râzî 107:3 daʿ açıklaması; Kurtubî 107:2; Kur’an 52:13,89:17–18,93:9–10,68:17–24')

# Home, implements and competing maun readings.
add(30,'MTH-009','method_note','Sehve, Maqāyîs’te sundurma veya evin önündeki yapı için kaydedilir; kaynak bu dalı ana asıldan ayrılan düzensiz örnekler arasında açıkça sayar. Bu yüzden raf/sundurma ile namazdan gafleti tek zorunlu etimoloji saymak mümkün değildir. S-k-n maddesindeki ev, ev halkı ve ocak ise gerçekten eski sözlük şahitleridir. Bir evin parçalarını bu kelimelerden toplamak imge katmanında kalır; sûrenin lafzı belirli bir evin mimarisini betimlemez.','MAQ|PACK107',ayah='107:3-7',role='constraint',relation='lexical',status='explicit',priority='core',audience='general',source_ref='Maqāyîs سهو: ومما شذ kaydı ve sehve; سكن bütün madde')
add(31,'TAF-010','tafsir','Küçük eşya yardımı eski ve somut bir tefsirdir. Ebû Dâvûd’daki İbn Mesʿûd sözü, Peygamber döneminde kova ve tencere ödüncünü maûndan saydıklarını bildirir; sayfanın Al-Albânî değerlendirmesi hasendir. Bu sahâbînin dönem tanıklığıdır; Peygamberin ayeti bizzat bu kelimelerle açıkladığını söylemez. Taberî, İbn Kesîr ve Süyûtî’deki kova/tencere/balta anlatımları aynı rapor ailesi olarak burada birleştirildi. İbn Kesîr ayrıca yardım nesnesinin kalıp geri dönmesini vurgular; ödünç evde kalıcı kayıp meydana getirmeyebilir.','AD1657|TAB107|KATH107|SUY107',ayah='107:7',tradition='rivayet',role='early_attestation',relation='direct_tafsir',status='reported',hadith_grade='hasan',priority='core',audience='general',transmitter='İbn Mesʿûd',attested_in='Ebû Dâvûd 1657; Taberî/İbn Kesîr/Süyûtî 107:7',source_ref='Ebû Dâvûd 1657 Al-Albânî hasan; İbn Kesîr 107:7 ödünç ve dönüş açıklaması')
add(31,'TAF-011','tafsir','Eşya yorumu erken dönemden beri tek seçenek değildir. Taberî’nin aktardığı bir konuşmada İbn Ömer maûnu malın zorunlu hakkı olarak açıklar; kendisine İbn Mesʿûd’un ödünç eşya sözü hatırlatılınca kendi zekât açıklamasını yeniden vurgular. Ali’ye hem zekât hem ev araçları açıklamaları nispet edilir. Taberî sonuçta yarar sağlayan şeyleri, zorunlu mal haklarıyla birlikte kapsayan geniş anlamı tercih eder. Erken görüş ayrılığı korunmalıdır; bütün sahâbîlerin aynı tek anlamda birleştiği söylenemez.','TAB107|KATH107|QURT107',ayah='107:7',tradition='rivayet',role='disagreement',relation='direct_tafsir',status='disputed',priority='core',audience='general',transmitter='İbn Ömer; İbn Mesʿûd; Ali',source_ref='Taberî 107:7 İbn Ömer ile soru-cevap ve son tercih; İbn Kesîr/Kurtubî 107:7')
add(31,'SEM-003','semantic_history','Maûn, dirayet eserlerinde de dallanmayı sürdürür. Zemahşerî zekât veya insanların birbirinden ödünç aldığı araçları; Râzî küçük yarar, su, itaat ve paylaşmayı; Kurtubî on iki açıklama yönünü kaydeder. Bunların bir kısmı aynı rivayetin tekrarları, bir kısmı anlamı genişleten yeni gerekçelerdir. Dolayısıyla yalnız “küçük eşya” yahut yalnız “zekât” çevirisi, diğer attested yorumları görünmez kılabilir. Küçüklük de zekâtın önemsiz olması değil, büyük malın küçük payı olması diye gerekçelendirilmiştir.','KASH107|RAZI107|QURT107|SIHAH|LISAN',ayah='107:7',tradition='dirayet',role='historical_development',relation='direct_tafsir',status='explicit',priority='extended',audience='general',source_ref='Zemahşerî/Râzî/Kurtubî 107:7 vecihleri; Sıhâh/Lisân معن')
add(31,'ASB-002','asbab','Süyûtî, İbn Merdûye’den İbn Mesʿûd’a nispet edilen başka bir haber aktarır: müminler münafıklardan yararlı araçları ödünç ister, onlar engeller ve son ayet buna bağlanır. Bu, ilk ayetlerin Ebû Süfyân/Âs anlatılarından ayrı bir sebep adaydır. Özgün İbn Merdûye eseri ve bu isnadın değerlendirmesi incelenmedi. Bu nedenle haber, maûnun hangi sosyal uygulamayı düşündürdüğünü gösteren aktarım olarak kaydediliyor; son ayetin kesin Medine olayını belirleyen tarihî kanıt sayılmıyor.','SUY107',ayah='107:7',tradition='rivayet',role='asbab_context',relation='asbab',status='reported',historicity='uncertain',hadith_grade='not_assessed',priority='research',audience='research',transmitter='İbn Mesʿûd’a nispet; Süyûtî İbn Merdûye’den',source_ref='Süyûtî 107:7 müminlerin münafıklardan araç ödünç istemesi haberi')
add(31,'RDR-002','reader_note','Bir yardımın küçük olması her durumda masrafsız veya risksiz olması demek değildir. Ödünç verilen şey geri dönebilir; geçici yokluğu, kullanım kaygısı ve iade riski yine olabilir. Zemahşerî ihtiyacı karşılamayı, zorunluluk ve toplumsal mürüvvet derecelerine göre ayırır. Kurtubî de bir tek kabı vermemenin tek başına bütün tehdide eşitlenemeyeceğini aktaran yorumu kaydeder. Ana vurgu, ihtiyaç karşısında yerleşmiş ve başka kusurlarla birleşen esirgeme tavrıdır.','KASH107|QURT107|KATH107',ayah='107:7',role='reader_orientation',relation='direct_tafsir',status='explicit',priority='core',audience='general')
add(32,'MTH-010','method_note','Daʿdaʿa ile kabı sallayıp doldurma, Maqāyîs ve Lisân’da gerçekten bulunan bir sözlük dalıdır; konuk doyurma ve yemeği tatma da t-ʿ-m ailesinde vardır. Fakat 107:2’de yetimi iten fiil, bu dal bulunduğu için yetimi doyurmak anlamına dönmez. Aynı elin kap doldurabileceği karşı sahne, bağlamsal şiddeti koruyan bir edebî tersine çevirmedir. İyilik seçeneğini gösterir; fiilin sözlük çevirisini değiştirmez.','MAQ|LISAN',ayah='107:2-3|107:7',role='constraint',relation='lexical',status='explicit',priority='extended',audience='general',source_ref='Maqāyîs دع ve طعم; Lisân دع kap doldurma örnekleri')
add(33,'HIS-002','historical_context','Ev ve komşuluk paylaşımı için yalnız sözlük imgesi yoktur. Râzî’nin 107:7 açıklaması, komşunun fırında pişirmesine imkân vermeyi ve eşyasını bir gün ya da yarım gün saklamayı küçük yararın somut örnekleri arasında verir. Bu, ocak ve ev ağının gerçek klasik öncülüdür. Buna karşılık bir miskînin mutlaka evi bulunmadığı veya ayetin tek bir hane düzenini anlattığı sonucu çıkmaz. Kaynak belirli bir mahalle, tarih ve mimariyi tespit eden saha belgesi değildir.','RAZI107|BUK1479|QURAN',ayah='107:3|107:7',tradition='historical',role='historical_context',relation='historical',status='explicit',historicity='not_applicable',priority='extended',audience='general',source_ref='Râzî 107:7 ikinci vecih fırın/saklama örnekleri; Buhârî 1479; Kur’an 4:6–7')
nov(33,12,'Maûnun ev araçları ve geri dönen ödünç oluşu açık klasik açıklamadır; Râzî’de komşunun fırını kullanması da bulunur. Bu yüzden ev/ocak yardımı salt proje yeniliği sayılmadı. Küçük çocuklar, ev halkı, raf, azık, doldurulan kap ve evsiz sayılan yoksulu kelime sırasından tek eve yerleştiren tamamlanmış sahne ise incelenen açıklamalarda açık bulunmadı. Sentez kısmî öncüllüdür; sehvenin düzensiz dal oluşu ve miskinin zorunlu evsizlik anlamına gelmemesi iç sınırlarını oluşturur.','partial','Maqāyîs سهو/سكن/دع/طعم/معن; Lisân دع/معن; Sıhâh معن; Râzî 107:7 fırın/saklama; İbn Kesîr 107:7 ödüncün dönüşü.','MAQ|LISAN|SIHAH',[30,31,32,33],ayah='107:2-7')
add(34,'CQ-004','cross_quran','Kehf 18:77’de konuk ağırlamayan kasaba ile 18:82’de yetimlerin korunmuş malı, aynı yolculuk içinde farklı sahnelerdir; yoksula ilişkin her örneği evsizlik veya parasızlık tanımına kapatmayı önler. Nisâ 4:8 miras taksiminde hazır olan yetim ve yoksulların gözetilmesini ister. Yâsîn 36:47’de “Allah istese doyururdu” sözü inkârcıların mazeretidir; Kurtubî 107:3’te bunu teşviksizliğe bağlar. Yusuf’un ölçeği ve Mutaffifîn’in eksik ölçüsü ise ayrı ölçü/hak karşılaştırmalarıdır; S107’nin nüzul olayını anlatmaz.','QURAN|QURT107',ayah='107:2-3|107:7',tradition='edebi',role='intertext',relation='comparative',status='interpretive',connection='strong',priority='extended',audience='general',source_ref='Kur’an 18:77/82,4:8,36:47,12:63,83:1–3,76:8–10; Kurtubî 107:3')
nov(34,13,'Doyurma, konukluk, yetim malının korunması ve eksik ölçme, karşılaştırılan ayetlerde açık sahnelerdir. Ayrıca Yâsîn’deki vermeme mazeretini 107:3’le karşılaştırmak Kurtubî’de doğrudan attested’dir. Fakat bütün sahneleri tek evin kapları ve ölçeği etrafında böyle toplamak incelenen 107 gövdelerinde açık bulunmadı. Bu nedenle ağ kısmî klasik öncüllüdür. Kehf’teki iki olayın farklı oluşu ve ölçek örneklerinin kendi iktisadî bağlamları sentezde silinmemelidir.','partial','Kurtubî 107:3 Yâsîn 36:47 bağlantısı; Kur’an18:77/82,4:8,36:47,12:63,83:1–3,76:8–10.','QURAN',[34],relation='comparative')

# Water: actual semantic antecedents, alternate derivations and a firm hadith.
add(37,'TAF-012','tafsir','Maûnun su anlamı yalnız sözlükte kalmış değildir. Taberî yağmur/su kullanımı için şiir şahidini ve yarar kapsamını kaydeder; Râzî Ferrâ’nın Araplardan doğrudan su için duyduğu kullanımı aktarır. Kurtubî de su ve otlak, ayrıca yalnız su açıklamalarını vecihler arasında verir. Dolayısıyla suyu paylaşma, incelenen klasik tefsirde gerçek bir yorum dalıdır. Bu dalı belirtmek, diğer zekât/ödünç/itaat yorumlarını kaldırmaz veya 107:7’de her anlamın aynı anda zorunlu olduğunu göstermez.','TAB107|RAZI107|QURT107|SIHAH|LISAN',ayah='107:7',tradition='dirayet',role='semantic_range',relation='direct_tafsir',status='explicit',priority='core',audience='general',source_ref='Taberî 107:7 su/şiir ve sonuç; Râzî 107:7 su vecihleri; Kurtubî 107:7 su-otlak ve su vecihleri')
add(37,'MTH-011','method_note','Maʿîn ile maûn arasında kök bağlantısı tartışmasız değildir. Maqāyîs m-ʿ-n ailesinde akan suyu kaydeder; fakat Kurtubî 67:30 ve Lisân, maʿîni görünür su/ayn kökünden mîmi fazlalıklı sayma ihtimalini de korur. Sıhâh ve Lisân maûnun maʿûne kökeniyle açıklanması ihtimalini ayrıca aktarır. Bu alternatiflerde m-ʿ-n ile ʿayn veya yardım ailesi aynı düzenli kök iddiası değildir. Projenin su ağı, attested su yorumuna ve açık ayetlere dayanabilir; tek kökeni kesinleştirerek güçlendirilmemelidir.','MAQ|QUR6730|LISAN|SIHAH|RAGHIB',ayah='107:7',role='constraint',relation='lexical',status='disputed',priority='core',audience='advanced',source_ref='Maqāyîs معن; Kurtubî 67:30; Lisân/Sıhâh معن; Râgıb معن ilgili bölüm')
add(37,'MTH-012','method_note','Tatmanın suya uzanması Maqāyîs t-ʿ-m maddesinde açıkça vardır; İbn Fâris Bakara 2:249’daki nehri tatmama lafzını delil gösterir. Bu, yiyecek/su ağının gerçek sözlük yapıtaşıdır. Bununla birlikte 107:3’te yoksulun taʿâmı için tefsirler doyurma ve gözetilecek hak üzerinde durur. Suya uzanan genel dil imkânı, bu ayetin yalnız içecekten veya belli bir nehirden söz ettiğini göstermez.','MAQ|QURAN|RAZI107|BIQ107',ayah='107:3|107:7',role='clarification',relation='lexical',status='explicit',priority='extended',audience='advanced',source_ref='Maqāyîs طعم bütün madde; Kur’an 2:249; Râzî/Bikâî 107:3')
add(38,'HAD-007','hadith','Buhârî’nin Ebû Hüreyre rivayeti, otlaktan yararlanmayı engellemek için ihtiyaç fazlası suyun tutulmamasını emreder. Bu sahih tematik delil, suyun kesilmesinin başkasının geçimini de kesebilmesini açıkça gösterir; maûn için su/otlak yorumuna güçlü bir karşılıktır. Hadis 107:7’yi açıkça açıklayan bir söz değildir. Ayrıca lafız ihtiyaç fazlası su ve otlak bağlantısını içerir; her özel eşyanın, her su kullanımının veya her ödünç isteğinin tek hükümle zorunlu olduğu sonucuna genişletilmez.','BUK2353|QURT107',ayah='107:7',tradition='hadith',role='corroboration',relation='thematic',status='explicit',hadith_grade='sahih',connection='strong',priority='core',audience='general',transmitter='Ebû Hüreyre',source_ref='Sahîh Bukhârî 2353; Kurtubî 107:7 su/otlak vecihleri')
add(39,'CQ-005','cross_quran','Mülk 67:30’daki “gördünüz mü” çağrısı ile maʿîn kelimesi, S107’nin açılışı ve son kelimesiyle ses/tema yakınlığı kurar. Yakın bağlam 67:28–29’da koruyacak merci ve tevekkül sorulur; son ayet suyun çekilmesi karşısında insanın kaynağa bağımlılığını açar. Mü’minûn 23:50’nin karar ve su bulunan barınağı, Duhâ 93:6’daki yetimin barındırılmasıyla ayrı kişilere ait iki koruma sahnesidir. Bunları tek su-barınak ağı olarak okumak karşılaştırmadır; ortak kelime tek başına kasıtlı ayetler arası atfın kanıtı sayılmadı.','QURAN|QUR6730',ayah='107:1|107:7',tradition='edebi',role='intertext',relation='comparative',status='interpretive',connection='resonant',priority='extended',audience='general',source_ref='Kur’an67:28–30,23:50,93:6; Kurtubî67:30')
nov(39,14,'Su/maûn, su-otlak ve suyu esirgeme için doğrudan klasik tefsir ve sahih tematik hadis vardır; bu içerik yeni sayılmadı. Akarsu yatakları, sulanmış bitki, s-k-n otlağı, taʿâmın suya uzanması, Mülk’ün eraeytum/maʿîn uçları ve iki barındırma sahnesinin bu tek ekolojiye bağlanması ise incelenen 107 açıklamalarında tam ağ olarak bulunmadı. Kısmî klasik öncüllü proje sentezidir. Maʿîn kökenindeki alternatif ve hadis hükmünün ihtiyaç fazlası suyla ilgili sınırı bu sonuca dahildir.','partial','Maqāyîs معن/سكن/طعم; Sıhâh ve Lisân معن; Râgıb معن ilgili bölüm; Kurtubî67:30 bütün gövde; Kur’an2:249,67:28–30,23:50,93:6; Buhârî2353.','MAQ|SIHAH|LISAN|RAGHIB|QUR6730|QURAN|BUK2353',[37,38,39],relation='comparative')

# Fire: separate roots/asls, weak candidate and clear Quranic judgment scenes.
add(42,'MTH-013','method_note','Ateş ve namaz ilişkisi için Maqāyîs belirleyici bir sınır koyar: ṣ-l-y başlığı altında iki asıl vardır; biri ateş/sıcaklık, diğeri ibadettir. Ateşte pişirme ve değneği ateşle düzeltme ilk asıldadır; dua/namaz açıklaması ikinci asıldadır. Harfler ve zayıf son harf nedeniyle aynı başlık veya yankı ailesi içinde görünmeleri, tek anlam kökeni olduklarını ispatlamaz. 107:4’te musallîn namaz kılanlardır. “Namazın kelimesinde ateş” sözü bağlamsal veya kesin etimolojik anlam değil, ayrılığı açık tutulan bir yankı imgesidir.','MAQ|PACK107|KATH107|RAZI107',ayah='107:4-5',role='constraint',relation='lexical',status='explicit',priority='core',audience='general',source_ref='Maqāyîs صلي: أصلان; özgün paket salw kimliği/sly yankı ayrımı; İbn Kesîr/Râzî107:4–5')
add(42,'HAD-008','hadith','İbn Mâce 2474’te Âişe’ye nispet edilen su, tuz ve ateşin esirgenmemesi haberi, görüntülenen Darussalam derecelendirmesinde zayıftır. Bu nedenle ödünç ocak/su ağına sahih bir doğrudan delil olarak katılmadı; haberin vaat ettiği ayrıntılı sevaplar da ana açıklamaya taşınmadı. Zemahşerî/Râzî’deki tekrarlar ve Kurtubî’nin isnadı yumuşak bulması bağımsız sahihlik tanıkları değildir. Bu önemli adayın varlığı ile delil gücünün yetersizliği birlikte kaydediliyor.','IM2474|KASH107|RAZI107|QURT107',ayah='107:7',tradition='hadith',role='rejected_candidate',relation='thematic',status='weak',hadith_grade='daif',connection='rejected',priority='research',audience='research',transmitter='Âişe’ye nispet',source_ref='Sünen Ibn Mâce2474: Daif/Darussalam; Kurtubî107:7 son vecih; Zemahşerî/Râzî107:7')
add(42,'SRC-004','source_note','Taş, demir ve suyu maûn sayan merfû haber İbn Kesîr’de çok garip, yükseltilmiş biçimi münker ve zincirinde tanınmayan kişiler bulunan bir aktarım olarak eleştirilir. Süyûtî’deki tekrar bu tenkidi gidermez. Ayrıca İbn Kâniʿ’e bağlanan başka varyantta İbn Kesîr Ali en-Nümeyrî, Süyûtî Ali b. Ebî Tâlib adını verir; özgün eserle bu fark çözülemedi ve kişiler özdeşleştirilmedi. İbn Ebî Hâtim’in ilk nüshasında bağımsız isnad tenkidi de yapılmadı. Su/ocak yardımı başka delillerle desteklenebilir; bu özel liste sahih Peygamber açıklaması olarak kullanılmadı.','KATH107|SUY107',ayah='107:7',role='source_criticism',relation='direct_tafsir',status='weak',hadith_grade='not_assessed',connection='rejected',priority='research',audience='research',source_ref='İbn Kesîr107:7 İbn Ebî Hâtim’den Kurra b. Daʿmûs haberi/tenkit ve İbn Kâniʿ varyantı; Süyûtî107:7 ilgili üç aktarım')
add(43,'TAF-013','tafsir','Veyl için de açıklama düzeylerini ayırmak gerekir. Kurtubî 107:4’te azap der; Râzî tehdidin suçun büyüklüğünü gösterdiğini açıklar. Taberî ise cehennemde irin akan bir vadi açıklamasını verir. Bu özel tasvir, kelimenin sözlük anlamının tamamı veya burada bağımsız sahih bir hadisle doğrulanmış coğrafya olarak alınmadı. Ayette ocak/ateş ismi geçmez; namazı önemsemeyen tavır için ağır tehdit vardır. Ocaktan ceza ateşine geçiş, aşağıdaki açık Kur’an sahneleriyle yapılan ayrıca işaretli karşılaştırmadır.','QURT107|RAZI107|TAB107|QURAN',ayah='107:4-5',tradition='dirayet',role='semantic_range',relation='direct_tafsir',status='reported',priority='core',audience='general',source_ref='Kurtubî107:4; Râzî107:4–5 birinci mesele; Taberî107:4')
add(44,'CQ-006','cross_quran','Hâkka 69:25–37, hesap defterini, azabı, Allahı tanımamayı ve yoksulun yemeğine teşvik etmeyişi aynı ceza sahnesinde açıkça birleştirir. Kurtubî 107:3’te 69:34’ü zaten anmaktadır. Mutaffifîn 83:10–17’de veyl, din gününü yalanlama ve yanma; Nisâ 4:10’da yetim malını haksız yeme ile ateş; Kāf 50:24–25’te hayrı engelleme ile cehennem birlikte bulunur. Bunlar güçlü metinsel karşılıklardır. Hâkka’daki yanmayı “paylaşılmayan ocak” diye adlandırmak ise ayetin lafzı değil, bu ortak sahnelerden kurulan imgedir.','QURAN|QURT107',ayah='107:1-7',tradition='edebi',role='intertext',relation='comparative',status='explicit',connection='strong',priority='extended',audience='general',source_ref='69:25–37,83:10–17,4:10,50:24–25,92:14–16; Kurtubî107:3 Hâkka karşılaştırması')
nov(44,15,'Ocak/fırın yardımının Râzî’de somut örneği, Hâkka ile teşviksizlik/azap bağının Kurtubî’de açık öncülü vardır. Bu yüzden yardım-ateş karşıtlığının bütün bileşenleri yeni değildir. Fakat namaz ailesindeki ateş kullanımından başlayıp s-k-n ocağı, maûn yardımı ve ceza ateşini tek kök sahnesine toplayan tam örgü incelenen 107 pasajlarında açık bulunmadı. Sentez kısmî öncüllüdür ve Maqāyîs’in iki ayrı asıl kaydına bağlıdır; ateş/namaz özdeşliği yahut zayıf su-tuz-ateş haberinin sahihliği olarak sunulamaz.','partial','Maqāyîs صلي/سكن; Râzî107:7 fırın örneği; Kurtubî107:3 Hâkka,107:7 son vecih/isnad kaydı; Kur’an69:25–37,83:10–17,4:10,50:24–25,92:14–16; İbn Mâce2474.','MAQ|QURAN|IM2474',[42,43,44],relation='comparative')

# Account, debt and obedience, including genuine early and late alternatives.
add(47,'MTH-014','method_note','Dîn/hesap ile dayn/borç aynı dil ailesinde yan yana kaydedilir; Maqāyîs bunları boyun eğme ve yükümlülükle ilişkilendirir. Ancak 107:1’deki dîn, borç senedi veya alacak-borç bakiyesi değildir. Aynı şekilde kezebe aleyke kalıbının teşvik/yükümlülük kullanımı Maqāyîs’te eski, güç açıklanan ve artık kullanılmayan dil malzemesi diye tanıtılır. Bu kalıp, yukadhdhibu bi’d-dîn fiilinin sözlükte “borcunu reddetmek” olduğu sonucunu vermez. Hesap defteri, yükümlülüğün ahlâkî ciddiyetini görünür kılan benzetmedir.','MAQ|SIHAH|TAB107|RAZI107',ayah='107:1|107:7',role='constraint',relation='lexical',status='explicit',priority='core',audience='general',source_ref='Maqāyîs دين/كذب; Sıhâh دين; Taberî/Râzî107:1')
add(48,'SEM-004','semantic_history','Maûnu Câhiliye’de yarar/bağış, İslâm’da zekât/itaat diye ayıran kayıt Sıhâh, Lisân ve tefsirlerde gerçekten bulunur. Bu, sözlük geleneğinin geçmişe dönük açıklamasıdır; kelimenin belirli yılda eski bütün anlamlarını bırakıp yalnız zekât olduğu kanıtlanmış bir değişim değildir. Nitekim aynı kaynaklar su, araç ve genel iyilik duyularını da sürdürür. Râzî 107:7’de iyi boyun eğme yorumunu açıkça verir. Dîn ve maûn arasındaki itaat bağı bu yüzden yalnız yeni bir kök yankısı değildir; klasik yorum aralığının da parçasıdır.','SIHAH|LISAN|RAZI107|QURT107|TAB107',ayah='107:1|107:7',tradition='edebi',role='historical_development',relation='lexical',status='reported',priority='extended',audience='advanced',source_ref='Sıhâh/Lisân معن; Râzî107:7 itaat vecihleri; Kurtubî/Taberî107:7')
add(48,'MTH-015','method_note','Hakkı götürmek ile hakkı inkârdan sonra tanımak için karşıt emʿan kullanımları Lisân’ın m-ʿ-n maddesinde gerçekten kaydedilir; itaat eden deve örneği de vardır. Bu, iki hukuk tavrını aynı ailede görmeye imkân veren sözlük delilidir. Ancak Lisân derlemesinin bunu önceki kaynaklardan aktarması, her ilk kaynağın bağımsız nüshasının denetlendiği anlamına gelmez. Ayrıca maûnun maʿûne kökeni ihtimali ve çok anlamlılığı sürer: bir ayette aynı anda bu karşıt deyimlerin tamamı kastedilmiş sayılamaz.','LISAN|MAQ|SIHAH',ayah='107:7',role='clarification',relation='lexical',status='explicit',priority='research',audience='research',source_ref='Lisân معن: أمعن بحقي/أمعن لي به ve itaat eden deve; Maqāyîs معن')
add(49,'NZM-002','nazm','Sûrenin sonunu başa bağlama Bikâî’de açıkça vardır: sona varan maûnu esirgeme, baştaki dîni yalanlamayı yeniden görünür kılar. Râzî de son ayette ilişkilerin ters çevrilmesini söyler: Allah için yapılacak ibadet insanlara gösterilir, insanlara ulaşması gereken yarar onlardan saklanır. Bu güçlü nazm öncülü, hesapla en küçük yardımı aynı ahlâkî ölçüde buluşturur. “Hesap defteri” somutlaştırması projenindir; ilk-son birliğin kendisini bütünüyle yeni diye sunmak doğru değildir.','BIQ107|RAZI107',ayah='107:1-7',tradition='nazm',role='early_attestation',relation='structural',status='explicit',priority='core',audience='general',source_ref='Bikâî107:7 sonun başa dönmesi; Râzî107:7 son paragraf')
add(49,'CQ-007','cross_quran','Meâric 70:19–35 bu çerçeve için çok belirgin bir olumlu karşı dizidir: eline hayır geçince esirgeyen insandan namazı sürdürenlere, malındaki bilinen hakka, din gününü tasdike ve namazı korumaya geçer. S107’deki inkâr-esirgeme-namaz üçlüsü burada başka yönde dizilir. Fussilet 41:6–7 zekât vermemeyi ahiret inkârıyla, İsrâ 17:26 ve Zâriyât 51:19 ise paylaşmayı hak diliyle bağlar. Bu metinsel yakınlık, her yardım türünü yalnız fıkhî borç yahut aynı tarihli tek emir saymadan okunmalıdır.','QURAN',ayah='107:1-7',tradition='edebi',role='intertext',relation='comparative',status='explicit',connection='strong',priority='core',audience='general',source_ref='Kur’an70:19–35,41:6–7,17:26,51:19,82:9,1:4')
nov(49,16,'Dîn için hesap/itaat, maûn için zekât/itaat ve yoksulun hakkı klasik kaynaklarda doğrudan vardır. Bikâî’nin ilk-son dönüşü ve Râzî’nin ibadeti gösterip insanın yararını saklama karşıtlığı da tam nazm öncülleridir. Bu yüzden iki ucun ahlâkî bağı yeni sayılmadı. Dayn, hakkı tanıma/kaçırma deyimleri ve Meâric karşı dizisini “hesap defteri”ne yerleştiren bu somut ağ ise incelenen bölümlerde tam biçimiyle bulunmadı. Kısmî öncüllü proje sentezi, parasal borcu 107:1’in tek çevirisi yapmamalıdır.','partial','Maqāyîs دين/كذب/معن; Sıhâh دين/معن; Lisân معن hak deyimleri; Bikâî107:7 ilk-son; Râzî107:7 son karşıtlık; Kur’an70:19–35,41:6–7,17:26,51:19.','MAQ|SIHAH|LISAN|QURAN',[47,48,49],relation='structural')

# Prayer directed towards others: an actual source anchor with scope limits.
add(52,'TAF-014','tafsir','Salâtın dua kullanımı ve ibadet kullanımı eski kaynaklarda ayrıdır. Maqāyîs ikinci asılda ikisini birlikte açıklar; Allahın salâtını ise yaratılmışın kıyam/rükû/secde eylemi gibi tanımlamaz. Tevbe 9:103’te Taberî, Peygamberin mal verenlere dua ve istiğfarını, onlar için huzur/teskin olmasını öne çıkarır; başka rivayetlerde rahmet ve vakar da vardır. Bu, salâtın başkasına yönelen yararını okumak için gerçek bir kaynak dayanağıdır; her musallînin burada yalnız dua ettiği anlamına gelmez.','MAQ|TAB9103|QURAN',ayah='107:4-5',tradition='dirayet',role='clarification',relation='lexical',status='explicit',priority='core',audience='general',source_ref='Maqāyîs صلي ikinci asıl; Taberî9:103 دعا/استغفار/سكن açıklamaları')
add(52,'QIR-003','qiraat','Ana metindeki “inne salawâtike sekenun lehum” alıntısı çoğul salavât okumasını yansıtır; kullanılan Hafs ayet metninde salâteke tekildir. Taberî 9:103’te Medine okuyucularının çoğulu, Irak ve bazı Mekke okuyucularının tekili okuduğunu kaydeder. Kendi tercihi tekildir; gerekçesini dua anlamının öne çıkmasıyla açıklar, huzurun namaz sayısına bağlı olmadığını belirtir. İki biçim arasında bu gerçek aktarım farkı ana alıntı değiştirilmeden kaydediliyor. Tek tek okuyucu isnadları burada bağımsız kıraat kitabıyla denetlenmedi; bu karşılaştırma için yeni canonical hükmü eklenmedi.','TAB9103|QURAN',ayah='107:4-5',tradition='rivayet',role='semantic_range',relation='grammatical',status='reported',priority='research',audience='research',source_ref='Taberî9:103 tekil/çoğul kıraat ve tercih bölümü; yerel Hafs/Uthmani 9:103')
add(53,'HAD-009','hadith','Buhârî’de Abdullah b. Ebî Evfâ, sadaka getirenlere Peygamberin dua ettiğini ve kendi ailesi için de dua ettiğini aktarır. Bu sahih haber, Tevbe 9:103’ün mal verme ile Peygamber duasını yan yana getiren pratiğine somut karşılıktır. S107’nin doğrudan hadis tefsiri değildir. Malın payı, dua ve gönül teskinini birlikte düşünebilmek için güçlü tematik yapıtaşıdır; bütün dua/yardım alışverişlerini otomatik ve ölçülebilir bir huzur yasası yapmaz.','BUK1497|TAB9103',ayah='107:4-7',tradition='hadith',role='corroboration',relation='thematic',status='explicit',hadith_grade='sahih',connection='strong',priority='extended',audience='general',transmitter='Abdullah b. Ebî Evfâ',source_ref='Sahîh Bukhârî1497; Taberî9:103')
add(53,'MTH-016','method_note','Tevbe 9:103’ün yakın bağlamı 9:102–104, kusurlarını kabul edenler, tövbe, sadaka ve Peygamberin duasıyla ilgilidir. Taberî de arındırma/istiğfar yönünü bu bağlamda açıklar. Bu nedenle pay-dua-huzur dizisi gerçekten vardır; fakat muhatabı ve olay bağlamı S107’nin musallîn lafzından farklıdır. S107’ye taşınan şey hazır bir nüzul sebebi veya burada emredilmiş aynı döngü değil, namaz ile başkasının hakkının kopmaması için kullanılan karşılaştırmalı okuma modelidir.','TAB9103|QURAN',ayah='107:4-7',role='constraint',relation='comparative',status='explicit',priority='extended',audience='general')
add(54,'TAF-015','tafsir','Dış görünüşteki namazın ahlâkî etkisinin kopması için Râzî güçlü bir öncül sağlar. Ankebût 29:45’i anıp namazın kötülükten alıkoyması gerekirken bu kişilerin niçin yetime zarar verdiğini sorar; cevapta riya ve sehv nedeniyle hakiki yönelişin eksilmesini açıklar. Aynı gövdede namazın suretini yerine getirmek ile Allahı hatırlamak ayrılır. Ayrıca bu kusurları taşıyan herkesin mutlaka münafık sayılamayacağını belirtir. Klasik açıklama etkisiz şekli eleştirir; görünür bir eksiklikten kişinin gizli imanına kesin hüküm çıkarmaz.','RAZI107|QURAN',ayah='107:2-6',tradition='dirayet',role='early_attestation',relation='direct_tafsir',status='explicit',priority='core',audience='general',source_ref='Râzî107:4–5 birinci/ikinci mesele:29:45, suret/zikir ve her kusurun nifak olmaması')
add(54,'HAD-010','hadith','Müslim’de Ebû Zer, iyi iş yapan bir kişinin insanlarca övülmesini sorar; cevap bunu mümine peşin verilen bir müjde olarak niteler. Bu sahih hadis, insanların bir ameli görmesi veya onu beğenmesinin tek başına riya sayılmayacağını gösteren tematik kontrol sağlar. Zemahşerî ve Râzî de açık farzı yerine getirmeyi, örnek olmayı ve övgü arayarak yapmayı ayırır. Riya teşhisi, seyircinin varlığından önce amelin maksadına bağlıdır.','MUS2642A|KASH107|RAZI107',ayah='107:6',tradition='hadith',role='constraint',relation='thematic',status='explicit',hadith_grade='sahih',connection='strong',priority='core',audience='general',transmitter='Ebû Zer',source_ref='Sahîh Muslim2642a; Zemahşerî/Râzî107:6')
add(55,'HAD-011','hadith','Müslim’in Ebû Hüreyre rivayetinde dulun ve yoksulun ihtiyacını gidermek için uğraşan kişi Allah yolunda mücadele edenle karşılaştırılır. Rivayetin devamındaki sürekli namaz ve oruç benzetmesini aktaran râvi ise “sanırım şöyle de dedi” diyerek lafız hakkında ihtiyat gösterir. Böylece yoksula hizmet ile ibadetin aynı ahlâkî ağırlıkta buluşması için sahih bir tematik delil vardır; devam lafzındaki râvi tereddüdü saklanmamalıdır. Bu, 107:3–5’in doğrudan açıklaması diye sunulmuyor.','MUS2982',ayah='107:3-5',tradition='hadith',role='corroboration',relation='thematic',status='explicit',hadith_grade='sahih',connection='strong',priority='extended',audience='general',transmitter='Ebû Hüreyre',source_ref='Sahîh Muslim2982; devamındaki وأحسبه قال kaydı')
add(55,'CQ-008','cross_quran','Hûd 11:87’de namaz ile mal tasarrufu bağını soranlar Şuayb’ın karşıtlarıdır; sözleri namazın ticaret ahlâkına karışmasını alaya alır. Meryem 19:31 ve Bakara 2:83 namazı ve zekâtı birlikte emreder; Tevbe 9:54 istemeksizin verme ve üşenerek namazı aynı kabul sorununda toplar. Ankebût 29:45 davranışı dönüştürme, Meryem 19:59 ise sonraki kuşakların namazı yitirmesi bağlamıdır. Aynı anda hepsi aynı kişi veya olayı anlatmaz; namazı hakkın dışında tutan görünüşü sınamak için birlikte okunur.','QURAN|RAZI107',ayah='107:4-7',tradition='edebi',role='intertext',relation='comparative',status='interpretive',connection='strong',priority='extended',audience='general',source_ref='11:87,19:31,2:83,9:54,29:45,19:59; Râzî107:4–5 birinci mesele')
nov(55,17,'Başkası için dua, mal verenin teskin edilmesi ve şeklen namazın ahlâkî etkisinin eksilmesi gerçek eski öncüllerdir: Taberî9:103, Buhârî1497 ve Râzî107:4–5 bunları ayrı bağlamlarda açıkça verir. Dolayısıyla bütün dışa dönük namaz fikri yeni sayılmadı. Fakat s-k-n huzur/miskin ailesiyle pay-dua-huzur döngüsünü S107’nin kırılmış sosyal dolaşımına böyle yerleştiren tam ağ incelenen 107 pasajlarında açık bulunmadı. Kısmî öncüllü sentez, Peygambere yönelik dua emriyle S107’nin namazını aynı bağlam veya kesin nüzul sırası saymaz.','partial','Taberî9:103 görüntülenen bütün gövde,dua/sken/kıraat; Buhârî1497; Maqāyîs صلي/سكن; Râzî107:4–5 birinci/ikinci mesele; Kur’an9:102–104,11:87,19:31,2:83,9:54,29:45,19:59; Muslim2642a.','TAB9103|BUK1497|MAQ|QURAN|MUS2642A',[52,53,54,55],relation='comparative')

# Each major meeting is audited separately rather than hidden in one final label.
add(58,'MTH-017','method_note','Alak 96:9–14’te soru, namazı engelleme, yalanlama/yüz çevirme ve Allahın görmesi açıkça bir aradadır. Bu yakınlık görme eksenine güçlü metinsel malzeme verir. Suhâ ise iki sûrede de anılmaz; yıldız, yalnız sözlük ailesinden katılan bir imgedir. “Asıl seyirci” sözü ilâhî bilgi ve insanın hesabı önemsememesi için okunabilir; Allahın görmesini insanın gösteri seyretmesi biçiminde tasvir eden bir eşitlik kurmaz.','QURAN|MAQ',ayah='107:1|107:4-6',role='constraint',relation='comparative',status='explicit',priority='extended',audience='general',source_ref='Kur’an96:9–14; Maqāyîs سهو/rأي')
nov(58,18,'Alak’ın soru/namaz/engel/tekzib/ilâhî görme dizisi metinde vardır; Suhâ’nın zor görünmesine dayalı sözlük önerisi de eskidir. Buna karşılık yıldızı Alak’ın gören merci sorusu ve S107’deki gözden kaçan yetimle bu tek karşılaşmaya sokan ağ incelenen ayet açıklamalarında açık bulunmadı. Yapıtaşları klasik, birleşim projenindir. Bu değerlendirme Suhâ önerisinin kaynakta kesin olmayışını ve yıldızın ayetlerde hiç adlandırılmamasını korur.','building_blocks_only','Kur’an96:6–19 bütün yakın bağlam; Maqāyîs سهو/رأي; Râgıb رأي soru kalıpları.','QURAN|MAQ|RAGHIB',[58],relation='comparative')
add(59,'MTH-018','method_note','“Yetimi iten el ateşe itilir” ifadesinin güçlü yanı aynı daʿʿ lafzının karşıt sahnelerde oluşudur; Râzî ve Kurtubî de Tûr bağlantısını görür. Fakat Tûr 52:11–16, yalanlayanların ateşe itilmesini söyler; her birini S107’deki tek yetim iticiyle özdeşleştirmez. İtişin karşılığı edebî/ahlâkî bir çıkarımdır. Hâkka’nın teşviksizlik ve ceza bağı daha açık olsa da “paylaşılmayan ocak” onun lafzı değildir. Önceki klasik öncül ile yeni somut tersleme aynı anda korunmalıdır.','QURAN|RAZI107|QURT107',ayah='107:1-3|107:7',role='constraint',relation='comparative',status='interpretive',priority='core',audience='general',source_ref='52:11–16,69:25–37; Râzî107:3, Kurtubî107:2–3')
nov(59,19,'Yetimi itme ile Tûr’un cehenneme itilişi, Hâkka’nın teşvik etmeme lafzı ile ceza sahnesi açık klasik intertext öncüllerine sahiptir. Bu ağ yeni diye bütünüyle sahiplenilmedi. İten kişinin tek tek aynı kimlikle itilmesi ve ortak bir ocağın paylaşılmamasından yanmaya geçiş ise incelenen açıklamaların açık hükmünü aşan proje somutlaştırmalarıdır. Kısmî klasik tanıklık vardır; kişiler arası özdeşlik ve ocak benzetmesi çıkarım düzeyinde bırakıldı.','partial','Râzî107:3 daʿ açıklaması; Kurtubî107:2 Tûr,107:3 Hâkka; Kur’an52:11–16,69:25–37.','QURAN',[59],relation='comparative')
add(60,'MTH-019','method_note','Müddessir 74:42–47’deki dört itiraf namaz kılmama, yoksulu doyurmama, yanlış uğraşa başkalarıyla dalma ve din gününü yalanlamadır. Bu, S107’ye güçlü bir tematik yakınlıktır. Ancak nakhûdu ne sahunla aynı kelime ne de burada gerçek bir suya girme tasviridir. Ayrıca Müddessir’de namaz kılmama açıkça söylenir; S107, musallîn denen kişilerin namazla ilişkisinin bozulmasını anlatır. İtirafı tüm imgelerin buluşması diye okumak bu farklılıkları silemez.','QURAN|TAB107|KATH107',ayah='107:1-7',role='constraint',relation='comparative',status='explicit',priority='core',audience='general',source_ref='Kur’an74:40–47,52:12,51:11; Taberî/İbn Kesîr107:4–5')
nov(60,20,'Müddessir’deki namaz/yoksul/yanlış uğraş/hesap inkârı dizisi doğrudan ayetlerde vardır. Fakat bunu S107’nin yıldız, bakış, ev, su, kumaş ve ocak imgelerinin tek itirafı olarak okuyan tamamlanmış ağ incelenen klasik 107 pasajlarında açık bulunmadı. Bu nedenle yapıtaşları düzeyinde tanıklık verildi. Açık lafız yakınlığı kuvvetlidir; yanlış uğraşa dalmanın mutlaka gaflet suyu olması ve namazı hiç kılmamakla görünen namazın bozulmasının özdeşliği desteklenmedi.','building_blocks_only','Kur’an74:40–47,52:10–16,51:10–14; Taberî51:11 su benzetmesi; Maqāyîs سهو.','QURAN|TAB5111|MAQ',[60],relation='comparative')
add(61,'MTH-020','method_note','Birçok maûn anlamının aktarılması, bir ayetin hepsini aynı anda söylediğini ispatlamaz. Zekât, su, ev aracı ve itaat kimi müfessirlerce alternatif, kimilerince geniş bir yarar kapsamının örnekleri sayılır. Taberî’nin geniş tercihi gerçek bir klasik dayanak olsa da her özel etimoloji aynı kesinliğe sahip değildir. Ev-su-borç birleşimi, bu yorum çoğulluğunu açıklayan edebî model olarak kalmalıdır; yetimin malı, miskinin evi ve ödüncün riski hakkındaki daha önce belirtilen sınırlar burada da geçerlidir.','TAB107|RAZI107|QURT107|LISAN|QURAN',ayah='107:1-7',role='methodological_note',relation='lexical',status='explicit',priority='core',audience='general')
nov(61,21,'Maûnun su/araç/itaat/zekât kapsamı, hakkı tanıma deyimleri, barındırma, kap doldurma ve korunak eski malzemedir. Ev-su-borç biçimindeki üç sahne ve el/çocuk/kap/barınak/koruma karşılaşmaları ise incelenen 107 pasajlarında aynı tam ağ olarak bulunmadı. Kısmî klasik öncüllü sentezdir: küçük yardım ve hakkın birliği eski, çeşitli kök ve ayet parçalarını bu hane sahnesinde birlikte okutma projeye aittir. Aynı anda çok anlam dayatılması yerine attested seçenekler görünür bırakılıyor.','partial','Maqāyîs دع/منع/معن/دين; Lisân معن; Râzî107:7 örnekler ve son nazm; Kur’an23:50,93:6,4:2/6/7.','MAQ|LISAN|QURAN',[61],relation='structural')
nov(62,22,'Meâric’te namaz, maldaki hak ve din gününü tasdik açık bir olumlu dizidir; Tevbe’de malın alınması ve Peygamberin teskin eden duası açıkça vardır. Ayrıca Bikâî 107’nin karşıtlarını Enfâl’de namaz/infak/iman üzerinden arar; bu çapraz okuma yöntemi de klasik öncüllüdür. Meâric ile Tevbe’yi birlikte S107’nin kırılmış pay-dua-huzur döngüsünün tamamlanmış karşı sahnesi yapma ise incelenen pasajlarda açık bulunmadı. Eski motifleri böyle birleştiren kısım projeye aittir; bu üç sûrenin kesin nüzul sırası ileri sürülmedi.','partial','Kur’an70:19–35,9:102–104,8:3–4/35/41/47; Taberî9:103 bütün gövde; Buhârî1497; Bikâî107:7 خاتمة bölümünde Enfâl karşılaştırması.','QURAN|TAB9103|BUK1497',[62],relation='comparative')
add(63,'NZM-003','nazm','Komşu sûrelerle ilişki için Bikâî’nin açık öncülü vardır. 107:1’de Kureyş’in doyurulması ve güvenliği karşısında ibadet yükümlülüğünü önceki sûreden taşır; S107’de o yükümlülüğün inkâr ve toplumsal sertlikle bozulduğunu okur. 108:1 açıklamasında ise en küçük yararı esirgemeyle biten sûrenin ardından en bol bağışın verilmesini karşılaştırır. Bu nazm, mushaf sırasındaki komşuluğu açıklar. Aynı sıra kesin nüzul sırası diye gösterilmedi.','BIQ107|BIQ108|QURAN',tradition='nazm',role='nazm',relation='structural',status='explicit',priority='core',audience='general',source_ref='Bikâî107:1 Kureyş bağlantısı; Bikâî108:1 açılış paragrafı; Kur’an106:1–4/108:1–3')
add(63,'NZM-004','nazm','Bikâî’nin sûrenin sonuç bölümündeki Enfâl karşılaştırması, namaz/infak ve gerçek iman, ev çevresindeki boş ibadet, yetim-yoksul payı ve gösterişle çıkış ayetlerini yan yana getirir. Bu, S107’yi yalnız bağımsız kelime imgeleriyle değil karşıt bir Kur’an dizisiyle okumanın klasik örneğidir. Onun bütün açıklaması bu projedeki ev, yıldız veya kumaş ağının aynısı değildir. İncelenen metnin fiilen verdiği benzerlikler kayıt altına alındı; projeye benzeyen her nazmı projenin tam öncülü saymadım.','BIQ107|QURAN',tradition='nazm',role='early_attestation',relation='comparative',status='explicit',priority='extended',audience='advanced',source_ref='Bikâî107:7 خاتمة:8:3–4,8:32/35–36/41/47 karşılaştırmaları')
add(63,'SRC-005','source_note','Bikâî’nin aynı sonuç bölümünde sûre kelimelerinin sayısını hicrî yıllar ve zekâtı engelleyenlerle mücadele olaylarına bağlayan bir alımlama da vardır. Bu bölüm gerçekten görüldü; fakat sayısal eşleştirme bağımsız olay kronolojisi veya sûrenin nüzul tarihini belirleyen delil olarak kabul edilmedi. Burada doğrulanan, müfessirin o yorumunun varlığıdır; yorumda anılan tüm olayların tarihî ayrıntıları ve sayımın sonuçları ayrıca incelenmedi. Nazm tanıklığı ile tarih tenkidi ayrılmalıdır.','BIQ107',role='rejected_candidate',relation='historical',status='interpretive',historicity='uncertain',connection='rejected',priority='research',audience='research',source_ref='Bikâî107:7 خاتمة sonundaki kelime sayısı/yıl/zekât engelleme karşılaştırması')
nov(63,23,'Bu bütünleşik son okumanın omurgası eskidir: din/amel bağı, yetim ve yoksulun hakkı, an/fî ayrımı, riya karşılıklılığı, maûnun paylaşılması ve baş/son dönüşü incelenen kaynaklarda açık veya güçlü kısmî öncüllere sahiptir. Ev, Suhâ, kumaş, ayna, su, ayrı ateş aslı ve hesap defterini aynı dolaşıma toplayan tam örgü ise bu sınırlı taramada açık bulunmadı. Dolayısıyla kısmî klasik tanıklıklı proje sentezi sayıldı. Tek tek eski öğeler “yeni” diye etiketlenmedi; bütün literatür için yokluk hükmü veya kesin kaynak kökeni iddiası kurulmadı.','partial','Maqāyîs رأي/كذب/يتم/سهو/دع/حض/سكن/معن/صلي/دين/طعم/منع; Râgıb رأي/كذب/يتم/معن ilgili bölümleri; Sıhâh دين/معن/سكن; Lisân يتم/دع/معن; Taberî51:11 ve9:103; Kurtubî67:30; Bikâî108:1; Kur’an karşılaştırmaları; ilgili doğrulanmış hadis kayıtları.','MAQ|RAGHIB|SIHAH|LISAN|TAB5111|TAB9103|QUR6730|BIQ108|QURAN',[63],relation='structural')
add(63,'MTH-021','method_note','Bu katmanda yenilik, eski bir motifi Türkçede başka sözle söylemek değildir. Bir bileşenin açık klasik öncülü, daha dar bir kısmî öncülü veya yalnız sözlük/Kur’an yapıtaşı tek tek gösterildi. “Bulunmadı” yalnız adı verilen ve gerçekten okunan pasajlar için geçerlidir. İndirilen fakat okunmamış bir dosya, bütün cilt, kayıp ilk kaynak veya tamamlanmamış isnad araştırması bu yokluk hükmüne dahil değildir. Ana metindeki olgusal çatışmalar düzeltilmiş gibi gizlenmedi; ilgili notlarda açık bırakıldı.','PACK107|MAQ|TAB107|RAZI107|BIQ107',role='methodological_note',relation='methodological',status='explicit',priority='research',audience='research')
add(63,'SRC-006','source_note','Çekirdek tarama sekiz müfessirin 107:1–7 sayfalarında görüntülenen gövdeleridir; Râzî’nin 4 ve 5 sayfaları aynı üç meseleyi tekrarlar. Süyûtî 107:3 ve Beyzâvî 107:4 görüntülerinde ayet dışında açıklama yoktur. Bu gövdeleri okudum; bunu bütün eser nüshalarına veya dinamik sayfalamanın tümüne erişim diye genişletmedim. İbn Merdûye, Beyhakī/Hâkim tenkitlerinin ilk nüshaları, bazı Tehzîb/Cemhere sözlük atıfları ve bütün kıraat isnadları bağımsız denetlenmedi. Kaynak kayıtları ve sondaki kontrol notu bu tamamlanmamış alanları ayrıca belirtir.','TAB107|KATH107|SUY107|KASH107|RAZI107|BAY107|BIQ107|QURT107|PACK107',role='source_criticism',relation='methodological',status='explicit',priority='research',audience='research')

# A reported light reading is useful for meaning, with no invented canonical label.
add(23,'QIR-004','qiraat','Zemahşerî 107:2’de şeddeli yeduʿʿu yanında hafif “yedaʿu” okumasını da aktarır ve onu bırakma/uzak tutma diye açıklar. İtme ile ihmal yönünün ayrı lafızlarda görünebilmesi yorum aralığını genişletir. Bu kayıtta okuyucu adı verilmez; bağımsız kıraat tasnifi kontrol edilmediği için kanoniklik hakkında hüküm eklenmedi. Hafif okumadan ana şeddeli lafzın artık itme anlamını kaybettiği sonucu da çıkarılmadı.','KASH107',ayah='107:2',tradition='dirayet',role='semantic_range',relation='grammatical',status='reported',priority='research',audience='research',source_ref='Zemahşerî107:2: وقرئ يدع açıklaması')
add(2,'SRC-007','source_note','İbn Atiyye’nin görüntülenen sûre girişinde Mekkîlik, bildiği karşı görüş bulunmadığı kaydıyla söylenir; hemen ardından Saʿlebî’nin Medenî görüşü de aktarılır. Bu pasajı ve diğer girişlerdeki ayrılıkları birlikte okuyunca bir müfessirin sınırlı bilgi kaydını bütün geleneğin ittifakı diye kullanmak mümkün değildir. Burada elektronik pasajların söyledikleri karşılaştırıldı; basılı nüshaların tüm varyantları ve bu girişlerin özgün kaynak zincirleri denetlenmiş sayılmadı.','ATI107|QURT107|ALUS107',role='source_criticism',relation='historical',status='explicit',historicity='contested',priority='research',audience='research',source_ref='İbn Atiyye107:1 sûre girişi; Kurtubî/Âlûsî107:1 girişleri')

author_specs=[
('TAB107','Taberî, Câmiʿu’l-beyân','tabary','ksu'),
('KATH107','İbn Kesîr, Tefsîru’l-Kurʾâni’l-ʿazîm','katheer','ksu'),
('QURT107','Kurtubî, el-Câmiʿ li-ahkâmi’l-Kurʾân','qortobi','ksu'),
('SUY107','Süyûtî, ed-Dürrü’l-mensûr','seoty','tafsir'),
('KASH107','Zemahşerî, el-Keşşâf','zamakhshary','tafsir'),
('RAZI107','Fahreddin er-Râzî, Mefâtîhu’l-gayb','alrazy','tafsir'),
('BAY107','Beyzâvî, Envâru’t-tenzîl','baidawy','tafsir'),
('BIQ107','Bikâî, Nazmu’d-dürer','beqaay','tafsir')]
registry={}
for key,title,slug,host in author_specs:
    site='https://quran.ksu.edu.sa/tafseer' if host=='ksu' else 'https://quran-tafsir.net'
    refs=', '.join(f'[107:{a}]({site}/{slug}/sura107-aya{a}.html)' for a in range(1,8))
    limits='Râzî107:4/5 gövdeleri aynı üç meseleyi tekrarlar; iki bağımsız açıklama diye sayılmadı.' if key=='RAZI107' else 'Süyûtî107:3 görüntüsünde yalnız ayet vardır.' if key=='SUY107' else 'Beyzâvî107:4 görüntüsünde yalnız ayet vardır; ilgili namaz açıklamaları komşu gövdelerde de görünür.' if key=='BAY107' else 'Bu yedi görüntülenen açıklama gövdesi ve bu sayfalardaki girişler incelendi.'
    registry[key]=f'{title}, Mâûn açıklaması. {refs}. {limits} Bütün cilt veya basılı sayfa kollasyonu iddia edilmiyor.'
registry.update({
'ALUS107':'Âlûsî, Rûhu’l-meʿânî. [107:1 sûre girişi/soru/kıraat](https://quran-tafsir.net/alusy/sura107-aya1.html) ve [107:7 anlamlar/etimoloji/gramer](https://quran-tafsir.net/alusy/sura107-aya7.html) görüntülenen bütün gövdeler incelendi; 107:2–6 ayrıca taranmadı.',
'ATI107':'İbn Atiyye, el-Muharrerü’l-vecîz. [107:1 sûre girişi ve soru açıklaması](https://quran-tafsir.net/atia/sura107-aya1.html), görüntülenen bütün kısa gövde incelendi; sûrenin başka pasajları incelenmedi.',
'WAH107':'Vâhidî, Esbâbü’n-nüzûl. [Mâûn,107:1–2 aktarımları](https://quranpedia.net/surah/1/107/book/2919). Görüntülenen Âs b. Vâil/Ebû Süfyân haberleri incelendi; sayfa107:3–7 için açıklama vermiyor. Tarihî güvenilirlik ve isnad derecesi bağımsız tenkit eserleriyle sonuçlandırılmadı.',
'BIQ108':'Bikâî, Nazmu’d-dürer. [108:1](https://quran-tafsir.net/beqaay/sura108-aya1.html), görüntülenen bütün gövde; özellikle Mâûn’un vermemesi/Kevser’in vermesi bağlantısı incelendi. Kevser sûresinin bütün tefsiri taranmadı.',
'TAB5111':'Taberî, Câmiʿu’l-beyân. [51:11](https://quran.ksu.edu.sa/tafseer/tabary/sura51-aya11.html), görüntülenen bütün açıklama; ghmra ve İbn Zeyd’in su içinde kalma benzetmesi incelendi.',
'TAB9103':'Taberî, Câmiʿu’l-beyân. [9:103](https://quran.ksu.edu.sa/tafseer/tabary/sura9-aya103.html), görüntülenen bütün gövde; sadaka/tövbe, dua-istiğfar, seken, tekil/çoğul kıraat ve tercih bölümleri incelendi. Buradaki nüzul haberlerinin özgün isnadlarına ayrıca derece verilmedi.',
'QUR6730':'Kurtubî, el-Câmiʿ. [67:30](https://quran.ksu.edu.sa/tafseer/qortobi/sura67-aya30.html), görüntülenen bütün kısa gövde; maʿîn için akış/görünürlük ve köken alternatifleri incelendi.',
'MAQ':'İbn Fâris, Muʿcemu Maqāyîsi’l-luga. Öncelikli sözlük tanığı: [elektronik eser metni](https://arabic-keyboard.info/books/ar/read-book/مقاييس-اللغة); yalnız رأي,كذب,يتم,سهو,دع,حض,سكن,معن,صلي,دين,طعم,منع maddeleri incelendi. Ayrıca Hawramani’de İbn Fâris’e ait ayrı yazar bloklarıyla [يتم](https://arabiclexicon.hawramani.com/يتم/), [سهو](https://arabiclexicon.hawramani.com/سهو/), [صلى](https://arabiclexicon.hawramani.com/صلى/), [دين](https://arabiclexicon.hawramani.com/دين/), [معن](https://arabiclexicon.hawramani.com/معن/), [سكن](https://arabiclexicon.hawramani.com/سكن/), [طعم](https://arabiclexicon.hawramani.com/طعم/) karşılaştırıldı. İki asıl, düzensiz dal, muhtemel türeyiş ve kıyas sınırı kayıtları korundu. Kitabın bütünü okunmuş sayılmadı.',
'RAGHIB':'Râgıb el-İsfahânî, el-Müfredât. Hawramani’nin Râgıb’a ait yazar bloklarından [رأى](https://arabiclexicon.hawramani.com/رأى/) ve [كذب](https://arabiclexicon.hawramani.com/كذب/) bütün madde, [يتم](https://arabiclexicon.hawramani.com/يتم/) bütün madde, [معن](https://arabiclexicon.hawramani.com/معن/) yalnız ilgili معن bölümü incelendi; çıkarımın sonuna birleşen sonraki مقت maddesi kapsam dışıdır. Tüm site/yazar sözlüğü taranmadı.',
'SIHAH':'Cevherî, Tâcü’l-luga ve Sıhâhu’l-ʿArabiyye. Hawramani’de Cevherî’ye ait yazar blokları: [دين](https://arabiclexicon.hawramani.com/دين/), [معن](https://arabiclexicon.hawramani.com/معن/), [سكن](https://arabiclexicon.hawramani.com/سكن/), görüntülenen bütün maddeler incelendi.',
'LISAN':'İbn Manzûr, Lisânü’l-ʿArab. Hawramani’de İbn Manzûr’a ait yazar blokları: [يتم](https://arabiclexicon.hawramani.com/يتم/), [دعع](https://arabiclexicon.hawramani.com/دعع/), [معن](https://arabiclexicon.hawramani.com/معن/), görüntülenen bütün maddeler incelendi. Daha eski yazarların buradaki aktarımları, o yazarların bağımsız nüshaları okunmuş diye sayılmadı.',
'MUHKAM':'İbn Sîde, el-Muhkem ve’l-muhîtu’l-aʿzam. Hawramani’de İbn Sîde’ye ait [دين](https://arabiclexicon.hawramani.com/دين/) yazar bloğu bütünüyle incelendi; yargıda doğrulama kullanımı buradan kontrol edildi.',
'ASAS':'Zemahşerî, Esâsü’l-belâga. Hawramani’de Zemahşerî’ye ait [دين](https://arabiclexicon.hawramani.com/دين/) yazar bloğu bütünüyle incelendi; borç/yönetme/kendi dinine bırakma kullanımları kontrol edildi.',
'QURAN':'Kur’an, Hafs/Uthmani yerel metni: [quran-uthmani.tsv](/Volumes/aro/projects/quran-data/data/text/quran-uthmani.tsv). Özgün metindeki bütün Kur’an atıfları ve belirtilen yakın bağlamlar bu birincil ayet metniyle kontrol edildi; 179 ayetin tam kontrol listesi [quran_passages.txt](/Volumes/aro/projects/prose_generation/enrichment/v1/work/107/sources/quran_passages.txt) içindedir. Ayet metninin denetimi bir tefsir külliyatı taraması değildir.',
'PACK107':'Projenin özgün [images.md](/Volumes/aro/projects/prose_generation/_commentary/v16/out/s107/images.r13.map3.nohft.tool.tool/images.md), bitişik [ledger.md](/Volumes/aro/projects/prose_generation/_commentary/v16/out/s107/images.r13.map3.nohft.tool.tool/ledger.md), [sözlük paketi](/Volumes/aro/projects/prose_generation/_commentary/v16/work/s107/surah.r2/dictionary.md) ve [özgün packet.json](/Volumes/aro/projects/prose_generation/_commentary/v16/work/s107/images.r13.map3.nohft.tool.tool/packet.json). Ledger’daki hafıza iddiaları, eski üretim aşamasında dışlanan hadis/tefsir adayları ve kök-yankı ayrımları incelendi. Paket, ilk kaynakların bağımsız doğrulanması yerine geçmez.',
'SHAMA638':'Ebû Şâme, İbrâzü’l-meʿânî min Hirzi’l-emânî. [Şâtıbiyye638 beytinin açıklaması](https://www.islamicbook.ws/qbook/alom/ibraz-almaani-004.html), yalnız soru kalıbında Kisâî’nin hemze düşürmesi ve Nâfiʿ’in kolaylaştırması açıklayan paragraf incelendi; bütün cilt okunmadı.'
})
hadith_specs=[
('MUS2985','Muslim','2985','Ebû Hüreyre, kudsî amel/ortak maksadı','sahih: Sahîh Muslim'),
('MUS2986','Muslim','2986','İbn Abbas, duyurma/gösteriş karşılığı','sahih: Sahîh Muslim'),
('MUS2642A','Muslim','2642a','Ebû Zer, iyi amelin övülmesi','sahih: Sahîh Muslim'),
('MUS622','Muslim','622','Enes, geciktirip aceleyle kılınan namaz','sahih: Sahîh Muslim'),
('MUS2982','Muslim','2982','Ebû Hüreyre, dul/yoksul için çaba; devam lafzındaki râvi tereddüdü korundu','sahih: Sahîh Muslim'),
('BUK6005','Bukhari','6005','Sehl b. Saʿd, yetime bakım sağlayan','sahih: Sahîh Bukhârî'),
('BUK1224','Bukhari','1224','Abdullah b. Buhayne, namaz içinde unutma ve sehiv secdesi','sahih: Sahîh Bukhârî'),
('BUK2353','Bukhari','2353','Ebû Hüreyre, ihtiyaç fazlası su/otlak','sahih: Sahîh Bukhârî'),
('BUK1497','Bukhari','1497','Abdullah b. Ebî Evfâ, sadaka getirenlere dua','sahih: Sahîh Bukhârî'),
('BUK1479','Bukhari','1479','Ebû Hüreyre, görülmeyen ihtiyacı olan miskin','sahih: Sahîh Bukhârî'),
('AD1657','Abudawud','1657','İbn Mesʿûd, Peygamber dönemindeki kova/tencere maûn tanıklığı; sahâbî sözü','hasan: sayfadaki Al-Albânî derecelendirmesi'),
('IM2474','Ibnmajah','2474','Âişe’ye nispet, su/tuz/ateş; zayıf aday','daif: sayfadaki Darussalam derecelendirmesi')]
for key,book,no,topic,grade in hadith_specs:
    slug={'Muslim':'muslim','Bukhari':'bukhari','Abudawud':'abudawud','Ibnmajah':'ibnmajah'}[book]
    registry[key]=f'{book}, [{no}](https://sunnah.com/{slug}:{no}). {topic}. Görüntülenen rivayet/metin ve kaynak numarası doğrulandı; derece dayanağı {grade}. Yeni bir isnad tahrici veya bağımsız derece hükmü verilmedi.'

audit_note='''### Kaynak-eleştiri ve kontrol kapsamı

Çekirdek klasik tarama, yukarıdaki sekiz müfessirin yedi ayet sayfasında fiilen görüntülenen açıklama gövdeleridir. Râzî’de107:4 ve107:5’in aynı üç meseleyi tekrar etmesi, Süyûtî107:3 ve Beyzâvî107:4’ün açıklamasız görüntüleri ayrı kaydedildi. Sayfanın adresi bütün cildi kapsadığı varsayılmadı; “sonraki paragrafı ekle” kopyalama yardımının bütün eseri dinamik sayfaladığı kanıtlanmış sayılmadı. Pasajlar Arapça metinleriyle incelendi; elektronik metnin her ayrıntısı basılı nüshalarla kollasyon edilmedi. Âlûsî yalnız107:1/7, İbn Atiyye107:1, Vâhidî’nin görünen107:1–2 haberleri ve kaynak kayıtlarında tek tek belirtilen ek ayet gövdeleri tarandı. İndirilen Bikâî106:4 gövdesi okunmadı ve yenilik taramasına katılmadı; komşu sûre bağı Bikâî107:1 ve108:1’den denetlendi.

Sözlükte Maqāyîs ana tanık tutuldu; yalnız adı verilen on iki madde okundu. Hawramani’de aynı kök sayfasında birçok yazar vardır: dosyası indirilmiş bütün yazar maddeleri okunmuş sayılmadı. Gerçekten okunan on dokuz ayrı yazar/madde bloğu ve eser metninden okunan Maqāyîs maddeleri çalışma kayıtlarında belirtilir. Tehzîb ve Cemhere’nin pakette anılan her alt pasajı bağımsız ilk nüshadan denetlenmedi. Özellikle yemin niyetine ilişkin d-y-n B007 kontrolü eksiktir. Lisân’ın eski yazar aktarımları ilk eserler için tam tarama yerine sayılmadı. Suhâ’da ihtimal, sehvede düzensiz dal, ṣ-l-y’de iki asıl ve maʿîn/maûn köken alternatifleri açıkça korundu.

Hadislerde Sahîhayn rivayetleri koleksiyon kaydıyla, Ebû Dâvûd1657 ve İbn Mâce2474 ise sayfada gösterilen derecelendirmeyle değerlendirildi. Bağımsız yeni isnad hükmü verilmedi. Saʿd/Ebû Berze ve taş-demir-su haberleri için doğrulanan şey İbn Kesîr/Süyûtî’nin açık kaynak tenkididir; İbn Ebî Hâtim, Beyhakī, Hâkim ve İbn Merdûye’nin özgün metinleri ayrıca taranmadı. İsnadı belirsiz nüzul haberleri kesin olay ve tarih sayılmadı. Tematik hadisler doğrudan ayet tefsiri etiketi almadı; İbn Mesʿûd’un araç haberi sahâbî dönem tanıklığı olarak ayrıldı. MUS2982’deki devam lafzı tereddüdü korundu. Doğrudan hadis sitesi indirmesinde erişim kısıtı olduğu için hadis pasajları web aracının görüntülediği birincil koleksiyon sayfalarından kontrol edildi.

Yenilik değerlendirmeleri yalnız bu sınırlı, gerçekten okunan korpus içindir. Doğrudan eski açıklamalar, kısmî öncüller ve yalnız yapıtaşları ayrı anlatıldı; bütün tefsir tarihinde yokluk veya ilk kez keşif hükmü verilmedi. Yirmi üç yenilik kaydı, her büyük proje ağını ve son bölümdeki birleşmeleri tek tek kapsar. Kesin nüzul tarihi/sırası, bütün kıraat isnadlarının tasnifi, her özel sözlük naklinin ilk kaynak denetimi ve modern literatürün sistematik taraması tamamlanmış araştırmalar değildir. Kanonik hüküm yalnız Ebû Şâme’nin gerçekten kontrol edilen Kisâî/Nâfiʿ açıklamasına verildi; diğer okuma haberleri aktarım sınırında bırakıldı. Eksik S107_comprehensive_reference_v2.md dosyasının içeriği varsayılmadı.

Özgün metin değiştirilmedi. Ayet107:3’te yemek kelimesinin bulunduğu,107:6’nın son ayet olmadığı,9:103’ün tekil/çoğul okuma farkı, yoksulluğun zorunlu evsizlik olmaması, Tûr sahnelerinde bireysel özdeşliğin söylenmemesi ve namaz/ateş kök ayrımı ilgili yerlerde açık yöntem notlarıyla gösterildi. Bütün özgün paragraflar, başlıklar, Kaynaklar satırları ve mevcut etiketler sırayla korunmuştur. Kanıt matrisi son ek katmanların yazılmasından önce tamamlandı. Kontrol tarihi:2026-10-02; annotation_schema_version:2.0.
'''

def render(d):
    return '{'+', '.join(k+':'+(str(v) if k in enums else json.dumps(v,ensure_ascii=False)) for k,v in d.items())+'}'

def compose():
    base=BASE.read_text()
    cm=json.loads((W/'claim_map.json').read_text())
    assert hashlib.sha256(BASE.read_bytes()).hexdigest()==cm['base_sha256']
    # Make the final all-network audit list every Quran passage actually inspected,
    # rather than treating an unspecified source bundle as evidence coverage.
    refs=', '.join(q['ref'] for q in json.loads((W/'quran_passages.json').read_text()))
    registry['QURAN']=registry['QURAN'].replace('179 ayetin',str(len(json.loads((W/'quran_passages.json').read_text())))+' ayetin')
    final_extra='Maqāyîs رأي/كذب/يتم/سهو/دع/حض/سكن/معن/صلي/دين/طعم/منع; Râgıb رأي/كذب/يتم bütün maddeler ve معن ilgili bölüm; Sıhâh دين/معن/سكن; Lisân يتم/دع/معن; Taberî51:11 ve9:103 görüntülenen bütün gövdeler; Kurtubî67:30 bütün gövde; Bikâî108:1 bütün gövde; Kur’an gerçekten okunan ayetler: '+refs+'. Hadislerin ayrı kontrol listesi: Muslim2985/2986/2642a/622/2982, Bukhârî6005/1224/2353/1497/1479, Ebû Dâvûd1657, İbn Mâce2474; tam rivayet pasajları ve kaynak numaraları.'
    novelty_map[-1]['additional_checked_passages']=final_extra
    for d in slots[63]:
        if d['id']=='S107-NOV-023':d['checked_sources']=corpus+' Ayrıca gerçekten incelenen pasajlar: '+final_extra
    for docs in slots.values():
        for d in docs:
            for k in ('prose','checked_sources','source_ref'):
                if k not in d:continue
                d[k]=d[k].replace('attested seçenekler','kaynaklarda tanıklanan seçenekler').replace('attested’dir','öncüllüdür')
                d[k]=d[k].replace('bu ağ yapıtaşları düzeyinde attested sayıldı','bu ağ için yapıtaşları düzeyinde tanıklık verildi').replace('diğer attested yorumları','kaynaklarda tanıklanan diğer yorumları').replace('attested su yorumuna','kaynaklarda yer alan su yorumuna').replace('klasik intertext öncüllerine','klasik ayetler arası bağ öncüllerine')
                for name in ['Taberî','Râzî','Bikâî','Kurtubî','Süyûtî','Beyzâvî','Buhârî','Bukhârî','Muslim','İbn Mâce','Ebû Dâvûd','Kur’an']:
                    d[k]=re.sub(re.escape(name)+r'(?=\d)',name+' ',d[k])
    # Preserve every original fragment, including its original separators and final newline.
    parts=re.split(r'(\n[ \t]*\n)',base)
    out='<!-- annotation_schema_version:2.0; target:107; mode:comprehensive; language:tr -->\n\n'
    spans=[];number=0;annotations=[]
    for part in parts:
        start=len(out);out+=part;spans.append((start,len(out)))
        if part.strip():
            number+=1
            attached=slots.get(number,[])
            if attached:
                annotations+=attached
                out+='\n\n'+'\n\n'.join(render(d) for d in attached)
    assert number==cm['base_blocks']==63
    assert len({d['id'] for d in annotations})==len(annotations)
    used={s for d in annotations for s in d['source'].split('|')}
    assert not used-set(registry),(used-set(registry))
    out+='\n\n## Kaynak kayıtları\n\n'
    out+='\n\n'.join(f'- **{key}** — {v}' for key,v in registry.items())+'\n\n'+audit_note
    OUT.parent.mkdir(parents=True,exist_ok=True)
    OUT.write_text(out)
    actual=OUT.read_text()
    recovered=''.join(actual[a:b] for a,b in spans)
    assert recovered.encode()==BASE.read_bytes()
    assert not any('\n' in render(d) for d in annotations)
    assert set(c['base_block'] for c in cm['claims']) <= set(slots)
    audit=dict(target=107,mode='comprehensive',composed_at_utc=datetime.now(timezone.utc).isoformat(),output_file=str(OUT),base_file=str(BASE),base_sha256=cm['base_sha256'],recovered_base_sha256=hashlib.sha256(recovered.encode()).hexdigest(),exact_original_fragments_and_separators=True,base_blocks=number,base_prose_paragraphs=len(cm['claims']),headings=len([l for l in base.splitlines() if l.startswith('#')]),source_lines=len([l for l in base.splitlines() if l.startswith('Kaynaklar:')]),base_inline_tags=len(re.findall(r'\{[^{}]*\}',base)),annotation_counts=dict(Counter(d['type'] for d in annotations)),annotation_total=len(annotations),source_registry_count=len(registry),unresolved_source_ids=[],matrix_precomposition_sha256=(W/'evidence_matrix.precomposition.sha256').read_text().strip(),matrix_completed_at_utc=matrix['completed_at_utc'],novelty_coverage=novelty_map,all_base_claim_paragraphs_locally_annotated=True,output_sha256=hashlib.sha256(OUT.read_bytes()).hexdigest(),original_fragment_character_spans=spans,limitations=['Bounded displayed corpus, not whole-volume absence.','Some first-source lexicon collations and original isnad criticism works not_checked.','No certain absolute revelation date/rank; named sabab historicity uncertain.','Only one canonical reading assessment independently verified.','Modern scholarly corpus not systematically searched.','Downloaded Biqai106:4 and other lexicon author blocks not inspected.'])
    (W/'content_audit.json').write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n')
    (W/'novelty_audit.json').write_text(json.dumps(novelty_map,ensure_ascii=False,indent=2)+'\n')
    (W/'annotations.json').write_text(json.dumps(annotations,ensure_ascii=False,indent=2)+'\n')
    print(json.dumps({k:audit[k] for k in ['output_file','base_blocks','base_prose_paragraphs','annotation_total','annotation_counts','source_registry_count','exact_original_fragments_and_separators']},ensure_ascii=False,indent=2))

if __name__=='__main__':compose()
