from pathlib import Path
from datetime import datetime, timezone
import json, hashlib

W=Path(__file__).parent
claims=json.loads((W/'claim_map.json').read_text())['claims']
# This file is an evidence synthesis, written after passage inspection and before
# the annotation composer exists. Each row preserves both support and limits.
rows={
2:('KASH107:1 taʿajjub/haber isteme; RAZI107:1 masala 2 hitap Peygambere veya akıllı her kişiye; BIQ107:1 gizli ikinci nesne; MAQ رأي göz/kalp; RAGHIB رأي dikkat kalıbı', 'Soru yalnız fiziksel görme veya bugünkü kişiyi tanıma değildir; beyandaki genel/somut kişi ihtimalleri ayrıdır.', 'Tabari 107:1 Ibn Abbas hüküm/Ibn Cüreyc hesap; Zemahşeri soru yorumu', 'Doğrudan tefsir eski; soru ile sonraki ayna ağını birleştirme ayrıca değerlendirilecek.', 'high'),
3:('KASH107:6, BAY107:6, RAZI107:6, BIQ107:6 gösterme karşılığında övgü/itibar; MAQ رأي ayna ve görünüş', '107:6 son ayet değildir; 107:7 maunu esirgeme ile biter. Ayna bağlamsal yuraun çevirisi değildir.', 'Mufaala karşılıklılığı açık dirayet öncülüdür.', 'partial: klasik karşılıklı görünme, sözlükte ayna; sureyi kapatan tam ayna çerçevesi proje.', 'high'),
4:('MAQ ayrı asıl ve düzensiz dalları belirtir; bütün tefsirler 107 bağlamında sosyal fiil/ibadet/yardım okur.', 'Kök ailesindeki bütün duyular ayetin aynı anda söylediği anlam yapılamaz.', 'Klasik lafız/siyaka bağlı anlam ayrımları', 'Yöntem kontrolü; bağımsız özgünlük iddiası yok.', 'high'),
5:('KASH107:1/6 soru ve karşılıklı gösteriş; BIQ107:7 sonun başa dönüşü', 'Tam gerçek bakış/ayna iki ucu şeması incelenen bu bölümlerde açık bulunmadı; bunu tüm tefsir tarihinde yok diye okumamak gerekir.', 'Bakış ve gösteriş bileşenleri klasik.', 'partial: bileşenler açık, bütün çerçeve proje.', 'medium'),
6:('RAZI107:3 masala 1 kötü fiil/iyiliği terk; BIQ107:2 fe gizli inkarın açığa çıkması; BIQ107:3,7 nazm', 'İşaret edatı tek başına her görünür kusurdan kişinin iç imanını kesin bilme yetkisi vermez.', 'Klasik din-denial davranış göstergesi', 'partial: sıranın ahlaki mantığı klasik; mekansal göz güzergahı proje.', 'high'),
7:('QURAN 96:6-14,26:218-219,4:38/142,76:8-10,92:19-20; MUS2985 ve MUS2986 niyet/gösteriş', 'Kuran karşılaştırması doğrudan S107 nüzul sebebi veya hadisin doğrudan ayet tefsiri değildir.', 'Ayetlerdeki görme, riya ve karşılık istemeden verme açık.', 'partial/building_blocks_only: bu karşılaştırmanın özel görme ağı proje.', 'high'),
10:('RAGHIB كذب söz ve fiil yanlışlığı; boyanmış kumaş nakışlı görünebilir. QURT107:6 giysiyle zahit görünme.', '107:1 din/hesabı yalanlamak: kumaş sözlük benzetmesidir. Kaynak boyalı desen der; gerçek dokuma teknolojisinin tüm ayrıntılarını vermez.', 'Klasik giysi ile riya açıklaması kısmidir; tam yalancı kumaş ağı değildir.', 'partial: sözlük kumaşı, tefsirde giysi-riya; özel tekzib-kumaş-namaz ağı proje.', 'high'),
11:('MAQ كذب hücumdan dönme/süt kesilmesi ve ihtiyat; RAGHIB كذب süt/hücum; RAGHIB رأي hamileliğin görünmesi', 'Süt için Maqayis ihtiyat gösterir; bu somut hayvan duyuları 107:1 bağlamsal tefsiri değildir. Her paket dalı bağımsız ilk kaynakla kollasyon edilmedi.', 'Lexical building blocks', 'building_blocks_only: ortak iki aileden devenin yalan/doğru biyografisi projede birleştirilir.', 'medium'),
12:('RAZI107:1-3 inkarın amel göstergeleri; SIHAH دين kendi dinine bırakmak; MUHKAM دين yargıda/Allah ile arasında doğrulamak; MUS2985 niyet', 'B007 yemin niyeti tam alıntısının bağımsız Tahdhib kontrolü tamamlanmadı. Bu özel hukuk deyimi ayette dinin tek anlamı değildir.', 'İnkar-amel ve riya-niyet bağı geleneksel.', 'building_blocks_only: hukuk deyimi-kumaş-gizli niyet ağı proje; özel ilk kaynak not_checked.', 'medium'),
13:('KASH107:5 an/fi; QURT107:5 Ibn Arabi herkes sehv yapar; RAZI107:4-5 masala 2 şeklen namaz/Allahı hatırlama; BIQ107:2 fe; BUK1224', 'An yalnız mekan dışı değildir. Klasik zaman, bırakma, şartlar/huşu aralığı sırf fiziksel dışarı imgesine indirgenemez.', 'An/fi ve görünüş/kalp ayrımı açık öncül.', 'partial: temel ayırım eski; ipliğe girmeyen boya/hayvan koşusu bağlantıları proje.', 'high'),
14:('QURAN 2:177/264,63:4,53:33-34,70:23/34,98:5', '2:177 şekli yönü tek ölçü saymaz; kıble/namazı hükümsüz kılmaz. 63:4 kütük ve 2:264 kaya kendi bağlamlarıdır.', 'Birr, riya ve süreklilik ayet metinlerinde.', 'building_blocks_only: aynı kumaşa bağlama proje.', 'high'),
17:('MAQ يتم ayrılık/baba kaybı; LISAN يتم Mufaddal ihmal, Abu Amr gecikme; MAQ سهو unutma/dinginlik', 'İhmal ve gecikme aynı tek etimolojik kök hükmü değildir; baba kaybı hukuki tanım ile mecazi yalnızlık ayrılmalı.', 'Sözlüklerde birden çok köken önerisi ve mecaz.', 'building_blocks_only: yetim-sehv tanımsal köprü proje.', 'medium'),
18:('MAQ سهو Suha görülmeme ihtimalini söyler, dost kusurunu görmezden gelmek; MAQ يتم yalnız inci', 'Maqayis Suha türeyişi için kesinlik değil muhtemeldir der. Yıldız/dost kusuru sahunun 107:5 bağlamsal anlamı değil.', 'Suhâ ve müsahat sözlük düzeyinde eski.', 'building_blocks_only: yetim-Suha-sehv-riya ağı incelenen tefsir kısımlarında yok.', 'medium'),
19:('TAB107:2-3 hak/yemek/başkasını teşvik; RAZI107:3 konuşmaya bile yanaşmama; QURAN107:3', 'Temel metin üçüncü ayette yemeğin hiç anılmadığını söyler; lafızda taʿam açıkça vardır. Yöntem notu çatışmayı belirtecek.', 'Yetimi itme ve teşviksizlik doğrudan eski tefsir.', 'partial: dikkat/görülme karşıtlığı bir sentez; literal yemek-yok cümlesi desteklenmiyor.', 'high'),
20:('TAB5111 ghmra sapma/şüphe; Ibn Zeyd suda kalan nesneye benzetir; QURAN93:6,9:67', '51:11 akarsu selinden doğrudan söz etmez; su imgesi benzetme olabilir. 9:67 nisyan ilahi bilgi kaybı anlamında alınamaz.', 'Suya gömülme benzetmesinin açık klasik yapıtaşı vardır.', 'building_blocks_only: gaflet seli-Suha-yetim ortak görünmezlik ağı proje.', 'high'),
23:('TAB107:2 hakka itiş; MAQ دع itmek/kap doldurma; LISAN دع küçük çocuk ve ses kullanımları', 'MAQ seslerin çoğunlukla kıyaslanamayacağını açıklar; düşene kalk seslenişi aynı düzenli asıl diye dayatılamaz.', 'İtiş doğrudan tefsir; ses ve çocuk ayrı sözlük dalları.', 'partial: sosyal el çerçevesi eski, aşağı/yukarı aynı el ağı proje.', 'high'),
24:('MAQ حض teşvik ve dip yer iki asıldır, Halil nakli yürüme/sürme değildir; RAZI107:3 kişi kendisi veya başkalarını teşvik eder', 'Hayra sürmek mecaz; hadd herding/physical pressure anlamının contextual eşdeğeri değil. Düşük yerdeki yoksul görüntüsü ikinci asıl analojisi.', 'Teşvik doğrudan eski tefsir; iki asıl ayrı lexical witness.', 'building_blocks_only: hadid dip/hadd teşvik sahnesi proje.', 'high'),
25:('MAQ سكن durgunluk/ev; SIHAH سكن yoksulluk/aşağılanma; MAQ منع vermenin tersi/korunak; BUK1479 gizli muhtaç', 'Miskin tanım gereği hareketsiz veya evsiz değil. Yetim de mutlaka yoksul/malsız/kabile korumasız değil: QURAN4:2/6/7 malı ve miras hakkı.', 'İhtiyacın görünmeyebileceği sahih hadis.', 'building_blocks_only: durgun beden/koruyucu çevre metaforu proje, evrensel tarih tanımı değil.', 'high'),
26:('RAZI107:3 muzari/alışkanlık ve şiddet, az söz dahi yok; BIQ107:3 söz-harcama karşıtlığı', 'Razi 107:3 teşvik etmemeyi her şartta günah saymaz; etkisiz/zararlı müdahale ve başkaları zaten doyurma örnekleri.', 'Devamlılık ve kolay teşvikin terkinde güçlü klasik öncül.', 'partial: ana fikir klasik; durgun kalp/engel imge dizisi proje.', 'high'),
27:('RAZI107:3 ve QURT107:2 52:13 bağlantısı; QURAN89:17-18,93:9-10,4:37-38,68:17-24,90:15-17', 'Turda ateşe itilen kişi metinde özellikle yetim itenin bireysel kimliği olarak gösterilmez; tematik fiil karşılığı.', 'Tur çaprazı açık klasik.', 'partial: klasik intertext + ek koruyucu eller ağı proje.', 'high'),
30:('MAQ سكن ev/ev halkı/ocak; LISAN دع çocuk; MAQ سهو sehve sundurma', 'Maqayis sehve için asıl dışı düzensiz dal der; raf-sahunun zorunlu düzenli türeyişi değildir. Kapsam tüm ev arkeolojisi değil.', 'House parts lexical witnesses', 'building_blocks_only/partial: ev eşyası klasik maun tefsiri, kelimelerde kurulmuş bütün ev proje.', 'high'),
31:('AD1657 Ibn Mesud sahabi sözü bucket/pot, Al-Albani hasan; TAB107:7 implements/zakat; KATH107:7 nesnesi kalıp dönen ödünç', 'Ibn Ömer Tabaride implements yorumuna açık itirazla zekatı söyler. Yardım hiç maliyet/risk/eksilme yok demek değildir.', 'Aynı Ibn Mesud raporu Tabari/IK/Suy çok tekrar: tek rapor ailesi.', 'explicit for lending/return; partial for whole house enclosure.', 'high'),
32:('MAQ دع daʿdaʿa kap sallamak/doldurmak; LISAN دع doldurma/yemek örnekleri; MAQ طعم tatma/yemek/konuk', 'Doldurma dalı yadʿu yetimi doyurmak anlamına çevrilmez; bağlamsal şiddet korunur.', 'Lexical container material old.', 'building_blocks_only: iten elin dolduran ele terslenmesi proje.', 'high'),
33:('KATH107:7 ödünçnesne; RAZI107:7 komşunun fırında pişirmesi/eşyasını kısa saklama; QURAN4:6/7', 'Yoksulun evi yok cümlesi miskinin tanımı değildir; sahip olduğu ev muhtaçlığını ortadan kaldırmak zorunda değildir.', 'Classical neighbor/home-sharing gives actual partial antecedent.', 'partial: ev yardımı doğrudan; yetim/raf/azık/kap bütün ev ağı proje.', 'high'),
34:('QURAN76:8-10,36:47,18:77/82,12:63,83:1-3,4:8; QURT107:3 36:47 kader mazereti reddi', 'Kehf kasabası ve yetim malı ayrı sahneler; tüm sure tek S107 olayı veya sababı değil. Eksik ölçme-maun karşılaştırması moral analogy.', '36:47 doğrudan classical intertext; diğer sahneler textual.', 'partial: beslenme-hak mal ağı eski, tamamı aynı ev sentezi proje.', 'high'),
37:('MAQ معن su/ease/channels; MAQ طعم 2:249 su tadılması; SIHAH/LISAN معن; RAZI107:7 maun su; QURT107:7 su/otlak', 'Maʿin mʿn veya ayn mim fazlalığı köken tartışması QUR6730/LISAN; maun kesin tek kök ailesiymiş gibi sunulamaz.', 'Water-maun explicit classical not novel.', 'partial: su dalı eski; barınak/otlak/kanal sahnesi sentez.', 'high'),
38:('BUK2353 surpluswater-pasture refusal; TAB107:7 all reciprocal benefits; QURT107:7 water/pasture', 'Bütün borç verme/özel mal/su kullanımına tek genel hukuki zorunluluk çıkarılmaz; klasik ihtiyaç/zaruret/muruwwa ayrımı KASH107:7.', 'Strong water-withholding thematic hadith, not direct ayah interpretation.', 'partial: su esirgeme eski; tıkanmış yatak imgesi proje.', 'high'),
39:('QURAN67:28-30,23:50,93:6; QUR6730 flowing/visible water and etymologies', 'Same interrogative/word alone proof of intended authorial intertext değildir; iki barındırma farklı kişiler/bağlam.', 'Textual components actual.', 'building_blocks_only: eraeytum→maʿin endpoint with shelter project.', 'medium'),
42:('MAQ صلي iki asıl: ateş/sıcaklık ve ibadet; s-k-n ocak; RAZI107:7 fırın kullanımı; QURT107:7 fire-water-salt softchain', 'Prayer and fire have two separate asls explicitly; packet salw/sly echoes not contextual meaning of musallin. IM2474 daif cannot independently certify reward.', 'Hearth-sharing direct classical; common letters not one origin.', 'partial: actual oven/lending antecedent; salat=fire network project echo with constraint.', 'high'),
43:('QURT107:4 azap; TAB107:4 wail hellvalley; MAQ صلي lexical limits; QURAN107:4-7', 'Wail valley is one reported exegesis not lexical definition/sahih proof. In verse4 fire/hearth noun not stated.', 'Classical judgment/prayer association.', 'partial: threat old; hearth withheld→fireword reversal project.', 'high'),
44:('QURT107:3 69:34 intertext; QURAN69:25-37,83:10-17,92:14-16,4:10,50:24-25', 'Comparative scenes not common concrete perpetrator nor hidden etymology: Hakka ties account/food denial/fire openly.', 'Hakka link explicitly attested; cross-Quran terms direct.', 'partial: clear textual network, private common oven metaphor project.', 'high'),
47:('MAQ دين obedience/submission/dayn; TAB107:1 account/rule; RAZI107:1 reward/Islam; MAQ كذب encouragement idiom', 'Dayn debt ≠ 107:1 din monetary debt. Maq states kezebe-aleyke obscure extinct idiom; not denotation of yukadhdhib.', 'Classical theological account and obedience directly attested.', 'partial: classical ingredients, debit ledger metaphor project.', 'high'),
48:('SIHAH/LISAN معن preIslam benefit/Islam zakat/obedience; TAB107:7; RAZI107:7 good submission; LISAN emʿan deny/acknowledge right', 'PreIslam/Islam contrast is lexicographic retrospective claim not proven sharp semantic chronology. Lisan explicitly maʿuna derivation alternative.', 'Ibn Abbas/Ali/IbnUmar early senses with conflicting attributions; direct obedience is not project innovation.', 'partial/explicit ingredients: din-maun itaʿat network has substantive old precedents.', 'high'),
49:('BIQ107:7 end back beginning; RAZI107:7 worship/people dues relational reversal; QURAN82:9,1:4,70:19-26,41:6-7,17:26,51:19', 'General economic obligation not equivalent to modern financial debt instrument; smallness does not cancel mandatory zakat.', 'Old explicit first/last moral unity.', 'partial: ledger image/this extended arc project but not wholly novel.', 'high'),
52:('MAQ صلي second asıl dua/ritual/Allah rahma; TAB9103 dua/istighfar; QURAN9:103; BUK1497', 'Base cites plural salawat but current Hafs display salat singular; both are attested readings Tabari. Allah salat ≠ God performs creature ritual.', 'Supplication vs ritual classical semantic differentiation.', 'explicit for lexical/9:103 meaning; project application later.', 'high'),
53:('TAB9103 passage donation/tawba, دعااستغفارسكنطمأنينة; BUK1497 dua for charity giver; QURAN9:102-104', '9:103 addresses Prophet and has tawba contextual setting; no automatic generic bidirectional law for all 107 musallin.', 'Charity→Prophetic dua→calm clearly old.', 'partial: cycle is direct source antecedent, importing to 107 is synthesis.', 'high'),
54:('RAZI107:4-5 masala1 quotes29:45 and says riya/sehv explains wrong persists; masala2 outwardshape/innerذكر; KASH107:6 intention; MUS2642A', 'Riyaa requires motive; public prayer/praise alone not proof. Razi expressly warns the three faults are not an automatic declaration of hypocrisy.', 'Outward prayer ethically ineffective direct classical precursor.', 'partial: outwardsocial huzur framing extends explicit ethical precursor.', 'high'),
55:('QURAN11:87,19:31,2:83,9:54,29:45,19:59; RAZI107:4-5 quotes29:45', '11:87 hostile speakers ask sarcastically, not approval of separating trade ethics; 19:59 later-generation neglect distinctcontext.', 'Prayer/wealth/duty text and classical29:45 link.', 'partial: root network combining all passages project.', 'high'),
58:('QURAN96:9-14; MAQ سهو/rʾy; KASH107:1/6', 'Suhâ is not stated in Alak or Maun; classical lexical possibility not prophetic star interpretation.', 'Seeing/prayer/prevention clear textual ingredients.', 'building_blocks_only: Alak-Suhâ interweaving project within checked sources.', 'medium'),
59:('RAZI107:3 and QURT107:2 52:13; QURAN52:11-16,69:25-37', 'Tur states deniers pushed to fire, not specifically the same orphan pusher; individual revenge identity is inferential. Shared hearth not Hakka contextual noun.', 'Direct classical52:13 lexical echo and69:34 phrase.', 'partial: classic intertext; individual counterpart and oven materiality project.', 'high'),
60:('QURAN74:40-47 prayer/feeding/falseengagement/dayofjudgment; QURAN52:12 khawd and51:11 ghmra', '74:45 means participating wrongful engagement; not identical word to sehv and not literal body submerged in a stream.', 'Fourfold confession textual.', 'building_blocks_only: exact collective meeting of all projectimages notfound in inspected tafsir sections.', 'high'),
61:('TAB107:7 expansivebenefits; RAZI107:7 water/oven/rights/obedience; LISAN معن; QURAN23:50,93:6; MAQ دع/منع', 'Maun multiple readings are not all simultaneously required denotations; loan/nohome limits and root differences persist.', 'Classical plurals, material lending, right and nazm old.', 'partial: triadic house-water-debt combination and manyrootmeeting project.', 'medium'),
62:('QURAN70:19-35,9:102-104; TAB9103; BUK1497; BIQ107:7 Anfal truefaith/prayerinfaaq analogy', 'Sources show prayer/due/faith old; Meʿarij-Tevbe combination not same direct107 tafsir and has no single proven nuzul order.', 'Counter-scenes textually explicit, cross-surah pattern classical in principle.', 'partial/building_blocks_only: precise 70+9 reading model for107 project.', 'high'),
63:('BIQ107:7 end-beginning; RAZI107:4-5 Creator/creatures and107:7 reverse worship/publicity; KASH107:6 reciprocity; all lexical/Q buildingblocks', 'Total multi-network picture was notlocated within inspected bounded corpus; not an exhaustiveabsenceclaim. Clashes in base remain plainly annotated.', 'Strong classical backbone for faith/socialcare/prayer/withholding.', 'partial: assembled house/star/cloth/mirror/water/fire/ledger synthesis project, not all components new.', 'medium')
}

def pieces(s):return [x.strip() for x in s.split(';') if x.strip()]
matrix=[]
for c in claims:
    b=c['base_block'];support,limits,early,nov,conf=rows[b]
    relation='No direct sahih Prophetic interpretation asserted; relevant evidence is tafsir/lexicon/Quran.'
    if b in (3,7,12,13,19,25,31,37,38,42,43,52,53,54,55,59,62):
        relation={3:'MUS2985/2986 thematic riya; MUS2642A contrast public praise.',7:'MUS2985/2986 thematic intention/showing.',12:'MUS2985 thematic motive; not legal lexical proof.',13:'BUK1224 contrast involuntary prayer forgetfulness; MUS622 thematic delay/pecking.',19:'BUK6005 positive orphan care; MUS2982 poor service/prayer analogy.',25:'BUK1479 hidden poor; thematic.',31:'AD1657 graded hasan by Al-Albani: Companion era testimony, not explicit Prophetic tafsir.',37:'BUK2353 thematic surpluswater/pasture.',38:'BUK2353 strong thematic; IM2474 daif rejected as independent rule/reward proof.',42:'IM2474 daif Darussalam; Namiri stone/iron/water marfu criticized by IK. Razi oven is tafsir, not hadith.',43:'No sahih valley identification checked; Prophetic sehv reports criticized in IK/Suy.',52:'BUK1497 thematic charity supplication.',53:'BUK1497 direct practical counterpart to9:103, thematic to107.',54:'MUS2642A praise is not automatic riya; MUS2985 motive.',55:'MUS622 thematic prayer heedlessness; MUS2982 combines poor help/prayer with transmitter uncertainty.',59:'No hadith identifies the exact orphan pusher as Turfirevictim.',62:'BUK1497/Tab9:103 charity-prayer anchor; not direct107.'}[b]
    hist='No dated event inferred from the lexical image.'
    if b in (2,6,12,19,25,31,33,37,38,42,48,49,53,62,63):
        hist='M/M reports are contested (Qurtubi/Alusi107 intro); named causes weakly established (Wahidi107:1-2; no complete isnad grading). Domestic loans/ovenwater are attested social examples, not site-specific archaeology. No certain absolute date/rank established.'
    matrix.append(dict(claim_id=c['id'],base_block=b,claim=c['claims'],supporting_sources=pieces(support),contradicting_sources=pieces(limits),early_attestation=early,later_development='The core eight authors were compared passage-by-passage; repetition is not independent corroboration. Alusi supplements M/M, grammar and etymology where stated.',hadith_relation=relation,historical_context=hist,novelty_status=nov,confidence=conf))
assert len(matrix)==44
record=dict(stage='substantive_evidence_matrix_complete_before_composition',annotations_composed=False,completed_at_utc=datetime.now(timezone.utc).isoformat(),corpus_scope='Eight authors: displayed 107:1-7 bodies and intros, including duplicate/empty bodies, not whole volumes. Specific supplementary passages and root entries separately logged.',duplicates=['Razi107:4 and107:5 repeat the same three-masala commentary (headers differ).','Ibn Masud bucket/pot/axe loans across Tabari, Ibn Kathir, Suyuti, Abu Dawud: one report family.','Ibn Abbas public-prayer/private-omission across authors: one report family.','Suyuti107:3 and Baydawi107:4 display verse only; no commentary coverage invented.','Wahidi named causes and later repetitions are not independent events or historical corroboration.'],meaningful_disagreements=['Maun: Ibn Umar zakat against Ibn Masud implements, with Tabari broad synthesis.','Sehv: Hasan rejects Abu Aliya ordinary intra-prayer error; valid timing/neglect readings remain.','Makki/Madani and unnamed/general vs named perpetrator differ.','Din reward/account vs Islam/obedience; maun attributions not one uniform tradition.','Maqayis fire/prayer two asls, sehve irregular, Suha possible; analogy cannot erase these.','Maʿin etymology mʿn vs ʿayn and maun maʿuna alternative.'],claims=matrix)
(W/'evidence_matrix.json').write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n')
(W/'evidence_matrix.precomposition.sha256').write_text(hashlib.sha256((W/'evidence_matrix.json').read_bytes()).hexdigest()+'\n')
# Actual read status is updated only for passages inspected, not downloaded files.
idx=json.loads((W/'retrieval_index.json').read_text())
for r in idx:r.update(state='inspected_displayed_body_complete',inspection_scope='All extracted div.nass paragraphs on this exact verse-page; no whole-volume/pagination claim.',coverage_note=('Repeated three-masala body across4/5' if r['key'] in ('alrazy_107_4','alrazy_107_5') else 'Verse only; no substantive commentary' if r['key'] in ('seoty_107_3','baidawy_107_4') else 'Substantive displayed commentary inspected'))
(W/'retrieval_index.json').write_text(json.dumps(idx,ensure_ascii=False,indent=2)+'\n')
lexread={'lex_yatam_dictionary_7_16.txt','lex_din_dictionary_7_21.txt','lex_man_dictionary_7_19.txt','lex_skn_dictionary_7_20.txt','lex_skn_dictionary_6_06.txt','lex_sla_dictionary_7_07.txt','lex_shw_dictionary_7_12.txt','lex_raa2_dictionary_31_01.txt','lex_kdhb_dictionary_31_18.txt','lex_yatam_dictionary_31_05.txt','lex_man_dictionary_31_05.txt','lex_man_dictionary_6_11.txt','lex_yatam_dictionary_1_11.txt','lex_daa_dictionary_1_07.txt','lex_tam_dictionary_7_17.txt','lex_din_dictionary_6_07.txt','lex_din_dictionary_8_09.txt','lex_man_dictionary_1_13.txt','lex_din_dictionary_9_01.txt'}
lex=json.loads((W/'lexicon_sections.json').read_text())
for r in lex:
    r['inspected']=r['file'] in lexread
    if r['inspected']:r['inspection_scope']='Full author/root block, except Raghib معن: relevant معن portion only; parser joins following مقت heading.' if r['file']=='lex_man_dictionary_31_05.txt' else 'Full extracted author/root block.'
(W/'lexicon_sections.json').write_text(json.dumps(lex,ensure_ascii=False,indent=2)+'\n')
ma=json.loads((W/'maqayis_sections.json').read_text())
for r in ma:
    r['inspected']=r['root'] in ['رأي','كذب','يتم','سهو','صلي','معن','سكن','دين','دع','حض','منع']
    if r['inspected']:r['inspection_scope']='Relevant named root only; extraction may append next-root transition. Hawramani author block preferred where independently extracted.'
(W/'maqayis_sections.json').write_text(json.dumps(ma,ensure_ascii=False,indent=2)+'\n')
print('Substantive matrix complete before annotations:',len(matrix),'claims;',len(idx),'tafsir page-bodies;',sum(r['inspected'] for r in lex),'lexicon author/root blocks.')
