import json
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT=Path('/Volumes/aro/projects/prose_generation')
W=ROOT/'enrichment/v1/work/1'
BASE=ROOT/'_commentary/v16/out/s001/images.r13.map3.nohft.tool.tool/images.md'
OUT=ROOT/'enrichment/v1/out/1/1_enriched.md'
matrix=json.loads((W/'evidence_matrix.json').read_text())
assert matrix['stage']=='evidence_populated_before_annotation_composition'
scopes=matrix['source_passage_inventory']
annotations=[]
at=defaultdict(list)
counts=Counter()
abbr={'tafsir':'TF','asbab':'ASB','hadith':'HD','qiraat':'QIR','revelation_history':'RH','historical_context':'HC','semantic_history':'SEM','nazm':'NZ','cross_quran':'XQ','method_note':'MET','reader_note':'RD','novelty':'NOV','source_note':'SRC'}
def A(line,typ,ayah,prose,sources,role='clarification',relation='direct_tafsir',status='explicit',tradition='dirayet',priority='core',audience='general',**extras):
 counts[typ]+=1
 d=dict(id=f'S1-{abbr[typ]}-{counts[typ]:03d}',type=typ,ayah=ayah,tradition=tradition,role=role,relation=relation,status=status,priority=priority,audience=audience,prose=prose,source=sources)
 d.update(extras)
 annotations.append(dict(base_line=line,**d))
 at[line].append(d)
 return d['id']
def N(line,ayah,prose,sources,checked,attestation='partial',connection='resonant',scope=None):
 return A(line,'novelty',ayah,prose,sources,role='novelty_assessment',relation='comparative',status='interpretive' if attestation!='not_checked' else 'not_assessed',tradition='project',priority='research',audience='research',classical_attestation=attestation,checked_sources=checked,connection=connection,scope=scope or f'Özgün metin paragrafı {line}')
def M(line,ayah,prose,sources,connection='resonant',priority='core',audience='advanced',**extras):
 return A(line,'method_note',ayah,prose,sources,role='constraint',relation='methodological',status='interpretive',tradition='project',priority=priority,audience=audience,connection=connection,**extras)
def X(line,ayah,prose,refs,connection='strong'):
 return A(line,'cross_quran',ayah,prose,'QUR',role='intertext',relation='thematic',status='interpretive',tradition='project',priority='extended',audience='general',source_ref=refs,connection=connection)
def H(line,ayah,prose,sid,grade,authority,relation='thematic',**extras):
 return A(line,'hadith',ayah,prose,sid,role='anchor' if relation=='direct_hadith_tafsir' else 'corroboration',relation=relation,status='reported',tradition='hadith',priority='core' if relation=='direct_hadith_tafsir' else 'extended',audience='general',hadith_grade=grade,source_ref=authority,**extras)

A(0,'reader_note','1:1-7','Bu metnin sözlüklerle örülen ana anlatısı aynen korunmuştur. Ek notlar dört ayrı şeyi görünür kılar: ayetin cümle içindeki anlamı, eski yorumlarda açıkça söylenen açıklama, sözlüğün verdiği başka kullanımlar ve burada bu malzemeden kurulan bağlantı. Bir kelimenin akraba kullanımı, o kullanımın ayette de söylendiği anlamına gelmez.','ENR',role='reader_orientation',relation='methodological',tradition='none')
A(0,'reader_note','1:1-7','Genel okuma için core notlar ana ayrımları izler; extended katman yardımcı örnekleri açar. research katmanı hangi pasajların gerçekten denetlendiğini ve yenilik değerlendirmesinin sınırını gösterir. audience bilgisi, teknik notları ayrı okumaya imkân verir; kaynak kayıtları sonda ortak bir kez verilir.','ENR',role='reader_orientation',relation='methodological',tradition='none',priority='core',audience='general')
A(0,'revelation_history','1:1-7','Okunan kaynaklar Fatiha için tek bir nüzul görüşü vermiyor. Vâhidî ve İbn Kesîr Mekkî görüşü tercih ederken Mücâhid’e nispet edilen Medenî görüşü de kaydeder; İbn Kesîr iki kez nüzul iddiasını da aktarır. 15:87’deki yedi tekrarlanan ayetin Fatiha oluşu, Mekkîlik lehine kullandıkları gerekçedir. Bu, kesin gün, olay ve bir defalık iniş zincirini tek başına belirlemez.','W_ASB|IK1|DUR1|BAY1|H_B4474',role='chronology',relation='historical',status='disputed',tradition='historical',historicity='contested',priority='extended',audience='advanced',source_ref='Vâhidî Fatiha bölümü; İbn Kesîr 1:1 giriş; ed-Dürr 1:1 satır 9–14; Beyzâvî 1:1 giriş')
A(0,'asbab','1:1-7','Vâhidî’de Ebû Meysere’ye ulaşan anlatı, korku ve Varaka ile görüşmenin ardından Fatiha’nın öğretilmesini konu edinir. Zincir, tâbiî Ebû Meysere’den Hz. Peygamber’e sahabî adı olmadan geçer; bu irsal boşluğu görülür, fakat burada ayrıca bir hadis münekkidinin derece hükmü doğrulanmadığından not_assessed kullanılır. Aynı anlatının Süyûtî’de tekrarı ikinci bağımsız olay tanığı sayılmaz; bütün sureyi kesin bir sebeb-i nüzule bağlamak için yeterli değildir.','W_ASB|DUR1',role='asbab_context',relation='asbab',status='reported',tradition='rivayet',historicity='uncertain',hadith_grade='not_assessed',priority='research',audience='research',source_ref='Vâhidî rapor 19, Ebû İshak→Ebû Meysere; ed-Dürr 1:1 satır 9',origin='Vâhidî’de incelenen aynı Ebû Meysere rivayet ailesi')
H(0,'1:1-7','Buhârî’de Âişe’nin ilk vahiy anlatısı Hira’da İkra başlangıcının okunmasını anlatır. Bu sahih kayıt, Fatiha’nın mushafı açmasıyla ilk vahyin aynı şey olmadığını gösterir. Fatiha’nın ilk tamamlanmış sure olup olmadığı ayrı bir sorudur; bu rivayet onu açıkça cevaplamaz.','H_B3','sahih','Buhârî 3; derece dayanağı Sahîh Buhârî koleksiyonu',relation='historical',historicity='probable')
H(0,'1:1-7','Ebû Saîd b. Muallâ rivayetinde Hz. Peygamber Fatiha’yı yedi tekrarlanan ayet ve kendisine verilen büyük Kur’an diye tanıtır. Bu doğrudan sureyi tanıtan sahih kayıt, sonraki bütün sözlük çağrışımlarını tasdik eden bir açıklama veya kronolojik ilk sırayı bildiren bir rivayet olarak genişletilmez.','H_B4474','sahih','Buhârî 4474; derece dayanağı Sahîh Buhârî koleksiyonu',relation='direct_hadith_tafsir')
A(0,'qiraat','1:1-7','Burada özgün metnin besmele = 1:1 sayımı izlenir. Besmelenin Fatiha ayeti sayılması konusunda incelenen müfessirler ayrılır: Taberî 1:3’te onu ayet saymaz; Beyzâvî yedi ayetin farklı bölümlemelerini aktarır. Bu sayım farkı, besmeleyi okuyuş, sureler arasındaki besmele uygulaması ve kelimelerin kanonik okuyuşlarıyla aynı mesele değildir.','TAB3|BAY1|ZAM1|NASHR',role='clarification',relation='structural',status='disputed',tradition='dirayet',priority='core',audience='advanced',source_ref='Taberî 1:3 bütünü; Beyzâvî 1:1 giriş; en-Neşr I, s.271')
H(0,'1:2-7','Müslim’deki kudsî rivayet, Fatiha’yı övgü ve talep düzeniyle açıklar: hamd, rahmet ve hükümranlık sözleri kulun Rabbini anması; kulluk ve yardım sözü ortak bölüm; hidayet duası ise kulun isteğidir. Böylece sureyi yalnız kelime akrabalığıyla değil, konuşanın hitabı ve talebin ilerleyişiyle de okumak için doğrudan bir dayanak verir.','H_M395','sahih','Müslim 395a; derece dayanağı Sahîh Müslim koleksiyonu',relation='direct_hadith_tafsir')
M(0,'1:1-7','Kök burada bir çağrışım kapısıdır; bütün dalların tek çekirdeğe bağlandığı garantisi değildir. Mekâyîs ʿabd için yumuşaklık/boyun eğme ile kuvvet/sertliği, q-w-m için topluluk ile dikilme/kararlılığı, h-d-y için önden rehberlik ile dostça gönderişi, gh-y-r için farklılık ile erzak/yarar dallarını ayrı asıllara ayırır. Aynı harflerden hareketle bu sınırları kaldıran bağ, ayetin tercümesi değil proje terkibidir.','M_ABD|M_QWM|M_HDY|M_GHYR',connection='direct',term='kök, asıl, dal ve bağlamsal anlam')

A(3,'tafsir','1:5-6','Çiğnenmiş yol ve uysallaştırılmış binek, yalnız bugünkü metnin bulduğu bir benzetme değildir. Taberî ve İbn Kesîr 1:5’te kulluğun dildeki boyun eğme anlamını bu iki örnekle açıklar. Ancak onların buradaki açıklaması ibadetin anlamını aydınlatır; Fatiha’nın bütün öteki sözlerini tek bir fiziksel yol sahnesine çevirmeyi kendiliğinden gerektirmez.','TAB5|IK5|M_ABD',role='early_attestation',source_ref='Taberî 1:5 satır 4–9; İbn Kesîr 1:5 başlangıcı',attested_in='İbn Kesîr 1:5; Beyzâvî 1:5')
A(5,'tafsir','1:6','Taberî ihdinâ isteğini, zaten iman edenin kalan ömründe itaatte sebat ve muvaffakiyet istemesi diye açıklar; yalnız daha önce bilinmeyen bir bilgiye yöneltmeyle sınırlandırmaz. Zemahşerî devam ve artış, Beyzâvî ise farklı hidayet dereceleri üzerinde durur. Bu yorumlar duanın yürüyüşü sürdürme boyutunu destekler; sözlükteki her sevk biçimini ayetin ayrı anlamı yapmaz.','TAB6|ZAM6|BAY6|IK6',role='anchor',source_ref='Taberî 1:6 tevfik/sebat tartışması; Zemahşerî 1:6 ilk cümle; Beyzâvî 1:6 dört derece')
A(7,'qiraat','1:6-7','en-Neşr’de sînli ve sâdlı sırât okuyuşları ile sâdın zâya yaklaştırıldığı işmam, belirli okuyucu ve rivayet yollarıyla ayrılır. Ruveys sîn okur; Kunbul için İbn Mücâhid ve İbn Şenebûz yolları farklıdır. Hamza’dan Halef’in işmamı saf zâ harfiyle sıradan bir ikame değildir; Hallâd yollarında uygulamanın hangi sırât lafızlarını kapsadığı da değişir. Dolayısıyla üç lehçe adı, üç serbestçe değiştirilebilir kanonik okuyuş diye okunmamalıdır.','NASHR|ZAM6|BAY6',role='clarification',relation='grammatical',tradition='rivayet',canonical=True,priority='research',audience='research',source_ref='İbnü’l-Cezerî en-Neşr I, s.271–272; burada Halef Hamza’nın râvisidir')
A(9,'nazm','1:5-7','Çoğul ses ve geçmiş nimetlilere yönelişin klasik karşılığı da vardır. Beyzâvî ve İbn Kesîr biz hitabını cemaatle okur; Bikâî 1:7’de iyi yol istenirken iyi yol arkadaşının da istendiğini söyler. İstek böylece yalnız çizginin adını öğrenmeye değil, o yolda yaşayabilmeye ve doğru örneklere katılmaya açılır.','BAY5|IK5|BIQ7',role='nazm',relation='structural',tradition='nazm',source_ref='Beyzâvî 1:5 çoğul; İbn Kesîr 1:5 sonu; Bikâî 1:7 satır 7')
M(11,'1:2-6','Mâlik/milk ailesinin yolun ortasına dair kullanımı, bu ayette mâlikin karşılığı değildir; 1:4’te sahiplik ve hükümranlık belirleyicidir. Aynı şekilde dîn için âdet malzemesi, yevmüddînin hesap/karşılık anlamına ek bir çağrışım olarak kalır. Mekâyîs âdet diye aktarılan bir şiirin dîn yerine deʾb okunabileceğini de kaydeder; bu tartışmalı örneği kesin bir kök köprüsü gibi kullanmamak gerekir.','TAB4|M_DYN|M_MLK',connection='resonant',source_ref='Mekâyîs d-y-n son şiir ve zabıt notu; Taberî 1:4 dîn açıklaması')
N(13,'1:5-7','Yol–uysal binek–kulluk bağı açık klasik öncüllüdür. Buna topluluk, dağılış, yol ortası, âdet ve evini bulamama dallarının katılması, burada incelenen malzemelerin yeniden örülmesidir. Mekâyîs qawmı diklikten ayrı bir asıl saydığı için, topluluğu mustaqîmin sözlükte zorunlu içeriği saymak doğru olmaz. Nimet/dağılış ve dalâl/ev örneklerinin bütün birleşimi için tam klasik Fatiha taraması yapılmadı.','TAB5|TAB6|TAB7|M_ABD|M_QWM|M_NAAM|M_DLL',checked='Taberî 1:5 yol/deve bölümü, 1:6 hidayet ve yol yorumları, 1:7 nimetli yolun açıklaması; Mekâyîs ʿabd, q-w-m, n-ʿ-m, d-l-l tam maddeler. İlgili diğer nadir sözlük dalları ile Râzî tam Fatiha denetlenmedi.',attestation='building_blocks_only',scope='Paragraflar 3–17; yol ağı ve topluluk/dağılış alt bağlantıları')
X(15,'1:6-7','6:153’te tek sırâta uyma ile başka yollara dağılma doğrudan karşı karşıyadır; 6:161 aynı yolu dîn ve İbrahim’in milletiyle açıklar. 16:15–16 ise coğrafi yollar, işaretler ve yıldızla yön bulmayı anlatır. Son pasaj manevi yolun açıklanmasına yardımcı bir paraleldir; ilk pasajla aynı kullanım bağlamı değildir.','6:153, 6:161, 16:15–16, 28:22')
M(17,'1:6-7','37:23’te sevk cehenneme yönelir; h-d-y fiilinin her kullanımında olumlu kurtuluş sonucu yoktur. 93:7’de Hz. Peygamber için kullanılan dâllen de kendi bağlamında değerlendirilir: Bikâî burada belirli bir yönelişi bilmezken hidayet bulmayı açıklar. Bu kullanım, 1:7’deki dinî sapmayı her d-l-l örneğine taşımaya izin vermez.','QUR|TAB6|IK6|BIQ6',source_ref='37:23; 93:7; Bikâî 1:6, dijital 93:6 atfı 93:7 olarak kontrol edildi')

A(23,'historical_context','1:5','Eski sözlüklerin efendi, memlûk, ev ve uysal hayvan örnekleri, kelimelerin kullanıldığı toplumsal dili korur. Bunlar tarih boyunca insan tahakkümünü onaylayan dinî hükümler değildir. Mekâyîs de Allah’ın ibâdıyla insanın sahip olduğu abîd arasındaki kullanım ayrımını kaydeder; sözlük tanıklığı ile bir kurumun meşruluğunu birbirine çevirmemek gerekir.','M_ABD|TAB5|QUR',role='historical_context',relation='historical',status='interpretive',tradition='historical',priority='extended',audience='advanced',source_ref='Mekâyîs ʿabd ilk asıl; 3:64; 26:22',historicity='not_applicable')
A(25,'tafsir','1:1-4','Taberî Rabb için efendi, ıslah edip gözeten ve sahip anlamlarını sayar; Beyzâvî tedricî tamamlama fikrini öne çıkarır. Mekâyîs a-l-h kökünü ibadet aslıyla açıklar. Allah adının ilâhtan türeyişi ise müfessirlerce tartışılan etimolojilerden biridir: Taberî bunun doğrudan işitilmiş bir fiil tanıklığından ziyade türetme açıklaması olduğunu belirtir; Beyzâvî başka köken ve özel ad görüşlerini de verir. Ana cümlenin belirli ilahi adı, bütün alternatif türetmelerin kesin birleşimi yapılmaz.','TAB1|TAB2|BAY1|BAY2|M_ALH',role='semantic_range',source_ref='Taberî 1:1 satır 64–85, 1:2 satır 31–44; Beyzâvî 1:1 Allah ve 1:2 Rabb; Mekâyîs a-l-h')
A(27,'semantic_history','1:4-5','Mekâyîs d-y-n ailesinde boyun eğme, itaat, hesap ve borcu akraba kullanımlar olarak toplar. Fakat dîn ve dayn ayrı kelimelerdir; Fatiha’da yevmüddîn hesabın ve karşılığın günüdür. Sahibi önünde kul imgesi bu semantik çevreyle aydınlanabilir, her borç veya boyun eğdirme dalı ayette ayrıca söylenmiş olmaz.','M_DYN|TAB4',role='semantic_range',relation='lexical',tradition='dirayet',priority='extended',audience='advanced',term='dîn / dayn')
A(29,'tafsir','1:5','Zemahşerî, Beyzâvî ve İbn Kesîr, önce sıfatlarıyla anılan Allah’a iyyâka ile doğrudan dönülmesini iltifat olarak açıklar. Nesnenin öne alınması yalnız sana vurgusunu, iki kere söylenmesi ibadet ile yardım talebinin ayrı ayrı O’na yönelişini belirginleştirir. Bu, özgün metnin sıra ve hitap gözleminin açık klasik öncülüdür.','ZAM5|BAY5|IK5|TAB5',role='early_attestation',relation='grammatical',source_ref='Zemahşerî/Beyzâvî/İbn Kesîr 1:5 iltifat ve hasr; Taberî 1:5 zamir tekrarı')
M(31,'1:5','19:93’ün herkesin Rahmân’a abd olarak gelişi, yaratılmışlığın ve bağımlılığın güçlü dayanağıdır. Buradan kulluğu yalnız edilgin bir mülkiyet statüsüne daraltmamak gerekir: incelenen tefsirler ibadetin fiilî yönünü, itaat, sevgi, korku ve ümidi de açıklar. Sözlükteki konuk ağırlama dalı, 1:5’in doğrudan tercümesi olarak doğrulanmış değildir.','QUR|TAB5|IK5|M_ABD',source_ref='19:93; Taberî ve İbn Kesîr 1:5')
A(33,'tafsir','1:2-5','12:23’te rabbî sözünü Taberî, kadının kocası olan insan efendi diye açıklar; bu, Rabb kelimesinin insan için kayıtlı kullanımına gerçek bir klasik tanıktır. Fatiha’daki bütün âlemlerin Rabbi ise böyle sınırlı efendilikle özdeş değildir. 3:64’ün insanları birbirine rab edinme yasağı ve Musa’nın 26:22’de köleleştirmeyi nimet iddiasına karşı anması, insan sahipliği benzetmesinin sınırını gösterir.','TAB1223|QUR|M_RBB',role='constraint',source_ref='Taberî 12:23 ana metin; 3:64; 26:18–22')
N(33,'1:1-5','Rab–sahip–kul sözlük ve tefsir zemini açıktır; iltifat ile bu ilişkiye doğrudan hitap edilmesi de eski açıklamalarda vardır. Yol, güçlü el, dîn ve konuk evi dallarını tek sahiplik sahnesine birleştiren çizgi ise daha geniş bir proje okumasıdır. Bu sahnenin bütün dalları için kaynak yokluğu veya ilk defa söylenmiş olma iddiası kurulmaz.','TAB1|TAB2|TAB5|TAB1223|BAY2|M_ABD|M_RBB|M_MLK|M_DYN',checked='Taberî 1:1 Allah türetmesi satır 64–85; 1:2 Rabb satır 31–44; 1:5 kulluk ve yardım; 12:23 rabbî açıklaması; Beyzâvî 1:2 terbiye; Mekâyîs ʿabd, r-b-b, m-l-k, d-y-n tam maddeler.',attestation='partial',scope='Paragraflar 23–33; sahip/efendi/kul ve ev terkibi')

A(39,'tafsir','1:4','Taberî dîn için hesap ve karşılık anlamını, önceki dil ve rivayet tanıklarıyla açıklar. İbn Kesîr de insanların amellerine göre karşılık görmesini, Allah’ın dilediğini bağışlaması kaydıyla anlatır. Böylece karşılık günü kesin bir alacak miktarının otomatik tahsili gibi düşünülmez; adalet ile af aynı dinî çerçevede durur.','TAB4|IK4',role='anchor',source_ref='Taberî 1:4 satır 35–50; İbn Kesîr 1:4 son bölüm')
A(41,'qiraat','1:4','İbnü’l-Cezerî’nin on okuyucu listesinde Âsım, Kisâî, Ya‘kūb ve onuncu okuyucu Halef mâliki; diğer altı okuyucu meliki okur. İkisi de kanonik olup sahiplik ile hükümranlığı farklı vurgu ile dile getirir. Taberî’nin melik tercihi ve gerekçesi bir müfessirin seçimidir; mâlik okuyuşunun geçersizliği anlamına gelmez. Buradaki onuncu okuyucu Halef, Hamza’dan işmam nakleden Halef’in rivayet göreviyle karıştırılmaz.','NASHR|TAB4|IK4|BAY4',role='clarification',relation='lexical',tradition='rivayet',canonical=True,source_ref='en-Neşr I, s.271; Taberî 1:4 satır 3–17; İbn Kesîr 1:4',priority='core',audience='advanced')
M(43,'1:4-7','Allah’a nispet edilen gazabı cezalandırma olarak açıklamak, Zemahşerî ve Beyzâvî’de görülen bir kelami yorumdur. Taberî ise ceza, kınama sözü ve ilahi sıfatın insani değişimden ayrılması yönündeki açıklamaları birlikte tartışır. Buradaki kısa tanım bütün geleneğin tek sözlük hükmü gibi sunulmaz; insanın bedensel öfke hali de Allah’a taşınmaz.','TAB7|ZAM7|BAY7|M_GHDB',source_ref='Taberî 1:7 gazap yorumları; Zemahşerî/Beyzâvî 1:7',connection='direct')
A(45,'tafsir','1:4','Borç/karşılık çağrışımının eski bir öncülü vardır: Taberî dîn açıklamasında karşılıklı borç verme ile karşılık vermeyi yan yana getiren bir şiiri kullanır. Mekâyîs de daynı aynı ailede işler; q-w-m maddesinde değer biçmeyi bir şeyin yerine ötekini koymayla açıklar. Bu malzeme hesap fikrini aydınlatır, fakat Fatiha’nın içinde bir dinar veya maddi fiyat geçtiği anlamına gelmez.','TAB4|M_DYN|M_QWM',role='early_attestation',relation='lexical',source_ref='Taberî 1:4 dîn şiiri satır 36–50; Mekâyîs d-y-n ve q-w-m')
M(47,'1:7','Mekâyîs gh-y-r için iki asıl ayırır ve Fatiha’daki ghayr kelimesini açıkça öteki/farklı olan anlamının altında verir. Erzak, yağmur ve kıskanıp koruma öteki asla aittir; diyet dalının bu iki asıldan hangisine bağlanacağı hakkında bile tereddüt belirtir. Bu yüzden diyet, 1:7’nin anlamına eklenemez; d-l-l ailesindeki boşa giden kan da bağlamsal sapıklığın kendisi değildir.','M_GHYR|M_DLL',source_ref='Mekâyîs gh-y-r tam madde, iki asıl ve Fatiha alıntısı; d-l-l madde',connection='rejected')
N(49,'1:4-7','Dîn–borç/karşılık ilişkisinin açık klasik tanığı, q-w-m değer/diklik ilişkisinin sözlük tanığı vardır. Fatiha’nın yolu ile başka ayetlerdeki doğru tartıyı tek borç–fiyat–terazi örgüsünde bir araya getiren okuma ise bu tanıkları aşan terkiptir. Sure teraziyi adlandırmaz; tartı sahnesi aşağıdaki Kur’an paralellerinden gelir. Tam birleşimin klasik bir yokluk taraması yapılmadı.','TAB4|M_DYN|M_QWM|QUR|H_M223',checked='Taberî 1:4 hesap/karşılık ve borç verme şiiri satır 35–50; Mekâyîs d-y-n ve q-w-m tam maddeler; 2:282, 17:35, 26:182, 83:3–6, 21:47 tam ayetler; Müslim 223 matın.',attestation='partial',scope='Paragraflar 39–53; hesap, borç, fiyat ve tartı')
X(51,'1:4','82:19 başkasına güç yetirememe ve emrin Allah’a aitliğini, 40:16 hükümranlığın kimde olduğunu açıklar. 83:3–6 ölçüyü eksiltme ile insanların Rabbü’l-âlemîn önünde kalkacağı günü aynı uyarıda buluşturur. Hesap–doğruluk bağlantısı burada gerçekten metinseldir; Fatiha’daki q-w-m lafzıyla kurulması ikinci yorum adımıdır.','82:16–19; 40:16; 25:26; 83:3–6; 21:47; 101:6–8')
M(53,'1:4-7','2:282’de unutma ihtimali ve tanıklığın aqwam oluşu, vadeli borcun yazıya ve tanıklığa bağlanmasıyla ilgilidir. Buradaki d-l-l, 1:7’nin bütün dinî kınamasını taşımadığı gibi aqwam da tanığın fiziksel olarak dik durması demek değildir. 2:16’daki ticaret benzetmesi ise gerçekten hidayet/dalâlet karşıtlığını kullanır; farklı bağlamların benzetme gücü aynı dilbilgisel anlam değildir.','QUR|M_DLL|M_QWM',source_ref='2:282 tam ayet; 2:16; 17:35; 26:182')
H(53,'1:2-5','Müslim 223’te hamdin teraziyi doldurması ve insanın kendisini satıp ya kurtarması ya da helake sürüklemesi birlikte anılır. Bu sahih rivayet övgü, değer ve hesabı düşünmeye yardımcı bir tematik paraleldir. Fatiha’ya doğrudan sözlük tefsiri yapmaz ve dîn ile daynı özdeş kelimeler haline getirmez.','H_M223','sahih','Müslim 223; derece dayanağı Sahîh Müslim koleksiyonu')

A(59,'tafsir','1:1-3','Rahim benzetmesinin klasik zemini vardır: Zemahşerî rahmi içindekini kuşatan yerle birlikte anarken merhametin insanda doğurduğu iç değişim ile Allah’ın ihsanını ayırır; Beyzâvî de ilahi rahmeti sonuçları ve iyilikle açıklar. Mekâyîs rahmet/rahim ailesini yumuşaklık ve yakınlık çevresinde işler. Rahmin ev diye bütün bir sureye yayılması ise bu klasik açıklamaların doğrudan tercümesi değildir.','ZAM1|BAY1|M_RHM',role='early_attestation',relation='lexical',source_ref='Zemahşerî 1:1 Rahman/Rahim son bölümü; Beyzâvî 1:1 rahmet; Mekâyîs r-h-m')
H(59,'1:1-3','Esirler arasında çocuğunu bulup emziren annenin şefkati, Buhârî’de Allah’ın kullarına merhametinin daha büyük oluşunu anlatmak için kullanılır. Bu sahih temsilde anneyle ilahi rahmet arasında öğretici bir benzerlik vardır; beden, doğum acısı veya insani iç değişim Allah’a isnat edilmez. Rivayet burada tematik dayanak olup Fatiha’nın doğrudan tefsiri değildir.','H_B5999','sahih','Buhârî 5999; derece dayanağı Sahîh Buhârî koleksiyonu')
H(59,'1:1-3','Buhârî’de rahim/akrabalık bağı Rahmân ile ilişkilendirilir ve akrabalık bağını koruma vurgulanır. Bu sahih kayıt rahmet ile akrabalığın dinî bağını güçlendirir; tarihsel dilbilim bakımından hangi kelimenin hangi çağda ötekinden türediğini tek başına ispatlamaz. Burada doğrudan Fatiha açıklaması olarak sınıflanmaz.','H_B5988','sahih','Buhârî 5988; derece dayanağı Sahîh Buhârî koleksiyonu')
A(61,'semantic_history','1:2','Rabbin tamamlama ve gözetme anlamı Taberî/Beyzâvî’de, koyunun bakım için evde tutulması gibi kullanım malzemesi Mekâyîs r-b-b’de bulunur. Bununla beraber 17:24’teki rabbayâni, r-b-w ailesindeki büyütme fiilidir. Yakın ses ve bakım anlamı iki ayrı kökün yankısını taşıyabilir; r-b-b ile r-b-w harf ve kök özdeşliği diye kaydedilmez.','TAB2|BAY2|M_RBB|QUR',role='semantic_range',relation='lexical',priority='core',audience='advanced',source_ref='Taberî 1:2 Rabb; Beyzâvî 1:2; Mekâyîs r-b-b; 17:24',term='r-b-b / r-b-w')
M(63,'1:1-7','İki rahmet anışının araya Rabbi alarak oluşturduğu çerçeve, burada korunan besmele sayımıyla okunur. Taberî besmeleyi Fatiha ayeti saymadığından bu tekrarı aynı şekilde kurmaz; Bikâî ise tekrarın nazm içindeki gelişimini açıklar. Ev içi erzak ve kıskanıp koruma dalları ghayrin 1:7’deki farklılık anlamına gizlice eklenemez.','TAB3|BIQ1|BIQ3|M_GHYR',source_ref='Taberî 1:3 bütünü; Bikâî 1:1 ve 1:3; Mekâyîs gh-y-r',connection='resonant')
N(63,'1:1-7','Rahmet–rahim ve Rabbi tamamlama ile açıklama klasik öncüllüdür; tekrarın sure düzeni bakımından işlenmesi de vardır. Rahimden doğup terbiye edilen, ev idaresi ve erzakla tutulan kişinin bütün yolunu bu çerçeveye yerleştirmek ise ayrı sözlük malzemelerinin proje terkibidir. İncelenen metinler bu parçaların tanığıdır; tam rahim→ev→yol ağı için klasik kaynak yokluğu göstermez.','ZAM1|BAY1|BAY2|TAB3|BIQ3|M_RHM|M_RBB|M_QWM|M_GHYR|M_NAAM',checked='Zemahşerî/Beyzâvî 1:1 rahmet/rahim bölümleri; Beyzâvî 1:2 Rabb; Taberî 1:3 tekrar itirazı; Bikâî 1:3 tekrar; Mekâyîs r-h-m, r-b-b, q-w-m, gh-y-r, n-ʿ-m tam maddeler.',attestation='building_blocks_only',scope='Paragraflar 59–67; rahim, büyütme ve ev ağı')
X(65,'1:1-5','17:23–24 ibadetin yalnız Allah’a yönelmesini, anne babaya iyiliği, merhameti ve onların büyütmesini aynı pasajda bir araya getirir. Bu, ana metnin kurduğu bakım paralelinin güçlü dayanağıdır. 4:23’teki üvey kızlar ise ev içi bir hukuk bağlamıdır; buradaki benzerlik kökleri veya hükümleri tekleştirmez.','17:23–24; 3:6; 4:1; 4:23')
X(67,'1:1-5','Musa’nın annesine geri döndürülmesi 28:7–13’te, ilahi gözetim altında yetiştirilmesi 20:39’da açıktır. Firavun’un yetiştirme iddiasına 26:22’de köleleştirme hatırlatılır. Böylece bakım nimet sayılabilse de zorbalığı borçlandırma aracına çevirmek metnin içinde sorgulanır; bu karşılaştırma Fatiha’nın tek bir ev kıssasını anlattığı anlamına gelmez.','20:39; 28:7–13; 26:18–22; 3:79; 55:1–4')

A(73,'tafsir','1:2-7','1:7’de nimet, her insana verilen servet veya rahatlıktan ayrılarak doğru dini yolun nimetiyle açıklanır. Taberî 4:69’daki peygamberler, sıddıklar, şehitler ve salihleri anarken Beyzâvî iman ve bağışlamayı öne çıkarır. Bu nedenle n-ʿ-m maddesindeki dünyevi iyi hayat, bitki veya yumuşaklık dalları bağlamı aydınlatabilir ama bu ayetteki nimetlilerin yeterli tanımı olmaz.','TAB7|BAY7|M_NAAM',role='anchor',source_ref='Taberî 1:7 ilk bölüm; Beyzâvî 1:7 nimet; Mekâyîs n-ʿ-m')
M(75,'1:2','Hamdın şükürden daha geniş oluşu tek yönlü bir kapsam hükmü değildir. Zemahşerî, Beyzâvî ve İbn Kesîr hamdin nimet dışındaki güzel nitelikleri de övmesini, şükrün ise nimet karşılığında kalp, dil ve davranışla gösterilebilmesini ayırır. Hamd konu bakımından, şükür araçları bakımından genişleyebilir. İbn Kesîr bu nedenle Taberî’nin iki lafzı bütünüyle aynı sayan açıklamasını eleştirir; özgün kısa karşılaştırma bu boyut ayrımıyla okunmalıdır.','IK2|ZAM2|BAY2|TAB2|M_HMD',connection='direct',source_ref='İbn Kesîr 1:2 satır 7–10; Zemahşerî/Beyzâvî 1:2 hamd–şükür; Taberî 1:2 satır 3')
A(77,'nazm','1:2-7','Nimet adlandırılmadan hamdin önde gelmesi, surede övgünün talebe zemin hazırladığını gösterir. Müslim 395’in doğrudan açıklaması ve Bikâî’nin övgü–rahmet–mülk–yardım–yol sırası, bu düzeni temellendirir. Nimetin yürüyüşte tamamlanması ise aşağıdaki ayet paralellerinden beslenen bir yorumdur; nazm tanıklığı her n-ʿ-m dalını aynı anda harekete geçirmez.','H_M395|BIQ2|BIQ3|BIQ4|BIQ7',role='nazm',relation='structural',tradition='nazm',source_ref='Müslim 395a; Bikâî 1:2–4 ve 1:7 ana metin')
N(77,'1:2-7','Övgüden duaya ilerleme ve nimetin dini hidayetle ayrılması açık klasik açıklamalardır. Bunları tamamlama, minnetin anlatılması ve sonunda hamde dönüş zinciriyle okumak, birden fazla Kur’an bağlamını sureye taşıyan kısmi terkiptir. Hamd/şükür arasında mutlak kapsam hiyerarşisi yenilik sayılmaz; zaten klasik kaynaklar bu basitleştirmeyi sınırlar.','TAB7|BAY7|IK2|ZAM2|BIQ2|BIQ7|QUR',checked='Taberî 1:7 nimetliler başlangıcı; Beyzâvî 1:7 iman/bağışlama; İbn Kesîr/Zemahşerî 1:2 hamd–şükür; Bikâî 1:2 ve 1:7 satır 1–8; 48:2, 16:121, 7:43, 10:10 tam ayetler.',attestation='partial',scope='Paragraflar 73–79; nimet/hamd ve tamamlanma sırası')
X(79,'1:2-7','48:2 nimet tamamlama ile sırâtı, 16:121 nimetlere şükür ile sırâtı, 7:43 cennette hidayet için hamdi gerçekten birlikte anar. 2:150 ve 5:3 ise yöneliş ve dinin tamamlanması gibi farklı bağlamlardadır. Birlikte okunabilirler; her birinin nimeti aynı somut nesne veya aynı zaman çizgisi değildir.','48:2; 16:121; 7:43; 10:10; 2:150; 5:3; 12:6; 93:11; 106:3–4')

A(85,'tafsir','1:7','İbn Kesîr nimetin anʿamta ile Allah’a açıkça nispet edilmesi, gazabın ise meçhul biçimde gelmesini zaten açıklar. Bu gramer farkı, gazabın ilahi iradeyle ilgisizliği demek değildir; onun devamındaki açıklama her şeyi ilahi kudret çerçevesinde değerlendirir. Taberî de gazap ve dalâl gruplarının birbirinin kusurundan tamamen uzak olmadığını söyler; üçlü düzen sabit etnik kelime tanımlarına indirgenmez.','IK7|TAB7|ZAM7|BAY7',role='early_attestation',relation='grammatical',source_ref='İbn Kesîr 1:7 satır 20; Taberî 1:7 iki grubun ortak kusuru ve gazap görüşleri')
H(85,'1:7','Adiyy b. Hâtim’den gelen rivayette gazaba uğrayanlar Yahudiler, sapanlar Hristiyanlar diye açıklanır. Tirmizî 2954’ün incelenen sayfasında Darussalam hükmü hasendir. Bu doğrudan ayet açıklaması, Taberî’nin iki grubun ortak kusurlarına dair açıklamasıyla birlikte okunur; d-l-l ve gh-d-b kelimelerinin her kullanımı topluluk adına dönüşmez ve kişilere yalnız aidiyetlerinden ötürü hüküm verilmez.','H_T2954|TAB7','hasan','Tirmizî 2954; sayfada Darussalam: hasen',relation='direct_hadith_tafsir',transmitter='Adiyy b. Hâtim',attested_in='Taberî 1:7; İbn Kesîr 1:7; ed-Dürr 1:7; aynı rivayet ailesi')
M(87,'1:7','Kızarma, şişme ve yüzün değişmesi insanda öfkelenen kişinin haliyle ilgilidir. Bunu Allah’ın gazabına uğrayan kişinin yüz renginin açıklaması yapmak özneyi değiştirir; sözlük böyle bir sonucu tek başına vermez. İlahi gazap da insanın kan ve beden değişimiyle tasvir edilmez. Nimetle rahat yüzün karşılaştırması ancak ayrı Kur’an yüz tasvirlerinin yardımıyla kurulabilir.','M_GHDB|M_NAAM|ZAM1|BAY1|QUR',connection='rejected',source_ref='Mekâyîs gh-d-b ve n-ʿ-m; ilahi sıfatlar için Zemahşerî/Beyzâvî 1:1; 80:38–41')
N(89,'1:4-7','Etkin nimet/meçhul gazap ayrımının açık öncülü İbn Kesîr’dir; dini grupların örneklenmesi ve gazabın açıklanması da klasiktir. Köklerdeki insani kızarmayı, ayetteki gazaba uğrayanın yüzüne taşıyan çıkarım ise yeterli değildir. Kıyametteki aydınlık/karanlık veya nimetli yüz sahnesi, aşağıdaki ayrı ayetlerin tematik paralelidir; 1:7’nin kelime içi rengi diye sunulmaz.','IK7|TAB7|M_GHDB|M_NAAM|QUR',checked='İbn Kesîr 1:7 satır 20 etkin/meçhul; Taberî 1:7 gazap açıklamaları ve grup karşılaştırması; Mekâyîs gh-d-b, n-ʿ-m tam maddeler; 80:38–41, 83:24, 88:2,8–9, 14:5 tam ayetler.',attestation='partial',scope='Paragraflar 85–93; gazap, nimet ve yüzler',connection='speculative')
M(91,'1:7','20:81’de gazabın kişinin üzerine gelmesi ve kişinin çöküp helake gitmesi açıkça söylenir; sonraki ayet tövbe ve hidayet imkânını ekler. Fatiha’daki alayhim ise gazabın muhatabını belirtir, zorunlu olarak yukarıdan inen fiziksel bir cismin hareketini anlatmaz. İki pasajın birlikte okunması mecazı genişletir; edat tek başına bu sahneyi üretmez.','QUR|TAB7|IK7',source_ref='20:81–82; 1:7; 3:162',connection='strong')
X(93,'1:7','4:69 nimet verilenlerin kimler olduğunu ve onlarla iyi arkadaşlığı açıklar; Taberî’nin 1:7 okumasında bu ayet zaten kullanılır. 88 ve 83’teki nimetli yüzler ile 80:38–41’deki karşıt yüzler ahiret sonucunu görünür kılar. Bu yüz ayetlerinin alayhâ/alayhim benzerliği tek başına aynı gramer veya aynı fiziksel örtü anlamı değildir.','4:69; 19:58; 88:2,8–9; 83:24; 80:38–41')

A(99,'semantic_history','1:1','İsm için sumuv/yükselme ve vesm/damga açıklamaları aynı kesin kökün iki dalı değildir. Zemahşerî sumuv türetmesini sarf gerekçeleriyle anlatır; Beyzâvî Basralıların sumuv, Kûfelilerin vesm görüşünü karşılaştırıp ikincisine baş harfi düşen biçime vasıl hemzesi gelmesi bakımından itiraz eder. İki görüşün varlığı tarihi bir tanıklıktır; yüksekten görünme ile izi okumanın tek anda adın zorunlu anlamı olması ayrıca kanıt gerektirir.','ZAM1|BAY1|M_SMW|M_WSM',role='disagreement',relation='lexical',status='disputed',priority='core',audience='advanced',source_ref='Zemahşerî/Beyzâvî 1:1 ism sarfı; Mekâyîs s-m-w ve w-s-m',term='ism: sumuv / vesm')
A(101,'tafsir','1:2','Âlemi yaratıcısını bildiren işaret diye açıklamak İbn Kesîr, Zemahşerî ve Beyzâvî’de açıkça vardır. Âlemînin bütün yaratılış türlerini mi, özellikle akıllı varlıkları mı kapsadığına dair farklı açıklamalar da aktarılır. Sözcüğü işaretle okumak bu klasik zemine dayanır; çoğulun her bağlamdaki kapsamını tek bir tanıma kilitlemez.','IK2|ZAM2|BAY2|M_ALM',role='early_attestation',source_ref='İbn Kesîr 1:2 son satırlar; Zemahşerî/Beyzâvî 1:2 âlem; Mekâyîs ʿ-l-m')
N(103,'1:1-2','Âlem–işaret ilişkisi açık klasik öncüllüdür; ism için rakip iki etimoloji de eski tartışmanın malzemesidir. Ad ile âlemi yan yana koyup işaret üzerinden bütün işin sahibine bağlamak, bu malzemeyi yeniden düzenleyen proje okumasıdır. Özellikle iki ism etimolojisini aynı anda kesin saymak veya derecesi denetlenmeyen ism-i a‘zam naklini kesin delil yapmak bu terkibin kanıtı değildir.','ZAM1|BAY1|ZAM2|IK2|M_SMW|M_WSM|M_ALM',checked='Zemahşerî/Beyzâvî 1:1 ism ve Allah bölümleri; Zemahşerî/İbn Kesîr 1:2 âlem işareti; Mekâyîs s-m-w, w-s-m, ʿ-l-m tam maddeler. İsm-i a‘zam naklinin bağımsız isnat/grade kaynağı denetlenmedi.',attestation='partial',scope='Paragraflar 99–107; ad, yükseklik ve işaret')
X(105,'1:1-2','87:1’de yüce Rabbin adı ve 55:78’de adın bereketi doğrudan anılır; 96:1 bir fiili Rabbin adıyla başlatır. 17:110 ise Allah ve Rahmân diye dua etmeyi O’nun güzel adları çerçevesinde birleştirir. Bunlar isim kullanımının dinî işlevini aydınlatır; tartışmalı etimolojinin bütün dallarını ayetlerden geri türetmez.','87:1; 55:78; 96:1; 19:65; 17:110; 25:60; 12:40')
A(107,'tafsir','1:1','Taberî ve Zemahşerî besmelede hangi işe başlanıyorsa ona uygun bir fiilin takdir edilmesini anlatır. Nuh’un gemisinde 11:41 ve Süleyman’ın mektubunda 27:30 gerçekten basmala vardır. Bu, adla başlanması için doğrudan bağlam desteğidir; vesm/damga kökenini tek başına kanıtlayan bir dil tarihi kaydı değildir.','TAB1|ZAM1|QUR',role='clarification',relation='grammatical',source_ref='Taberî 1:1 satır 22–26; Zemahşerî 1:1 başlangıç fiili; 11:41; 27:30')

M(113,'1:1-6','Gün, hilal, gök, yıldız adı ve öğle dengesi burada farklı sözlük maddelerinin resimlerini yan yana getirir. Mekâyîs s-m-w ve n-ʿ-m gök/kozmik kullanımlarını verir; q-w-m öğle sözü ise bu çalışmada yalnız projenin aktardığı 341–394. satırlardan kontrol edildi. Her nadir kelimenin asıl sözlük maddesi bağımsız olarak görülmediği için bu ağ tam bir birincil kaynak denetimi yapılmış sayılmaz.','M_YWM|M_SMW|M_NAAM|M_ALM|PKT',priority='research',audience='research',source_ref='Mekâyîs y-w-m, s-m-w, n-ʿ-m, ʿ-l-m; proje sözlük paketi q-w-m B017')
M(115,'1:1-6','Öğleyin gölgenin hiç olmaması, her yer ve her mevsim için sözlükten çıkarılabilecek bir olgu değildir. Paket, aktardığı Arapça söyleyişte gölge için kaada, yani neredeyse ifadesini içerir. Bu yüzden özgün metnin gölgesizlik tasviri yaklaşık bir öğle mecazı olarak sınırlandırılır; astronomik bir genelleme sayılmaz. Güneşin ilâhe adı ise Mekâyîs a-l-h maddesinde tapılmasına bağlı bir adlandırma açıklaması olarak doğrulandı; bu müellifin etimoloji görüşüdür, belirli tarih ve topluluk belgesi değildir.','PKT|M_ALH',connection='speculative',source_ref='Proje dictionary.md q-w-m B017, satır 384–385; asıl öğle maddesi denetlenmedi. Mekâyîs a-l-h tam madde')
N(115,'1:1-6','Mekâyîs’te gök/yükseklik, yıldız, gün ve ilâhe/güneş adı malzemesi denetlendi; fakat günün terazisi, sıfır gölge ve güneş adını Fatiha’nın ad–ibadet–istikamet dizisine bağlayan tam bağlantı için klasik Fatiha araştırması yeterli değildir. Bu özel sentezin sınıfı not_checked olarak kalır. Sözlükte bir parçanın bulunması, birleşimin klasiklerde bulunmadığı veya yeni olduğu sonucunu vermez.','M_YWM|M_SMW|M_NAAM|M_ALM|M_ALH|PKT',checked='Mekâyîs y-w-m, s-m-w, n-ʿ-m, ʿ-l-m, a-l-h tam maddeler; proje q-w-m B017. q-w-m öğle maddesinin asıl tam kitabı ve Râzî tam Fatiha denetlenmedi; bütün gök/terazi bağlantısının corpus taraması tamamlanmadı.',attestation='not_checked',scope='Paragraflar 113–117; gök, öğle ve terazi',connection='speculative')
A(117,'tafsir','1:1-2','İbrahim’in bu Rabbim sözü, tefsirde tek bir tarihsel inanç evresi olarak okunmaz. İbn Kesîr 6:79’da gerçek araştırma/nazar ile kavme karşı münazara görüşlerini ayırır; kendisi münazara yorumunu tercih eder ve araştırma görüşünü Taberî’ye nispet eder. 6:76’da kaybolanın sürekli Rabb olamayacağını vurgular. Ana metindeki gök okuması bu ihtilaf içinde düşünülmeli; İbrahim’in kesinlikle önce gök cisimlerine iman ettiği diye tarih yazılmamalıdır.','IK676|IK679|QUR',role='disagreement',relation='comparative',status='disputed',source_ref='İbn Kesîr 6:76 son bölüm ve 6:79 web satır 19–28; 6:75–79',priority='core',audience='advanced')

A(123,'tafsir','1:1-3','Rahmet ile yağmur/bitki bağının tefsirde gerçek bir öncülü vardır. Taberî Rahmân–Rahîm açıklamasında mümin ve inkârcının ortak yararlandığı bedeni imkânlar, rızık, bulut, yağmur ve yetişen bitkileri bir arada anar. Buradaki geniş yağmur ağı yalnız birbirinden ayrı sözlük parçalarından doğmuyor; bu kısım aynı ayetin klasik yorumunda zaten yan yana bulunuyor.','TAB1|M_RBB|M_SMW|M_WSM|M_NAAM',role='early_attestation',source_ref='Taberî 1:1 yerel satır 98; Mekâyîs r-b-b, s-m-w, w-s-m, n-ʿ-m')
M(125,'1:2-7','Yağmurun fayda vermesi gh-y-r maddesinin erzak/yarar aslı içindedir; 1:7’deki ghayr ise öteki/farklı asla aittir. Yağmuru Fatiha’nın rahmet/rızık düzeniyle karşılaştırmak mümkündür, fakat ghayr kelimesini yağmur diye ikinci kez tercüme etmek mümkün değildir. Beğenilen toprak gibi nadir h-m-d dalları da bu çalışmada bütünüyle asıl kitap maddesinden bağımsız denetlenmedi.','M_GHYR|TAB1|M_RBB|M_NAAM|PKT',connection='rejected',source_ref='Mekâyîs gh-y-r iki asıl; Taberî 1:1 rahmet/rızık; nadir h-m-d dalı özgün kaynak etiketi düzeyinde')
A(127,'semantic_history','1:2-6','Kuyu donanımı için bağımsız birincil sözlük tanığı görüldü: Ezherî Tehzîb’in III. cilt 10. sayfasında naʿâma kiriş, qâma ise ondan sarkan makara diye anlatılır ve farklı kurulumlar ayrılır. Mekâyîs n-ʿ-m de kuyudaki ağaçları; m-l-k yolcunun suyla işine hâkim olmasını verir. ʿAylamın ʿ-l-m ile ilişkisi ise Mekâyîs’te toplama anlamından mümkün görülen alternatif bir etimolojidir, kesin tarihsel türeme değildir.','THD3_10|M_NAAM|M_MLK|M_ALM',role='semantic_range',relation='lexical',priority='extended',audience='advanced',source_ref='Tehzîb III, s.10; Mekâyîs n-ʿ-m, m-l-k, ʿ-l-m son bölüm',term='naʿâma / qâma / ʿaylam')
N(129,'1:1-6','Bulut–yağmur–bitki–rızık bağlantısı Taberî’de açıkça vardır; yağmur duasında Fatiha’nın övgü ayetlerinin okunması da rivayette bulunur. Kuyu kiriş/makara ve yolcunun suyla hâkim oluşu ayrı sözlük tanıklarıdır. Bütün bunları susuz kalmayan yolcunun Fatiha sahnesi halinde birleştirmek kısmi öncüllü proje terkibidir; kuyu düzeneğini 1:6’nın anlamı yapan bir klasik yokluk araması tamamlanmadı.','TAB1|DUR4|H_AD1173|M_RBB|M_SMW|M_WSM|M_ALM|M_NAAM|M_MLK|THD3_10',checked='Taberî 1:1 satır 98; ed-Dürr 1:4 son Âişe rivayeti ve Ebû Dâvûd 1173 asıl matın/grade; Mekâyîs r-b-b, s-m-w, w-s-m, ʿ-l-m, n-ʿ-m, m-l-k tam maddeler; Tehzîb III:10 tam sunulan pasaj. Râzî tam Fatiha ve başka kuyu bağlantısı aramaları denetlenmedi.',attestation='partial',scope='Paragraflar 123–133; yağmur, su ve kuyu ağı')
H(129,'1:2-4','Âişe’nin yağmur duası rivayetinde Hz. Peygamber hamd, Rabbü’l-âlemîn, Rahmân–Rahîm ve meliki yevmiddîn sözlerini okuyup yağmur ister. Ebû Dâvûd isnadı ceyyid diye niteler; incelenen asıl sayfada Elbânî’nin hükmü hasendir. Bu, Fatiha’nın övgü bölümünün rızık ihtiyacı içinde kullanıldığı tematik tanıktır; kuyu veya her yağmur dalı için doğrudan lafız tefsiri değildir.','H_AD1173','hasan','Ebû Dâvûd 1173; sayfada Elbânî: hasen; müellif: garîb, isnadı ceyyid',attested_in='ed-Dürr 1:4 son rivayet; ayrı bağımsız tanık sayılmaz')
X(131,'1:1-3','42:28 yağmuru, rahmeti ve Hamîd adını; 7:57 ise bulut sevkini, rahmeti, bitkiyi ve ölülerin çıkarılmasını gerçekten birlikte anar. 80:24–32 yiyecek ve suyu hem insan hem hayvan yararı için işler. Bu doğrudan paraleller merhamet/rızık okumasını güçlendirir; Fatiha’nın içinde kuyu makarası tasvir edildiğini göstermez.','42:28; 7:57; 30:48–50; 80:24–32; 32:27')
M(133,'1:2-6','28:23’te Musa su yerine varır ve insanlarla hayvanların sulanmasını görür; 28:24’te su verir, gölgeye çekilip Rabbinden hayır ister. Ayet kuyu kirişinin, makaranın veya hangi aletin kullanıldığını söylemez. Sözlükte görülen düzenek, bu kıssaya açıklayıcı bir tasvir olarak eklenebilir; Musa’nın kullandığı aygıtın tarihsel kanıtı diye verilemez.','QUR|THD3_10',source_ref='28:22–24 tam ayetler; Tehzîb III:10',connection='speculative')

A(139,'tafsir','1:6','Sürü rehberi Fatiha tefsirinde de görülür: Beyzâvî hidayeti latifçe yol gösterme diye açarken hayvanların öncülerine havâdî denmesini örnek verir. Mekâyîs h-d-y de öndeki boyunlar, ilk at grubu ve bastonun önden gidişini aynı rehberlik aslına bağlar. Böylece öncüyü izleme resmi sağlam bir dil zemini bulur; damga, süt ve otlak zincirinin tamamı bu kısa tefsirin içinde değildir.','BAY6|M_HDY|M_RBB|M_NAAM|M_WSM',role='early_attestation',relation='lexical',source_ref='Beyzâvî 1:6 ilk cümleler; Mekâyîs h-d-y ilk asıl')
M(141,'1:2-7','Rabrab diye yaban sürüsünün anılması, Rabb ile evcil sürü arasında kesin bir kök tarihi sağlamaz. Mekâyîs bu kullanımı istisna sayıp toplama anlamına bağlanmasının mümkün olduğunu söyler. Dâlle/kayıp hayvanın sahibinden kopması ise d-l-l’nin başka kullanımıdır; 1:7’de insanın dinî sapmasını anlamak için ancak sınırları belirtilen bir benzetme olabilir.','M_RBB|M_DLL|M_NAAM',source_ref='Mekâyîs r-b-b son bölüm ve d-l-l tam madde',connection='resonant')
H(141,'1:6-7','Müslim’de, susuz çölde yiyecek ve suyunu taşıyan devesini kaybedip sonra bulan kişinin sevinci Allah’ın kulun tövbesinden razı oluşunu anlatan temsilin parçasıdır. Bu sahih rivayet kayıp binek ve yeniden buluşma resmini dinî bir anlam içinde kullanır. Burada Fatiha’nın doğrudan tefsiri veya dâllîn kelimesinin deve olarak tercümesi değildir.','H_M2747','sahih','Müslim 2747a; derece dayanağı Sahîh Müslim koleksiyonu')
N(143,'1:2-7','Hidayet–sürü öncüsü ilişkisi Beyzâvî’de açık klasik öncüllüdür; kayıp hayvan ve rabrab malzemesi sözlükte, kayıp deveyle tövbe temsili hadiste vardır. Sahibi/markası/beslenmesi bilinen sürü ile 1:7’deki dalâl arasında kurulan bütün karşıt örgü ise bu parçaları aşar. Bu çalışma bütün sürü zincirini klasiklerde yok sayacak ölçüde tarama yapmadı.','BAY6|TAB6|M_HDY|M_RBB|M_DLL|M_NAAM|H_M2747',checked='Beyzâvî 1:6 hidayet/havâdî cümleleri; Taberî 1:6 yol ve sebat yorumları; Mekâyîs h-d-y, r-b-b, d-l-l, n-ʿ-m tam maddeler; Müslim 2747a matın. Başka tam Fatiha ve nadir sürü maddeleri eksiksiz taranmadı.',attestation='partial',scope='Paragraflar 139–145; sürü, öncü ve kayıp hayvan')
M(145,'1:6-7','16:5–9 hayvanların yararından yolun istikametine gerçekten geçer. Fakat 7:179’daki hayvandan daha sapmış insan karşılaştırmasının açıklanan nedeni kalple anlamama, gözle görmeme ve kulakla işitmemedir; hayvan sahibini tanır, insan tanımaz cümlesi ayetin açık gerekçesi değildir. O cümle ana metnin tematik çıkarımı olarak okunur.','QUR|BAY6|M_HDY',source_ref='16:5–9; 7:179; 25:44',connection='resonant')

A(151,'semantic_history','1:5-6','Destek alarak yürümenin dil tanığı vardır: Mekâyîs h-d-y, iki kişi arasında onlara yaslanarak yürümeyi rehberlik aslına bağlar. Aynı maddede hemzeli h-d-ʾyi bunun dışında tutar; omuzun göğse yönelmesi bu ayrı kökün istisna dalıdır. Benzer ses ve beden imgesi h-d-y, h-d-ʾ veya h-d-dyi tek kök yapmaz. Durmuş/yorgun binek örneği de burada yalnız proje q-w-m paketinden görülmüştür.','M_HDY|PKT',role='semantic_range',relation='lexical',priority='core',audience='advanced',source_ref='Mekâyîs h-d-y iki kişiye dayanma, sonra hemzeli kök ayrımı; proje q-w-m B016',term='h-d-y / h-d-ʾ / h-d-d')
A(153,'tafsir','1:5','Beyzâvî yardımın zorunlu imkânlar ve araçlar ile isteğe bağlı kolaylaştırmalarını ayırır; yürüyebilecek kişiye binek verilmesini ikinci türe örnek gösterir. Bu, nastaʿîn ile yolcunun güç ve araç ihtiyacı arasındaki açıklayıcı bağın klasik öncülüdür. Mekâyîs’in kuvvetli kumaş anlamındaki ʿabada aslını ise kulluktaki yumuşaklık aslıyla aynı çekirdek saymak doğru olmaz.','BAY5|TAB5|ZAM5|M_ABD',role='early_attestation',source_ref='Beyzâvî 1:5 yardım ayrımı ve binek; Mekâyîs ʿabd iki asıl')
A(155,'nazm','1:5-6','Zemahşerî, ibadetin, yardım istemenin ve ardından hidayet talebinin sırasını özellikle açıklar. Taberî de 1:5’te itaat için yardımın 1:6’daki sebat duasını belirlediğini söyler; bu gerekçeyle gelin/hediye gibi başka sevk anlamlarını birincil yorum yapmaz. Yardıma yaslanıp yolu sürdüren kişi resmi bu sırayı açan bir benzetmedir.','ZAM5|ZAM6|TAB5|TAB6',role='nazm',relation='structural',tradition='nazm',source_ref='Zemahşerî 1:5–6 sıra; Taberî 1:5 yardım ve 1:6 alternatif yorumun reddi')
N(155,'1:5-6','Yardım→hidayet sırası klasik tefsirde açıktır; iki kişiye yaslanarak yürüme Mekâyîs’te, binek yardımı Beyzâvî’de açık malzemedir. Bunları yorgun binek, dik beden, omuz ve Fatiha duasında tek yolcu sahnesi olarak birleştirmek kısmi öncüllü proje terkibidir. Ayrı köklerin ses benzerliği terkibin sözlükte tek asıl olduğu delili değildir.','TAB5|TAB6|ZAM5|BAY5|M_HDY|M_ABD|M_QWM|PKT',checked='Taberî 1:5 yardım ve 1:6 tevfik/alternatif yorumu reddetme; Zemahşerî 1:5 sıra; Beyzâvî 1:5 yardım/binek; Mekâyîs h-d-y, ʿabd, q-w-m tam maddeler; q-w-m B016 sadece proje paketi. Nadir h-d-d maddesi bağımsız kontrol edilmedi.',attestation='partial',scope='Paragraflar 151–157; destek, beden ve yürüyüş')
X(157,'1:5-6','18:77’de duvarın doğrultulması, 18:95’te güçle yardım, 67:22’de yüzüstü yürüyenle düzgün yolda yürüyenin karşılaştırılması ayrı sahnelerdir. Bunlar dayanma/doğrulma resmini güçlü biçimde besler. Aynı resme katılmaları, Fatiha’daki mustaqîmin her bir sahneyi bağlamsal olarak söylediğini göstermez.','18:77; 18:95; 12:18; 21:112; 7:128; 2:45; 5:2; 67:22; 25:63')
H(157,'1:6','Nevvâs rivayetindeki düz yol, duvarlar ve açık kapılar temsili İslam, Allah’ın sınırları, yasaklar ve çağırıcılarla açıklanır. Tirmizî’nin kendi hükmü hasen garîbdir; aynı incelenen sayfada Darussalam sahih yazar. Burada müellif hükmü esas alınarak hasan kaydedildi. İbn Kesîr bu temsili Fatiha şerhinde kullanır; asıl rivayet ise Fatiha’nın iniş olayı veya bu ayetin açık zikri olmadan verilen tematik açıklamadır.','H_T2859','hasan','Tirmizî 2859: müellif hasen garîb; sayfada Darussalam sahih',attested_in='İbn Kesîr 1:6; ed-Dürr 1:6; Nevvâs rivayet ailesi')

A(163,'semantic_history','1:6-7','Yutulan şeyin gözden kaybolması ve yürüyenin yolda kaybolup görünmez olması, Mekâyîs s-r-ṭ maddesinde eski köken açıklamalarıdır; Zemahşerî ve Beyzâvî de yol için yutma türetmesini verir. Bunlar kelimenin niçin böyle adlandırıldığına ilişkin açıklamalarla, ayetteki düz yol anlamının ayrılmasını gerektirir. D-l-l’nin süt içinde kayıp veya gömülme kullanımları başka bağlamlardır.','M_SRT|M_DLL|ZAM6|BAY6',role='semantic_range',relation='lexical',priority='extended',audience='advanced',source_ref='Mekâyîs s-r-ṭ ve d-l-l tam maddeler; Zemahşerî/Beyzâvî 1:6 sırât',term='s-r-ṭ / d-l-l')
N(165,'1:6-7','Sırâtın yutma/gözden kaybolma etimolojisinin açık klasik tanıkları vardır; d-l-l’nin gizlenme/kayıp malzemesi de klasiktir. İki kayboluşu biri yönü ve varışı olan, diğeri varışsız diye karşılaştırmak ise burada ayrı malzemelerden kurulan terkiptir. Ayetin birincil karşıtlığı dini doğru yol ve sapmadır; bu fiziksel karşılaştırmanın tam klasik öncül taraması tamamlanmadı.','M_SRT|M_DLL|ZAM6|BAY6|TAB6|IK6',checked='Mekâyîs s-r-ṭ ve d-l-l tam maddeler; Zemahşerî/Beyzâvî 1:6 yutma türetmesi; Taberî 1:6 yol yorumları; İbn Kesîr 1:6 yol ve hidayet. Diğer klasiklerde bütün iki-kayboluş terkibi eksiksiz taranmadı.',attestation='building_blocks_only',scope='Paragraflar 163–167; iki kayboluş')
M(167,'1:6-7','32:10’da toprakta kaybolma, ölümden sonra yeniden yaratılma itirazının içindedir; 20:52’de kaybetmeme/unutmama ilahi bilgi hakkındadır. 6:24’te uydurulan ortakların kaybolması başka bir hesaptır. Ortak d-l-l çevresi bu bağlamları karşılaştırmayı mümkün kılar; hepsini 1:7’deki aynı ahlaki hükme veya tek fiziksel yok oluşa indirgemez.','QUR|M_DLL',source_ref='32:10; 20:51–52; 6:24; 82:16; 36:66',connection='resonant')

A(173,'semantic_history','1:6','Mekâyîs, Harem’e yaklaşma amacıyla gönderilen kurbanlık ile gelin ve hediyeyi dostça gönderme aslı altında; önden rehberliği ayrı asıl altında işler. Bu tarihi sözlük düzeni aynı harflerin iki anlam alanına tanıktır. 22 ve 48’de kurbanın belirlenmiş yere ulaştırılması açıktır; ihdinâ fiilinin doğrudan tercümesi ise kurbanı Harem’e götürmek değildir.','M_HDY|QUR|M_WSM|M_NAAM',role='semantic_range',relation='lexical',priority='extended',audience='advanced',source_ref='Mekâyîs h-d-y ikinci asıl; 22:33–37; 48:25',term='hidayet / hediye / hedy')
A(175,'tafsir','1:6','Gelin ve hediye sevkini Fatiha’ya bağlayan teklif Taberî’de zaten vardır. O, bu anlamları ve 37:23’te cehenneme sevki kullanıp ihdinâyı ahirette cennet yoluna götürme diye açıklayan görüşü aktarır; ardından 1:5’in itaat için yardım bağlamı yüzünden bu görüşü ayetin birincil anlamı olarak reddeder. Bu, aynı bağlantının klasik tartışmaya girmiş olduğunu gösterir; aktarımın varlığı müfessirin onayı değildir.','TAB6|M_HDY',role='rejected_candidate',relation='direct_tafsir',status='disputed',source_ref='Taberî 1:6 gelin/hediye/37:23 ve cennet yolu teklifi, ardından reddiyesi; Mekâyîs h-d-y',connection='rejected',priority='core',audience='advanced')
M(177,'1:6-7','Eve varış ana anlatının ikincil resmidir; Taberî’nin reddettiği görüşü onun kabul ettiği asli tefsir gibi göstermek doğru olmaz. İbn Kesîr ise dinî hidayetten ahiret sıratına ve cennet yakınlığına uzanan bir devam ilişkisi kurar; bu, dünyadaki itaat duasının yalnızca ahiret adresine indirgenmesi değildir. Türkçe yoluna yönelt/ilet ifadesi de varışı zorunlu olarak dışlamaz; ek resim bir çevirinin eksikliği diye kanıtlanmış değildir.','TAB6|IK7|M_HDY',source_ref='Taberî 1:6 reddiye; İbn Kesîr 1:7 satır 19; Mekâyîs h-d-y iki asıl',connection='resonant')
N(177,'1:6-7','Bu ağın sınıfı partialdır: gelin/hediye→ahiret yolu önerisi Taberî’de açıkça tartışılır ve asli yorum olarak reddedilir; dinî hidayet→ahiret sıratı bağı İbn Kesîr’de bulunur. Ana metin bunları ev, nikâh, sığınma ve kurbanla geniş bir ikincil varış resmine dönüştürür. Böyle bir resim hiç klasik öncülü yok diye sunulamaz; reddedilmiş teklif ile burada izin verilen sınırlı rezonans ayrı tutulmalıdır.','TAB6|IK7|M_HDY|M_MLK|M_RBB|QUR',checked='Taberî 1:6 gelin/hediye/cennet yolu teklifinin tam aktarımı ve reddiyesi; İbn Kesîr 1:7 satır 19 ahiret sıratı; Mekâyîs h-d-y, m-l-k, r-b-b tam maddeler; 9:6, 22:33–37, 27:35–36 tam ayetler. Râzî tam Fatiha ve bütün diğer tefsirlerde ev zinciri eksiksiz taranmadı.',attestation='partial',scope='Paragraflar 173–179; ev, hediye, gelin, kurban ve varış')
M(179,'1:6','9:6’da sığınan kişinin güvenli yere ulaştırılması ayrı, açık bir emirdir; h-d-y kelimesi o cümlede geçmez. Süleyman’ın hediyeyi reddinde 27:36’nın açık gerekçesi Allah’ın verdiklerinin maldan üstünlüğüdür. Hediyenin dosta değil rakibe götürülmesinin sebep olduğu psikoloji ise ana metnin ek yorumudur; ayetin aktardığı gerekçe yerine geçirilmez.','QUR|M_HDY',source_ref='9:6; 27:35–36; 22:37; 6:118',connection='resonant')

N(185,'1:5-6','Kulluk ile yolun birlikte okunması temel düzeyde açık öncüllüdür: Taberî 1:5 yol/deve örneklerini verir ve 36:61 kullukla sırâtı aynı cümlede buluşturur. Bu yerel buluşma yeni bir keşif olarak sınıflanmaz; özgün metindeki daha geniş ağları otomatik olarak doğrulayan bir delil de değildir.','TAB5|IK5|M_ABD|QUR',checked='Taberî 1:5 satır 4–9; İbn Kesîr 1:5 başlangıcı; Mekâyîs ʿabd tam madde; 36:61 tam ayet.',attestation='explicit',scope='Paragraf 185; kulluk/yol buluşması',connection='direct')
N(187,'1:6-7','Sürü öncülüğünün hidayet örneği klasik, 16:5–9’un hayvanlardan yolun istikametine geçmesi metinseldir. Bunlara kayıp deve, damga, kurban ve adın tamamını katmak kısmi proje terkibidir. Aynı 16:9 için özgün metinde görülen iki Türkçe gloss okuyuş farkı değildir; lafzın mana vurgularını farklı ifade eder. İkinci açıklama başka bir kanonik Kur’an cümlesi gibi sunulmaz.','BAY6|M_HDY|M_NAAM|M_WSM|QUR',checked='Beyzâvî 1:6 hidayet/havâdî; Mekâyîs h-d-y, n-ʿ-m, w-s-m tam maddeler; 16:5–9, 22:34–37, 36:71–72 tam ayetler. Bütün sürü/kurban/ad zinciri için tam klasik arama yapılmadı.',attestation='partial',scope='Paragraf 187; sürü, yol, kurban ve ad')
N(189,'1:1-5','Musa’nın yetiştirilmesi ve Firavun’un nimet iddiası aynı kıssada açıkça karşılaşır; merhamet ve terbiye için klasik sözlük/tefsir malzemesi vardır. Burada görülen beş ağın bir araya gelişi, asılları ayrı olan kelimelerle kurulan proje çözümlemesidir. Bir ayette buluşmaları tek kök veya klasiklerde aynı beşli sentezin mevcut/yok olduğu anlamına gelmez.','QUR|M_RHM|M_RBB|ZAM1|BAY2',checked='26:18–22, 17:23–24, 28:7–13 tam ayetler; Mekâyîs r-h-m ve r-b-b tam maddeler; Zemahşerî 1:1 rahmet; Beyzâvî 1:2 terbiye.',attestation='building_blocks_only',scope='Paragraf 189; rahim, terbiye ve Firavun')
N(191,'1:4-7','Gazapla helak/düşüş 20:81’de ve yüzüstü/düz yürüme karşıtlığı 67:22’de açıktır; etkin nimet/meçhul gazap İbn Kesîr’in eski açıklamasıdır. Bunların q-w-m doğrultması ve tökezleme olarak tek sahneye alınması proje benzetmesidir. Helaki basit fiziksel sürçmeye veya alayhimi dikey harekete eşitleyen anlam çıkarılmaz.','QUR|IK7|TAB7|M_QWM|M_GHDB',checked='20:81–82, 67:22 tam ayetler; İbn Kesîr 1:7 satır 20; Taberî 1:7 gazap bölümü; Mekâyîs q-w-m, gh-d-b tam maddeler.',attestation='building_blocks_only',scope='Paragraf 191; düşüş ve doğrulma',connection='resonant')
N(193,'1:4-7','2:282’de borç–unutma–daha sağlam tanıklık, 83:3–6’da ölçü–Rabb önünde kalkış aynı pasajlarda açıkça vardır. Bunların öğle terazisi ve yazının insanı dik tutmasıyla birleşmesi burada ayrı resimlerin terkibidir. Özellikle öğle sözlüğü ve sıfır gölge için bağımsız tam kaynak denetimi yoktur; bu birleşimin yeniliği hakkında genel bir yokluk hükmü verilmez.','QUR|M_DYN|M_DLL|M_QWM|PKT',checked='2:282 ve 83:3–6 tam ayetler; Mekâyîs d-y-n, d-l-l, q-w-m tam maddeler; proje q-w-m B017. Asıl öğle maddesi ve bütün klasiklerde yazı/diklik terkibi denetlenmedi.',attestation='building_blocks_only',scope='Paragraf 193; borç, kayıt, öğle ve terazi')
N(195,'1:2-6','Medyen kıssasında yol duası, su ve gölge; İbrahim’in 26:78–82 sözlerinde yaratma, hidayet, besleme ve hesap birlikte bulunur. Kuyu kiriş/makara gerçek sözlük terimleridir. Bunların Musa’nın kullandığı donanıma veya Fatiha’nın gizli sahnesine dönüşmesi metinde açık değildir; bu birleşim malzemelerin proje terkibi olarak kalır.','QUR|THD3_10|M_NAAM|M_MLK',checked='28:22–24 ve 26:78–82 tam ayetler; Tehzîb III:10 tam sunulan pasaj; Mekâyîs n-ʿ-m, m-l-k tam maddeler. Musa için aygıt kullanımını belgeleyen bağımsız tarihsel metin denetlenmedi.',attestation='building_blocks_only',scope='Paragraf 195; Musa, kuyu donanımı ve rızık')
N(197,'1:1-2','Gök işaretiyle sürekli yaratıcının ayrılması İbrahim pasajında ve incelenen klasik yorumda öncüllüdür. Ancak İbrahim’in araştırması mı münazarası mı olduğu ihtilafı korunur; s-m-w, âlem ve Rabb dallarının hepsini bu kıssada aynı anda çalıştırmak kısmi proje terkibidir. İhtilafın bir tarafı kesin kişisel inanç tarihi olarak verilmez.','QUR|IK676|IK679|M_SMW|M_ALM|M_RBB',checked='6:76–79 tam ayetler; İbn Kesîr 6:76 son açıklama ve 6:79 web satır 19–28; Mekâyîs s-m-w, ʿ-l-m, r-b-b tam maddeler. İbrahim kıssasının bütün klasik rivayetleri denetlenmedi.',attestation='partial',scope='Paragraf 197; gök, işaret ve Rabb')
A(199,'nazm','1:1-7','Bikâî, Fatiha sonunda yolculuğu farklı geçitler, vadiler ve denizlerle genişletir; iyi yol için iyi arkadaş ihtiyacını anar ve surenin adlarını/ana sıfatlarını dünya–ahiret bakımından birlikte okur. Taberî’nin övgüden ihtiyaç duasına geçişi ve Müslim 395’in konuşma düzeni de bütünü taşır. Bunlar ana metnin tek tek köklerden kurduğu zincire nazm bakımından gerçek öncüller sağlar; her sözlük dalını bağlamın eşit parçası yapmaz.','BIQ1|BIQ7|TAB7|H_M395',role='nazm',relation='structural',tradition='nazm',source_ref='Bikâî 1:1 maksat; 1:7 ana satırlar 6–8; Taberî 1:7 son sure açıklaması; Müslim 395a')
N(199,'1:1-7','Övgü→Rabb/rahmet/mülk→kulluk/yardım→yol/öncü düzeni ve geniş yolculuk/iyi refik resmi eski kaynaklarda kısmen açıktır. Ad, gök, yağmur, kuyu donanımı, sürü, rahim ve ev dallarının tamamını tek eşzamanlı anlatıda birleştirmek ise bu projeye ait terkiptir. Bu çalışmanın sınırlı pasaj karşılaştırması terkibin mutlak yeniliğini göstermez; özellikle Râzî’nin tam Fatiha metni ve başka eserlerin ilgili bütün bölümleri denetlenmiş değildir.','TAB5|TAB6|TAB7|BIQ1|BIQ7|H_M395|M_HDY|M_RBB|M_NAAM|RAZ_SCOPE',checked='Taberî 1:5 ana metin, 1:6 ana tefsir pasajı, 1:7 tam sunulan metin; Bikâî 1:1 ana 1–9, 1:7 ana 1–8; Müslim 395a tam matın; Mekâyîs h-d-y, r-b-b, n-ʿ-m tam maddeler. Râzî’de yalnız giriş/dil pasajları incelendi, tam Fatiha not_checked; tüm ağ bağlantıları için eksiksiz corpus taraması yok.',attestation='partial',scope='Paragraf 199 ve bütün sure; genel proje sentezi')

A(199,'reader_note','1:1-7','Bu ağın en güvenli okuma sırası cümleden başlar: övgü, ilahi sıfatlar, yalnız O’na kulluk ve yardım, doğru yola yöneliş, nimetlilerle beraber olma ve yanlış yönlerden kaçınma. Yol, sürü, rahim, su ve ev resimleri bu sırayı düşünmeye yardımcı olur. Bir resmi ikinci anlam diye okumak, bütün resimlerin her okuyuşta zorunlu veya aynı derecede kanıtlı olduğu demek değildir.','ENR|TAB6|TAB7|H_M395',role='reader_orientation',relation='methodological',tradition='none',connection='direct')
A(199,'source_note','1:1-7','Aynı haberin Taberî, İbn Kesîr ve Süyûtî’de bulunması üç bağımsız isnat tanığı sayılmadı. Adiyy’nin grup açıklaması, Nevvâs’ın yol temsili ve Vâhidî’deki Ebû Meysere anlatısı birer rivayet ailesi olarak işlendi; sonrakiler attested_in veya kaynak kaydıyla anıldı. Tefsir içindeki şiir, sahabî yorumu, müellif tercihi, hadis matnı ve modern sayfa derece alanı birbirinin yerine kullanılmadı.','TAB7|IK7|DUR7|TAB6|IK6|DUR6|W_ASB|DUR1|H_T2954|H_T2859',role='source_criticism',relation='methodological',tradition='none',priority='research',audience='research',source_ref='Adiyy / Nevvâs / Ebû Meysere rivayet aileleri')
A(199,'qiraat','1:7','İbn Kesîr ve Süyûtî’deki bazı sahabîlere nispet edilen farklı ghayr düzenleri ile Taberî’nin i‘rab ihtimalleri, kanonik on okuyuşun yerine geçirilmiyor. İbn Kesîr bazı biçimleri açıklayıcı okuyuş olarak niteler; yalnız kaynağın aktarması kanonik kabul değildir. Buna karşılık en-Neşr’de verilen mâlik/melik, sırât sesleri ve ilgili zamir rivayetleri okuyucu, râvi ve tarîkleriyle değerlendirilir.','IK7|DUR7|TAB7|NASHR',role='constraint',relation='grammatical',status='reported',tradition='rivayet',canonical=False,priority='research',audience='research',source_ref='İbn Kesîr 1:7 ilk bölüm; ed-Dürr 1:7 satır 1–15; Taberî 1:7 ghayr i‘rabı; en-Neşr I:271–272')
A(199,'source_note','1:1-7','Bu çıktı için yedi müfessirin 49 ayet sayfası getirildi; getirilmiş sayfa ile denetlenmiş pasaj aynı şey sayılmadı. Zemahşerî ve Beyzâvî’nin sunulan anlamlı Fatiha metinleri okundu. Taberî’de 1:1,2,4,5 belirtilen bölümler; 1:3 bütünü; 1:6 ana tefsir pasajı; 1:7 sunulan metnin bütünü incelendi. İbn Kesîr’de 1:1 giriş 1–22, 1:2,4,5,6 sunulan metinler, 1:7 1–21 incelendi. İlgili boş/sadece başlık sayfaları, eksiksiz ayrı ayet şerhi diye sayılmadı.','TAB1|TAB2|TAB3|TAB4|TAB5|TAB6|TAB7|IK1|IK2|IK4|IK5|IK6|IK7|ZAM1|ZAM2|ZAM4|ZAM5|ZAM6|ZAM7|BAY1|BAY2|BAY4|BAY5|BAY6|BAY7',role='source_criticism',relation='methodological',tradition='none',priority='research',audience='research',scope='Gerçekte denetlenen çekirdek corpus; ayrıntılı yerel satırlar kaynak kayıtlarında')
A(199,'source_note','1:1-7','Süyûtî’de 1:1 satır 1–17; 1:2 1–18 ve 36–44; 1:3,4,5,6 sunulan metinlerin bütünü; 1:7 1–15 incelendi. Bikâî’de 1:1 ana 1–9; 1:2,3,4,6 sunulan metinler; 1:5 ana 1–3; 1:7 ana 1–8 incelendi. Râzî’nin getirilen 1:1–6 sayfaları giriş, 1:7 sayfası da geniş giriş/dil tartışması sundu; bunlar tam Fatiha şerhi diye kabul edilmedi. Sayfanın kopyalama yardımcısı bir eksik metin/pagination kanıtı değildir; sınır, gerçekten görülen içerik ve ayet etiketinin uyuşmamasıdır.','DUR1|DUR2|DUR3|DUR4|DUR5|DUR6|DUR7|BIQ1|BIQ2|BIQ3|BIQ4|BIQ5|BIQ6|BIQ7|RAZ_SCOPE',role='source_criticism',relation='methodological',tradition='none',priority='research',audience='research',scope='Seçilmiş aktarım/nazm metinleri; Râzî tam Fatiha not_checked')
A(199,'source_note','1:1-7','Sözlük denetiminde Mekâyîs öncelendi: burada kayıtlı 18 kökün Hawramani’deki asıl Arapça maddeleri bütünüyle okundu. Tehzîb III:10 kuyu terimleri için ayrıca görüldü; projenin q-w-m paketi ise nadir öğle, sikke, duran binek gibi dalların aktarımını göstermek için kullanıldı. Dijital metinler matbu sayfa görüntüleriyle kollasyon edilmedi. Bağımsız görülmeyen nadir dallar doğrulanmış birincil metin veya bütün corpusun yokluk kanıtı sayılmadı.','M_ABD|M_ALH|M_ALM|M_DLL|M_DYN|M_GHDB|M_GHYR|M_HDY|M_HMD|M_MLK|M_NAAM|M_QWM|M_RBB|M_RHM|M_SMW|M_SRT|M_WSM|M_YWM|THD3_10|PKT',role='source_criticism',relation='methodological',tradition='none',priority='research',audience='research',scope='Dijital birincil sözlük maddeleri ve açıkça ayrılmış proje aktarımı')
A(199,'source_note','1:1-7','Özgün metindeki 169 farklı Kur’an atfının tam ayetleri Tanzil’in resmî Uthmani 1.1 metninden okundu; 205 Arapça Kur’an etiketinin lafız eşleştirmesinde 203 doğrudan normalleştirilmiş eşleşme, iki yalnız yazım farkı görüldü. 15:75 ve 6:76’daki bu iki fark hamza/tatvil gösterimine aittir; kelime veya atıf uyuşmazlığı saptanmadı. Türkçe glosslar açıklayıcı karşılıklardır; bu kontrol bütün alternatif tefsir anlamlarını veya 169 pasajın bütün klasik yorumlarını denetlediğimiz anlamına gelmez.','QUR',role='source_criticism',relation='methodological',tradition='none',priority='research',audience='research',scope='Tam ayet ve Arapça etiket denetimi; bağlam karşılaştırmaları')
A(199,'source_note','1:1-7','Yenilik notlarındaki checked_sources alanı, her özel bağlantı için gerçekten görülen pasajları belirtir. Bir müellifin bütün sure adını listede taşımak, kuyu, gök, sürü veya ev bağının her yerde eksiksiz arandığı anlamına gelmez. Sınıflar olumlu klasik öncül, ayrı malzeme ve denetlenmemiş alanı ayırır; bu çalışmada hiçbir ağ için klasik geleneğin tamamında bulunmaz hükmü verilmez. Hadis dereceleri asıl sayfalardaki yetkili değerlendirmeden veya Sahîhayn koleksiyonundan alınır; ayrıca derecelendirilmeyen anlatılar not_assessed kalır.','ENR|RAZ_SCOPE|W_ASB|H_T2954|H_T2859|H_AD1173',role='source_criticism',relation='methodological',tradition='none',priority='research',audience='research',scope='Araştırmanın sınırı, hadis derece yetkisi ve yenilik karşılaştırması')

def serialize(d):
 pieces=[]
 enums={'type','tradition','role','relation','status','priority','audience','confidence','historicity','hadith_grade','connection','classical_attestation'}
 for key,value in d.items():
  if key=='canonical': v='true' if value else 'false'
  elif key in enums: v=value
  else: v=json.dumps(value,ensure_ascii=False)
  pieces.append(f'{key}:{v}')
 return '{'+', '.join(pieces)+'}'

# Define every cited source once, with the observed edition/range rather than an
# inflated whole-author corpus claim.
registry={
 'ENR':'Tafsir Comprehensive Annotation Instructions, enrichment/v1, kanonik yöntem ve enumlar. [Yerel talimat](/Volumes/aro/projects/prose_generation/enrichment/v1/Tafsir_Comprehensive_Annotation_Instructions.md). Bu bir birincil tefsir kaynağı değildir.',
 'PKT':'Projenin özgün sözlük aktarımı, _commentary/v16/work/s001/surah.r2/dictionary.md, q-w-m satır 341–394; özgün base etiketleri ve aynı çıktıdaki ledger.md. [Sözlük paketi](/Volumes/aro/projects/prose_generation/_commentary/v16/work/s001/surah.r2/dictionary.md:341). Aktarılan nadir dalların her birinin tam asıl kitabı bağımsız görülmedi; proje kaydı birincil sözlük kontrolüyle aynı sayılmaz.',
 'QUR':'Kur’an, Tanzil Uthmani 1.1, resmî indirme metni; özgün r13 içindeki 169 farklı atfın tam ayetleri. [Tanzil metin ve kullanım kaydı](https://tanzil.net/download/). Kaynak Arapça metin değiştirilmeden kontrol edildi; © 2007–2026 Tanzil Project, CC BY 3.0. Yerel ana dosya SHA256 6933e133dd56db778c801bf738848454e43648105a151e8d84d86a7cae39ec5f.',
 'RAZ_SCOPE':'Fahreddin er-Râzî, Mefâtîhu’l-gayb, quran-tafsir.net’te Fatiha diye etiketli 1:1–6 giriş pasajları ve 1:7’de 37.475 karakterlik giriş/dil tartışması. [1:1](https://quran-tafsir.net/alrazy/sura1-aya1.html), [1:7](https://quran-tafsir.net/alrazy/sura1-aya7.html). Sunulan metin okundu; ayet etiketlerinden tam ayet şerhi sonucu çıkarılmadı. Basılı tam Fatiha cildi ve özel ağların o ciltte tam taraması not_checked.',
 'W_ASB':'Vâhidî, Esbâbü’n-nüzûl, Fatiha bölümü; İslamweb ana metin 575–582, rapor 19–22. [Asıl bölüm](https://islamweb.net/ar/library/content/63/5/القول-في-سورة-الفاتحة). Nüzul görüşleri ve Ebû Meysere zinciri görüldü; anlatıların bağımsız hadis derecesi araştırılmadı.',
 'NASHR':'İbnü’l-Cezerî, en-Neşr fi’l-kırââti’l-aşr, I, s.271–272, Dârü’l-kütübi’l-ilmiyye, Beyrut olarak tanıtılan dijital edisyon; ABL sayfa 279–280. [s.271](https://ablibrary.net/book_content/b/8339/279), [s.272](https://ablibrary.net/book_content/b/8339/280). Okuyucu/râvi/tarîk listeleri doğrudan görüldü; görüntü kolasyonu yapılmadı.',
 'THD3_10':'Ezherî, Tehzîbü’l-luga, III, s.10; Dâr ihyâi’t-türâsi’l-Arabî, Beyrut olarak tanıtılan dijital metin. [Asıl sayfa](https://ablibrary.net/book_content/b/14638/10). Sunulan tam pasaj, n-ʿ-m ve naʿâma/qâma kuyu terimleri için okundu; matbu görüntüyle kollasyon yapılmadı.',
 'TAB1223':'Taberî, Câmiʿu’l-beyân, 12:23; rabbî yorumunda özellikle web satır 88–105. [Asıl pasaj](https://quran.ksu.edu.sa/tafseer/tabary/sura12-aya23.html).',
 'IK676':'İbn Kesîr, Tefsîrü’l-Kur’âni’l-azîm, 6:76 sunulan ana metin. [Asıl pasaj](https://quran.ksu.edu.sa/tafseer/katheer/sura6-aya76.html).',
 'IK679':'İbn Kesîr, Tefsîrü’l-Kur’âni’l-azîm, 6:79, web satır 19–28 nazar/münazara tartışması. [Asıl pasaj](https://quran.ksu.edu.sa/tafseer/katheer/sura6-aya79.html).',
}
authors={'TAB':('Taberî','Câmiʿu’l-beyân','tabary'),'IK':('İbn Kesîr','Tefsîrü’l-Kur’âni’l-azîm','katheer'),'ZAM':('Zemahşerî','el-Keşşâf','zamakhshary'),'BAY':('Beyzâvî','Envârü’t-tenzîl','baidawy'),'DUR':('Süyûtî','ed-Dürrü’l-mensûr','seoty'),'BIQ':('Bikâî','Nazmü’d-dürer','beqaay')}
for prefix,(author,title,code) in authors.items():
 for a in range(1,8):
  sid=prefix+str(a)
  if sid not in scopes: continue
  site='https://quran.ksu.edu.sa/tafseer' if prefix in ['TAB','IK'] else 'https://quran-tafsir.net'
  url=f'{site}/{code}/sura1-aya{a}.html'
  registry[sid]=f'{author}, {title}, 1:{a}. [Sunulan asıl metin]({url}). {scopes[sid]} Dijital aktarım; matbu edisyon görüntüsüyle kollasyon yapılmadı.'
lex_files={'ABD':'abd_v','ALH':'alh','ALM':'alm_v','DLL':'dll_v','DYN':'dyn','GHDB':'ghdb_v','GHYR':'ghyr_v','HDY':'hdy','HMD':'hmd','MLK':'mlk_v','NAAM':'naam_v','QWM':'qwm','RBB':'rbb_v','RHM':'rhm','SMW':'smw','SRT':'srṭ','WSM':'wsm','YWM':'ywm_v'}
for name,f in lex_files.items():
 text=(W/'sources'/f'lex_{f}_maqayis.txt').read_text()
 url=re.search(r'https://arabiclexicon\.hawramani\.com/\?p=\d+#[a-z0-9]+',text).group()
 registry['M_'+name]=f'İbn Fâris, Mekâyîsü’l-luga, {name} kökü; Hawramani dictionary_7 birincil Arapça madde aktarımı. [Tam madde]({url}). Sunulan madde bütünü okundu; matbu edisyonla kollasyon yapılmadı. Köken açıklamaları müellifin kıyas/etimoloji görüşü olarak, modern tarihsel etimolojiden ayrılarak kullanıldı.'
names={'H_M395':'Müslim 395a','H_B4474':'Buhârî 4474','H_T2954':'Tirmizî 2954','H_B5999':'Buhârî 5999','H_B5988':'Buhârî 5988','H_M2747':'Müslim 2747a','H_T2859':'Tirmizî 2859','H_M223':'Müslim 223','H_AD1173':'Ebû Dâvûd 1173','H_B3':'Buhârî 3'}
for sid,h in matrix['hadith_checked'].items():
 registry[sid]=f'{names[sid]}, asıl Arapça matın/isnat ve numara, Sunnah.com koleksiyon aktarımı. [Asıl rivayet]({h["url"]}). Derece: {h["grade"]}; yetki: {h["grade_authority"]}. Denetlenen web satırları {h["web_lines"]}; ilişki sınıfı {h["relation"]}. Modern tercüme yerine Arapça matın esas alındı.'

used={s for d in annotations for s in d['source'].split('|')}
assert used<=registry.keys(),used-registry.keys()
prefix='<!-- enrichment/v1; TARGET 1; comprehensive; özgün r13; besmele 1:1; ek bloklar tek fiziksel satır -->\n\n'+'\n\n'.join(serialize(d) for d in at[0])+'\n\n'
pieces=[prefix]
for line_no,line in enumerate(BASE.read_text().splitlines(keepends=True),1):
 pieces.append(line)
 if line_no in at:
  pieces.append('\n'+'\n\n'.join(serialize(d) for d in at[line_no])+'\n')
pieces.append('\n## Kaynak kayıtları\n\n')
for sid in registry:
 if sid in used: pieces.append(f'- **{sid}** — {registry[sid]}\n\n')
OUT.write_text(''.join(pieces))
(W/'annotations.json').write_text(json.dumps(annotations,ensure_ascii=False,indent=2)+'\n')
(W/'novelty_coverage.json').write_text(json.dumps(dict(evidence_matrix_stage_before_composition=matrix['stage'],base_claim_paragraphs=73,novelty_blocks=[dict(id=a['id'],base_line=a['base_line'],scope=a.get('scope'),attestation=a['classical_attestation'],checked_sources=a['checked_sources']) for a in annotations if a['type']=='novelty'],no_universal_absence_claim=True,complete_classical_connection_audit=False,unresolved=matrix['corpus_limitations']),ensure_ascii=False,indent=2)+'\n')
print(json.dumps(dict(output=str(OUT),annotations=len(annotations),types=counts,sources=len(used),bytes=OUT.stat().st_size),ensure_ascii=False))
