from pathlib import Path
from collections import defaultdict,Counter
import json,hashlib
W=Path('enrichment/v1/work/107_astra_high');B=Path('_commentary/v16/out/s107/images.r13.map3.nohft.tool.tool/images.md');O=Path('enrichment/v1/out/107/107_enriched.astra-high.md')
assert (W/'evidence_matrix.json').exists()
A=defaultdict(list);counts=Counter();registry={}
def source(k,s):registry[k]=s
def add(p,t,a,prose,src,role='clarification',relation='direct_tafsir',tradition='dirayet',status='explicit',priority='extended',audience='general',**kw):
 codes={'tafsir':'TAF','reader_note':'READ','method_note':'MET','novelty':'NOV','revelation_history':'REV','asbab':'ASB','hadith':'HAD','source_note':'SRC','qiraat':'QIR','historical_context':'HIS','semantic_history':'SEM','nazm':'NAZ','cross_quran':'QUR','modern_scholarship':'MOD'}
 counts[t]+=1;d=dict(id=f'S107-{codes[t]}-{counts[t]:03}',type=t,tradition=tradition,ayah=a,role=role,relation=relation,status=status,priority=priority,audience=audience,prose=prose,source=src);d.update(kw);A[p].append(d)
def nov(p,a,prose,src,att,checked,**kw):
 add(p,'novelty',a,prose,src,role='novelty_assessment',relation='comparative',tradition='project',status='interpretive',priority='research',audience='research',classical_attestation=att,checked_sources=checked,confidence='medium',**kw)
C='Taberî Câmiu’l-beyân 107:1–7; İbn Kesîr Tefsîr 107:1–7; Süyûtî ed-Dürr 107:1–7; Zemahşerî el-Keşşâf 107:1–7; Râzî Mefâtîh 107:1 mesele 1–4, 107:2–3 açıklaması, 107:4–5 mesele 1–3, 107:6 ve 107:7 dört görüş/uyum/son dua; Beyzâvî Envâr 107:1–7; Bikāî Nazm 107:1–7 ve hatime'
add(-1,'reader_note','107:1-7','Bu metinde düz paragraflar asıl yorumu korur. Ek kayıtlar ayetin bağlam anlamını, aktarılan rivayeti, sözlük ailesini ve projenin kurduğu bağı ayrı gösterir. Bir benzetmenin sözlükte malzemesinin bulunması, ayetin o benzetmeyi söylediği anlamına gelmez. Yenilik kayıtları yalnız adları ve bölümleri belirtilen okunmuş kaynaklarla karşılaştırmadır.','BASE|PROTO',role='reader_orientation',relation='methodological',tradition='project',priority='core')
add(-1,'revelation_history','107:1-7','Surenin yeri üzerinde tek rivayet yoktur. İbn Kesîr başlıkta Mekkî der; Süyûtî, İbn Merdûye üzerinden İbn Abbas ve İbn Zübeyr’e Mekkî görüşünü nispet eder. Zemahşerî Mekkî görüşünün yanında Medenî görüşünü, Beyzâvî ihtilafı kaydeder. Kurtubî Atâ, Câbir ve İbn Abbas’ın bir görüşünü Mekkî; Katâde ve İbn Abbas’ın başka görüşünü Medenî olarak aktarır. Bu nispetler birbirini ortadan kaldırmaz.','IK-107|SUY-107|KASH-107|BAY-107|QURT-107',role='chronology',relation='historical',tradition='rivayet',status='disputed',historicity='contested',priority='core',source_ref='Sure girişleri; Süyûtî 107:1; Kurtubî 107:1')
add(-1,'modern_scholarship','107:1-7','İbn Âşûr, İtkān’dan ilk üç ayetin Mekke’de, kalanının Medine’de indiği görüşünü aktarır ve ikinci bölümün münafıklara yönelik okunmasını bunun gerekçesi sayar. Mekkî kabulüne bağlı on yedinci sıra bilgisini de verir. Burada doğrudan okunan kaynak İbn Âşûr’un sure girişidir; İtkān’ın ilgili bölümü ayrıca denetlenmedi. Edebî iki bölüm ile iki ayrı iniş tarihi aynı iddia değildir.','ASH-107',role='chronology',relation='historical',tradition='historical',status='reported',historicity='uncertain',audience='advanced',source_ref='107:1 sayfası, sure adları ve Mekkî/Medenî giriş paragrafları')
add(1,'tafsir','107:1','Râzî soruyu, hesabı yalanlayanın kim olduğunu tanımaya çağrı ve hayret uyandırma olarak okur; hitabın Peygamber’e veya her akıl sahibine yöneldiği görüşlerini ayırır. Beyzâvî de soru biçimindeki hayreti öne çıkarır. Dolayısıyla ana metindeki bakma emri ifadesi sözün işlevini anlatır; أَرَأَيْتَ dilbilgisel olarak emir değil, soru biçimidir.','RAZI-107|BAY-107',role='anchor',relation='grammatical',priority='core',source_ref='Râzî 107:1 mesele 2; Beyzâvî 107:1')
add(1,'qiraat','107:1','Ebû Şâme, Şâtıbiyye’nin 638. beytini açıklarken soru hemzesinden sonraki رأيت ailesinde Kisâî’nin kök hemzesini düşürdüğünü, Nâfi‘in onu kolaylaştırdığını ve Verş için elifle değiştirme yolunun aktarıldığını belirtir. Bunlar yedi kıraat geleneği içindeki seslendirme vecihleridir. Zemahşerî ve Râzî’nin hemze düşürmeyi dil tercihi bakımından eleştirmesi, Kisâî okuyuşunu kendiliğinden geçersiz veya şâz yapmaz.','SHAMA-638|KASH-107|RAZI-107',role='clarification',relation='grammatical',tradition='rivayet',priority='research',audience='advanced',canonical=True,source_ref='İbrâzü’l-meânî, 638. beyit şerhi; Keşşâf 107:1; Râzî 107:1 mesele 1')
add(1,'qiraat','107:1','İbn Mes‘ûd’a Zemahşerî ve Râzî’de أَرَأَيْتَكَ, Taberî’de بِالدِّينِ yerine الدِّينَ okuyuşu nispet edilir. İlki hitap kâfını ekler; ikincisini Taberî bâ harfinin bulunması ile bulunmaması arasında anlamı değiştirmeyen bir kullanım diye açıklar. Bu kayıtlar sahabeye nispet edilen okuyuş haberleridir; burada tam isnat ve kıraat yolu denetimi yapılmadığından kanonik sınıf veya sıhhat hükmü verilmedi.','TAB-107|KASH-107|RAZI-107',role='semantic_range',relation='grammatical',tradition='rivayet',status='reported',priority='research',audience='research',source_ref='Taberî 107:1 son paragraf; Keşşâf 107:1; Râzî 107:1 mesele 1')
add(2,'tafsir','107:6','İki taraflı gösterme açıklamasının açık klasik karşılığı vardır. Zemahşerî’ye göre kişi insanlara işini gösterir, onlar da ona övgülerini ve beğenilerini gösterir. Beyzâvî ve Râzî aynı açıklamayı taşır. Bu alışveriş yalnız iki gözün birbirine bakması değil, ibadetin karşılığını insanlardan beklemektir.','KASH-107|RAZI-107|BAY-107',role='corroboration',priority='core',source_ref='Her üç müfessirin 107:6 açıklaması')
add(2,'method_note','107:1|107:6-7','Ana metindeki sure aynı kökten bir kelimeyle kapanır sözü, görme ağının altıncı ayetteki dönüşünü anlatır. Surenin gerçek son kelimesi yedinci ayetteki mâûndur. Ayna ise ر أ ي ailesinde tanıklanmış bir nesnedir; burada ayetin adlandırdığı nesne veya tarihî sahne değildir. Aynanın derinliksizliği üzerine kurulan cümle de ahlaki bir benzetmedir.','QURAN|MQ-RAY|RAG-RAY',role='constraint',relation='lexical',tradition='project',status='interpretive',connection='resonant',priority='core')
add(3,'tafsir','107:6','Görünen her ibadet gösteriş sayılmaz. Zemahşerî, farzın açık yapılmasını dinin görünür işaretleriyle; nafilenin başkaları örnek alsın diye gösterilmesini de ayrı bir niyetle açıklar. Râzî ayrıca münafığın gizlide kılmaması ile riyakârın insanlar yanında daha güzel kılması arasında ayrım kurar. Ana metindeki göz çekilince namazın yok olması, rivayetlerdeki bir tipe uyar; riyanın bütün biçimlerini tüketmez.','KASH-107|RAZI-107',role='constraint',priority='core',source_ref='Keşşâf 107:6; Râzî 107:6 ilk iki paragraf')
add(3,'hadith','107:6','Ebû Zer rivayetinde iyilik yapan ve insanların övdüğü kişi sorulur; Peygamber bunu mümin için dünyada gelen müjde diye niteler. Bu, övgünün kendisiyle övgü için iş yapmanın ayrılmasına yardım eder. Hadis Mâûn’un doğrudan tefsiri değildir.','MUS-2642',role='constraint',relation='thematic',tradition='hadith',hadith_grade='sahih')
add(4,'hadith','107:6','Müslim’in Ebû Hüreyre’den aktardığı kudsî hadiste Allah, kendisine başkasının ortak edildiği ameli ve ortaklığı bırakacağını bildirir. Böylece gösterişte sorun, işin insanların önünde bulunmasından önce yöneldiği amaçtır. Bu hadis ayeti adlandırmaz; ihlâs temasını destekler.','MUS-2985',role='corroboration',relation='thematic',tradition='hadith',hadith_grade='sahih',connection='strong')
nov(4,'107:1|107:6','Gösteren kişi ile övgü veren seyirci arasındaki alışveriş Keşşâf, Râzî ve Beyzâvî’nin 107:6 açıklamalarında açıkça vardır. Maḳāyîs ve Müfredât’ın رأى maddelerinde görme, riya ve ayna aynı ailede yer alır. Fakat 107:1’deki çağrıyı 107:6’daki seyirci arayışıyla karşılaştırıp aynanın yüzeyine yerleştiren bütün çerçeve, aşağıdaki S107 pasajlarında bulunmadı. Klasik karşılıklı gösterme açıklaması korunmalı; aynalı düzenleme proje sentezi diye okunmalıdır.','KASH-107|RAZI-107|BAY-107|MQ-RAY|RAG-RAY','partial',C+'; Maḳāyîs رأى tam madde; Müfredât رأى ayna/riya paragrafları',connection='resonant')
add(5,'tafsir','107:1-3','İşaretin davranışı delile dönüştürmesi klasik tefsirde de vardır. Taberî yetimin hakkının itilmesini, ona zulmedilmesini ve doyurulmamasını ayrı rivayetlerle verir. Râzî 107:2–3’ü yapılan kötülük ile yapılmayan iyilik diye ayırır; Beyzâvî fâ ile hesabı yalanlama arasındaki nedenselliği açıklar. Buradaki el yalnız fiziksel şiddetin değil, hak mahrumiyetinin de elidir.','TAB-107|RAZI-107|BAY-107',role='anchor',priority='core',source_ref='Taberî 107:2–3; Râzî 107:2–3 giriş; Beyzâvî 107:3')
add(5,'asbab','107:1-2','Vâhidî, Mukātil ve Kelbî’den Âs b. Vâil’i; İbn Cüreyc’den, et isteyen yetime sopasıyla vuran Ebû Süfyân’ı aktarır. Râzî ayrıca Velîd b. Muğîre, Ebû Cehil ve adı verilmeyen cimri bir münafık görüşlerini sıralar; Kurtubî bunlara Amr b. Âiz nispetini de ekler. Bunlar aynı kişinin farklı adları değil, birbiriyle yarışan haberlerdir. Tekini surenin kesin biyografisi olarak seçmek için burada yeterli delil yoktur.','WAH-107|RAZI-107|QURT-107',role='asbab_context',relation='asbab',tradition='rivayet',status='reported',historicity='contested',priority='extended',source_ref='Vâhidî 871 ve 871 m; Râzî 107:1 mesele 3; Kurtubî 107:1')
add(5,'source_note','107:1-2','Vâhidî’de açılan kısa kayıtlar tam bir kesintisiz isnat sunmaz. Ebû Süfyân’ın haftalık kesimi Vâhidî ve Râzî’de iki deve, Kurtubî’de bir deve olarak anlatılır. Râzî’nin Ebû Cehil hikâyesindeki olağanüstü korunma ayrıntısı da ayrıca doğrulanmadı. Bu farklar, ana metindeki kapı ve el sahnesinin kesin nüzûl olayı diye okunmaması gerektiğini gösterir.','WAH-107|RAZI-107|QURT-107',role='source_criticism',relation='historical',tradition='historical',status='explicit',priority='research',audience='research')
add(5,'tafsir','107:5-7','Taberî’nin İbn Abbas’tan aktardığı açıklamada, insanların yanında namaz kılıp uzakta bırakmak ile ödünç eşyayı esirgemek birlikte bulunur. Süyûtî aynı rivayetin sonraki aktarım yerlerini sıralar. Bu, ana metindeki görünür ibadet/görünmez yardım ayrımının erken bir dayanağıdır; her tekrar bağımsız tanık sayılmadı.','TAB-107|SUY-107',role='early_attestation',tradition='rivayet',status='reported',source_ref='Taberî 107:5 ikinci görüş ve 107:6; Süyûtî 107:4–5',attested_in='İbn Kesîr 107:4 ve 107:7')
add(6,'cross_quran','107:1|107:6','Nisâ 4:142 hem namazı hem يُرَاؤُونَ fiilini birleştirdiği için doğrudan sözcük ve konu desteği sağlar; İbn Kesîr de bu ayeti burada kullanır. Alak 96:9–14’ün bakış, engellenen namaz ve Allah’ın görmesi; İnsan 76:8–9’un yiyecek ve karşılık beklememesi, ayrı sahneler arasında kurulan güçlü karşılaştırmalardır. Bunlar aynı tarihî olayın parçaları veya gizli bir alıntı olduğunun kanıtı değildir.','QURAN|IK-107',role='intertext',relation='thematic',tradition='project',status='interpretive',connection='strong',source_ref='İbn Kesîr 107:5 sonu; Kur’an 4:142, 96:9–14, 76:8–9')
nov(6,'107:1|107:6','İbn Kesîr’in 107:5’te 4:142’yi kullanması açık öncüldür. Açılışı Alak’taki üç soruya, ilahî görmeyi Şuarâ 26:218–219’a, karşılık beklemeyen yemeği İnsan 76:8–9 ve Leyl 92:19–20’ye bağlayan birleşik bakış dizisi taranan S107 pasajlarında bu bütünlükte bulunmadı. Ayrı ayetlerin açık anlamı ile onları bu sırada bir araya getirme işlemi ayrılmalıdır.','QURAN|IK-107','partial',C,connection='strong')
add(9,'semantic_history','107:1','Râgıb’ın كذب maddesi yalanın sözde ve fiilde kullanılabildiğini söyler; boyalı kumaşın hâliyle yalan söylemesini de gerçekten örnek verir. Böylece kumaş resmi sözlük bakımından dayanaklıdır. Fakat ayetin fiili, o kumaşı veya boya tekniğini adlandırmaz: bağlamdaki nesne dîndir, yani burada öncelikle hesap ve karşılıktır.','RAG-KDHB|TAB-107',role='semantic_range',relation='lexical',tradition='historical',source_ref='Müfredât كذب ilk ve son paragraflar; Taberî 107:1')
add(10,'source_note','107:1','Maḳāyîs, hücumda sadık kalmama örneğini verir; deve sütünün kesilmesi kullanımını ise aktardıktan sonra onda şüphe bulunduğunu, kıyasının uygun olduğunu söyler. Râgıb aynı süt örneğini beklenen süre kadar sürmemek diye açıklar. Dolayısıyla her sözlük kolu eşit kesinlikte değildir. Gebeliğin doğruluğunu gösteren deve de رأى maddesinin ayrı örneğidir; ayette iki devenin bulunduğu sonucu çıkmaz.','MQ-KDHB|RAG-KDHB|RAG-RAY',role='source_criticism',relation='lexical',tradition='historical',priority='research',audience='advanced')
nov(10,'107:1|107:5-6','Yarıda kesilen hücum, süt ve koşu ile görünen gebelik eski sözlük malzemesidir. Maḳāyîs كذب, Cemhere كذب ve Müfredât كذب/رأى maddelerinin incelenen parçaları bu ayrı örnekleri sağlar. Görülmeyince bırakılan namaz da Taberî 107:5–6’da vardır. Bunları bir başlayan ama devam etmeyen hayat çizgisine ve iki deve karşıtlığına dönüştüren bağlantı taranan S107 tefsirlerinde bulunmadı.','MQ-KDHB|RAG-KDHB|JAM-KDHB|RAG-RAY|TAB-107','building_blocks_only',C+'; Maḳāyîs كذب ilk madde; Cemhere كذب; Müfredât كذب son ve رأى gebelik paragrafları',connection='resonant')
add(11,'method_note','107:1|107:6','Kumaşın içi ile insanın niyeti arasındaki eşleştirme yorumdur. Tedyîn, bir yemin edeni niyetine bırakma veya dinine havale etme kullanımı taşır; buradan 107:1’deki dînin doğrudan boyanın altına bakan hüküm diye çevrilmesi çıkmaz. Râzî’nin riyakârı kalbindekinden fazlasını gösteren kişi olarak açıklaması, benzetmenin ahlaki merkezini ayrıca destekler.','SIH-DYN|TAH-DYN|RAZI-107',role='constraint',relation='lexical',tradition='project',status='interpretive',connection='resonant',source_ref='Ṣıḥâḥ دين; Tehẕîb دين; Râzî 107:6 ilk paragraf')
nov(11,'107:1|107:4-6','Râgıb’ın كذب maddesindeki yalancı kumaş ile Râzî 107:6’daki kalpte olmayan huşûu dışarıda gösterme açıklaması ayrı ayrı açıktır. Kumaşın yüzeyi, namazın dış hareketleri ve tedyînin niyet değerlendirmesini aynı resimde birleştiren tefsir taranan pasajlarda görülmedi. Bu nedenle kumaş ve iç-dış ahlakı eski, kurulan üçlü resim proje düzenlemesidir.','RAG-KDHB|RAZI-107|SIH-DYN|TAH-DYN','building_blocks_only',C+'; Müfredât كذب son paragraf; Ṣıḥâḥ ve Tehẕîb دين tedyîn kullanımları',connection='resonant')
add(12,'semantic_history','107:5','Taberî üç açıklama kümesini ayırır: namazı vaktinden sonraya bırakmak, gizlide tümüyle terk etmek ve ona aldırmayıp başka işlerle oyalanmak. Sonuncuyu kapsayıcı görerek ilk ikisini içine alır. İbn Kesîr buna rükün ve şartları gözetmemeyi, huşû ve anlam üzerinde durmamayı da katar. Ayeti yalnız namazın dış görünüşü sürerken kalbin gitmesiyle sınırlamak, bu çoğul tefsir alanını daraltır.','TAB-107|IK-107',role='semantic_range',tradition='rivayet',priority='core',source_ref='Taberî 107:4–5 görüş kümeleri ve tercih; İbn Kesîr 107:4–5')
add(12,'tafsir','107:5','عن ile في ayrımı Zemahşerî’de açıkça yapılır: namazdan uzak durmak veya aldırmamak ile namaz içinde insana gelebilen dalgınlık aynı değildir. Bununla birlikte Râzî, namazı büsbütün terk anlamına getirmenin onlara namaz kılanlar denmesiyle gerilimini tartışır; görünüşçe kılma, anlamca terk etme cevabını da verir. Edat ayrımı değerli bir sınırdır; ayetin bütün yorumlarını çözen mekanik bir kural değildir.','KASH-107|RAZI-107',role='disagreement',relation='grammatical',priority='core',audience='advanced',source_ref='Keşşâf 107:5 son soru-cevap; Râzî 107:4–5 mesele 2')
add(12,'hadith','107:5','Buhârî’de İbn Mes‘ûd’un rivayeti, Peygamber’in öğle namazını beş rekât kıldığının bildirilmesi üzerine iki sehiv secdesi yaptığını anlatır. Bu sahih haber, bir rekât yanılmasını ayetteki umursamazlıkla özdeşleştirmeyi engeller; Mâûn hakkında doğrudan bir tefsir sözü değildir.','BUKH-1226',role='constraint',relation='thematic',tradition='hadith',hadith_grade='sahih',priority='core')
add(12,'hadith','107:5-6','Müslim’in Enes rivayetinde, ikindiyi güneşin batışına kadar bekletip ardından dört rekâtı aceleyle kılan ve Allah’ı az anan kişinin namazı münafığın namazı diye nitelenir. Bu, geciktirme ile iç boşluğunu birlikte gösterir. İbn Kesîr haberi ayetin yanında kullanır; hadisin kendi metni ayeti açıklayan bir soru-cevap değildir.','MUS-622|IK-107',role='corroboration',relation='thematic',tradition='hadith',hadith_grade='sahih',connection='strong')
add(12,'source_note','107:5','Sa‘d b. Ebî Vakkās’ın vakti geçirme açıklaması hem kendi sözü olarak hem Peygamber’e çıkarılarak aktarılmıştır. Süyûtî, Hâkim ve Beyhakī’nin mevkuf biçimi daha doğru bulduğunu kaydeder; İbn Kesîr de aynı tercihi verir. Ebû Berze’ye bağlanan doğrudan açıklama için İbn Kesîr zayıf Câbir el-Cu‘fî ile adı bilinmeyen raviyi gösterir. Bu iki merfû haber burada sağlam bir peygamber tefsiri diye kullanılmadı.','TAB-107|SUY-107|IK-107',role='source_criticism',relation='direct_hadith_tafsir',tradition='hadith',status='disputed',priority='research',audience='research',source_ref='Taberî 107:5 son iki haber; Süyûtî 107:5; İbn Kesîr 107:6 son paragraflar')
add(12,'qiraat','107:5','Süyûtî İbn Mes‘ûd’a ساهون yerine لاهون, yani oyalananlar okuyuşunu nispet eder; Zemahşerî ve Bikāî de bunu anar. Bu haber, anlamın umursamama yönünü aydınlatan sahabe okuyuşu kaydı olarak tutuldu. Tam kıraat yolu ve kabul derecesi incelenmediği için on kıraatten biri gibi sunulmadı.','SUY-107|KASH-107|BIQ-107',role='clarification',relation='grammatical',tradition='rivayet',status='reported',priority='research',audience='advanced',source_ref='Her üç kaynakta 107:5')
nov(12,'107:5','Namazdan gaflet ile namaz içinde yanılma ayrımı yeni değildir: Keşşâf 107:5 bunu soru-cevapla açıkça kurar; Taberî 107:5 ve İbn Kesîr 107:5 farklı lafızlarla taşır. Râzî’nin 107:4–5 mesele 2’deki itiraz ve cevabı da gelenek içinde ayrımın tartışıldığını gösterir. Projenin bu ayrımı kumaş ve yarım koşu görüntüleriyle anlatması, ayrımın keşfi sayılmamalıdır.','KASH-107|TAB-107|IK-107|RAZI-107','explicit',C,connection='direct')
add(13,'method_note','107:1|107:4-6','Bakara iyiliği görünen bir duruştan ayırarak başlar cümlesinde başlangıç, surenin ilk ayeti değildir; kastedilen 2:177’deki cümlenin kuruluşudur. 2:264’te gösteriş, iman ve yüzeyi yıkan yağmur doğrudan birleşir. 63:4’ün dayalı kütükleri ile kumaş benzetmesinin bağlantısı ise iki ayrı temsilin proje tarafından yan yana okunmasıdır.','QURAN',role='constraint',relation='thematic',tradition='project',status='interpretive',connection='strong')
add(16,'semantic_history','107:2','Yetimin temel insanî tanımı, ergenlikten önce babasını yitirmiş çocuktur. Gaflet açıklamasını Tehẕîb el-Mufaddal’a, iyiliğin gecikmesi açıklamasını Ebû Amr’a nispet eder. Maḳāyîs يتم maddesi babasızlık ve tek kalmayı kaydeder; adı mutlaka başkalarının gafletinden türetmez. Ana metindeki adının gafleti taşıması, nakledilen etimolojik açıklamalardan birinin genişletilmesidir.','MQ-YTM|TAH-YTM|RAG-YTM',role='semantic_range',relation='lexical',tradition='historical',priority='core')
add(17,'source_note','107:5','İbn Fâris, Suhâ’nın fark edilmesi güç olduğu için sehv ailesinden sayılmasını mümkün bulur; bunu kesin köken hükmü olarak vermez. Aynı maddede başkasının sürçmesini görmezden gelen iyi geçinmeyi açıklar. Yıldız ile iyi gözden kaçırma sözlükte tanıklıdır; bunların yetimle ve namazla oluşturduğu gökyüzü sahnesi ayetin doğrudan tefsiri değildir.','MQ-SHW',role='source_criticism',relation='lexical',tradition='historical',connection='resonant',source_ref='Maḳāyîs سهو, müsâhât ve Suhâ son cümlesi')
add(18,'hadith','107:2','Sehl’den gelen sahih rivayette Peygamber, yetime bakıp işini üstlenen kimseyle cennette yakınlığına işaret ve orta parmağını göstererek dikkat çeker. Bu, yetimi iten elin karşısına koruyup gözeten eli koyar. Hadis ayetin açıklaması olarak söylenmiş değildir; güçlü bir karşı sahnedir.','BUKH-5304',role='contrast',relation='thematic',tradition='hadith',hadith_grade='sahih',connection='strong')
add(18,'hadith','107:3','Buhârî’nin Ebû Hüreyre rivayetinde, kendisine yetecek imkân bulamayan, ihtiyacı fark edilmediğinden yardım edilmeyen ve insanlardan istemeyen yoksula dikkat çekilir. Gözden kaçan ihtiyaç yalnız projenin edebî imgesi değildir; hadis bunu açıkça konu eder. Suhâ yıldızıyla eşleştirme ise hadiste yoktur.','BUKH-1479',role='corroboration',relation='thematic',tradition='hadith',hadith_grade='sahih',connection='strong')
nov(18,'107:2-3|107:5-6','Yetim adı için gaflet/gecikme açıklamaları Tehẕîb يتم’de; Suhâ için ihtimalli görmeme açıklaması Maḳāyîs سهو’da mevcuttur. Buhârî 1479 görünmeyen ihtiyacı ayrıca açıklar. Yetim, tek inci, Suhâ, kalbi gitmiş namaz ve görünmek isteyen riyakârı aynı görme düzenine yerleştiren sentez taranan S107 pasajlarında bulunmadı. Bu birleşim sözlükteki ayrı tanıkların ötesine geçer.','TAH-YTM|MQ-YTM|MQ-SHW|BUKH-1479','building_blocks_only',C+'; Tehẕîb يتم Mufaddal/Ebû Amr nakilleri; Maḳāyîs يتم ve سهو tam maddeleri; Buhârî 1479',connection='resonant')
add(19,'method_note','107:2-3|107:5','Yoksulun görülmemesi ile 51:11’deki غمرة içinde kalmak arasında kurulan bağ benzetmedir. O ayette gerçek bir su seli anlatıldığı sonucu, yalnız kelimenin kaplama alanından çıkarılamaz. Aynı biçimde her yetimin hiçbir koruyucusu kalmadığı veya her yoksulun evsiz olduğu, Mâûn’un lafzında verilmez. Ana metnin bu sahneleri durumun ağırlığını görünür kılan örneklerdir.','QURAN|MQ-YTM|IK-107',role='constraint',relation='lexical',tradition='project',status='interpretive',connection='resonant')
add(22,'tafsir','107:2','Taberî’nin açıklamasında itmek, yetimi kendi hakkından uzaklaştırmak ve zulmetmektir; Mücâhid’den doyurmama, Katâde’den ezip haksızlık etme aktarılır. Zemahşerî kaba ve incitici itişi vurgular. Böylece fiziksel hareket yerindedir, fakat yorum yalnız çocuğun bedenini kapıdan dışarı sürme sahnesine indirgenmez.','TAB-107|KASH-107',role='anchor',tradition='rivayet',priority='core')
add(22,'qiraat','107:2','Zemahşerî ve Beyzâvî, şeddesiz يدع biçimini bırakmak diye aktarır. Râzî ayrıca يدعو اليتيم biçimini anıp gösteriş için çağırarak doyurmama veya hizmet ettirme yönünde açıklar. Bunlar ana okuyuşun yerine geçirilmedi; adı verilmeyen tefsir okuyuşları olarak kaydedildi. Burada kıraat isnatları ve kanonik sınıfları denetlenmedi.','KASH-107|BAY-107|RAZI-107',role='semantic_range',relation='grammatical',tradition='rivayet',status='reported',priority='research',audience='research',source_ref='Keşşâf ve Beyzâvî 107:2; Râzî 107:3 sayfasındaki يدع açıklaması')
add(22,'method_note','107:2','İbn Fâris, دع ailesinde itme ile ölçeği sarsmayı hareket ve itiş altında toplar. Fakat koyunu sürme ve düşene دع دع diye seslenmeyi, ses taklitlerinin düzenli kök kıyasına girmediğini söyleyerek ayırır. Dolayısıyla bir kökün düşüren ve kaldıran iki anlamı olduğu cümlesi, Maḳāyîs’in kendi yöntemi açısından koşulsuz değildir. Tehẕîb kaldırma çağrısını aktarır; bu, aynı kökten zorunlu anlamsal türeme demek değildir.','MQ-DAA|TAH-DAA',role='rejected_candidate',relation='lexical',tradition='project',status='interpretive',connection='rejected',reason='Maḳāyîs ilgili seslenişleri düzenli kök kıyasından açıkça ayırır.',priority='core',audience='advanced')
add(23,'tafsir','107:3','Taberî teşviki başka birini doyurmaya yöneltmek diye açıklar. Râzî, insanın kendisini yahut başkasını teşvik etmesi ihtimallerini ayırır; طعام المسكين tamlamasını yoksulun hakkını bildiren bir ifade sayar. Bikāî de yemeğin yoksula eklenmesini, malda ona ayrılmış payın işareti olarak okur. Teşvik etmemenin ağırlığı yalnız yemek vermemekte değil, iyiliğe yönelten sözü bile esirgemektedir.','TAB-107|RAZI-107|BIQ-107',role='anchor',priority='core',source_ref='Taberî 107:3; Râzî 107:3 son iki soru öncesi; Bikāî 107:3')
add(23,'method_note','107:3','Maḳāyîs حض maddesi teşvik ile aşağıdaki zemin anlamını iki ayrı asıl diye düzenler; aktardığı Halîl açıklaması da teşviki fiziksel yürütme ve hayvan sürmeden ayırır. Ana metindeki dipte yatana doğru itiş resmi bu nedenle kelimenin doğrudan açılımı değildir. Alçak zemin ve teşvik, ses ailesinden kurulmuş ikincil bir çağrışım olarak kalır.','MQ-HDD',role='constraint',relation='lexical',tradition='project',status='interpretive',connection='speculative',priority='core')
add(24,'method_note','107:2-3|107:7','Miskîn burada ihtiyacını karşılayacak imkânı olmayan kişidir; bedenen kıpırdayamaması şart değildir. Men‘ kökünün koruma alanı bulunması da babasız her çocuğun soy çevresinden tümüyle kopmuş olduğunu göstermez. Koruyucu halka ile engelleyici el karşıtlığı, mevcut sözlük alanlarını seçerek kurulan ahlaki bir resimdir.','IK-107|MQ-SKN|TAH-MNA',role='constraint',relation='lexical',tradition='project',status='interpretive',connection='resonant',source_ref='İbn Kesîr 107:3; Maḳāyîs سكن; Tehẕîb منع men‘a açıklaması')
add(25,'tafsir','107:2-3','Râzî, yetimi itmede alışkanlık ve ısrarı vurgular; bir kötülükten sonra pişman olanla ısrar edeni ayırır. Ayrıca her teşvik etmeyişin günah olmadığını sorup, başkasının işi üstlenmesi, sözün kabul edilmemesi veya beklenen zarar gibi durumları sayar. Burada eleştirilen ihmalin hesabı yalanlama ile bağlantısını korur. Bu sınırlamalar, ana metindeki tek söz bile söylememe vurgusunu bağlamına oturtur.','RAZI-107',role='constraint',priority='extended',audience='advanced',source_ref='107:3 sayfası, يدع açıklaması ve السؤال الأول')
add(25,'hadith','107:3-5','Buhârî 6007, dul ve yoksul için çaba göstereni Allah yolunda mücadele eden kişiye benzetir. Rivayetin gece ibadeti ve kesintisiz oruçla ilgili devamında ravinin tereddüdü de metinde korunur. Bu karşı sahne, insan ihtiyacını gidermeyi ibadetin yanına yerleştirir; ayetin doğrudan tefsiri olarak sunulmaz.','BUKH-6007',role='contrast',relation='thematic',tradition='hadith',hadith_grade='sahih',connection='strong')
nov(25,'107:2-3|107:5|107:7','İtiş, yemek teşviki ve hak engelleme ayet tefsirlerinde açıkça vardır; Tehẕîb دع kaldıran çağrıyı ve Maḳāyîs سكن durulmayı ayrıca kaydeder. Fakat bunları dipteki hareketsiz beden, içeride durmuş kalp ve koruma/engelleme halkası biçiminde birleştiren şema taranan S107 pasajlarında bulunmadı. Üstelik Maḳāyîs’in دع seslenişini kıyastan ayırması ve حض için iki asıl vermesi, bu ağın bazı köprülerini zayıflatır.','TAB-107|RAZI-107|MQ-DAA|TAH-DAA|MQ-HDD|MQ-SKN|TAH-MNA','building_blocks_only',C+'; Maḳāyîs دع, حض, سكن; Tehẕîb دع ve منع ilgili sesleniş/koruma kısımları',connection='resonant')
add(26,'cross_quran','107:2-3','Tûr 52:13’teki itiliş ile Mâûn 107:2’nin itişini hem Tehẕîb دع maddesi hem Râzî aynı fiilin açıklamasında yan yana getirir. Fecr 89:17–18’de yetim ve yemeğe teşvik etmeme birlikte tekrar eder. Bunlar salt kök benzerliğinden daha güçlü bağlardır. İtenin bizzat aynı kişi olarak ateşe itildiği eşleştirme ise farklı sahnelerin ahlaki karşılıklılık içinde okunmasıdır.','QURAN|TAH-DAA|RAZI-107',role='intertext',relation='lexical',tradition='project',status='interpretive',connection='strong',source_ref='Râzî 107:3 sayfası يدع açıklaması; Tehẕîb دع ilk paragraf')
add(29,'source_note','107:2-3|107:5','Küçük çocuklar ile dolu çanak Tehẕîb دع maddesinde; ev halkı, durulma ve barınılan ateş Maḳāyîs سكن maddesinde tanıklıdır. Fakat İbn Fâris سهو maddesinde ev önündeki sehveyi ana kök anlamından sapan örnek diye işaretler. Bir sözlük başlığı altında bulunmak, rafın gafletin içinden türediğini kanıtlamaz.','TAH-DAA|MQ-SKN|MQ-SHW',role='source_criticism',relation='lexical',tradition='historical',priority='core',audience='advanced')
add(30,'tafsir','107:7','Mâûnun gündelik ödünç eşya oluşu güçlü bir erken açıklamadır; fakat tek açıklama değildir. Taberî Ali’ye zekât, İbn Mes‘ûd’a balta-kova-tencere, İbn Ömer’e malın hakkı, Muhammed b. Kâ‘b’a iyilik, Saîd b. Müseyyeb’e Kureyş dilinde mal açıklamalarını nispet eder. Son tercihinde hem yardımlaşılan eşyayı hem yoksulun maldaki hakkını kapsar.','TAB-107',role='semantic_range',tradition='rivayet',priority='core',source_ref='107:7 görüş kümeleri ve وأولى الأقوال ile başlayan tercih')
add(30,'hadith','107:7','Ebû Dâvûd 1657’de İbn Mes‘ûd, Peygamber zamanında mâûnu kova ve tencere ödüncü saydıklarını anlatır. Açılan kayıtta Elbânî’nin hasen değerlendirmesi vardır. Bu doğrudan erken anlam tanığıdır; cümlenin söyleyeni İbn Mes‘ûd’dur, Peygamber’in ağzından yapılmış bir ayet açıklaması gibi tırnaklanmamalıdır.','AD-1657',role='early_attestation',relation='direct_tafsir',tradition='hadith',status='reported',hadith_grade='hasan',priority='core',transmitter='Abdullah b. Mes‘ûd',source_ref='Sünen Ebî Dâvûd 1657; sitedeki derece: Elbânî')
add(30,'historical_context','107:7','İbn Kesîr, bu ödünçte eşyanın kendisinin kaldığını ve sahibine döndüğünü özellikle söyler. Râzî, hem yoksulun hem varlıklının isteyebildiği araçları; komşunun fırında ekmek pişirmesini ve eşyasını kısa süre bırakmasını örnekler. Bu pasajlar ev ve komşuluk sahnesinin gerçek kaynak dayanağıdır. Yine de her ödüncün masrafsız, risksiz veya her durumda zorunlu olduğu sonucu çıkmaz.','IK-107|RAZI-107',role='historical_context',relation='historical',tradition='historical',source_ref='İbn Kesîr 107:7 ilk paragraf; Râzî 107:7 ikinci görüş')
add(30,'asbab','107:7','Süyûtî, İbn Merdûye yoluyla İbn Mes‘ûd’a, Müslümanların münafıklardan araç istediği ve reddedildiği için ayetin indiği haberini nispet eder. Bu, kova-tencere anlam açıklamasından ayrı bir nüzûl iddiasıdır. Burada tam isnat ve bağımsız güvenilirlik incelemesi yapılmadığı için tarihî olay olarak kesinleştirilmedi.','SUY-107',role='asbab_context',relation='asbab',tradition='rivayet',status='reported',historicity='uncertain',priority='research',audience='research',source_ref='107:7, وأخرج ابن مردويه عن ابن مسعود paragrafı')
add(31,'semantic_history','107:7','Süyûtî ve İbn Kesîr, İkrime’den mâûnun başının zekât, en küçük örneklerinin elek, kova ve iğne olduğu açıklamasını aktarır. İbn Kesîr bunu görüşleri mal veya yararla yardımlaşma altında topladığı için beğenir. Bu sonraki birleştirme, İbn Mes‘ûd’un eşya açıklamasını silmez; zekâtla küçük yardımı tek bir yarar alanında tutar.','SUY-107|IK-107',role='historical_development',relation='comparative',tradition='historical',source_ref='Her iki kaynakta 107:7 İkrime kaydı ve İbn Kesîr’in hemen sonraki değerlendirmesi')
add(31,'tafsir','107:7','Zemahşerî, bu küçük nesneleri zorunlu ihtiyaç halinde esirgemenin yasak, öteki durumlarda ise mürüvvete aykırı olabileceğini ayırır. Süyûtî ve Kurtubî’de İkrime, her eşya vermeyenin tek başına veyl tehdidine girmediğini; namaz ihmali, riya ve esirgemenin birlikte tarif edildiğini söyler. Bikāî de tehdidi açıklarken verilmesi gereken hakları öne çıkarır.','KASH-107|SUY-107|QURT-107|BIQ-107',role='constraint',priority='core',audience='advanced',source_ref='107:7 açıklamaları; Kurtubî son iki paragraf')
nov(32,'107:2-3|107:5|107:7','Ev gereçleri ve komşu fırını Râzî 107:7 ikinci görüşte, geri dönen ödünç İbn Kesîr 107:7 girişte açıkça vardır. Bu yüzden ev ve paylaşım ilişkisi yeni sayılamaz. Küçük çocuklar, sarsılarak dolan kap, miskînin meskeni ve sehvenin rafını ayet sırasına yerleştiren bütün ev planı ise taranan pasajlarda bulunmadı. Raf kolunun Maḳāyîs’te kıyas dışı bırakılması bu planın etimolojik iddiasını sınırlar.','RAZI-107|IK-107|TAH-DAA|MQ-SKN|MQ-SHW','partial',C+'; Tehẕîb دع çocuklar/dolu çanak; Maḳāyîs سكن ve سهو',connection='resonant')
add(33,'cross_quran','107:2-3|107:7','İnsan 76:8 yetim ve yoksulu aynı yemek sahnesinde toplar. Kehf 18:77 ile 18:82’de yemek vermeyen yerleşim ve korunan yetim malı aynı anlatı içindedir. Bu güçlü karşı sahneler, Mâûn’daki kapların yahut evin aynı olayda bulunduğunu göstermez. Yûsuf 12:63’teki ölçünün engellenmesi de kardeşin getirilmesine bağlanan ayrı bir hikâyedir; oradaki her engelleme ahlaken Mâûn’daki esirgemeyle bir tutulamaz.','QURAN',role='constraint',relation='thematic',tradition='project',status='interpretive',connection='strong')
nov(33,'107:2-3|107:7','Kehf’in misafir ağırlamayan yerleşimi ile korunan yetim duvarını, İnsan’ın doyurma sahnesini, Yûsuf’un ölçüsünü ve Mutaffifîn’in eksik ölçüsünü ev ağına bağlayan dört yönlü düzenleme taranan S107 pasajlarında açıkça bulunmadı. Kur’an’daki ayrı sahneler korunarak kurulmuş bir karşılaştırmadır; klasik tefsirde aynı kompozisyonun yokluğuna dair hüküm yalnız aşağıdaki S107 bölümleriyle sınırlıdır.','QURAN|TAB-107|RAZI-107|BIQ-107','none_found_in_checked_sources',C,connection='resonant')
add(36,'tafsir','107:7','Mâûn ile su ilişkisi yalnız yeni bir kök çağrışımı değildir. Taberî sözcüğün yağmur suyuna da söylendiğini şiirle gösterir; Râzî üçüncü görüşte Ferrâ’nın su açıklamasını aktarır ve cehennem halkının su istemesine, cennette içirilen suya uzanır. Kurtubî de suyu ve su-otlak birlikteliğini ayrı görüşler olarak kaydeder.','TAB-107|RAZI-107|QURT-107',role='semantic_range',priority='core',source_ref='Taberî 107:7 giriş; Râzî 107:7 üçüncü görüş; Kurtubî 107:7 yedinci-sekizinci görüşler')
add(36,'hadith','107:3|107:7','İbn Mâce 2473’te su, otlak ve ateşin esirgenmemesi birlikte anılır; açılan hadisin derecesi Darussalam tarafından sahih olarak verilmiştir. Bu, ana metindeki su-otlak-ocak ağının paylaşma boyutuna güçlü bir tematik tanıktır. Mâûn ayetini adlandırmaz; her su kullanımı için bütün ayrıntıları belirleyen sınırsız bir hukuk hükmü olarak buradan genişletilmedi.','IM-2473',role='corroboration',relation='thematic',tradition='hadith',hadith_grade='sahih',connection='strong')
add(37,'method_note','107:3|107:7','Maḳāyîs معن maddesi kolay akışı, su yatağını, suya kanmış toprağı ve otluğu bir arada kaydeder. Bu sözlük alanı gerçek olmakla birlikte Mâûn suyun akışını tıkayan bir vadi sahnesi anlatmaz. Ayetteki esirgemenin akarsuya benzetilmesi, yararın başkasına ulaşmasını görünür kılan proje yorumudur.','MQ-MAN|QURAN',role='constraint',relation='lexical',tradition='project',status='interpretive',connection='resonant')
add(38,'method_note','107:1|107:7','67:30 ve 23:50’deki مَعِين için tek köken açıklaması yoktur. Maḳāyîs معن altında akışı verir; Râgıb عين maddesinde görünen veya kaynaktan çıkan su açıklamasını ve mîmin kök harfi olduğu alternatifini birlikte kaydeder. Kurtubî 67:30 da عين ile معن yollarını ayırır. Bu yüzden surenin son kelimesinin kökü 67:30’da kesinlikle aynıdır cümlesi, tartışmalı yollardan birine dayanır; kesin kök özdeşliği olarak okunmamalıdır.','MQ-MAN|RAG-AYN|QURT-6730',role='constraint',relation='lexical',tradition='project',status='disputed',connection='resonant',priority='core')
nov(38,'107:1|107:3|107:7','Su ve mâûn bağı Taberî 107:7 girişte ve Râzî 107:7 üçüncü görüşte açıktır; su-ateş paylaşımı da gelenekte vardır. 67:30’un bakış sorusunu, 23:50’nin barınağını, 93:6’nın yetime sığınağını, otluğu ve yemeği tek akış haritasında birleştirmek taranan S107 pasajlarında bulunmadı. Yeni görünen bu birleşimdir; mâûnun su anlamı değildir. Ma‘în kökeninin alternatifleri de bu karşılaştırmayı koşullu kılar.','TAB-107|RAZI-107|QURAN|MQ-MAN|RAG-AYN|QURT-6730','partial',C+'; Maḳāyîs معن tam madde; Müfredât عين ma‘în bölümü; Kurtubî 67:30 tam açıklama',connection='resonant')
add(12,'tafsir','107:5','Erken aktarımda bile ayrıntı tartışmalıdır. Süyûtî, Ebü’l-Âliye’nin kaç rekât kıldığını bilmemeyi söylediği, Hasan’ın ise onu durdurup vaktin geçirilmesini öne çıkardığı haberi verir. Bu karşılıklı itiraz, bütün ilk yorumcuların tek bir açıklamada birleştiği izlenimini önler. Rivayet burada aktarım olarak tutuldu; zincirine bağımsız sıhhat hükmü verilmedi.','SUY-107',role='disagreement',tradition='rivayet',status='reported',audience='advanced',source_ref='107:5, Abdürrezzâk ve İbnü’l-Münzir yoluyla Mâlik b. Dînâr kaydı')
add(38,'semantic_history','107:3|107:7','Ta‘âmın suya uzanması Maḳāyîs طعم maddesinde açıkça savunulur; İbn Fâris 2:249’daki sudan tatmayı delil getirir ve bana su yedir ifadesine yöneltilen dil eleştirisini kabul etmez. Böylece yemek-su köprüsü eski sözlük tanığı taşır. Bu tanık, 107:3’teki yemeği yalnız suya indirmez; beslenme ihtiyacının daha geniş alanını görünür kılar.','MQ-TAM|QURAN',role='early_attestation',relation='lexical',tradition='historical',source_ref='Maḳāyîs طعم, والإطعام يقع في كل ما يطعم ile başlayan bölüm')
add(41,'method_note','107:4-5','Maḳāyîs صلى maddesi ateş ve ibadeti iki ayrı asıl olarak düzenler. Bu nedenle aynı harflerin bulunması, namaz kelimesinin bağlamda ateş anlamını da zorunlu olarak taşıdığına delil değildir. Tehẕîb’in aktardığı Zeccâc bunları bağlı kalma üzerinden birleştirir; bu da tek ve tartışmasız köken demek değildir. Ana metindeki ateşi duymak, burada yankı-kök benzetmesi olarak tutulmalıdır.','MQ-SLW|TAH-SLW',role='constraint',relation='lexical',tradition='project',status='interpretive',connection='resonant',priority='core',source_ref='Maḳāyîs صلى iki asıl; Tehẕîb صلا Zeccâc açıklaması')
add(41,'semantic_history','107:4-5','Ateş ile namaz arasında eski bir yorum da vardır. Râgıb, adını vermediği bazı dilcilerin namazı ateşi kişinin üzerinden uzaklaştıran ibadet diye türettiğini aktarır. Bu görüş ateş kolunun ibadetin içinde sesini duyurma fikrine kısmi öncüldür; fakat aynı maddede genel dilci açıklaması dua olarak verilir. Rivayet edilmiş etimoloji ile yerleşik ayet anlamı ayrılmalıdır.','RAG-SLW',role='early_attestation',relation='lexical',tradition='historical',status='reported',priority='core',source_ref='Müfredât صلا, وقال بعضهم أصل الصلاة من الصلى paragrafı')
nov(42,'107:3-5|107:7','Namaz-ateş bağlantısı bütünüyle yeni değildir: Müfredât صلا maddesinde ateşten uzaklaştırma türetmesi, Râzî 107:7 ikinci görüşte komşunun fırınını kullanma ve ateş paylaşımı, Maḳāyîs سكن maddesinde barınılan ateş vardır. Bunları evin sıcaklığından paylaşılmayan ocağa ve ceza ateşine uzanan bir sahne olarak kurmak, taranan S107 pasajlarında bulunmadı. Maḳāyîs’in iki asıl ayrımı, bu sahneyi namaz kelimesinin zorunlu sözlük anlamı saymayı engeller.','RAG-SLW|MQ-SLW|MQ-SKN|RAZI-107','partial',C+'; Müfredât صلا ateşten uzaklaştırma paragrafı; Maḳāyîs صلى iki asıl ve سكن ateş cümlesi',connection='resonant')
add(42,'hadith','107:7','Âişe’ye nispet edilen su, tuz ve ateşle ilgili uzun rivayet, İbn Mâce 2474’te her birini verene büyük mükâfatlar sayar; açılan kaynak Darussalam derecesini zayıf olarak gösterir. Kurtubî de Mâûn açıklamasında bu haberin isnadını gevşek bulur. Bu metin, yukarıdaki sahih dereceli su-otlak-ateş rivayetiyle aynı haber değildir; uzun mükâfat ayrıntıları sağlam delil olarak kullanılmadı.','IM-2474|QURT-107',role='source_criticism',relation='thematic',tradition='hadith',status='weak',hadith_grade='daif',priority='research',audience='research',source_ref='İbn Mâce 2474; Kurtubî 107:7, Âişe rivayetinden sonraki وفي إسناده لين')
add(43,'cross_quran','107:1-4|107:7','Hâkka 69:34 ile Mâûn 107:3 arasında aynı cümlenin tekrarı güçlü bir metin bağıdır; 4:10 da yetim malı ile ateşi açıkça birleştirir. Bununla birlikte Mâûn 107:4’te ateş kelimesi geçmez. Başka ayetlerdeki ceza sahneleri, veyl tehdidini açıklayan karşı okumalar olabilir; onlar ayetin musallîn sözünü ateşe girenler diye çevirmeye izin vermez.','QURAN|MQ-SLW',role='constraint',relation='thematic',tradition='project',status='interpretive',connection='strong',priority='core')
nov(43,'107:1-4|107:7','Hâkka’nın yemek teşviki ve ateşini, Mutaffifîn’in veyl-hesap-yanma dizisini, Leyl’in cimrilik ve yalanlamasını, Nisâ’nın yetim malını ve Kâf’ın hayrı esirgeyenini tek ocak ağına yerleştiren tam düzenleme taranan S107 pasajlarında bulunmadı. Râgıb’ın صلا maddesi Leyl ve Nisâ’daki ateş örneklerini zaten yan yana kaydeder; bu ayrı sözlük öncülü korunmalıdır. Bağın gücü ayetlerdeki ortak kelime ve temalardadır, tek tarihî fail iddiasında değildir.','QURAN|RAG-SLW','building_blocks_only',C+'; Müfredât صلا ateş örnekleri açılış kısmı',connection='strong')
add(46,'semantic_history','107:1','İbn Fâris dîn, hüküm ve deyn ilişkisini boyun eğiş altında toplar; bu sözlük ailesi ana metnin hesap resmine dayanak verir. Ancak Taberî bu ayette dîni Allah’ın sevap ve cezası; Râzî ise İslâm veya hesap-ceza görüşleriyle açıklar ve hesap yorumunu tercih eder. Deyn, yani insanlar arası parasal borç, ayetin doğrudan nesnesi olarak bu pasajlarda seçilmez.','MQ-DYN|TAB-107|RAZI-107',role='semantic_range',relation='lexical',tradition='historical',priority='core',source_ref='Maḳāyîs دين; Taberî 107:1 giriş; Râzî 107:1 mesele 4')
add(46,'method_note','107:1','Kezebe aleyke deyimiyle yükümlülük veya teşvik anlatılması eski bir kullanımdır. Fakat Maḳāyîs bunu anlamı bugün kolay bilinmeyen eski bir ifade diye ayırır; Cemhere de kalıplaşmış teşvik sözü olarak kaydeder. 107:1’deki يُكَذِّبُ kalıbında, üzerinde borç vardır anlamı dilbilgisel olarak gizli değildir. Deyim ile ayet fiilini karşılaştırmak bir çağrışım kurar; ayet çevirisini değiştirmez.','MQ-KDHB|JAM-KDHB',role='constraint',relation='lexical',tradition='project',status='interpretive',connection='speculative',priority='core')
add(47,'semantic_history','107:7','Kurtubî mâûnun Câhiliye’de genel yarar ve bağış, İslâm’da itaat ve zekât diye anlatılan tarihî ayrımını aktarır; ayrıca onu معن yerine عون ile ilişkilendiren türetmeyi de kaydeder. Bunlar sözlük ve tefsir geleneğinin açıklamalarıdır. İslâm sonrasında günlük eşya anlamının ortadan kalktığı ileri sürülemez; aynı kaynak ve erken rivayetler bu anlamı kullanmayı sürdürür.','QURT-107|TAB-107',role='historical_development',relation='lexical',tradition='historical',source_ref='Kurtubî 107:7 dördüncü ve onuncu görüş; Taberî 107:7 eşya rivayetleri')
add(47,'tafsir','107:1|107:7','Dîn ve mâûnun itaatte buluşması için ayrı klasik malzeme vardır: Râzî mâûnun dördüncü açıklamasını güzel boyun eğiş olarak verir; kolay yapılan bütün itaatleri kapsamasını daha yararlı bulur. Bikāî de son ayetteki esirgemeyi başlangıçtaki hesap yalanlamasına döndürür. Bunlar defter benzetmesini doğrudan kurmaz, fakat ilk ve son ayet arasında ahlaki bağın eski olduğunu gösterir.','RAZI-107|BIQ-107|MQ-DYN',role='corroboration',source_ref='Râzî 107:7 dördüncü görüş ve tercih; Bikāî 107:7 hatime öncesi son paragraf')
add(48,'method_note','107:1|107:7','Yedinci ayette küçük borcun ödenmemesi, ana metnin hak diliyle kurduğu mecazdır. Ayet, alınmış bir ödüncün iade edilmediğini söylemez; gerekli yardımın veya kullanılacak aracın verilmemesini eleştirir. Ödünç verme, borç ödeme ve zekât yükümlülüğü birbirine bağlı ahlaki alanlar olsa da aynı işlem değildir.','TAB-107|IK-107|QURAN',role='constraint',relation='methodological',tradition='project',status='interpretive',connection='resonant',priority='core')
nov(48,'107:1-3|107:7','İbn Fâris’in دين maddesindeki deyn-boyun eğiş bağı, Râzî 107:7’deki itaat anlamı, Râzî ve Bikāî 107:3’te yoksul yemeğinin hak sayılması ve Bikāî 107:7’de sonun başa dönmesi açık öncüllerdir. Fakat bunları hesap defterinin satırları, küçük borç ve كذب عليكم deyimindeki yükümlülük karşıtlığıyla tek tefsire dönüştürme taranan S107 pasajlarında bulunmadı. Bu sentezin borç kelimesini ahlaki hak yerine mecazen kullandığı açık tutulmalıdır.','MQ-DYN|RAZI-107|BIQ-107|MQ-KDHB|JAM-KDHB','partial',C+'; Maḳāyîs دين ve كذب; Cemhere كذب teşvik deyimi',connection='resonant')
nov(48,'107:1|107:4-7','Meâric 70:19–26’nın esirgeme, namaza devam, maldaki hak ve hesap gününü doğrulama sırasını Mâûn’un olumlu karşı düzeni olarak okumak güçlü metinsel desteğe sahiptir. Taranan S107 pasajlarında bu tam madde dizisi bulunmadı. Buna karşılık namaz ve infakın olumlu birlikteliği klasik tefsirde zaten vardır; Bikāî S107 hatimesinde bunu Enfâl 8:2–4 ile kurar. Yenilik, genel ibadet-yardım bağına değil, seçilen Meâric dizisiyle kurulan sistemli eşleştirmeye aittir.','QURAN|BIQ-107','partial',C+'; yalnız Kur’an 70:19–26 metni, bu ayetlerin bütün tefsirleri not_checked',connection='strong')
add(51,'semantic_history','107:4-5','Salâtın dua ve belirli ibadet anlamlarını Maḳāyîs ayrı açıklamalarla verir; Râgıb ibadetin dua adını, içerdiği parçalardan birinin adıyla anılması diye açıklar. Mâûn’daki musallîn ve salâtihim öncelikle namaz bağlamındadır. Allah’ın salâtı, Peygamber’in duası ve müminin rükû-secdesi aynı kelimenin her yerde aynı tür fiili gösterdiği varsayımıyla birleştirilemez.','MQ-SLW|RAG-SLW|TAB-107',role='semantic_range',relation='lexical',tradition='historical',priority='core')
add(52,'tafsir','107:3-5|107:7','Tevbe 9:103’te dua eden, sadakayı almakla görevlendirilen Peygamber’dir; huzur verilen kişiler malından sadaka alınanlardır. Taberî bunu bağışlarının kabulü ve tövbelerine güven duymalarıyla açıklar. Dolayısıyla alan veren için dua eder cümlesi burada Peygamber’in aldığı sadakaya özgü sahneyi genelleştirir; ayet doğrudan yoksul alıcının duasını anlatmaz. Taberî aynı yerde tekil salât ile çoğul salavât okuyuşlarını da kaydeder.','TAB-9103|QURAN',role='constraint',relation='thematic',priority='core',source_ref='Taberî 9:103, وصل عليهم açıklamasından son kıraat tercihine kadar')
add(52,'hadith','107:4|107:7','Buhârî 1497’de Abdullah b. Ebî Evfâ, insanlar sadakalarını getirdiğinde Peygamber’in onlar için dua ettiğini; babası getirdiğinde de Ebû Evfâ ailesi için dua ettiğini anlatır. Bu sahih haber 9:103’teki verme ve dua ilişkisine somut tanıktır. Mâûn’un doğrudan tefsiri değildir ve namaz kılan herkesin duasının mutlaka yoksula yöneldiğini söylemez.','BUKH-1497',role='corroboration',relation='thematic',tradition='hadith',hadith_grade='sahih',connection='strong')
add(53,'method_note','107:3-7','Miskînin kök ailesiyle sekenin huzuru arasındaki köprü sözlük düzeyindedir. 9:103’te huzurun muhatabı bağışçı olduğu için, o ayetten namazın yoksula iletmesi gereken huzur diye doğrudan bir görev tanımı çıkarılamaz. Ana metindeki kopmuş halka, paylaşma ile iç huzuru arasında kurulmuş ahlaki sentezdir; Mâûn’un lafzî açıklaması değildir.','QURAN|TAB-9103|MQ-SKN',role='constraint',relation='methodological',tradition='project',status='interpretive',connection='resonant',priority='core')
add(53,'tafsir','107:4-7','Bu sentezin güçlü klasik çekirdeği Râzî’de açıkça bulunur: Namaz Allah’a aitken insanlara gösterilir; mâûn insanların hakkıyken onlardan gizlenir. Böylece iki ilişki tersine çevrilmiştir. Bu açıklama, ibadetin seyirciye ve yardımın muhtaca yönelişi arasındaki yanlışlığı, huzur döngüsüne başvurmadan kurar.','RAZI-107',role='anchor',priority='core',source_ref='107:7, ثم قال المحققون في الملاءمة paragrafı')
nov(53,'107:3-7','Dışa dönük ibadet ile esirgenen insan hakkı karşıtlığı Râzî 107:7’de açıkça vardır. Sadaka, Peygamber duası ve bağışçının huzuru Taberî 9:103 ile Buhârî 1497’de de açıktır. Fakat bu malzemeyi miskînin سكن ailesi üzerinden Mâûn’a taşıyan ve huzurun yoksula ulaşmamasını kapalı halka sayan düzenleme taranan pasajlarda bulunmadı. Klasik karşıtlık korunmalı; alıcıların yerini değiştiren halka genişletmesi proje yorumu diye sınırlandırılmalıdır.','RAZI-107|TAB-9103|BUKH-1497|MQ-SKN','partial',C+'; Taberî 9:103 وصل عليهم/saken açıklaması ve kıraat sonu; Buhârî 1497; Maḳāyîs سكن',connection='resonant')
add(54,'tafsir','107:2-6','Râzî, namazın kötülükten alıkoyacağını bildiren 29:45’i bu surenin içinde soruya dönüştürür: Yetimi iten ve yoksulu gözetmeyen nasıl namaz kılıyor olabilir? Cevabında riya ve gafletle yapılan ibadetin böyle bir işlev göstermediğini söyler. Yaratıcıya hizmet ile yaratılana iyiliği de dinin iki yönü olarak açıklar. Bu ahlaki bütünlük, ana metnin yeni keşfi değil açık klasik dayanağıdır.','RAZI-107',role='anchor',priority='core',source_ref='107:4 sayfası, mesele 1 içindeki الوجه الثاني ve الوجه الثالث')
nov(54,'107:2-7','İbadetin davranışı düzeltmesi Râzî 107:4–5 mesele 1’de, görünür şekille haklarını yerine getirmenin farkı Müfredât صلا maddesinde açık öncüle sahiptir. Şuayb’in 11:87’deki mal itirazını, Îsâ’nın 19:31 sözünü, 2:83 ahdini, 9:54 isteksizliğini ve 19:59 kaybını tek toplumsal ibadet dizisinde toplamak ise incelenen S107 bölümlerinde bu sırayla bulunmadı. Ayrı Kur’an sahnelerini bu amaçla seçmek proje kompozisyonudur.','RAZI-107|RAG-SLW|QURAN','partial',C+'; Müfredât صلا إقامة/هيئة ve 9:54 paragrafları',connection='strong')
add(54,'source_note','107:4-5','Râgıb’ın صلا maddesi, إقامة vurgusuyla namazın yalnız şeklini değil hak ve şartlarını tamamlamayı öne çıkarır. Aynı pasajdaki musallîn sözünün yalnız münafıklar için kullanıldığı biçimindeki genelleme ise 70:22’nin olumlu istisnası karşısında evrensel bir kelime kuralı olarak alınamaz. Kaynağın yararlı ayrımı korunurken bu genellemenin sınırı da belirtilmelidir.','RAG-SLW|QURAN',role='source_criticism',relation='lexical',tradition='historical',audience='advanced',source_ref='Müfredât صلا, ولم يقل المصلين إلا في المنافقين cümlesi; Kur’an 70:22')
nov(57,'107:1-2|107:5-6','Görme ağının Suhâ üzerinden sehve, Alak üzerinden engellenen namaza bağlanması iki ayrı klasik malzeme kümesini birleştirir. Maḳāyîs سهو’da yıldız ihtimalli bir köken örneğidir; S107 tefsirlerinde gösteriş için yapılan ibadet açıktır. Fakat sönük ihtiyacı kaçıran kişinin kendi görünürlüğünü büyütmesi şeklindeki yıldız-bakış-ibadet çerçevesi incelenen S107 pasajlarında bulunmadı. Kelimelerin sözlükte yan yana bulunması, ayetler arası bilinçli gönderme kanıtı sayılmadı.','MQ-SHW|TAB-107|KASH-107|QURAN','building_blocks_only',C+'; Maḳāyîs سهو Suhâ son cümlesi; Alak 96:9–14 yalnız Kur’an metni',connection='resonant')
nov(58,'107:1-4','İtme ile Tûr 52:13’teki ateşe itiliş bağı Râzî 107:3 sayfasında ve Tehẕîb دع girişinde açıktır. Hâkka 69:34’ün Mâûn 107:3 ile lafzî özdeşliği de doğrudan metindedir. Bu bağları evin pişmeyen yemeği ve paylaşılmayan ocağına dönüştüren birleşik sahne taranan S107 pasajlarında bulunmadı. Klasik köprüler yeni sayılmadı; ocak düzenlemesi ve karşılıklılık yorumu onlardan ayrıldı.','RAZI-107|TAH-DAA|QURAN','partial',C+'; Tehẕîb دع ilk paragraf; Kur’an 52:13–14 ve 69:31–34',connection='strong')
add(59,'cross_quran','107:1|107:3-5','Müddessir 74:43–46 namaz, yoksulu doyurmama ve hesap gününü yalanlamayı gerçekten aynı itirafta toplar. Fakat orada namaz kılanlardan olmadık denirken Mâûn görünüşte namaz kılan bir grubu niteler. Ayrıca 74:45’teki خوض, birlikte dalıp konuşma ve uğraşma sahnesidir; kendiliğinden, istemsiz sehivle aynı kelime veya aynı fiil değildir. Karşılaştırmanın ortaklığı bu ayrımları silmemelidir.','QURAN|RAG-SLW',role='constraint',relation='thematic',tradition='project',status='interpretive',connection='strong',priority='core')
nov(59,'107:1|107:3-5','Müfredât صلا maddesi Mâûn 107:4–5 ile Müddessir 74:43’ü biçim ve gerçek ibadet ayrımında zaten birlikte anmaktadır. Bu açık kısmi öncüldür. Müddessir 74:42–46’nın bütün cevaplarını Mâûn’daki boş namaz, kapalı kap, gözden kaçan yoksul ve inkâr edilen hesabın tek itirafı olarak düzenlemek taranan S107 pasajlarında bulunmadı. Özellikle خوض ile gafletin eşlenmesi doğrudan lafız özdeşliği değil yorumdur.','RAG-SLW|QURAN','partial',C+'; Müfredât صلا إقامة paragrafından 74:43 açıklamasına kadar',connection='strong')
nov(60,'107:2-3|107:7','Mâûnun eşya, su ve zekât/itaat açıklamalarının bir arada bulunması Taberî, Râzî ve Kurtubî 107:7’de açıkça tanıklıdır; bunları yalnız projenin keşfi diye sunmak doğru olmaz. Raftaki kap, akarsu yatağı, hak defteri, iki barınma ayeti ve koruyucu halka biçimindeki bütün ev-su-borç haritası ise incelenen pasajlarda yoktur. Özellikle ma‘în etimolojisi, sehve kolunun kıyas dışılığı ve yetimin bütünüyle korumasız sayılması hakkındaki önceki sınırlar bu birleşim için de geçerlidir.','TAB-107|RAZI-107|QURT-107|MQ-SHW|RAG-AYN|QURAN','partial',C+'; Maḳāyîs سهو sehve kısmı; Müfredât عين ma‘în alternatifleri',connection='resonant')
nov(61,'107:1|107:3-7','Meâric’in olumlu sırasını Tevbe 9:103’ün sadaka-dua-huzur sahnesiyle birleştirip Mâûn’u çözülmüş halkalar olarak okuma, taranan S107 pasajları ile Taberî 9:103’te bu bütünlükte bulunmadı. Namaz ve mal hakkının birliği ile Râzî’nin yanlış yöne çevrilen ibadet/yardım karşıtlığı ise açık öncüllerdir. Birleşimin özgün görünen yanı ayetlerin bu örgüyle seçilmesidir; ibadetin sosyal yükümlülüğü değildir.','QURAN|TAB-9103|RAZI-107','partial',C+'; Taberî 9:103 tam açıklama; Meâric 70:19–26 metni, bütün tefsirleri not_checked',connection='strong')
add(62,'nazm','107:1-7','Bikāî başlangıçtaki hesap yalanlamasının sonunda küçük hakkın bile engellenmesine vardığını açıkça söyler; son böylece başa döner. Önceki Kureyş suresindeki doyurma, güven ve evin Rabbine kulluk çağrısını da Mâûn’un minnet bilmez davranışıyla ilişkilendirir. Bu komşuluk, ana metnin yemek-ev-ibadet çizgisine klasik destek sağlar; edebî sıra tek başına iniş sırasının kanıtı değildir.','BIQ-107|QURAN',role='nazm',relation='structural',tradition='nazm',priority='core',source_ref='Bikāî 107:1 giriş ve 107:7 hatime öncesi; Kur’an 106:3–4')
add(62,'nazm','107:1-7','Râzî, Kevser’in ilk latifesinde dört karşılık kurar: cimriliğin karşısında bol bağış; namazı kaybetmenin karşısında namaza devam; riyanın karşısında Rab için yöneliş; mâûnu esirgemenin karşısında kurbanla verme. Bu, Mâûn’u başka bir sureyle ters yönden okumanın açık klasik örneğidir. Burada yalnız 108:1 sayfasının ilk latifesi denetlendi; Kevser tefsirinin bütünü için tarama iddiası yoktur.','RAZI-1081|QURAN',role='nazm',relation='structural',tradition='nazm',priority='core',source_ref='Mefâtîh 108:1, اعلم أن هذه السورة ... إحداها diye başlayan ilk latife')
add(62,'nazm','107:1-7','Bikāî hatimede Enfâl’in iman, namaz, infak, yetim-yoksul payı ve gösteriş sahnelerini Mâûn’un karşısına getirir. Bu benzerliklerin metinsel temeli vardır; ancak sure numaralarının karşılıklılığı onun özel tertip yöntemidir. Metindeki örneklerden ilkinde verilen 8:4 numarası, alıntının namaz-infak kısmını da içerdiğinden 8:3–4 aralığı olarak okunmalıdır.','BIQ-107|QURAN',role='corroboration',relation='structural',tradition='nazm',audience='advanced',source_ref='Bikāî 107:7 hatime; Kur’an 8:2–4, 8:32, 8:35–36, 8:41, 8:47')
add(62,'source_note','107:1-7','Bikāî’nin aynı hatimesinde kelime sayılarından hicrî 12 ve 16. yıllara gidilerek tarihî olaylarla bağ kurulması, burada nüzûl tarihi veya gerçekleşmiş bir önbildirim kanıtı olarak benimsenmedi. Bu sayısal düzen, olayları bağımsız biçimde tarihlendiren belge değildir. Kaynağın son-baş ve komşu sure ilişkileri bundan ayrı değerlendirildi.','BIQ-107',role='rejected_candidate',relation='historical',tradition='project',status='interpretive',connection='rejected',reason='Kelime sayısı eşleştirmesi bağımsız tarih ve nüzûl delili sağlamaz.',priority='research',audience='research',source_ref='107:7 hatime, ولقد انطبقت ile başlayan son uzun paragraf')
nov(62,'107:1-7','Sonun baştaki yalanlamaya dönmesi Bikāî 107:7’de, ibadetin yaratıcıya ve yardımın insana yönelmesi Râzî 107:4–5 ve 107:7’de, komşu sureyle karşılık kurulması Râzî 108:1 ilk latifede açıktır. Buna karşılık bakıştan ev kapısına, namaz yerine, seyirciye ve rafa uzanan tam güzergâh; ayna-kumaş-Suhâ-su-ocak-defter ağlarının aynı bütün içinde düzenlenmesi incelenen bu pasajlarda bulunmadı. Sonuç, bilinen malzeme ve kısmi öncüller üzerine kurulmuş proje sentezidir; bütün tefsir tarihinde öncülü yoktur iddiası değildir.','BIQ-107|RAZI-107|RAZI-1081|QURAN','partial',C+'; Râzî 108:1 yalnız ilk latife; sözlük maddeleri ve sınırları kaynak kayıtlarında ayrı gösterildi',connection='resonant')
add(62,'source_note','107:7','İbn Kesîr’in andığı taş, demir ve suyu mâûn sayan Kurrâ b. Da‘mûs haberi için kendi hükmü çok garip ve merfû biçimi münkerdir; zincirde tanınmayan kişiler bulunduğunu söyler. Haber Süyûtî’de de aktarılır. Bu kayıt bağımsız güçlü bir peygamber açıklaması sayılmadı. Aynı şekilde Keşşâf ve Râzî’de geçen sureyi okuyana özel bağışlanma vaadi için burada bağımsız isnat denetimi yapılmadı ve fazilet hükmü kurulmadı.','IK-107|SUY-107|KASH-107|RAZI-107',role='source_criticism',relation='direct_hadith_tafsir',tradition='hadith',status='not_assessed',priority='research',audience='research',source_ref='İbn Kesîr 107:7 Kurrâ haberi ve kendi değerlendirmesi; Süyûtî 107:7; Keşşâf 107:7 son cümle; Râzî 107:7 ilk görüş')
add(62,'method_note','107:1-7','Kaynak denetimi, ayet başına açılmış dijital pasajlarla sınırlıdır. Yedi çekirdek müfessirin S107 pasajları baştan sona okundu; birbirini tekrarlayan aktarım bağımsız şahit diye çoğaltılmadı. URL’deki ayet numarası içerik sınırını tek başına belirlemez: Râzî’nin 107:4 ve 107:5 sayfaları aynı tartışmayı büyük ölçüde tekrarlar; 107:2 açıklaması 107:3’te sürer. Beyzâvî 107:4 ve Süyûtî 107:3 sayfalarında ayrı açıklama bulunmaması, kayıp kitap sayfası denetlendiği anlamına gelmez.','PROTO|RAZI-107|BAY-107|SUY-107',role='methodological_note',relation='methodological',tradition='project',priority='research',audience='research')
add(62,'source_note','107:1-7','Denetlenen ek parçalar Kurtubî 107:1 ve 107:7 ile 67:30; Vâhidî’nin 871 ve 871 m kayıtları; İbn Âşûr’un 107:1 sayfasındaki sure girişi ve açıklama; Taberî 9:103; Râzî 108:1’in ilk latifesi; Ebû Şâme’nin 638. beyit açıklaması ve kaynak kayıtlarındaki sözlük maddeleridir. Kurtubî 107:2–6, bütün basılı ciltler, diğer surelerdeki bütün tefsirler, okunmayan İtkān bölümü ve modern akademik literatür not_checked durumundadır. Yokluk değerlendirmesi bunlara yayılmaz.','QURT-107|QURT-6730|WAH-107|ASH-107|TAB-9103|RAZI-1081|SHAMA-638|PROTO',role='source_criticism',relation='methodological',tradition='project',priority='research',audience='research',scope='Açıkça adlandırılmış dijital pasajlar; basılı cilt çapında tarama değil')
add(62,'source_note','107:1-7','Maqāyîs kökleri ayırdığı veya bir örneği şüpheli/kıyas dışı gördüğü yerde bu kayıt belirleyici tutuldu. Sözlükler yerel kaynak indeksindeki özgün Arapça metinlerden kontrol edildi; kök eşleştirmesinin yanlış başlığa götürdüğü kayıtlar kullanılmadı. Bir sayfada kaynak adının görünmesi bütün rivayetlerin doğrulandığı anlamına gelmez. Hadislerde belirtilen sahih/hasen/zayıf dereceleri kaynak kaydında adı verilen değerlendirmelerdir; burada yeni bir isnat tenkidi yapılmadı.','PROTO|MQ-SHW|MQ-DAA|MQ-HDD|MQ-SLW|MQ-KDHB|AD-1657|IM-2473|IM-2474',role='source_criticism',relation='methodological',tradition='project',priority='research',audience='research')
add(62,'reader_note','107:1-7','Okuyucu için ağırlık sırası şöyledir: önce ayetin cümlesi ve açık Kur’an karşılıkları; sonra bağlamla ilgili tefsir ve güvenilir rivayet; ardından sözlükte tanıklanmış anlam kolları; en sonda bu kolları bir araya getiren imgeler. Aynı kökten olmak aynı ayet anlamı olmak değildir. Metindeki insanı eleştiren sözler de tek davranıştan hareketle herhangi bir kişinin inancı hakkında kesin hüküm kurmak için kullanılmamalıdır.','QURAN|RAZI-107|PROTO',role='reader_orientation',relation='methodological',tradition='project',priority='core',source_ref='Râzî 107:4–5 mesele 2’de münafıklık ve günah ayrımı; protokol bağlam/yöntem sınırları')
add(12,'tafsir','107:4-7','Yorumun muhatabı konusunda da farklı vurgu vardır. Zemahşerî, gösteriş ve gevşeklik taşıyan kendini Müslüman sayanlara, hatta bazı âlimlere eleştiriyi açıkça uzatır. Râzî ise bu günahların tek başına kişiyi münafık yapmadığı itirazını sorar ve asıl muhatabın münafıklar olduğu cevabını esas alır. İbn Kesîr kusurların ne kadarını taşıyorsa kişinin o kadar uyarı payı bulunduğunu söyler. Böylece ahlaki uyarının genelliği ile kişinin imanına kesin hüküm ayrı tutulur.','KASH-107|RAZI-107|IK-107',role='disagreement',priority='core',audience='advanced',source_ref='Keşşâf 107:5, وكم ترى من المتسمين بالإسلام; Râzî 107:4–5 mesele 2; İbn Kesîr 107:5 son paragraf')
nov(5,'107:1-3','Hesabı yalanlamanın soyut bir sözden davranışa geçirilmesi yeni değildir: Taberî 107:2 hak mahrumiyetini, Râzî 107:2–3 yapılan kötülük/yapılmayan iyilik ayrımını, Beyzâvî 107:3 fânın nedenselliğini açıklar. Bikāî 107:2 de içteki yalanlamanın bu işle anlaşılmasını söyler. Projenin kapı, el ve susan ağızla sahne kurması anlatım düzeyindedir; davranışın inançla ilişkisini ilk kez keşfetme iddiası değildir.','TAB-107|RAZI-107|BAY-107|BIQ-107','explicit',C,connection='direct')
source('BASE','Asıl metin: `_commentary/v16/out/s107/images.r13.map3.nohft.tool.tool/images.md`; 107:1–7. Bütün paragraflar, başlıklar, Kaynaklar satırları ve satır içi kayıtlar korunmuştur. B kodları özgün metnin yerel sözlük tanıklarını gösterir; ek katmanın kaynak kimlikleri onlardan ayrıdır.')
source('PROTO','`enrichment/v1/Tafsir_Comprehensive_Annotation_Instructions.md`, bu ek katmanın kanonik yöntem ve şema belgesi. Adı geçen S107_comprehensive_reference_v2.md mevcut olmadığından içeriği varsayılmadı. Asıl r13 üretimindeki hadis/müfessir sınırı korunmuş asıl metne aittir; buradaki ek katman farklı kanıtları açıkça ayırır.')
source('QURAN','Kur’an ayet metinleri: `/Volumes/aro/projects/quran-data/data/text/quran-uthmani.tsv`; asıl metinde atıf yapılan ayetler ile 106:1–4, 108:1–3, 8:2–4,32,35–36,41,47, 7:50 ve 76:21 karşılaştırıldı. Okunan ayetlerin dökümü çalışma klasöründeki `sources/quran_checked.txt` ve `sources/quran_additional_checked.txt` dosyalarındadır. Bu kayıt, her ayetin bütün tefsirlerinin incelendiğini söylemez.')
for key,name,slug,host in [
 ('TAB-107','Taberî, Câmiu’l-beyân','tabary','ksu'),('IK-107','İbn Kesîr, Tefsîrü’l-Kur’âni’l-azîm','katheer','ksu'),
 ('KASH-107','Zemahşerî, el-Keşşâf','zamakhshary','tf'),('RAZI-107','Fahreddin er-Râzî, Mefâtîhu’l-gayb','alrazy','tf'),
 ('BAY-107','Beyzâvî, Envârü’t-tenzîl','baidawy','tf'),('SUY-107','Süyûtî, ed-Dürrü’l-mensûr','seoty','tf'),('BIQ-107','Bikāî, Nazmü’d-dürer','beqaay','tf')]:
 def url(n):return f'https://quran.ksu.edu.sa/tafseer/{slug}/sura107-aya{n}.html' if host=='ksu' else f'https://quran-tafsir.net/{slug}/sura107-aya{n}.html'
 links='; '.join(f'[107:{n}]({url(n)})' for n in range(1,8))
 note={'RAZI-107':' İncelenen sınırlar: 107:1 mesele 1–4; 107:2 giriş ve 107:3 devamı; 107:4–5 mesele 1–3; 107:6 açıklaması; 107:7 dört görüş, tercih, uyum sorusu ve son dua. 4 ve 5 sayfaları büyük ölçüde aynı içeriktir.','BIQ-107':' Sure girişi, yedi ayetin açıklaması ve 107:7 hatimesi bütünüyle okundu; kelime sayısından tarih çıkaran kısım da görüldü ve delil olarak reddedildi.','BAY-107':' 107:4 sayfasında müstakil açıklama yoktur; ilgili fâ açıklaması 107:3 sayfasındadır.','SUY-107':' 107:3 sayfasında ayrı rivayet metni yoktur; kalan sure rivayetleri ve giriş okundu. Kaynak adlarıyla aktarılan isnatlar, ilgili kitaplara ayrıca gidilmiş sayılmaz.'}.get(key,' Sure girişi ve 107:1–7 için sunulan açıklamaların tamamı okundu.')
 source(key,f'{name}, Mâûn suresi. Dijital pasajlar: {links}.{note} Arşiv: `sources/{slug}_1..7.html` ve `.txt`. Basılı cilt çapında denetim yapılmadı.')
source('QURT-107','Kurtubî, el-Câmi‘ li-ahkâmi’l-Kur’ân. Yalnız [107:1 sure girişi ve nüzûl görüşleri](https://quran.ksu.edu.sa/tafseer/qortobi/sura107-aya1.html) ile [107:7 bütün açıklama](https://quran.ksu.edu.sa/tafseer/qortobi/sura107-aya7.html) okundu; ikincide on iki anlam, alternatif türetme, Âişe haberi ve İkrime sınırlaması yer alır. 107:2–6 not_checked. Arşiv: `sources/qortobi_1.txt`, `qortobi_7.txt`.')
source('ASH-107','İbn Âşûr, et-Taḥrîr ve’t-tenvîr, [107:1 sayfası](https://quran-tafsir.net/ashour/sura107-aya1.html): sure adları, Mekkî/Medenî ve parça parça iniş görüşü, amaçlar, soru ve fâ kuruluşu, okuyuşlar bütünüyle okundu. Diğer ayetlerdeki İbn Âşûr açıklamaları not_checked. Arşiv: `sources/ibnashur_1.txt`.')
source('WAH-107','Vâhidî, Esbâbü’n-nüzûl, [Mâûn: 871 ve 871 m kayıtları, s. 239](https://islamweb.net/ar/library/index.php?ID=534&bk_no=63&idfrom=462&idto=462&page=bookcontents). Âs b. Vâil ve Ebû Süfyân haberlerinin doğrudan açılan metni. Arşiv: `sources/wahidi_web.html`, `.txt`. Tam isnat doğrulaması yapılmadı.')
source('QURT-6730','Kurtubî, [Mülk 67:30 açıklaması](https://quran.ksu.edu.sa/tafseer/qortobi/sura67-aya30.html), bütün pasaj: ma‘înin عين/معن türetme seçenekleri. Arşiv: `sources/qortobi_67_30.txt`.')
source('TAB-9103','Taberî, [Tevbe 9:103](https://quran.ksu.edu.sa/tafseer/tabary/sura9-aya103.html), ayetin bütün dijital açıklaması okundu; eklerde özellikle وصل عليهم, سكن لهم ve salât/salavât okuyuşları kullanıldı. Arşiv: `sources/tabary_9_103.txt`.')
source('RAZI-1081','Râzî, [Kevser 108:1 sayfası](https://quran-tafsir.net/alrazy/sura108-aya1.html), yalnız sure girişindeki ilk latife: Mâûn’un dört niteliğine Kevser’in dört karşılığı. Kaynak indirildi, fakat bütün sayfa için okuma iddiası yoktur; denetlenen sınır `sources/alrazy_108_1_inspected_excerpt.txt` dosyasında ayrıldı.')
source('SHAMA-638','Ebû Şâme, İbrâzü’l-meânî min Ḥırzi’l-emânî, [638. beyit ve açıklaması](https://www.islamicbook.ws/qbook/alom/ibraz-almaani-004.html). رأيت kelimesinin soru hemzesi sonrasındaki hemzesi: Kisâî, Nâfi‘ ve Verş yolları. Yalnız ilgili beyit şerhi kıraat delili olarak okundu; tam cilt taraması yoktur. Arşiv: `sources/shama_638.html`, `shama_638_excerpt.txt`.')
lex={
 'MQ-RAY':(3311,'İbn Fâris, Maḳāyîsü’l-luġa','رأى','tam madde'),
 'RAG-RAY':(3316,'Râgıb el-İsfahânî, el-Müfredât','رأى','gebeliğin görünür olması, riya ve ayna paragrafları'),
 'MQ-KDHB':(8029,'İbn Fâris, Maḳāyîsü’l-luġa','كذب','yalnız كذب maddesi; ardından gelen başka başlıklar kapsam dışında'),
 'RAG-KDHB':(8034,'Râgıb el-İsfahânî, el-Müfredât','كذب','tam madde, özellikle fiille yalan, süt ve kumaş'),
 'JAM-KDHB':(8031,'İbn Düreyd, Cemheretü’l-luġa','كذب','tam madde; koşup duran hayvan ve teşvik deyimi'),
 'MQ-DYN':(3148,'İbn Fâris, Maḳāyîsü’l-luġa','دين','yalnız دين maddesi'),
 'SIH-DYN':(3151,'Cevherî, eṣ-Ṣıḥâḥ','دين','tam madde, özellikle tedyîn son cümlesi'),
 'TAH-DYN':(3152,'Ezherî, Tehẕîbü’l-luġa','دين','tam madde; yemin edenin niyetine bırakılması son paragrafı'),
 'MQ-YTM':(10548,'İbn Fâris, Maḳāyîsü’l-luġa','يتم','tam madde'),
 'TAH-YTM':(10553,'Ezherî, Tehẕîbü’l-luġa','يتم','tam madde; Mufaddal ve Ebû Amr açıklamaları'),
 'RAG-YTM':(10554,'Râgıb el-İsfahânî, el-Müfredât','يتم','tam madde'),
 'MQ-DAA':(2981,'İbn Fâris, Maḳāyîsü’l-luġa','دع','tam madde; ses taklidini kıyastan ayıran son açıklama dahil'),
 'TAH-DAA':(2985,'Ezherî, Tehẕîbü’l-luġa','دع','tam madde; Tûr ayeti, kaldıran çağrı, küçük çocuklar ve dolu kap'),
 'MQ-HDD':(2089,'İbn Fâris, Maḳāyîsü’l-luġa','حض','tam madde; iki asıl ve Halîl nakli'),
 'MQ-SKN':(4517,'İbn Fâris, Maḳāyîsü’l-luġa','سكن','tam madde; durulma, aile ve ateş'),
 'TAH-MNA':(9014,'Ezherî, Tehẕîbü’l-luġa','منع','tam madde; himaye çevresi ve esirgeme'),
 'RAG-AYN':(6654,'Râgıb el-İsfahânî, el-Müfredât','عين','ma‘în kelimesinin iki türetme yolunu gösteren bölüm'),
 'MQ-TAM':(5808,'İbn Fâris, Maḳāyîsü’l-luġa','طعم','tam madde; su için ta‘âm kullanımının savunusu'),
 'MQ-SLW':(5471,'İbn Fâris, Maḳāyîsü’l-luġa','صلى','tam madde; ateş ve ibadet için iki asıl'),
 'RAG-SLW':(5476,'Râgıb el-İsfahânî, el-Müfredât','صلا','tam madde; ateş, dua, ateşten uzaklaştırma türetmesi ve إقامة/هيئة ayrımı'),
 'TAH-SLW':(5475,'Ezherî, Tehẕîbü’l-luġa','صلى','dua ve salât açıklamaları, Zeccâc etimolojisi, ateş ve değnek kullanımları')}
rows={x['id']:x for x in json.loads((W/'lexicon_index.json').read_text())}
for k,(n,author,head,scope) in lex.items():
 d=rows[n]
 fname=next(p.name for p in (W/'sources').glob(f'lex_*_{n}.txt'))
 source(k,f'{author}, {head} maddesi. Denetlenen parça: {scope}. Yerel özgün Arapça kaynak derlemi: `/Volumes/aro/projects/quran-data/data/lexicon/v4.sqlite.gz`, dictionary_entries.id={n}; source_entry_id={d["source_entry_id"]}; kaynak izi `{d["source_ref"]}`. Açılan metin: `sources/{fname}`. Temizlenmiş dijital madde denetimidir; basılı nüsha karşılaştırması yapılmadı.')
source('MQ-SHW','İbn Fâris, Maḳāyîsü’l-luġa, [سهو maddesi](https://www.islamweb.net/ar/library/index.php?ID=277&bk_no=124&idfrom=2062&idto=2071&page=bookcontents_ver3). Tam madde okundu: gaflet, müsâhât, kıyas dışı sehve, Suhâ için ihtimal kaydı. Arşiv: `sources/mq_shw_web.html`, `.txt`.')
source('MQ-MAN','İbn Fâris, Maḳāyîsü’l-luġa, [معن maddesi](https://www.islamweb.net/ar/library/content/124/4253/). Tam madde: kolay akış, su yatağı, suya kanmış toprak, otluk ve hak kullanımları. Arşiv: `sources/mq_man_web.html`, `.txt`.')
for k,col,num,desc,grade in [
 ('MUS-2642','muslim','2642a','Ebû Zer: iyilik yapan kişiye gelen övgü','Sahîh-i Müslim'),
 ('MUS-2985','muslim','2985','Ebû Hüreyre: ortak edilen amelin bırakılması','Sahîh-i Müslim'),
 ('MUS-622','muslim','622','Enes: geciktirilip acele kılınan ikindi','Sahîh-i Müslim'),
 ('BUKH-1226','bukhari','1226','İbn Mes‘ûd: beş rekât ve sehiv secdesi','Ṣaḥîḥ-i Buḫârî'),
 ('BUKH-5304','bukhari','5304','Sehl: yetimi üstlenenle cennette yakınlık','Ṣaḥîḥ-i Buḫârî'),
 ('BUKH-1479','bukhari','1479','Ebû Hüreyre: fark edilmeyen ve istemeyen yoksul','Ṣaḥîḥ-i Buḫârî'),
 ('BUKH-6007','bukhari','6007','Ebû Hüreyre: dul ve yoksul için çaba; devam cümlesindeki ravi tereddüdü korunur','Ṣaḥîḥ-i Buḫârî'),
 ('BUKH-1497','bukhari','1497','İbn Ebî Evfâ: sadaka getirene dua','Ṣaḥîḥ-i Buḫârî'),
 ('AD-1657','abudawud','1657','İbn Mes‘ûd: kova ve tencere ödüncü','açılan sayfada Elbânî: hasen'),
 ('IM-2473','ibnmajah','2473','Ebû Hüreyre: su, otlak, ateş','açılan sayfada Darussalam: sahih'),
 ('IM-2474','ibnmajah','2474','Âişe: su, tuz, ateş ve uzun mükâfat anlatısı','açılan sayfada Darussalam: daif')]:
 source(k,f'[{col} {num}](https://sunnah.com/{col}:{num}), {desc}. Arapça metin ve kimlik doğrudan açılarak denetlendi; derece dayanağı: {grade}. Web erişim dökümü çalışma klasöründeki `hadith_batch1.json`, `hadith_batch2.json`, `hadith_batch3.json` içinde. Burada ayrıca bağımsız isnat tahkiki yapılmadı.')
# Serialize a flat canonical block, one physical line per annotation.
import importlib.util
spec=importlib.util.spec_from_file_location('checker','enrichment/v1/validate_output.py');check=importlib.util.module_from_spec(spec);spec.loader.exec_module(check)
def block(d):
 def val(k,v):
  if isinstance(v,bool):return 'true' if v else 'false'
  return v if k in check.ENUMS else json.dumps(v,ensure_ascii=False)
 assert all('\n' not in str(v) for v in d.values())
 return '{'+', '.join(k+':'+val(k,v) for k,v in d.items())+'}'
used={s for arr in A.values() for d in arr for s in d['source'].split('|')}
assert not used-registry.keys(),used-registry.keys()
chunks=B.read_text().strip().split('\n\n');assert len(chunks)==63
out=['<!-- Comprehensive enrichment: S107 / Turkish / independent Astra HIGH. Original text retained; annotations are separate evidence layers. -->']
out.extend(block(d) for d in A[-1])
for n,ch in enumerate(chunks):
 out.append(ch);out.extend(block(d) for d in A[n])
out.append('## Kaynak kayıtları')
out.extend('- **'+k+'** — '+v for k,v in registry.items() if k in used)
O.write_text('\n\n'.join(out)+'\n')
(W/'annotation_records.json').write_text(json.dumps([dict(base_block=n,**d) for n,arr in A.items() for d in arr],ensure_ascii=False,indent=2)+'\n')
(W/'composition_counts.json').write_text(json.dumps({'annotations':sum(counts.values()),'types':dict(counts),'registry':len(used),'base_blocks':len(chunks)},ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'output':str(O),'annotations':sum(counts.values()),'types':dict(counts),'registry':len(used)},ensure_ascii=False))
