from pathlib import Path
from collections import Counter,defaultdict
import hashlib,json,re

W=Path(__file__).resolve().parent
ROOT=Path('/Volumes/aro/projects/prose_generation')
BASE=ROOT/'_commentary/v16/out/s100/images.r13.map3.nohft.tool.tool/images.md'
OUT=ROOT/'enrichment/v1/out/100/100_enriched.md'
assert json.loads((W/'evidence_matrix.json').read_text())['prepared_before_composition']
catalog={}
def register(key,title,url,file=None,scope='',note='',state='inspected'):
 data={'id':key,'title':title,'url':url,'scope_actually_inspected':scope,'note':note,'state':state}
 if file:
  p=W/'sources'/file
  data['artifact']=str(p);data['sha256']=hashlib.sha256(p.read_bytes()).hexdigest()
 catalog[key]=data

authors={
 'TAB':('tabary','Taberî, Câmiʿu’l-beyân','https://quran.ksu.edu.sa/tafseer'),
 'KAT':('katheer','İbn Kesîr, Tefsîru’l-Kurʾâni’l-azîm','https://quran.ksu.edu.sa/tafseer'),
 'ZAM':('zamakhshary','Zemahşerî, el-Keşşâf','https://quran-tafsir.net'),
 'RAZ':('alrazy','Fahreddin er-Râzî, Mefâtîhu’l-gayb','https://quran-tafsir.net'),
 'BAY':('baidawy','Beyzâvî, Envâru’t-tenzîl','https://quran-tafsir.net'),
 'SUY':('seoty','Süyûtî, ed-Dürrü’l-mensûr','https://quran-tafsir.net'),
 'BIQ':('beqaay','Burhâneddin el-Bikāî, Nazmü’d-dürer','https://quran-tafsir.net'),
 'QURT':('qortobi','Kurtubî, el-Câmiʿ li-ahkâmi’l-Kurʾân','https://quran.ksu.edu.sa/tafseer'),
 'ASH':('ashour','İbn Âşûr, et-Tahrîr ve’t-tenvîr','https://quran-tafsir.net'),
}
for key,(slug,title,origin) in authors.items():
 pages=range(1,12) if key in ['TAB','KAT','ZAM','RAZ','BAY','SUY','BIQ'] else [1,4,6,9,10,11] if key=='QURT' else [1]
 for a in pages:
  note='Dijital ayet sayfasında yazar metninin tamamı okundu; basılı cildin tamamı denetlenmedi.'
  state='inspected_full_digital_body'
  if key=='SUY' and a in [3,4,5]:
   note='100:2 sayfasının gövdesiyle aynı metin; ayet başlığı farkı kontrol edildi. Bağımsız rivayet veya ayrı tarihsel tanıklık sayılmadı.';state='inspected_duplicate_body'
  if key=='SUY' and a in [9,10,11]:
   note='Dijital sayfa ayet başlığı/sınırlı işaret dışında müstakil tefsir gövdesi sunmuyor; basılı eserde de metin yok sonucu çıkarılmadı.';state='inspected_no_substantive_body'
  register(f'{key}100-{a}',f'{title}, 100:{a}',f'{origin}/{slug}/sura100-aya{a}.html',f'{slug}_100_{a}.txt',f'100:{a}, dijital sayfadaki yazar gövdesinin tamamı',note,state)
for key in ['TAB','RAZ']:
 slug,title,origin=authors[key]
 for a in [32,33]:
  register(f'{key}38-{a}',f'{title}, 38:{a}',f'{origin}/{slug}/sura38-aya{a}.html',f'{slug}_38_{a}.txt',f'38:{a}, dijital gövdenin tamamı; Râzî 38:33 sayfasının tekrar ettiği 38:32 tartışması da okundu','Süleymanın at sevgisi ve meshin yorumu için seçili ek kontrol; Sâd sûresinin tamamı denetlenmedi.')
lex_files={
 'MAQ-adw':'lex_adw_d7_14.txt','MAQ-dbh':'lex_dbh_d7_13.txt','MAQ-gwr':'lex_gwr_d7_19.txt','MAQ-hbb':'lex_hbb_v_d7_0.txt','MAQ-hsl':'lex_hsl_d7_14.txt','MAQ-jma':'lex_jma_v_d7_0.txt','MAQ-knd':'lex_knd_d7_16.txt','MAQ-qbr':'lex_qbr_d7_21.txt','MAQ-qdh':'lex_qdh_d7_15.txt','MAQ-rbb':'lex_rbb_v_d7_0.txt','MAQ-sbh':'lex_sbh_d7_20.txt','MAQ-sdr':'lex_sdr_v_d7_0.txt','MAQ-shd':'lex_shd_d7_19.txt','MAQ-shdd':'lex_shdd_v_d7_0.txt','MAQ-twr':'lex_twr_d7_19.txt','MAQ-wry':'lex_wry_v_d7_0.txt','MAQ-wst':'lex_wst_d7_20.txt','MAQ-alm':'lex_alm_v_d7_0.txt','MAQ-ans':'lex_ans_v_d7_0.txt','MAQ-khyr':'lex_khyr_v_d7_0.txt','MAQ-khbr':'lex_khbr_m_d7_0.txt','MAQ-nqa':'lex_nqa_d7_19.txt',
 'RAG-hsl':'lex_hsl_d31_3.txt','RAG-bathr':'lex_bathr_d31_0.txt','RAG-wry':'lex_wry_v_d31_7.txt','RAG-qbr':'lex_qbr_d31_16.txt','RAG-khyr':'lex_khyr_d31_11.txt','RAG-khbr':'lex_khbr_d31_6.txt','RAG-rbb':'lex_rbb_v_d31_3.txt','RAG-hbb':'lex_hbb_v_d31_6.txt','RAG-twr':'lex_twr_d31_4.txt','RAG-sdr':'lex_sdr_d31_8.txt','RAG-shd':'lex_shd_d31_0.txt','RAG-jma':'lex_jma_v_d31_8.txt','RAG-ans':'lex_ans_d31_19.txt',
 'SIH-hbb':'lex_hbb_d6_7.txt','SIH-hsl':'lex_hsl_d6_0.txt','SIH-qdh':'lex_qdh_d6_12.txt','SIH-jma':'lex_jma_d6_11.txt','SIH-sdr':'lex_sdr_d6_10.txt','SIH-ans':'lex_ans_d6_8.txt','SIH-shd':'lex_shd_d6_14.txt','LIS-knd':'lex_knd_d1_12.txt','LIS-shd':'lex_shd_d1_11.txt',
}
roots={'adw':'ع د و','dbh':'ض ب ح','gwr':'غ و ر','hbb':'ح ب ب','hsl':'ح ص ل','jma':'ج م ع','knd':'ك ن د','qbr':'ق ب ر','qdh':'ق د ح','rbb':'ر ب ب','sbh':'ص ب ح','sdr':'ص د ر','shd':'ش ه د','shdd':'ش د د','twr':'ث و ر','wry':'و ر ي','wst':'و س ط','alm':'ع ل م','ans':'أ ن س / إنس','khyr':'خ ي ر','khbr':'خ ب ر','nqa':'ن ق ع','bathr':'ب ع ث ر'}
lex_names={'MAQ':'İbn Fâris, Muʿcemü mekāyîsi’l-luga','RAG':'Râgıb el-İsfahânî, el-Müfredât','SIH':'Cevherî, es-Sıhâh','LIS':'İbn Manzûr, Lisânü’l-Arab'}
for key,file in lex_files.items():
 text=(W/'sources'/file).read_text();url=re.search(r'https://arabiclexicon\.hawramani\.com/\?p=\d+#[A-Za-z0-9]+',text).group()
 prefix,root=key.split('-');scope=f'{roots[root]} maddesinin dijital yazar metninin tamamı'
 if key=='LIS-shd':scope='ش ه د maddesi, atın koşusunun kalitesine/önde gelişine şahitlik ettiği altpasaj; madde başlığı ve sınırlı ilk pasaj. Maddenin tamamı okunmadı.'
 register(key,f'{lex_names[prefix]}, {roots[root]} maddesi',url,file,scope,'Hawramani bir taşıyıcıdır; yazar ve madde metni ayrıca kontrol edildi. Kök önceliğinde İbn Fârisin açık ayrımları korunmuştur.')
for key,collection,number,summary in [
 ('BUK2371','bukhari','2371','Atların sevap, korunma yahut günah oluşu; niyet, koşu, su ve Zilzal 99:7–8.'),
 ('BUK1684','bukhari','1684','Müzdelife/Jamʿdan güneş doğmadan ayrılma; eski uygulama ile fark.'),
 ('BUK6436','bukhari','6436','İki vadi malı olanın üçüncüyü istemesi ve insanın karnını toprağın doldurması.'),
 ('BUK1130','bukhari','1130','Namazda ayakların şişmesi ve şükreden kul olma.'),
 ('MUS382','muslim','382','Sabah baskınında ezan dinleme ve ezan duyulursa durma.'),
 ('MUS2564c','muslim','2564c','Allahın kalplere ve amellere bakması; şekil ve servet karşılaştırması.'),
 ('MUS127a','muslim','127a','Söylenmemiş/işlenmemiş iç vesvesenin bağışlanması.'),
 ('MUS2625c','muslim','2625c','Et suyunu artırıp komşulara uygun biçimde paylaşma.'),
]:
 name='Buhârî, el-Câmiʿu’s-sahîh' if collection=='bukhari' else 'Müslim, el-Câmiʿu’s-sahîh'
 register(key,f'{name}, no. {number}',f'https://sunnah.com/{collection}:{number}',scope='Tek hadis kaydının Arapça metni, ravi/bab ve numarası web aracıyla kontrol edildi.',note=f'{summary} Sahih sınıflaması koleksiyonun tasnifine dayanır; yeni ve bağımsız isnad tahkiki yapılmadı. Adiyatın doğrudan sebeb-i nüzulü olarak sunulmadı.')
register('WAH100','Vâhidî, Esbâbü’n-nüzûl, Adiyat, no.867–868, s.238','https://www.islamweb.net/ar/library/content/63/458/سورة-العاديات',scope='Adiyat altbaşlığındaki iki rivayet ve kaynak zinciri tamamen okundu.',note='867 Mukatilin Kinaneye gönderilen Münzir b.Amr birliği; 868 Hafs b.Cemîʿ–Simak–İkrime–İbn Abbas kanalıyla bir ay haber gelmeyişi. Quranpedia sayfa kabuğu bu metin yerine kullanılmadı.')
register('SHAD178','İbn Hâleveyh, Kitâbü’l-kırââti’ş-şâzze, Rahmâniyye 1934, s.178','https://sites.dlib.nyu.edu/viewer/books/columbia_aco000916/display?lang=ar','ibn-khalawayh-shadhdha-1934.pdf','Şevâzzü sûreti’l-Adiyat altbaşlığının tamamı; basılı s.178, PDF sıfır tabanlı sayfa190 (191. fiziksel sayfa).','NYU/Columbia taraması; yalnız bu altbaşlık görüntüden okundu. Kitabın tamamı ve on kıraatin bütün yolları denetlenmedi.')
register('QURAN','Tanzil Project, Kurʾan metni, Uthmani v1.1','https://tanzil.net/pub/download/index.php?quranType=uthmani&outType=txt-2&agree=true','quran-uthmani-numbered.txt','100:1–11; özgün metnin 106 ayrı ayet atfı ve 22 seçili bağlam/ek ayet, toplam128 ayrı ayet.','6236 ayetlik numaralı veri indirildi; yalnız kaydedilen128 ayet anlam karşılaştırması için okundu. 126 temel Arapça alıntı ayrıca mekanik olarak tarandı; 7:58 hemze yazımı farkı elle gözden geçirildi. Özgün veri ve telif notu korunmuştur.')
register('BASE100','Özgün S100 r13 temel metni',str(BASE),scope='151 satır; 76 temel blok, tamamı sınırlı parçalarla okundu.',note='Enrichment girdisidir; aktarımları kaynak eleştirisinden muaf değildir.')
register('LEDGER100','Özgün S100 r13 ledger ve üretim kapsamı',str(BASE.with_name('ledger.md')),scope='Bitişik ledger tamamı; özgün çalışma isteminin ilk90 satırı ve ilgili metadata.',note='Eski sözlük/Kurʾan kapsamı ile bugünkü ek yetkisi birbirinden ayrıldı.')
register('PROTOCOL','Kapsamlı zenginleştirme yönergesi',str(ROOT/'enrichment/v1/Tafsir_Comprehensive_Annotation_Instructions.md'),scope='990 satırın tamamı sınırlı parçalarla okundu.',note='S107 referans dosyası mevcut değildi; yazılı yönerge esas alındı.')
register('CORPUS100','S100 kontrol edilen birincil pasajlar dökümü',str(W/'checked_source_catalog.json'),scope='Yedi çekirdek müfessirin 100:1–11 dijital gövdeleri ve tek tek kayıtlı ek kaynaklar.',note='İndirme ve tam metin incelemesi ayrı durum alanlarıyla kaydedildi; Süyûtî tekrarları/boş bölümleri belirtildi. Tam basılı cilt veya bütün klasik literatür yokluk denetimi değildir.')

annotations=[]
by_block=defaultdict(list)
enums={'type','tradition','role','relation','status','confidence','historicity','hadith_grade','connection','classical_attestation','priority','audience','canonical'}
def readable(text):
 replacements={
  'Taberînin':'Taberî’nin','Taberîde':'Taberî’de','Taberîyi':'Taberî’yi','Taberîye':'Taberî’ye',
  'Râzînin':'Râzî’nin','Râzîde':'Râzî’de','Râzîye':'Râzî’ye',
  'Kurtubînin':'Kurtubî’nin','Kurtubîde':'Kurtubî’de',
  'Cevherînin':'Cevherî’nin','Cevherîde':'Cevherî’de','Cevherîye':'Cevherî’ye',
  'Râgıbın':'Râgıb’ın','Râgıbda':'Râgıb’da','Râgıba':'Râgıb’a',
  'Mekāyîsin':'Mekāyîs’in','Mekāyîste':'Mekāyîs’te','Mekāyîs atasözü':'Mekāyîs’teki atasözü',
  'Süyûtînin':'Süyûtî’nin','Süyûtîde':'Süyûtî’de','Süyûtîye':'Süyûtî’ye',
  'Hâleveyhin':'Hâleveyh’in','Bikāîde':'Bikāî’de',
  'Vâhidînin':'Vâhidî’nin','Hâkimin':'Hâkim’in','Fârisin':'Fâris’in',
  'Peygamberin':'Peygamber’in','Peygambere':'Peygamber’e',
  'Allahın':'Allah’ın','Allahı':'Allah’ı',
  'Ümâmenin':'Ümâme’nin','Ümâmeye':'Ümâme’ye','Kurʾanda':'Kurʾan’da','Kurʾanın':'Kurʾan’ın',
  'Adiyatın':'Adiyat’ın','Adiyatta':'Adiyat’ta','Adiyattaki':'Adiyat’taki','Adiyatı':'Adiyat’ı',
  'Süleymanın':'Süleyman’ın','Zilzalin':'Zilzal’in','Zilzaldeki':'Zilzal’deki',
  'Kinaneye':'Kinâne’ye','Müzdelifedeki':'Müzdelife’deki','Müzdelifede':'Müzdelife’de',
  'toplam128':'toplam 128','ve100:':'ve 100:','ve47:':'ve 47:','veRâzî':'ve Râzî','Buhârî1684':'Buhârî 1684',
 }
 for old,new in replacements.items():text=text.replace(old,new)
 text=re.sub(r'(\d{1,3}:\d+(?:[–-]\d+)?)(de|da|te|ta|den|dan|ten|tan|e|a|in|ın)(?=\W|$)',r'\1’\2',text)
 text=re.sub(r'(?<![\w:])(\d{2,4}[a-z]?)(de|da|te|ta|den|dan|ten|tan)(?=\W|$)',r'\1’\2',text)
 return text
defaults={
 'tafsir':('rivayet','clarification','direct_tafsir','explicit','direct'),
 'asbab':('rivayet','asbab_context','asbab','reported','direct'),
 'hadith':('hadith','corroboration','thematic','explicit','strong'),
 'qiraat':('rivayet','clarification','grammatical','reported','direct'),
 'revelation_history':('historical','chronology','historical','disputed','not_applicable'),
 'historical_context':('historical','historical_context','historical','reported','strong'),
 'semantic_history':('dirayet','semantic_range','lexical','explicit','strong'),
 'nazm':('nazm','nazm','structural','interpretive','strong'),
 'cross_quran':('project','intertext','comparative','interpretive','strong'),
 'method_note':('project','constraint','methodological','interpretive','not_applicable'),
 'reader_note':('none','reader_orientation','methodological','explicit','not_applicable'),
 'novelty':('project','novelty_assessment','comparative','interpretive','resonant'),
 'modern_scholarship':('dirayet','historical_development','historical','reported','strong'),
 'source_note':('none','source_criticism','methodological','explicit','not_applicable'),
}
def add(block,key,type,ayah,prose,source,**kw):
 tradition,role,relation,status,connection=defaults[type]
 d=dict(id=f'S100-{key}',type=type,ayah=ayah,tradition=tradition,role=role,relation=relation,status=status,connection=connection,priority='core',audience='general',prose=prose,source=source)
 d.update(kw)
 for field in ['prose','source_ref','checked_sources','origin','note']:
  if field in d:d[field]=readable(d[field])
 assert set(source.split('|'))<=catalog.keys(),source
 annotations.append({'base_block':block,**d});by_block[block].append(d)
def nov(block,key,ayah,prose,source,attestation,checked,**kw):
 add(block,key,'novelty',ayah,prose,source,classical_attestation=attestation,checked_sources=checked,priority='research',audience='research',confidence='medium',**kw)

# The substantive matrix above precedes every annotation composed below.
add(1,'RD01','reader_note','100:1-11','Açılıştaki kontrol betiği ve görüntü zinciri bilgileri özgün üretim kaydıdır; okura dönük sûre açıklamasıyla aynı türden değildir. Belge bütünlüğü için korundu. Sonraki bağımsız ekler, kaynak metnini açıklama, karşı görüş, tarihsel nakil ve proje sentezi olarak ayırır.','BASE100|LEDGER100',priority='extended',audience='advanced')
add(1,'MT01','method_note','100:1-11','Özgün r13 üretiminin hadis ve müfessir kullanmama sınırı temel metnin kapsamını belirler. Kapsamlı zenginleştirme yönergesi bu ek katmanda onları kullanmayı yetkilendirir. Bir sözlük ailesinin yan anlamı ayetin bağlamsal çevirisi sayılmaz; farklı kök, tarihsel etimoloji önerisi ve Kurʾan paraleli de ayrı delil türleridir.','PROTOCOL|LEDGER100',status='explicit',audience='advanced')
add(3,'TF01','tafsir','100:1-5','At tasviri güçlü klasik bir tercihtir: Taberî nefes sesini esas alarak atları seçer. Bunun yanında İbn Mesud ve başka erken isimlerden, Arafat–Müzdelife–Mina hareketindeki develer yorumu aktarılır. Ali–İbn Abbas tartışması bu iki anlayışı karşılaştırır; rivayetin farklı ayrıntıları bulunduğu için tartışma burada kesin olay tarihi veya sahih hadis yerine ihtilafın erken tanığıdır.','TAB100-1|KAT100-1|ZAM100-5',role='anchor',status='disputed',source_ref='Taberî 100:1 rivayet kümeleri ve son tercih; İbn Kesîr 100:1; Keşşâf 100:5 Ali–İbn Abbas nakli',historicity='uncertain')
add(3,'HX01','historical_context','100:1-5','Hac yorumundaki sabah hareketinin gerçek bir ibadet bağlamı vardır. Buhârî 1684te Ömer, eski uygulamanın güneş doğana dek Müzdelifede beklemek olduğunu; Hz. Peygamberin ise güneş doğmadan ayrıldığını anlatır. Bu kayıt hac hareketini aydınlatır, Adiyatın mutlaka haccı anlattığını yahut o olay üzerine indiğini kanıtlamaz.','BUK1684|TAB100-3',historicity='established',note='Koleksiyon kaydı tarihsel bağlam içindir; doğrudan Adiyat tefsiri değildir.')
add(3,'NZ01','nazm','100:1-6','İlk üç ayetteki dişil çoğul ism-i fâillerden dördüncü ve beşincide geçmiş zaman fiillerine geçiş klasik gramerde zaten açıklanır. Zemahşerî, ism-i fâillerin içinde düşünülen fiil cümlesine atfı gösterir; Bikāî hareketin birbirini doğuran sonuçlarını vurgular. Altıncı ayet yemin cevabıdır. Fâ zinciri aynı sahneyi kuvvetlendirir; her ayrıntının değişmez fizik takvimini tek başına belirlemez.','ZAM100-5|BIQ100-2|BIQ100-4|BAY100-6',tradition='dirayet',status='explicit',relation='grammatical')
add(3,'RH01','revelation_history','100:1-11','Sûrenin Mekke veya Medinede inişi nakillerde ihtilaflıdır. Kurtubî, Mekkî ve Medenî diyen farklı isimleri kaydeder; İbn Kesîr başlıkta Mekkî kabul eder. Râzî, savaş anlatısı üzerinden Medenîliği destekler. Bir seriyye rivayetini doğru kabul ederek varılan yer tayini, o rivayetten bağımsız bir kronoloji delili değildir.','QURT100-1|KAT100-1|RAZ100-1',historicity='contested',audience='advanced',source_ref='Kurtubî sûre girişindeki Mekke/Medine listeleri; İbn Kesîr sûre başlığı; Râzî 100:1 son kronoloji paragrafı')
add(3,'AS01','asbab','100:1-5','Vâhidî iki haber-gecikmesi anlatısı aktarır: Mukatile göre Kinaneye gönderilen, Münzir b.Amrın komuta ettiği birliğin haberi gecikir; diğer nakilde İbn Abbasa ulaşan zincir bir ay haber alınmamasını söyler. İkinci zincirde Hafs b.Cemîʿ vardır. Bunlar ayetlerin askerî at tasvirine uygulanmasını açıklar; burada bağımsız isnad incelemesi yapılmadığından kesin nüzul sebebi veya olay tarihi ilan edilmez.','WAH100',historicity='uncertain',hadith_grade='not_assessed',source_ref='Esbâbü’n-nüzûl, Adiyat, no.867–868; ikinci isnad Hafs b.Cemîʿ–Simak–İkrime–İbn Abbas')
add(3,'SC01','source_note','100:1-5','Geciken seriyye anlatısının Beyzâvî, Süyûtî ve başka geç kaynaklarda görünmesi, aynı çekirdeğe ait aktarım ve kabul tarihini gösterir; ayrı ayrı bağımsız olay tanıklıkları üretmez. Süyûtînin Ali–İbn Abbas haberi için Hâkimin tashihini aktarması da Hâkimin asıl metninin ve isnadının burada bağımsız kontrol edildiği anlamına gelmez.','WAH100|BAY100-5|SUY100-1',priority='research',audience='research')
add(3,'MS01','modern_scholarship','100:1-11','İbn Âşûr, askerî haber rivayetindeki Hafs b.Cemîʿin zayıflığını belirtmesine rağmen Medenîlik yönünde değerlendirme yapar; ayrıca Câbir b.Zeyde nispet edilen nüzul sıralamasını aktarır. Bu, sonraki bir müfessirin delilleri tartma biçimidir. Sıra nakli, seriyye anlatısı ve müfessirin tercihi tek bir doğrulanmış tarih çizelgesi gibi birleştirilmemelidir.','ASH100-1',historicity='contested',priority='extended',audience='advanced',source_ref='İbn Âşûr 100:1 giriş, Mekke/Medine, Hafs b.Cemîʿ ve Câbir b.Zeyd sıralaması altpasajları')
add(4,'SM01','semantic_history','100:1','Dabhın ses ve solukla ilişkisi güçlüdür; ön ayaklarını ileri atarak koşmak anlamıyla dhabʿdan dönüşüm ise ihtilaflı bir açıklamadır. İbn Fâris bunu şartlı kıyas olarak anarken Zemahşerî sabit bulmaz. İbn Fâris ayrıca ses ile ateşin değiştirdiği renk için iki ayrı başlangıç ayırır. Bu yüzden soluk, ön ayak hareketi ve yanma aynı kesin etimolojik tanım olarak okunmamalıdır.','MAQ-dbh|ZAM100-5',status='disputed',audience='advanced',term='ضبح / ضبع',source_ref='Maqayis ضبح maddesinin tamamı; Keşşâf 100:5 deve ve ضبع açıklamasının reddi')
add(5,'SM02','semantic_history','100:2|100:5','İncelmiş at, henüz tamamlanmamış ok ve ateş çakma q-d-h ailesinde eski sözlük tanıklarıdır; Cevherî bunları kaydeder. Fakat İbn Fâris çarpma/oyma ile kepçeleme için iki ayrı başlangıç kurar. Ok, at ve sofra kaplarını yan yana getirmek sözcük ailesinden doğan bir okuma imkânıdır; 100:2deki kadhın her bir nesneyi fiilen anlattığı anlamına gelmez.','MAQ-qdh|SIH-qdh',audience='advanced',term='قدح')
add(6,'MT02','method_note','100:1|100:6-8|100:10','Hayvanın biniciye bakan tarafı, koşusunun başarısına şahit oluşu ve yarışta göğsüyle öne geçmesi gerçekten eski sözlüklerde bulunur: Râgıbın ins maddesi, Lisânın at-koşu altpasajı ve Cevherînin sadr maddesi bunu doğrular. Bunların sûrenin insan, şehîd ve sudûr sözleriyle birlikte bir at bedeni oluşturması ise bağlamsal çeviriye eklenen proje düzenidir.','RAG-ans|LIS-shd|SIH-sdr|BASE100',audience='advanced')
add(7,'TF02','tafsir','100:1-8','Atın sahibine itaati karşısında insanın Rabbine nankörlüğü ana karşılaştırması Râzîde açıkça vardır: güçten düşen at sahibine uyarken insanın kendi efendisine itaatten kaçışını sorgular. Böylece temel ahlaki kıyas klasik bir öncüle dayanır. Bu kıyasın ayetlerdeki her kökü atın ayrı bir organına bağlayacak kadar genişletilmesi ise aynı ölçüde doğrudan aktarılmış değildir.','RAZ100-1',tradition='dirayet',role='early_attestation',source_ref='Râzî 100:1, en güçlü at yorumu altında atın efendiye itaati ve insanın Rabbine itaati karşılaştırması')
add(7,'HD01','hadith','100:1-8','Buhârî 2371de at, sahibinin amacı ve hakkı gözetmesine göre sevap, korunma yahut günah vesilesi olur. Allah yoluna bağlanan atın koşusu ve sudan içmesi de iyilik hesabına girer; gösteriş ve Müslümanlara karşı düşmanlık için tutulan at günah yüküdür. Bu sağlam tematik kayıt, koşan atı veya mal sevgisini niyetten bağımsız olarak tek ahlaki sınıfa sokmayı önler.','BUK2371',hadith_grade='sahih',origin='Ebû Hüreyre; Buhârî, no.2371',relation='thematic',note='Hadis sonunda 99:7–8 anılır; 100:1–8in doğrudan tefsiri olarak verilmez.')
nov(7,'N01','100:1-8','Atın insan sahibine itaati ile insanın Rabbine itaatsizliğini karşılaştırmak yeni değildir: Râzî bunu Adiyatın at yorumunda doğrudan kurar. Burada yenilik değerlendirmesi kıyasın kendisini değil, sözlük ailelerinden eklenen ayrıntıların hangi ölçüde o eski çekirdeği genişlettiğini ilgilendirir.','RAZ100-1','explicit','Fahreddin er-Râzî, 100:1, at tercihinin altındaki yorulan at–efendi/insan–Rab karşılaştırmasının tamamı')
nov(7,'N02','100:1-8|100:10','Biniciye dönük yan, koşunun lehindeki tanıklığı, sıkılan koşu ve göğüsle öne geliş eski sözlük malzemesidir. Bunları aynı sûredeki insan, şehîd, şedîd ve sudûr ile bütün bir beden karşılaştırmasına dönüştüren ayrıntılı düzen, incelenen pasajlarda aynı kuruluşla gösterilmedi. Ana itaat kıyasının klasik öncülüğü korunur; değerlendirme bu daha dar birleşime aittir.','RAG-ans|LIS-shd|SIH-sdr|MAQ-shdd|RAZ100-1','partial','Râgıb, إنس maddesinin tamamı; Lisânü’l-Arab, شهد maddesinde atın koşusunun şahitliği altpasajı; Cevherî, صدر maddesinin tamamı; İbn Fâris, شدّ maddesinin tamamı; Râzî, 100:1 at–efendi karşılaştırması')
add(8,'CQ01','cross_quran','100:1-8','38:31–33te atlar, hubbü’l-hayr ve Rabb zikri gerçekten yan yana gelir; 3:14 de atları sevilen dünya varlıkları arasında sayar. Fakat Süleymanın sevgisinin anlamı ihtilaflıdır: Taberî 38:32de zikirden uzaklaşmayı esas alır, Râzî ise sevginin ilahi emirden doğmasını tercih eder. Paralel iki ihtimali görünür kılar; hangisinin ayette zorunlu olduğu sonucunu tek başına vermez.','QURAN|TAB38-32|RAZ38-32',status='disputed',connection='strong',source_ref='Kurʾan 38:31–33 ve 3:14; Taberî 38:32; Râzî 38:32, عن ذكر ربي açıklamaları')
add(8,'TF03','tafsir','100:1-8','Süleyman kıssasındaki mesh için de önemli karşı görüş korunmalıdır. Taberî, atların ayak ve boyunlarını kesme nakillerini verir; fakat İbn Abbasa nispet edilen sevgiyle elle sıvazlamayı tercih eder. Râzî kesme anlatısına karşı çıkar ve inceleme/saygıyla dokunma açıklamasını savunur. Bu ihtilaf, Adiyat ile karşılaştırmanın hayvanların öldürülmesine zorunlu olarak dayanmasını engeller.','TAB38-33|RAZ38-33',tradition='dirayet',role='disagreement',relation='comparative',status='disputed',source_ref='Taberî 38:33 nakiller ve son tercih; Râzî 38:33 kesme görüşünün reddi ve alternatif mesh gerekçeleri')
nov(8,'N03','100:1-8','At-hubb-hayr-Rabb kümesi Kurʾanda vardır ve Süleyman kıssasının ahlaki yorumları klasik kaynaklarda tartışılmıştır. Bu kümenin Adiyatın insan–at karşılaştırmasına ayna yapılması burada bir sûreler arası proje sentezidir. İncelenen Adiyat ve seçili Sâd pasajları, bu bütün kuruluşun eski bir müfessirin aynen aktarılan açıklaması olduğunu göstermedi; kelime kümesinin kendisi yeni sayılmaz.','QURAN|TAB38-32|TAB38-33|RAZ38-32|RAZ38-33|RAZ100-1','partial','Taberî, 38:32 ve 38:33 dijital gövdelerinin tamamı; Râzî, 38:32 ve 38:33 dijital gövdelerinin tamamı ile 100:1 at–efendi kıyası; Kurʾan 38:31–33 ve 3:14')
add(11,'MT03','method_note','100:1|100:3','ʿA-d-w ailesindeki sınır aşma ile udvânın ahlaki saldırı anlamı, her koşuyu yahut her askerî hareketi haksız yapmaz. Mughîrâtın buradaki güçlü bağlamı baskın; eski hac yorumundaki karşılığı sabah hareketidir. Haritada reddedilmiş yağmur-erzak açıklaması bu fiilin doğrudan anlamı olarak geri alınamaz; ses yakınlığı ayrı kökleri eşitlemez.','MAQ-adw|MAQ-gwr|TAB100-3|LEDGER100',audience='advanced')
add(12,'HX02','historical_context','100:3','Şafak baskını yalnız edebî bir varsayım değildir. Müslim 382de Hz. Peygamberin sabah hareketinde ezan dinlediği, duyunca saldırıyı durdurduğu kaydedilir. Râzî de gece görünmezlik, gündüz hazırlık ihtimallerine karşı sabahın elverişliliğini açıklar. Hadis tarihsel uygulamayı aydınlatır; sûrenin tek tek uyuyan veya silahsız kişileri anlattığına dair ek bilgi vermez.','MUS382|RAZ100-3',historicity='established',note='Müslim 382 kaydı ve ayet yorumu farklı delil düzeyleridir.')
add(12,'MT04','method_note','100:3-5','Gece yaklaşma, hazırlıksız yakalanma ve kaçışın kapanması baskın sahnesini canlılaştıran yorum ayrıntılarıdır. Ayetler gece yürüyüşünün bütün aşamalarını, hedefteki herkesin silahsızlığını veya sivillerden oluşan bir köyü belirtmez. Sonradan gelen ahlaki ve kıyamet karşılaştırması bu tasviri kullanabilir; kaynakta açıkça yazılmış olay ayrıntısı diye sunmamalıdır.','QURAN|TAB100-5|RAZ100-3',priority='extended',audience='advanced')
add(13,'TF04','tafsir','100:4-5','Toz ana açıklamadır; bihînin işaret ettiği unsur ise ihtilaflıdır. Taberî tozun yükseldiği, lafızda adı geçmeyen yeri düşünür. Râzî yer, sabah vakti veya koşu ihtimallerini; Zemahşerî sonraki ayet için de toz ve hareketi kaydeder. Ses/çığlık açıklaması da eski tefsirde bulunur. Dolayısıyla her iki bihîyi aynı tek nesneye bağlamak zorunlu değildir.','TAB100-4|RAZ100-4|ZAM100-4|ZAM100-5',status='disputed',source_ref='Taberî 100:4 son tercih; Râzî 100:4 zamir seçenekleri; Keşşâf 100:4–5')
add(13,'SC02','source_note','100:4','Nakʿın ses anlamını açıklarken kullanılan nakʿ/laklaka sözü kaynaklar arasında farklı kişiye nispet edilir: Zemahşerî onu Peygamber sözü gibi verir; Kurtubî Halid için ağlayan kadınlarla ilgili Ömer sözü olarak açıklar. Bu incelemede bağımsız sahih bir Peygamber hadisi doğrulanmadı. İki aktarım aynı sağlam nebevî delil gibi birleştirilmez.','ZAM100-5|QURT100-4',status='disputed',priority='research',audience='research')
add(14,'TF05','tafsir','100:5','Klasik açıklamada cemʿ genellikle düşman topluluğu, kâfirler veya askerî taburdur; hac yorumunda Müzdelife/Jamʿ vardır. Sözlükteki cümâʿ, farklı toplulukların karışımını anlatabilir, fakat bu ayrı kullanım cemʿin burada zorunlu olarak karma sivil kalabalık olduğu sonucunu vermez. Baskının merkezine girme güçlü bağlamdır; hedefin toplumsal yapısı bundan daha belirli hale getirilemez.','TAB100-5|RAG-jma|SIH-jma',status='disputed',source_ref='Taberî 100:5, İkrime/Atâ/Dahhâk ve İbn Mesud nakilleri; Müfredât ve Sıhâh جمع maddeleri')
add(14,'QR01','qiraat','100:4-5','İbn Hâleveyhin şaz kıraatler kitabındaki Adiyat bölümünde, 100:4te aththarna şeklinde ث harfi şeddeli olarak Ebû Hayve/İbn Ebî Able; 100:5te şeddeli fawassatna Ali ve başka isimlerle kaydedilir. Bunlar hareketin yoğunlaştırılması ve ortaya girme ifadesinin tarihsel okuma alanını gösterir. Buradaki şaz sınıflaması o birincil koleksiyonun açık bölüm başlığına dayanır.','SHAD178|ZAM100-5',canonical='false',priority='research',audience='research',term='فأثّرن | فوسّطن',source_ref='İbn Hâleveyh, basılı s.178, Şevâzzü sûreti’l-Adiyat, 100:4–5 satırları; Keşşâf 100:5')
add(15,'CQ02','cross_quran','100:3-5|100:9-11','Sabah azabı 11:81, 15:83, 54:38 ve 37:177de; hızlı mezar çıkışı ise 70:43 ve 50:44te açık metinle desteklenir. Buna karşılık 17:64teki şeytanın süvarisi ve 8:60taki savunma hazırlığı farklı ahlaki bağlamlardır. Hepsini aynı atlı grubun tarihsel kimliği saymak yerine, ani gelişi ve insanın güvendiği düzenin çözülüşünü karşılaştırmak daha ölçülü bir delil kullanımıdır.','QURAN',connection='resonant',source_ref='Kurʾan 11:81;15:83;54:38;37:176–177;70:43;50:44;17:64;8:60')
nov(15,'N04','100:3-5|100:9-11','Sabah baskınını kabirlerin açılışı ve evrensel hesap için küçük bir prova gibi okumak yorumdur. Bikāî Adiyatı komşu Zilzalin yargı çerçevesine açıkça bağlar; Kurʾanda sabah azabı ve hızlı haşir malzemesi de vardır. Fakat incelenen ilgili pasajlar tozlu baskının bütün ayrıntılarını aynı kıyamet provasıyla eşleştirmez. Eski yargı çerçevesi, birleşimin kısmi öncülüdür.','BIQ100-1|BIQ100-9|QURAN','partial','Bikāî, 100:1 Zilzal bağlantısı ve 100:9 kabir/haşir açıklamasının tamamı; Râzî, 100:3 sabah gerekçeleri ve 100:9 diriliş açıklamasının tamamı; Kurʾan 37:177,11:81,15:83,54:38,70:43,50:44')
add(18,'TF06','tafsir','100:2','Toynak veya nalın taşa vurup ateş çıkarması güçlü klasik açıklamadır; maddi ayrıntı ise aynı biçimde anlatılmaz. İbn Kesîr nalı anarken Râzî, doğal toynak ile taşın kıvılcımını daha çarpıcı bulan görüşü kaydeder. Taberî savaş ateşi, sözle düşmanlık, hile ve yemek pişirme ateşi gibi başka açıklamaları da derler. Bunlar tek ve kesin bir eski nal teknolojisi tarihi oluşturmaz.','KAT100-2|RAZ100-2|TAB100-2',status='disputed',priority='extended',audience='advanced')
add(18,'SC03','source_note','100:2-3','Tercih aktarımında somut bir uyuşmazlık vardır: İbn Kesîr Taberîyi toynak kıvılcımı açıklamasını seçmiş gibi özetler; incelenen Taberî 100:2 sonuç paragrafı ise münhasır bir belirleme bulunmadığından farklı ateş çıkarma türlerini birlikte kapsar. 100:3te de sabah hareketini tek askerî olaya daraltmaz. Bu iki yazarın tercihleri aynı kesin hüküm diye nakledilemez.','KAT100-2|TAB100-2|TAB100-3',status='disputed',priority='research',audience='research',source_ref='İbn Kesîr 100:2 son cümle ile Taberî 100:2 ve 100:3 son tercih paragrafları doğrudan karşılaştırıldı.')
nov(19,'N05','100:1-2','Soluk sesinden yanmış renk ve küle açılan kapı, bütünüyle yeni bir sözlük keşfi değildir. İbn Fâris ضبح için ses ile ateşin değiştirdiği rengi ayrı başlangıçlar olarak kaydeder; Kurtubî de 100:1 açıklamasında yanma ve kül kullanımlarını anmıştır. Projenin bu malzemeyi hemen sonraki kıvılcıma bağlaması kısmi bir geliştirmedir; iki kökeni aynı zorunlu anlam yapmaz.','MAQ-dbh|QURT100-1','partial','İbn Fâris, ضبح maddesinin tamamı; Kurtubî, 100:1 gövdesinin tamamı, ses/yanma/kül ve şiir altpasajları; Râzî, 100:2 ateş çıkarma açıklamalarının tamamı')
add(19,'MT05','method_note','100:1|100:9','Kurtubînin dabh açıklamasında mezar sesi/kuşu hakkında eski şiir de bulunur. Bu, sözün edebî kullanım tarihine tanıktır; ölenin mezarda kuşa dönüşmesine ilişkin bir inancı ayetin öğretisi yapmaz. Aynı şekilde ses köküyle yanma renginin ayrı başlangıçlar olduğunu gösteren Mekāyîs ayrımı, metindeki peş peşe imgelemden daha sınırlayıcı bir filolojik delildir.','QURT100-1|MAQ-dbh',role='rejected_candidate',connection='rejected',priority='research',audience='research')
add(20,'SM03','semantic_history','100:2|100:8','Hübâhib ateşinin cimrilikle bağlantısı klasik kaynaklarda vardır. Râzî ve Cevherî, misafir görmesin diye küçük ateş yakan cimri kişi açıklamasını; atın kısa kıvılcımı için adın kullanımını kaydeder. Bu açıklama eski bir adlandırma hikâyesidir, bağımsız kişi biyografisi değildir. İbn Fârisin h-b-b içindeki sevgi, tane ve küçüklüğü ayrı kökenlerde ele alması da bu adın hubb ile tek kök anlamına indirgenmesini sınırlar.','RAZ100-2|SIH-hbb|MAQ-hbb',priority='extended',audience='advanced',historicity='uncertain')
nov(20,'N06','100:2|100:8','Kısa, faydasız kıvılcımı cimri sevgiyle karşılaştırmanın önemli eski malzemesi vardır: Râzî Adiyat 100:2de Hübâhibi cimrilik ve yararsız ateş üzerinden açıklar. Bu nedenle cimri-ateş bağlantısı yokmuş gibi bir yenilik iddiası kurulamaz. Sürekli sabah ışığı ve içteki sevgiyle oluşturulan daha geniş karşıtlık ise incelenen pasajlarda bu bütün düzenle gösterilmedi.','RAZ100-2|SIH-hbb|MAQ-hbb','partial','Râzî, 100:2 Hübâhib/cimri ve ateş yorumlarının tamamı; Cevherî, حبب maddesinin tamamı; İbn Fâris, حبّ maddesinin tamamı; Zemahşerî, 100:2 kısa ateş açıklamasının tamamı')
add(21,'TF07','tafsir','100:2|100:5-6','Düşüncenin ateş çakması da eski bir tefsir malzemesidir. Râzî 100:2de fikirle hile üretmeyi ve başarı için çakmağı kaydeder. Beyzâvî 100:5te düşüncelerin bilgi ışığını yakması ve nefislerin yükselişi şeklinde işarî bir okuma verir. Bikāî 100:6da koşan düşüncelerin iyi anlam veya kötü aldatma doğurmasını anlatır. Bunlar literal at sahnesiyle aynı delil sınıfında değildir.','RAZ100-2|BAY100-5|BIQ100-6',tradition='dirayet',role='early_attestation',status='reported',audience='advanced')
nov(21,'N07','100:2|100:5-8','Ateş–düşünce benzerliği ve düşüncenin iyi yahut kötüye yönelmesi klasik öncüllere sahiptir; yokluk iddiası kurulamaz. Projenin insanın görmesi, düşüncede isabet/hata, sürekli aydınlık ve cimri sevgiyle ördüğü birleşik ağ bu öncülleri genişletir. Dolayısıyla özgünlük, zihinde ateş yakma imgesinde değil, bu sözlük ve sûre parçalarının belirli düzeninde aranabilir.','RAZ100-2|BAY100-5|BIQ100-6|MAQ-ans','partial','Râzî, 100:2 savaş/dil/hile/fikir/başarılı çakmak açıklamalarının tamamı; Beyzâvî, 100:5 nefis ve ilim nuru altpasajı; Bikāî, 100:6 fikirlerin koşup anlam/aldatma yakması altpasajı; İbn Fâris, أنس maddesinin tamamı')
add(22,'CQ03','cross_quran','100:2|100:9-11','36:78–80de ilk yaratılış, çürümüş kemiğin diriltilmesi ve yeşil ağaçtan ateş açık bir delil dizisidir. 56:71–74 ise ateşi kimin yarattığını sorar, onu hatırlatma ve yarar sayar, Rabb tesbihine bağlar. Bu bağlamlar ateşten dirilişe geçişi güçlü biçimde destekler; at kıvılcımının sûrede doğrudan bu iki pasajın tamamını anlattığı sonucunu gerektirmez.','QURAN|RAG-wry',connection='strong',source_ref='Kurʾan 36:78–80 ve 56:71–74; Müfredât و ر ي maddesi ateşin gizliliği ve 56:71')
add(22,'CQ04','cross_quran','100:2|100:6|100:11','Mûsânın 20:10, 27:7 ve 28:29daki ateşi görmesi, yol bilgisi veya ısınma umuduyla habere yönelmesidir. Bu, insanın dış işaretten bilgi aramasına uygun bir paraleldir. Habîr sözünün ilahi bilgiye uygulanması ise bundan farklıdır: Allahın önceden bilmediğini deneyerek öğrenmesi anlamına taşınamaz. Haber kelimesi bağlantıyı kurar; iki öznenin bilgi biçimini eşitlemez.','QURAN|RAG-khbr|RAZ100-11',connection='resonant',audience='advanced')
nov(22,'N08','100:2|100:6|100:11','Mûsâdaki ateş–görme–haber dizisi Kurʾan metninde vardır; Adiyattaki insan ve Habîr sözleriyle bir epistemik hat kurmak projenin çapraz yorumudur. İncelenen Adiyat 100:2 ve 100:11 pasajlarında bu bütün Mûsâ hattı açık kurulmuş olarak bulunmadı. Bu sınırlı kontrol, bütün klasik literatürde yokluk anlamına gelmez; ilahi bilgiye insanî öğrenme yüklenmemesi ayrıca korunur.','QURAN|RAZ100-2|RAZ100-11|RAG-khbr|MAQ-ans','building_blocks_only','Râzî, 100:2 ateş/hile/fikir açıklamalarının tamamı ve 100:11 Allahın deneyle bilgi edinmediği altpasaj; İbn Kesîr, 100:2 ve 100:11 gövdelerinin tamamı; Râgıb, خبر maddesinin tamamı; İbn Fâris, أنس maddesinin tamamı; Kurʾan 20:10,27:7,28:29')

add(25,'SM04','semantic_history','100:4|100:9','İbn Fâris th-w-r için yayılma/yükselme/heyecanı ve boğa adını inceler; Râgıb da bulut kaldırma ile toprağı sürmeyi aynı maddede kaydeder. Ancak kan davası çağrışımındaki th-ʾ-r ayrı bir köktür; baʿtharanın dört harfli b-ʿ-th-r kökü de th-w-r ile aynı değildir. Toprak ve toz üzerinden kurulan benzerlik, kök kimliği iddiasından ayrı tutulmalıdır.','MAQ-twr|RAG-twr',term='ثور | ثأر | بعثر',audience='advanced')
add(26,'TF08','tafsir','100:9','Kabirlerin içindekiler klasik temel okumada ölülerdir. Taberî çıkartılma ve açığa çıkarılmayı; Râzî ve Bikāî mā zamirini dirilmeden önceki cansız halde oluşlarıyla açıklar. Son ayette hum gelmesi yeniden insan olarak muhatap alınmayla ilişkilendirilir. Mā kelimesi burada zorunlu olarak eşya, servet veya kasa içeriği demek değildir; bunlar yorumun ek benzerlikleridir.','TAB100-9|RAZ100-9|BIQ100-9|BAY100-11',role='anchor',source_ref='Taberî 100:9; Râzî 100:9 mā açıklaması; Bikāî 100:9; Beyzâvî 100:11 mā/hum karşılaştırması')
add(26,'QR02','qiraat','100:9','İbn Hâleveyh, Adiyatın şaz okumaları arasında İbn Mesuda nispetle bahatha ve Esved b.Yezide nispetle de aynı fiili kaydeder; Taberî de İbn Mesudun mushafına nispet edilen bahatha naklini verir. Toprağı arama/açma fiili, baʿtharanın anlam çevresini aydınlatır. Mushafa nispet edilen nakil, elde bir sahabî mushafının doğrudan incelendiği anlamına gelmez.','SHAD178|TAB100-9',canonical='false',priority='research',audience='research',term='بحث',source_ref='İbn Hâleveyh s.178, Adiyat 100:9 iki bahatha kaydı; Taberî 100:9 mushaf nispeti')
nov(26,'N09','100:4|100:9','Atın toprağı kabartmasından kabirlerin altüst edilmesine geçişin eski malzemesi açıktır. Râgıb baʿthara maddesinde toprağı çevirmeyi anlatır ve baʿth ile uthîranın birleşimini mümkün gören bir etimoloji önerir. Bu, projenin thawr çağrışımına bir öncüldür; ayrı kökleri aynı kök haline getirmez. Bütün at–tarla–kabir sahnesinin birlikte kuruluşu ise incelenen pasajlarda aynı biçimde aktarılmaz.','RAG-bathr|MAQ-twr|TAB100-9|RAZ100-9','partial','Râgıb, بعثر maddesinin tamamı, 82:4 ve baʿth/uthîra birleşim önerisi; İbn Fâris, ثور maddesinin tamamı; Taberî, 100:9 gövdesinin tamamı; Râzî, 100:9 gövdesinin tamamı')
add(27,'SM05','semantic_history','100:2|100:9','Râgıb w-r-y maddesinde ateşi, çakan taşın arkasından veya içinde saklı yerden belirme üzerinden açıklar; örtme ve gömme kullanımlarını da verir. İbn Fâris ise bu ailenin kelimelerinin tek bir kıyasa indirgenmediğini söyler. Temel metnin saklama–ateş ağını besleyen eski bir açıklama vardır; fakat bütün aileye tek zorunlu gizlilik özü yüklemek sözlükler arası ihtilafı siler.','RAG-wry|MAQ-wry',status='disputed',audience='advanced',term='وري')
add(27,'TF09','tafsir','100:9','Temel metindeki örtülü insan halleri ifadesi, Râgıbın q-b-r maddesinde yalnız genel bir sözlük benzetmesi değildir: 100:9 için aktardığı alternatif mecazi tefsirdir. Aynı yerde gerçek ölülerin kabirlerden çıkarılması da korunur. Bu ayrım önemlidir; yaşayanın saklı durumunun açılması ile gerçek diriliş tek ve tartışmasız literal karşılık gibi kaynaştırılmamalıdır.','RAG-qbr|TAB100-9',tradition='dirayet',role='semantic_range',status='reported',source_ref='Müfredât قبر maddesinin tamamı; 100:9da kabirler=örtülü insan halleri ve cehalet-ölüm alternatifleri')
nov(27,'N10','100:2|100:9-10','Gizli ateş ile örtülü insan hallerini yan yana düşünmenin iki açık eski dayanağı vardır: Râgıbın w-r-y ve q-b-r maddeleri. Proje bunları kıvılcım, gömme, mezarın açılması ve içtekinin çıkarılması üzerinden aynı sûre ağına yerleştirir. İncelenen maddeler ve Adiyat pasajları bu bütün ağı aynı kuruluşla sunmaz; eski gizlilik açıklamalarının öncülüğü ise korunmalıdır.','RAG-wry|RAG-qbr|MAQ-wry|TAB100-9','partial','Râgıb, و ر ي ve قبر maddelerinin tamamı; İbn Fâris, و ر ي maddesinin tamamı; Taberî, 100:9 gövdesinin tamamı; İbn Kesîr, 100:2 ve 100:9 gövdelerinin tamamı')
add(28,'SC04','source_note','100:10','Tahsilin madenden altın ve gümüş ayırmadan geldiği açıklama kesin tarihsel köken bilgisi değildir. İbn Fâris bunu bazı dilcilerin iddiası olarak aktarır ve doğruysa kendi kıyasına uyacağını söyler. Cevherî, maden toprağını işleyen kadın anlamındaki muhassılayı doğrular. Böylece işçilik imgesi kaynaklıdır; temel metnin köken ifadesi kaynakta bulunan şartlılıkla okunmalıdır.','MAQ-hsl|SIH-hsl',audience='advanced',source_ref='Maqayis حصل, زعم ناس... فإن كان كذا altpasajı; Sıhâh حصل maddesinin tamamı')
add(29,'CQ05','cross_quran','100:4|100:9','82:4–5 kabirlerin altüst oluşunu ardından kişinin yaptıklarını bilmesine; 99:2 ve 84:4 toprağın içindekini çıkarmasına; 20:55 insana toprağa dönüş ve yeniden çıkarılışa bağlar. 2:71deki sürülmeyen inek ve 30:9daki toprağı işleyen eski toplumlar ise farklı bağlamlardır. Bunlar ortak toprak/çıkarma imgesini destekler; sûrede tarla ekiminin literal olarak bulunduğunu göstermez.','QURAN',connection='strong',source_ref='Kurʾan 82:4–5;99:2;84:4;20:55;22:7;54:7;30:9;2:71')
add(32,'TF10','tafsir','100:10','Kabukla özün, altınla cevherin ve buğdayla samanın ayrılması 100:10 için doğrudan eski bir açıklamadır: Râgıb bu ayeti h-s-l maddesinde böyle açıklar. Zemahşerî ve Râzî elek ve iyi-kötü ayrımı verir; Taberî de göğüslerdeki hayır ve şerrin belirginleşmesini anlatır. Dolayısıyla içten çıkan yalnız temiz altın yahut yalnız kötü servet değildir; her iki nitelik ayrılır.','RAG-hsl|ZAM100-10|RAZ100-10|TAB100-10',tradition='dirayet',role='early_attestation',source_ref='Müfredât حصل maddesi, 100:10 örneği; Keşşâf ve Râzî 100:10 elek/ayırt etme; Taberî 100:10')
add(32,'MT06','method_note','100:10','Hussila, edilgen ve tefʿîl kalıbındadır; ayıklama, görünür kılma ve toplama alanı vardır. Fakat kalıp tek başına yavaş, aşamalı veya yorucu bir süreci zorunlu kılmaz. Bikāî bu edilgen kuruluşu ortaya çıkarmanın kolaylığı yönünde okur. Adım adım maden işçiliği imgesi bu nedenle doğrudan bir gramer sonucu değil, sözcük ailesinden geliştirilen tasvirdir.','BIQ100-10|MAQ-hsl|QURAN',relation='grammatical',audience='advanced')
add(32,'QR03','qiraat','100:10','Kurtubî hafif ve etken hasala okumasını Ubeyd b.Umeyr, Saîd b.Cübeyr, Yahyâ b.Yaʿmer ve Nasr b.Âsıma nispet eder; anlamını belirip ortaya çıkmak diye açıklar. İbn Hâleveyhin Adiyat şazları bölümünde de hafif hasala ve farklı seslendirmeler kaydedilir. Bu tarihsel okuma alanı, standart edilgen hussila üzerine kurulmuş işçilik yorumunun tek mümkün kuruluş olmadığını gösterir.','QURT100-10|SHAD178',canonical='false',priority='research',audience='research',term='حصل',source_ref='Kurtubî 100:10 hafif/etken okuma paragrafı; İbn Hâleveyh s.178, Adiyat 100:10 kayıtları')
nov(32,'N11','100:10','Altın-maden, buğday-saman ve kabuk-öz benzetmeleri bu ayet için yeni değildir. Râgıb bunları doğrudan 100:10 açıklamasına yerleştirir; Zemahşerî ve Râzî de elek/ayırt etme malzemesini verir. Projenin bu işlem sahnesini sûre boyunca başka köklerin yağma, sevgi ve toplama imgeleriyle birleştirmesi ayrıca değerlendirilebilir; ayıklama imgesinin kendisine yenilik atfedilemez.','RAG-hsl|ZAM100-10|RAZ100-10','explicit','Râgıb, حصل maddesinin tamamı, 100:10 altında kabuk/öz–altın/cevher–buğday/saman–hesap kalanı açıklaması; Zemahşerî, 100:10 gövdesinin tamamı; Râzî, 100:10 gövdesinin tamamı')
add(33,'SM06','semantic_history','100:8|100:10','Sevgi ile kalp tanesinin bağlantısında iki klasik dil yaklaşımı ayrılmalıdır. Râgıb sevgiyi kalbin tanesine ulaşma açıklamasıyla ilişkilendirir; İbn Fâris bağlanma/sevgi, tane ve küçüklük için üç ayrı başlangıç ayırır. Bu yüzden hubb–habb–kalbin özü hattının eski öncülü vardır, ama tek tartışmasız etimoloji olduğu söylenemez. Ayetteki hubbın bağlamsal anlamı sevgidir.','RAG-hbb|MAQ-hbb',status='disputed',audience='advanced',term='حبّ')
nov(33,'N12','100:8|100:10','Sevgiyi kalp tanesiyle ilişkilendirmek eski bir açıklamadır; Râgıb h-b-b maddesinde bunu açık kurar. Yine onun h-s-l maddesi kabuk-öz ve tahıl-saman ayrımını ayete uygular. Projenin sevginin tohumu, göğüs haznesi, harman artığı ve mal yığma üzerinden kurduğu bütün zincir bu iki öncülü genişletir; öncüller yokmuş gibi bir özgünlük hükmü verilemez.','RAG-hbb|RAG-hsl|SIH-hsl|MAQ-hbb','partial','Râgıb, حبب maddesinin tamamı, kalp tanesinden sevgi açıklaması; Râgıb, حصل maddesinin tamamı, 100:10 ayrıştırma örnekleri; Cevherî, حصل maddesinin tamamı, kursak/harman artığı; İbn Fâris, حبّ maddesinin tamamı')
add(34,'HD02','hadith','100:8|100:10-11','Müslim 2564cde Allahın insanın biçimine ve malına değil kalbine ve amellerine baktığı bildirilir. Bu sahih tematik delil, servetten göğüsteki yönelişe geçişi destekler: dış zenginlik kendi başına değerlendirme ölçüsü değildir. Hadis Adiyatı doğrudan açıklayan bir rivayet olarak değil, sûrenin iç-dış ve niyet-amel vurgusunu tamamlayan kayıt olarak kullanılır.','MUS2564c',hadith_grade='sahih',origin='Ebû Hüreyre; Müslim, no.2564c',relation='thematic')
add(34,'HD03','hadith','100:10-11','Müslim 127ada kişinin içinden geçen, söylemediği veya yapmadığı vesveselerin bağışlandığı bildirilir. Bu sahih kayıt, içtekinin bilinmesiyle her gelip geçen düşüncenin cezalandırılmasını eşitlemeye karşı bir sınırdır. Kalbin yerleşmiş niyeti ve amelle ilişkisi önemini korur; ayet yalnız içten geçmekle otomatik ceza veren bir hükme dönüştürülmez.','MUS127a',hadith_grade='sahih',origin='Ebû Hüreyre; Müslim, no.127a',role='constraint',relation='thematic')
nov(34,'N13','100:9-11','Kabir içi ile göğüs içinin birlikte açılması ayetlerin kendi dizisidir; Râgıb örtülü insan hallerinin kabir gibi yorumlanmasını da aktarır. Râzî, göğüste niyetlerin bulunmasını ve uzuvların onlara uymasını açıklar. İç hazne, çekirdek ve gömülü cevher üzerinden geliştirilen bütün benzerlik bu eski çekirdeği genişletir. Gizli içeriğin yargıda belirginleşmesi fikrinin kendisi yeni değildir.','RAG-qbr|RAG-hsl|RAZ100-10|RAZ100-11|QURAN','partial','Râgıb, قبر ve حصل maddelerinin tamamı; Râzî, 100:10 ve 100:11 gövdelerinin tamamı, göğüs/kalp/niyet açıklamaları; Kurʾan 100:9–11')
add(35,'CQ06','cross_quran','100:10-11','3:153–154 savaş kederi ve insanların sakladığı düşünceler içinde göğüslerin sınanıp kalplerin arındırılmasını söyler; 3:29 gizli/açık her içeriğin bilindiğini, 47:29 gizli kinlerin çıkarılmasını, 86:9 sırların sınanmasını destekler. Bu ayetler iç-dış karşılaştırması için güçlüdür. Yaşarken sınanma sahnesi ile Adiyattaki diriliş aynı tarihsel olay değildir; açıklama ortak içeriğin görünür oluşundadır.','QURAN',connection='strong',source_ref='Kurʾan 3:153–154;3:29;47:29;86:9;99:7–8')
add(38,'SM07','semantic_history','100:6|100:11','Rabbın sahiplik, bakım ve yetiştirme anlamları eski dil açıklamasında birlikte bulunur. İbn Fâris bakım/onarım, süreklilik ve bir araya toplama başlangıçlarını tartışır; Râgıb besleyen bulutu da anarak yetiştirme yönünü açıklar. Bu aile alanı nimetin kaynağıyla nankörlüğü karşılaştırmayı besler. Sûredeki Rabb ise ilahi hitaptır; her su kabı veya ok kılıfı anlamı onun bağlamsal tanımı olmaz.','MAQ-rbb|RAG-rbb',audience='advanced',term='ربّ')
add(39,'TF11','tafsir','100:6','Kenûdun nimet inkârı açıklaması klasik ana anlamdır. Taberî kısır/ürünsüz toprağı ve Hasan el-Basrînin felaketleri sayıp nimetleri unutan insan açıklamasını aktarır; Kurtubî teşekkür bağını kesme benzetmesini verir. İbn Fâris de kesme kökeninden nankörlük ve bitki vermeyen toprak kullanımını açıklar. İnsan–toprak ve nimet–bağ ilişkisi böylece erken ve sözlüksel öncüllere dayanır.','TAB100-6|QURT100-6|MAQ-knd',role='early_attestation',source_ref='Taberî 100:6 erken açıklamalar; Kurtubî 100:6 teşekkür/bağ yorumu; Maqayis كند maddesinin tamamı')
add(39,'AS02','asbab','100:6','İnsan sözünün belirli bir kişi hakkında indiğine dair nakiller de uyuşmaz: Râzî İbn Abbasa nispetle Kurt b.Abdullah b.Amr b.Nevfel adını; Kurtubî Dahhâka nispetle Velîd b.Muğîreyi kaydeder. İsnadları burada bağımsız derecelendirilmedi. Bu adlandırmalar ayetin insan nankörlüğüne dair daha geniş öğüdünü tek bir kesin biyografik kişiye kapatmak için kullanılamaz.','RAZ100-6|QURT100-6',status='disputed',historicity='uncertain',hadith_grade='not_assessed',priority='research',audience='research',source_ref='Râzî 100:6 belirli kişi nakli; Kurtubî 100:6 Dahhâk/Velîd nakli')
nov(39,'N14','100:6|100:11','Nankörlüğü nimete cevap bağının kesilmesi ve ürün vermeyen toprakla anlatmak açık klasik malzemedir; İbn Fâris, Taberî ve Kurtubî bunu doğrular. Projenin ip, su, bulut ve Rabb kelimesinin diğer aile imgelerini birleştirerek iki yönlü bağ kurması bu çekirdeği genişletir. Allahın nimet vermesi insandan bir ihtiyaç karşılığı beklemesi gibi okunmamalıdır.','MAQ-knd|TAB100-6|QURT100-6|MAQ-rbb|RAG-rbb','partial','İbn Fâris, كند ve ربّ maddelerinin tamamı; Taberî, 100:6 gövdesinin tamamı, çorak toprak/Hasan açıklamaları; Kurtubî, 100:6 gövdesinin tamamı, teşekkür bağını kesme altpasajı; Râgıb, ربّ maddesinin tamamı')
add(40,'SM08','semantic_history','100:6|100:11','Habîrin çiftçi ve sulak toprakla sözlüksel yakınlığı, ilahi sıfatın aynı anlamda kullanıldığını göstermez. İbn Fâris kh-b-r için bilgi ile yumuşak/sulu toprağı iki ayrı başlangıç sayar; paylaşılan et anlamındaki khubrayı da bu iki başlangıç dışında değerlendirir. 100:11deki Habîr, dış ve iç halleri bilen Rabdir. Tarla ve sofra katmanı bunun çağrışımı olabilir, Allahı çiftçi diye tanımlayan bir çeviri değildir.','MAQ-khbr|RAG-khbr|TAB100-11',audience='advanced',term='خبر')
nov(40,'N15','100:4|100:6|100:11','Çorak insan imgesinin Taberîde; besleyen bulutun Râgıbda; su birikmesi ve iyi toprağın klasik sözlük ve Kurtubîde öncülleri vardır. Proje bunları bulut–havuz–tohum–tarla–habîr ağında birlikte düzenler. İncelenen ilgili Adiyat pasajları ve maddeler bu bütün tarım sahnesini aynen kurmaz. Habîrin bilgi ve toprak başlangıçları ayrı olduğundan bütün ağ bağlamsal anlam yerine yorum düzeyinde kalır.','TAB100-6|RAG-rbb|MAQ-nqa|QURT100-4|MAQ-khbr|QURAN','partial','Taberî, 100:6 çorak toprak altpasajı; Kurtubî, 100:4 gövdesinin tamamı, su/iyi killi toprak açıklamaları; Râgıb, ربّ maddesinin tamamı; İbn Fâris, نقع ve خبر maddelerinin tamamı; Kurʾan 7:57–58 ve 30:48')
add(41,'TF12','tafsir','100:7','Şehîdin öznesi önemli bir ihtilaftır. Taberî Allahı tercih eder; İbn Kesîr Allah yorumu yanında Muhammed b.Kâʿb el-Kurazîye nispet edilen insanın söz ve haliyle kendi nankörlüğüne şahitliği yorumunu verir. Râzî yakın öncül olarak Rabb ile sonraki ayetin insan zamiri arasında iki gramer gerekçesini tartışır. Temel metnin insan tanık çizgisi mümkün bir okumadır, tek yerleşik sonuç değildir.','TAB100-7|KAT100-7|RAZ100-7',role='disagreement',status='disputed',source_ref='Taberî 100:7 tercih; İbn Kesîr 100:7 iki özne ve 9:17; Râzî 100:7 zamir gerekçeleri')
add(42,'CQ07','cross_quran','100:6|100:11','7:58in verimli/verimsiz ülke ve şükür bağlantısı güçlü bir anlam paralelidir; ancak oradaki nakid n-k-d, buradaki kenûd k-n-d kökündendir, aynı kök değildir. 14:34 nimet sayamama ve insanın inkârını, 17:67 kurtulunca yüz çevirmeyi, 96:6–7 kendini yeterli görmeyi doğrudan birleştirir. Bu ortak ahlak alanı, sûrenin her aile sözcüğünü aynı türetime çevirmez.','QURAN|MAQ-knd',connection='strong',audience='advanced',source_ref='Kurʾan 7:57–58;14:34;17:67;96:6–7;82:6;76:3; Mekāyîs كند')
add(45,'SC05','source_note','100:8','Temel metindeki mal çok ve temiz kaynaktan olmadıkça hayr denmez hükmü, bütün kaynakların ortak bağlamsal kuralı değildir. Râgıb bunu bazı âlimlerin açıklaması olarak ve özellikle vasiyet bağlamıyla aktarır. Taberî 100:8de ise insanın helal-haram ayrımı yapmadan sevdiği malı hayr diye adlandırabildiğini açıklar. Dolayısıyla ayetin kınadığı mal sevgisi mutlaka temiz/helal servetle sınırlandırılamaz.','RAG-khyr|TAB100-8|QURAN',status='disputed',audience='advanced',source_ref='Müfredât خير, قال بعض العلماء ve 2:180/100:8 altpasajları; Taberî 100:8, İbn Zeyd nakli ve son açıklama')
add(46,'SM09','semantic_history','100:8','Sevginin bağlanma ve ayrılmama yönü Mekāyîsin birinci h-b-b başlangıcında açıklanır; Cevherî ve Râgıb da devenin çökmek/durmakta kalması türünden aile kullanımlarını kaydeder. Bu dilsel aralık sevginin insanı tutmasını düşündürebilir. Ayetteki hubbı gerçekten duran deve veya içilen su diye çevirmek ise başka kullanımları bağlam yerine geçirmek olur.','MAQ-hbb|SIH-hbb|RAG-hbb',audience='advanced',term='حبّ')
add(47,'TF13','tafsir','100:8','Şedîd için cimrilik güçlü eski açıklamadır; fakat tek yorum değildir. Taberî yoğun sevgi, mal için gayret veya cimrilik seçeneklerini; İbn Kesîr yoğun sevgi ile cimriliğin birlikte geçerli olabileceğini kaydeder. Bu nedenle sıkılmış kese imgesi ayetin anlam alanını daraltmadan kullanılmalı; kelimenin bütün sertliğini yalnız ekonomik cimriliğe eşitlememelidir.','TAB100-8|KAT100-8|RAZ100-8',status='disputed',source_ref='Taberî 100:8 Basra/Kûfe açıklamaları; İbn Kesîr 100:8 iki geçerli anlam; Râzî 100:8')
add(47,'HD04','hadith','100:6','Yalnız yiyen, kölesini döven ve yardımını esirgeyen kenûd tarifi, Ebû Ümâme üzerinden Hz. Peygambere nispetle nakledilir; fakat İbn Kesîr Caʿfer b.Zübeyri metrûk sayar ve bu yolu zayıf diye niteler. Süyûtî de zayıf isnadı belirtir. Dolayısıyla temel sözlük aktarımı sahih bir nebevî tefsir olarak sunulamaz; burada zayıf doğrudan tefsir rivayeti olarak tutulur.','KAT100-6|SUY100-6|TAB100-6',role='clarification',relation='direct_hadith_tafsir',status='weak',hadith_grade='daif',origin='Ebû Ümâme; merfû yol: Caʿfer b.Zübeyr–Kāsım–Ebû Ümâme',source_ref='İbn Kesîr 100:6, جعفر بن الزبير - وهو متروك - فهذا إسناد ضعيف; Süyûtî 100:6 بسند ضعيف')
add(47,'SC06','source_note','100:6','Üçlü tarifin ayrı bir Ebû Ümâme sözü olarak, yalnız konaklayan ifadesiyle mevkuf varyantı da Taberîde bulunur; bu yol burada ayrıca derecelendirilmedi. Lisânü’l-Arabda İbn Sîde, üçlü tarifin dilde kökenini bilmediğini ve li-rabbihî ifadesiyle uyuşmadığını söyler. Böylece hadis sıhhati, mevkuf öğüt ve sözlük anlamı üç ayrı mesele olarak korunur; tekrarlanan üçlü tek rivayet kümesi sayılır.','TAB100-6|LIS-knd|SUY100-6',priority='research',audience='research',source_ref='Taberî 100:6, Harîz b.Osman–Hamza b.Hânî–Ebû Ümâme mevkuf yolu; Lisân كند, İbn Sîde itirazı')
nov(47,'N16','100:5-10','Toplama ailesindeki yumruk ve bukağı eski sözlüktedir; Râgıbın cemʿ maddesi mal yığmayı, evrensel toplanmayı, yumruk ve zinciri zaten yan yana verir. Şedîdin cimri yorumu da klasiktir. Projenin kapalı elin malı tuttuğu, sonunda göğsün içeriğinin toplatıldığı tersine dönüşü bu malzemeyi sûre içinde yeniden düzenler. Yeni sayılan yalnız bu belirli birleşimdir.','RAG-jma|SIH-jma|TAB100-8|MAQ-shdd|RAG-hsl','partial','Râgıb ve Cevherî, جمع maddelerinin tamamı; Taberî, 100:8 gövdesinin tamamı; İbn Fâris, شدّ maddesinin tamamı; Râgıb, حصل maddesinin tamamı, 100:10')
add(48,'HX03','historical_context','100:2|100:5-8','Kazan, kepçe, kap, kura oku ve okları toplayan kılıf dil tarihi bakımından gerçektir: Cevherî q-d-h maddesinde kap/kepçe/okları; j-m-ʿ maddesinde büyük kazanı; İbn Fâris r-b-b maddesinde ok kılıfını kaydeder. Aynı harf ailesindeki bu nesneler bir sosyal sahne kurmaya elverişlidir. Fakat hepsinin Adiyatın doğrudan anlattığı aynı yemek törenine ait olduğu bağımsız tarihsel veri değildir.','SIH-qdh|SIH-jma|MAQ-rbb|MAQ-nqa',historicity='uncertain',priority='extended',audience='advanced')
add(48,'MT07','method_note','100:2|100:5-8','Meysire ait kura oklarının et paylaştırmada kullanılması sözlükteki tarihsel nesne alanını açıklar; onu Kurʾanın önerdiği yardımlaşma usulü yapmaz. 5:90 meysiri kaçınılması gereken işler arasında sayar. Q-d-h içinde çarpma ve kepçelemenin Mekāyîste ayrı başlangıçları bulunması da bütün sofra araçlarının ateş çakmanın aynı bağlamsal anlamı olmadığını gösterir.','QURAN|MAQ-qdh|MAQ-rbb|SIH-qdh',audience='advanced')
nov(48,'N17','100:2|100:4-8','Büyük kazan, kepçe, kap, oklar ve yolcu yemeği eski sözlük malzemesidir; yalnız yiyen kenûdun sosyal eleştirisi de eski fakat isnadı zayıf merfû rivayet ve mevkuf öğütlerde vardır. Bunların bütün sûre köklerinden ortak bir sofra kuracak şekilde birleştirilmesi, incelenen pasajlarda doğrudan aynı tefsir olarak gösterilmedi. Öncüller korunur; geniş sofra düzeni proje sentezidir.','SIH-jma|RAG-jma|SIH-qdh|MAQ-qdh|MAQ-rbb|MAQ-nqa|KAT100-6|TAB100-6','building_blocks_only','Cevherî, جمع ve قدح maddelerinin tamamı; Râgıb, جمع maddesinin tamamı; İbn Fâris, قدح/ربّ/نقع maddelerinin tamamı; İbn Kesîr ve Taberî, 100:6 gövdelerinin tamamı, üçlü merfû ve mevkuf tarifler')
add(49,'TF14','tafsir','100:10-11','Malı toplayanın içinin toplanması etkili bir karşıtlıktır; ayetin mahkeme alanı bundan daha geniştir. Taberî ve Râzî iyi-kötü içeriğin ayrılmasını; Beyzâvî göğsün amellerin başlangıcı olmasını; İbn Kesîr saklı sırların ortaya çıkmasını açıklar. Böylece hesap yalnız servet biriktirme suçuna veya sadece ekonomik bilgiye indirgenmez.','TAB100-10|RAZ100-10|BAY100-10|KAT100-10',tradition='dirayet',role='constraint')
add(50,'HD05','hadith','100:8-10','Buhârî 6436da iki vadi malı bulunan insanın üçüncüyü istediği, karnını ancak toprağın doldurduğu anlatılır; tövbenin kabulü de hemen eklenir. Bu sahih tematik kayıt servet arzusunun doymazlığıyla ölümlülüğü karşılaştırır. Toprak mecazı Adiyatın toz ve kabirini düşündürebilir; hadisin doğrudan bu sûrenin tefsiri olduğu söylenmez.','BUK6436',hadith_grade='sahih',origin='İbn Abbas; Buhârî, no.6436',connection='resonant')
add(51,'HD06','hadith','100:6|100:8','Müslim 2625cde Ebû Zerre, et suyu pişirince suyunu artırması ve komşu hanelere uygun biçimde pay vermesi öğütlenir. Bu sahih tematik kayıt, kapalı kese ve yalnız yeme karşısındaki ortak sofra yönünü destekler. Zayıf kenûd rivayetinin sıhhatini düzeltmek için değil, paylaşmanın bağımsız ahlaki dayanağı olarak kullanılır.','MUS2625c',hadith_grade='sahih',origin='Ebû Zer; Müslim, no.2625c',relation='thematic')
add(51,'HD07','hadith','100:6','Buhârî 1130da Hz. Peygamberin namazda ayakları şişinceye kadar durduğu ve niçin yaptığı sorulduğunda şükreden bir kul olmayı dile getirdiği kaydedilir. Nimet karşısındaki cevap yalnız sözle sayma değil amelle şükürdür. Bu sahih tematik örnek kenûdun olumlu karşılığını görünür kılar; sûrenin özel nüzul sebebi sayılmaz.','BUK1130',hadith_grade='sahih',origin='Muğîre b.Şuʿbe; Buhârî, no.1130')
add(51,'CQ08','cross_quran','100:6|100:8|100:10','34:13te büyük kazanlar ve kaplar şükür emriyle birlikte geçer; 76:8, 2:177 ve 3:92 sevilen mal/yemekten vermeyi; 59:9 sevgi, göğüste ihtiyaç duymama ve başkasını kendine tercih etmeyi birleştirir. Bunlar ortak sofranın güçlü Kurʾan dayanaklarıdır. İmgelerin ayetler arası birleşmesi, Adiyatın kap ve kazanları literal olarak saydığı iddiasından ayrıdır.','QURAN',connection='strong',source_ref='Kurʾan 34:13;76:8;2:177;3:92;59:9;69:34;107:7')

add(39,'SM11','semantic_history','100:6','Kenûd için lehçe açıklamaları da aktarılır. Râzî ve Zemahşerî Kinde dilinde âsi, Benî Mâlikte cimri, Mudar/Rabîada nimet inkârcısı anlamlarını kaydeder; Kurtubî cimrilik için Kinâneyi de anarak farklı bir liste verir. Bunlar eski nakledilmiş dil tasnifleridir. Burada bağımsız kabile lehçesi derlemesi yapılmadığından aynı kesin saha verisi gibi birleştirilmez.','RAZ100-6|ZAM100-6|QURT100-6',status='reported',priority='research',audience='research',historicity='uncertain',source_ref='Râzî 100:6 ve Keşşâf 100:6 Kelbî lehçe listesi; Kurtubî 100:6 Kinâne/Kinde/Rabîa-Mudar listesi')
add(41,'QR05','qiraat','100:7','Taberî Katâdeden, bazı okumalarda innallāhe alâ zâlike le-şehîd biçiminde Allah adının açıkça geldiği bir nakil verir. Bu, Allahın şahit oluşu yorumunun eski dayanağıdır. İbarenin hangi kıraat yoluna ait olduğu ve kanonik sınıfı bu incelemede bağımsız doğrulanmadı; bu nedenle standart ayet yerine konmaz ve sahih kanonik okuyuş diye etiketlenmez.','TAB100-7',priority='research',audience='research',note='Bu nakilde canonical alanı özellikle kullanılmadı; bağımsız sınıflama not_assessed.',source_ref='Taberî 100:7, بشر–يزيد–سعيد–قتادة yolu, في بعض القراءات kaydı')
add(42,'TF15','tafsir','100:6','İnsan hakkındaki genellemenin kapsamı da yorum konusudur. Râzî belirli bir inkârcı yahut ilahi yardımla korunmadığında insan tabiatının bu eğilimi şeklindeki iki yaklaşımı ayırır. İbn Âşûr inkârcı/münafık tutumlarını belirtirken müminleri de uyarır. Ayet her insanın her davranışını nankör diye mahkûm etmek yerine, insanın nimet karşısında düşebildiği tutumu teşhis eden bir öğüt olarak okunabilir.','RAZ100-6|ASH100-1',tradition='dirayet',role='constraint',status='reported',priority='extended',audience='advanced')
add(54,'SM10','semantic_history','100:3|100:8|100:10','Sabah hayvanı sulama ve suya doyma sözlük ailesinde vardır; Cevherî habbabati’l-ibil ile develerin suyla dolmasını kaydeder. Buna karşılık İbn Fâris s-d-r için sudan/yerden ayrılma ile bedendeki göğsü iki ayrı başlangıç sayar. Sabah–su–sevgi–göğüs zinciri bu eski malzemeyi bir araya getirir; hubbın ayette su içmek, sudûrun da sudan dönmek anlamına geldiğini göstermez.','MAQ-sbh|SIH-hbb|MAQ-sdr|RAG-sdr',audience='advanced',term='صبح | حبب | صدر')
add(55,'SC07','source_note','100:11','Şerrâb bi-enkuʿ atasözünde Mekāyîsin tercihi temel metnin deneyim vurgusundan ayrılır. İbn Fâris tekrarlayan/işe yeniden girişen açıklamasını aktarır; kendi açıklamasını ise tehlikeli su yoluna inmeyen, güvenli birikintiden içen ihtiyatlı kuş ve tedbirli insan üzerinden kurar. Denenmiş tecrübe sözlükte bir yorumdur; kök önceliğinde bu karşı tercih saklanmalıdır.','MAQ-nqa',priority='research',audience='research',source_ref='Maqayis نقع, شرّاب بأنقع atasözü, كذا يقولون ve وجهه عندنا cümlelerinin tamamı')
add(56,'CQ09','cross_quran','100:3|100:10-11','28:23 Mûsânın Medyen suyuna gelişinde çobanların hayvanlarını çıkarıp ayrılmasını; 99:6 insanların amellerini görmek için ayrı gruplar halinde çıkmasını anlatır. Râgıb sadr maddesinde 100:10 göğsü ile 99:6 çıkışı zaten aynı maddede verir. Ortak dönüş/çıkış alanı sağlamdır; Medyen suyunun kıyamet sahnesi veya Adiyat göğsünün su kaynağı olduğu sonucu bu paralelin söylediğinden fazlasıdır.','QURAN|RAG-sdr',connection='resonant',source_ref='Kurʾan 28:23 ve 99:6; Müfredât صدر maddesinin tamamı')
nov(56,'N18','100:3|100:8|100:10-11','Sudan dönüş ile göğüs aynı sözlük maddesinde eski malzemedir; Râgıb Adiyat 100:10 ve Zilzal 99:6yı da birlikte anmıştır. Bu nedenle dönüş–göğüs bağlantısının sözlüksel öncüllüğü açıkça korunur. Projenin sabah sulaması, doyma, havuz ve hesap dönüşüyle bütünleşen yolculuk sahnesi daha geniş bir düzenlemedir; Mekāyîsin iki ayrı başlangıcı bu düzenin literal anlam olmadığını gösterir.','RAG-sdr|MAQ-sdr|SIH-hbb|MAQ-sbh|QURAN','partial','Râgıb, صدر maddesinin tamamı, 100:10 ve 99:6 örnekleri; İbn Fâris, صدر ve صبح maddelerinin tamamı; Cevherî, حبب maddesinin tamamı; Kurʾan 28:23 ve 99:6')
nov(56,'N19','100:3|100:11','Havuzdan içen ihtiyatlı veya deneyimli insan üzerinden Habîre geçmek, sözlükteki atasözü ve bilgi alanının projede birleştirilmesidir. İncelenen Mekāyîs atasözü pasajı ihtiyatı tercih eder; Râzî 100:11 ilahi bilginin deneyerek edinilmesini açıkça reddeder. Bu kaynaklar aynı su-deneyim-ilahi bilgi zincirini kurmaz. Birleşim yalnız insan tecrübesi için çağrışımlı kalabilir; Allahın öğrenmesi sonucu çıkarılamaz.','MAQ-nqa|MAQ-khbr|RAG-khbr|RAZ100-11','building_blocks_only','İbn Fâris, نقع maddesinin tamamı ve شراب بأنقع karşı tercih pasajı; İbn Fâris, خبر maddesinin tamamı; Râgıb, خبر maddesinin tamamı; Râzî, 100:11 ilk soru ve iki cevap pasajının tamamı')
add(59,'TF16','tafsir','100:5|100:9-11','Cemʿin hac yorumunda özel bir yer adı olması eski ve önemlidir: Taberî İbn Mesuddan Müzdelife açıklamasını aktarır; Cevherî de Müzdelifeye insanların toplanması sebebiyle Jamʿ denmesini kaydeder. Askerî host ve hac toplanması aynı açılış sahnesinin iki yorumudur. Son ayetlerdeki bütün insanları kapsayan hesapla karşılaştırma ikisini kullanabilir, fakat bu iki sahnenin birlikte literal olarak gerçekleştiğini varsaymaz.','TAB100-5|SIH-jma|BUK1684',status='disputed',priority='extended',source_ref='Taberî 100:5 İbn Mesud/Müzdelife nakli; Sıhâh جمع; Buhârî1684 Jamʿ babı')
nov(59,'N20','100:5|100:9-11','Toplama kelimesinden mal yığma ve kıyamet toplanmasına geçişin klasik sözlük öncülü kuvvetlidir: Râgıb cemʿ maddesinde 70:18/104:2 ile 18:99/11:103/64:9u birlikte sıralar. Jamʿın Müzdelife yorumu da eskidir. Bu nedenle küçük kalabalıktan büyük hesap toplanmasına geçiş bütünüyle yeni sayılamaz; projenin baskın merkezini bütün insanlığın sahnesine büyütme düzeni bu malzemeyi sûrede yeniden kurar.','RAG-jma|TAB100-5|BIQ100-1|QURAN','partial','Râgıb, جمع maddesinin tamamı, mal yığma/evrensel toplanma ayetleri; Taberî, 100:5 gövdesinin tamamı, askerî topluluk ve Müzdelife; Bikāî, 100:1 Zilzal bağlantısı; Kurʾan 18:99,11:103,64:9,36:51–53')
add(60,'NZ02','nazm','100:5-11','Baskın merkezinden evrensel hesaba ölçek büyütme, askerî cemʿ okuyuşuna göre yapılmış bir yapı karşılaştırmasıdır. Hac yorumu seçilirse ilk toplanma zaten ibadet yolculuğundaki Jamʿ olur ve aynı kıyasın tonu değişir. İnsan tekilinden rabbehümdeki çoğula geçişi Râzî ve Beyzâvî insan sözünün tür/çoğul anlamıyla açıklar; özel bir köyün büyümesini tek gramer sonucu yapmaz.','TAB100-5|RAZ100-11|BAY100-11',audience='advanced')
add(64,'SM12','semantic_history','100:7|100:9|100:11','Şahitlik yalnız gözle görmek değildir. İbn Fâris حضور/علم/إعلامı aynı alan içinde değerlendirir; Râgıb şahitliğin gözle görme yahut iç kavrayışla olabileceğini belirtir. 100:7de Allah şahittir yorumu da bu geniş anlamla uyumludur. İnsan için görme–anlama–haber sırası kurulabilir; bunu sözlüğün şahitliği yalnız dış duyuma kapattığı bir gelişim çizgisi saymamak gerekir.','MAQ-shd|RAG-shd|SIH-shd|TAB100-7',audience='advanced',term='شهد | علم | خبر')
add(64,'MT08','method_note','100:11','Bu bilgi deneyerek kazanılır cümlesi, habîrin insanî kullanımındaki tecrübe alanı için okunmalıdır; son ayetteki Allahın bilgisi için geçerli değildir. Râzî aynı ayette bu çıkarımı açıkça sorar ve reddeder: Allah önceden bilmeyip sonradan deneme ile bilen değildir. O gün vurgusu bilginin ilk kazanıldığı zamanı değil, bilginin hüküm ve karşılık olarak ortaya çıkışını belirtir.','RAZ100-11|RAG-khbr|TAB100-11',status='explicit',audience='general',source_ref='Râzî 100:11, ilk soru ve iki cevap; Müfredât خبر ilahi bilgi açıklaması; Taberî 100:11')
nov(65,'N21','100:7|100:9|100:11','Şehîd–yaʿlam–Habîr üçlüsü sûredeki gerçek kelime sırasına dayanır; sözlükler şahitlik, bilgi ve haberi, klasik tefsir de iç niyetleri bilen Rabbi açıklar. Projenin bunları üç bilme biçimi halinde düzenlemesi kısmi bir sentezdir. Üçlünün insan tanıktan başlaması, 100:7de insan öznesi tercihine bağlıdır; Allah öznesi seçildiğinde aynı açıklama değişir.','MAQ-shd|MAQ-alm|RAG-khbr|RAZ100-7|RAZ100-11|TAB100-7','partial','İbn Fâris, شهد ve علم maddelerinin tamamı; Râgıb, خبر maddesinin tamamı; Râzî, 100:7 ve 100:11 gövdelerinin tamamı; Taberî, 100:7 gövdesinin tamamı')
add(66,'CQ10','cross_quran','100:7|100:9-11','67:13–14te gizli/açık söz, göğsün içini bilme, yaratma ve Habîr peş peşe gelir; Adiyatın kapanışıyla yakın bir anlam karşılaştırmasıdır. 75:13–15 kişinin kendi lehine mazeretlerine rağmen öz tanıklığını; 24:24 ve 41:21 uzuvların tanıklığını; 99:4–5 toprağın Rabbinden gelen izinle haber vermesini belirtir. Farklı özneler aynı tanıklık sözcüğünün tek literal kişisi haline getirilmez.','QURAN',connection='strong',source_ref='Kurʾan 67:13–14;75:13–15;24:24;41:21;99:4–5;50:16;29:10')
nov(66,'N22','100:9-11','67:13–14ü Adiyatın iç bilgi kapanışına ayna yapmak güçlü metin benzerliğine dayanan proje yorumudur. Kontrol edilen ilgili Adiyat pasajları Allahın her zaman bilmesi, iç niyet ve göğüs temasını açık işler; seçili 67 paralelini burada aynı ayna kuruluşuyla göstermez. Bu, bütün klasik tefsirlerde yokluk hükmü değildir. Paralelin değeri, doğrudan karşılaştırılan iki Kurʾan pasajının yakınlığıdır.','QURAN|RAZ100-10|RAZ100-11|BIQ100-9|BIQ100-11','building_blocks_only','Râzî, 100:10 ve 100:11 gövdelerinin tamamı; Bikāî, 100:9 ve 100:11 gövdelerinin tamamı; Taberî, 100:11 gövdesinin tamamı; Kurʾan 67:13–14 ve100:9–11')
add(69,'RD02','reader_note','100:1-11','Bu son birleşmelerde önce ayetin güçlü bağlamsal anlamı, sonra gerçekten kaynaklı aile imgeleri, en sonunda onları birleştiren yorum izlenmelidir. Bir at hem literal baskın sahnesinin hayvanı hem düşünce için benzetme olabilir; bu, tüm sözlük anlamlarının aynı anda ayetin çevirisi olduğu sonucunu vermez. Önceki ihtilaf ve sınır notları burada da geçerlidir.','PROTOCOL|BASE100|RAZ100-2|BAY100-5',priority='extended',audience='advanced')
add(70,'MT09','method_note','100:1-5|100:9-11','Hızlı koşu ve tozla kabirlerden hızlı çıkış arasında benzerlik kurulabilir. Ancak 50:44teki kolay haşir ve 70:43teki mezardan çıkış kıyametin açık sahnesidir; Adiyatın ilk beş ayetindeki hayvan baskını yahut hac hareketi başka bir bağlamdır. Son birleşmedeki bütün insanlık ve kaçışsızlık büyütmesi bu iki sahneyi anlam yoluyla karşılaştırır, olay kimliği yoluyla birleştirmez.','QURAN|TAB100-1|TAB100-5',audience='advanced')
add(71,'CQ11','cross_quran','100:2|100:4|100:6|100:9','7:57de yağmurun ölü toprağa gelişi ile ölülerin çıkarılması açıkça karşılaştırılır; 36:78–80de yeşil ağaçtan ateş de diriliş sorusunun içindedir. Böylece su ve ateş üzerinden saklı hayatın ortaya çıkışı güçlü Kurʾan malzemesidir. Projenin bunları Adiyat kökleriyle bütünleştirmesi yorum katmanıdır; her ateş çıkarmanın ve her toz kaldırmanın bağlamsal anlamı diriliş değildir.','QURAN',connection='strong',source_ref='Kurʾan 7:57–58;36:78–80;30:48;100:2,4,6,9')
add(72,'CQ12','cross_quran','100:8|100:10-11','9:34–35te yığılan altın ve gümüş ateşte kızdırılıp alın, yan ve sırtı dağlayan bir karşılığa dönüşür; 47:37de mal talebinin cimrilik ve gizli kinleri açması vardır. Göğüs içinin çıkarılmasıyla güçlü bir ahlaki paralel kurulur. Ancak 9:35 göğüs sözcüğünü kullanmaz; karşılaştırma bedensel karşılık ve gizli yöneliş üzerindedir, aynı lafzın tekrarı değildir.','QURAN|RAG-hsl',connection='strong',source_ref='Kurʾan 9:34–35 ve47:37; Müfredât حصل, altın/cevher örneği')
nov(72,'N23','100:8-11','Servet–altın–ateş–göğüs içi ağının bazı parçaları doğrudan eskidir: Râgıb 100:10u altın/cevher ayırmayla açıklar; Kurʾan 9:34–35 ve47:37 yığma, ateş ve iç kinin açılmasını verir. Projenin bu parçaları tahıl/çekirdek ve bütün sûrenin kıvılcımına bağlayan kuruluşu kısmi bir sentezdir. İncelenen ilgili maddeler ve Adiyat pasajları bütün ağı aynı biçimde sunmaz.','RAG-hsl|RAG-hbb|RAZ100-10|TAB100-8|QURAN','partial','Râgıb, حصل ve حبب maddelerinin tamamı; Râzî, 100:10 gövdesinin tamamı; Taberî, 100:8 gövdesinin tamamı; Kurʾan 9:34–35,47:37 ve100:8–11')
add(73,'CQ13','cross_quran','100:3|100:6|100:8-11','68:17–33ün tamamında sabah hasadı planlayan sahipler, yoksulu dışarıda tutma, uykudayken Rabbinden gelen afet, kayıp, Rabbini tesbih ve zulmünü itiraf vardır; sonunda daha büyük ahiret azabı hatırlatılır. Bu, sabah çıkarı ve yoksulu esirgeme karşısındaki tersine dönüş için güçlü paraleldir. Metin afeti atlı bir baskın diye adlandırmaz; Adiyatın aynı bahçe sahipleri hakkında indiğini de söylemez.','QURAN',connection='strong',source_ref='Kurʾan 68:17–33 tamamı, özellikle17/19/21–25/28–33')
nov(73,'N24','100:3|100:6|100:8-11','Bahçe sahiplerinin sabah planı ile Adiyatın sabah baskını ve kenûd sevgisini tersine bir yağmalama sahnesi gibi karşılaştırmak proje yorumudur. Bahçedeki yoksulu dışlama, Rabb sözü ve son hesap uyarısı Kurʾanda açık malzemedir. İncelenen ilgili Adiyat pasajlarında bu bahçe kıssasıyla aynı ayrıntılı birleşim gösterilmedi; bu sınırlı kontrol bütün klasik literatürün tarandığı anlamına gelmez.','QURAN|RAZ100-3|RAZ100-6|BIQ100-8','building_blocks_only','Râzî, 100:3 ve100:6 gövdelerinin tamamı; Bikāî, 100:8 gövdesinin tamamı; Taberî, 100:3/100:6/100:8 gövdelerinin tamamı; Kurʾan 68:17–33 tamamı')
add(74,'MT10','method_note','100:3|100:10-11','Zilzaldeki yasdur sözü ve Adiyattaki sudûr arasındaki aile bağlantısı klasik sözlükte zaten kayıtlıdır; burada önceki su-dönüş yenilik değerlendirmesi geçerlidir. Bu son birleşmenin işlevi, ayrı imgeleri yeniden hatırlatmaktır. Kökteki farklı başlangıçları ve 99:6nın kıyamet bağlamını kaldırarak sudûru gerçek bir su dönüşü diye çevirmek değildir.','RAG-sdr|MAQ-sdr|QURAN',priority='extended',audience='advanced',note='İlgili birleşim S100-N18de değerlendirildi; aynı çekirdek yeni bir bağımsız kaynak iddiası sayılmadı.')
nov(75,'N25','100:6-7|100:11','7:172de Rabb sorusu ve insanın kendisi hakkında şahitliği; sözlükte atın lehine koşu tanıklığı vardır. Bunları Adiyattaki aleyhte şahitliğe karşı yerleştirmek projenin birleşimidir. İncelenen 100:7 pasajlarında bu bütün ahid–at–insan kıyası açık gösterilmedi. 7:172 paraleli, 100:7de Allah mı insan mı öznesi bulunduğu ihtilafını tek başına çözmez; karşılaştırma insan okuyuşuna göre çalışır.','QURAN|LIS-shd|TAB100-7|RAZ100-7|KAT100-7','building_blocks_only','Lisânü’l-Arab, شهد maddesinde atın koşusunun lehine şahitliği altpasajı; Taberî/Râzî/İbn Kesîr, 100:7 gövdelerinin tamamı; Kurʾan 7:172 ve100:6–7,11')
add(76,'NZ03','nazm','100:1-11','Dış hareketten saklı içeriğe açılan ana yönelişin ciddi klasik öncülü vardır. Bikāî koşan düşünceleri, duyulur mala bağlanmayı, görünmeyen sevgiyi ve dirilişi, ardından Rabbın iç-dış bütün halleri bilmesini işler; kapanışın başlangıçtaki Rabb/nankörlükle döndüğünü belirtir. Râzî de amelin kalpteki niyete bağlılığını açıklar. Projenin bütün sözlük imgelerini bu eksene yerleştirmesi bu eski yapı açıklamasını genişletir.','BIQ100-6|BIQ100-8|BIQ100-9|BIQ100-11|RAZ100-11',role='early_attestation',status='explicit',source_ref='Bikāî 100:6/8/9/11 gövdeleri; Râzî 100:11 kalp niyetleri–uzuv amelleri sorusu')
nov(76,'N26','100:1-11','Bütün sûrenin dıştan içe, görünür hareketten saklı niyet ve ilahi bilgiye yöneldiğini söylemek tamamen yeni değildir: Bikāî ve Râzî önemli parçaları açıkça işler. At bedeni, ateş, tarla, maden, tahıl, sofra ve su yolculuğunun bütün kökler üzerinden aynı ağda düzenlenmesi daha geniş proje kuruluşudur. Yenilik hükmü bu belirli birleşimle sınırlıdır; yapı fikrinin eski öncülleri reddedilmez.','BIQ100-6|BIQ100-8|BIQ100-9|BIQ100-11|RAZ100-10|RAZ100-11|CORPUS100','partial','Bikāî, 100:6 düşünce/iyi-kötü anlam;100:8 duyulur mal/görünmeyen din;100:9 sevgi/kabir;100:11 iç-dış bilgi ve başlangıca dönüş altpasajlarının tamamı; Râzî,100:10 ve100:11 gövdelerinin tamamı. Daha geniş dijital corpus kapsamı Kaynak eleştirisi notunda tek tek belirtilir; basılı cilt yokluğu denetimi yapılmadı.')
add(76,'QR04','qiraat','100:11','İbn Hâleveyhin şaz Adiyat bölümünde Ebû Semmâl ve Haccâca nispet edilen anna rabbahum...khabîr, yani an ile başlayıp habîrden önce lâmı kaldıran okuyuş kaydedilir; Râzî ve Kurtubî de bunu tartışır. Şaz sınıflaması okunan basılı bölüme dayanır. Haccâcın dil sürçmesi anlatısının bağımsız olay tarihi ise burada doğrulanmadı; kıraat kaydıyla biyografik anekdot ayrıdır.','SHAD178|RAZ100-11|QURT100-11',canonical='false',priority='research',audience='research',term='أنّ ربهم ... خبير',historicity='uncertain',source_ref='İbn Hâleveyh s.178, Adiyat100:11; Râzî100:11 son mesele; Kurtubî100:11 son paragraf')
add(76,'SC08','source_note','100:1-11','Sûre okumaya bağlanan yarım Kurʾan sevabı veya Müzdelifedeki kişi sayısı kadar sevap nakilleri Süyûtî, Zemahşerî, Beyzâvî ve Râzînin incelenen pasajlarında yer alır. Asıl hadis kaynakları ve her isnadın derecesi burada bağımsız kontrol edilmedi. Bu nedenle sahih fazilet hadisi diye aktarılmaz, at/deve tercihine veya sûrenin iniş tarihine kesin delil yapılmaz; aktarım tarihinin derecelendirilmemiş malzemesi olarak kaydedilir.','SUY100-1|ZAM100-11|BAY100-11|RAZ100-1',status='not_assessed',hadith_grade='not_assessed',priority='research',audience='research')
add(76,'SC09','source_note','100:1-11','Yenilik alanı bu çalışmada gerçekten okunan pasajlarla sınırlıdır. Yedi çekirdek müfessirin 100:1–11 dijital gövdeleri kontrol edildi; Süyûtîde tekrar ve içeriksiz ayet bölümleri ayrıca kaydedildi. Seçili Kurtubî, İbn Âşûr, Sâd, sözlük ve hadis pasajları bunları tamamlar. Bir sayfanın indirilmesi veya anahtar sözcük bulunmaması, basılı cilt yahut bütün klasik tefsirler üzerinde yokluk kanıtı sayılmadı.','CORPUS100|PROTOCOL',priority='research',audience='research',checked_sources='Taberî/İbn Kesîr/Zemahşerî/Râzî/Beyzâvî/Süyûtî/Bikāî,100:1–11 dijital gövdeleri; Kurtubî100:1/4/6/9/10/11; İbn Âşûr100:1; Taberî veRâzî38:32–33; registryde kapsamı belirtilen sözlük/hadis/şaz kıraat pasajları')

def serialize(d):
 return '{'+', '.join(f'{k}: {v}' if k in enums else f'{k}: {json.dumps(v,ensure_ascii=False)}' for k,v in d.items())+'}'
base=BASE.read_text()
chunks=[p for p in re.split(r'\n[ \t]*\n',base) if p.strip()]
assert len(chunks)==76
cursor=0;insertions=[]
for index,chunk in enumerate(chunks,1):
 pos=base.find(chunk,cursor);assert pos>=0
 end=pos+len(chunk);cursor=end
 if index in by_block:
  inserted='\n\n'+'\n\n'.join(serialize(d) for d in by_block[index]);insertions.append((end,inserted,index))
body=base
for off,inserted,index in reversed(insertions):body=body[:off]+inserted+body[off:]
prefix='<!-- Adiyat 100:1–11: kapsamlı ek katmanı; özgün r13 metni aşağıda aynen korunmuştur. -->\n\n'
used_ids=[]
for annotation in annotations:
 for s in annotation['source'].split('|'):
  if s not in used_ids:used_ids.append(s)
registry=['## Kaynak kayıtları','', 'Kaynak kimlikleri ek bloklarını çözer. Temel metnin özgün Kaynaklar satırları ve yerel sözlük etiketleri ayrıca aynen korunmuştur. İnceleme kapsamı her kaydın altında sınırlıdır; bir dijital taşıyıcı yazarın kendisi veya bağımsız tarih tanığı değildir.','']
for key in used_ids:
 s=catalog[key];target=s['url'];link=f'[{s["title"]}]({target})'
 registry.append(f'- **{key}** — {link}. İncelenen: {s["scope_actually_inspected"]}. {s["note"]}')
 registry.append('')
registry+=['## Kaynak eleştirisi ve kontrol edilen korpus','',
 'Taberî, İbn Kesîr, Zemahşerî, Râzî, Beyzâvî ve Bikāî için 100:1den 100:11e kadar her dijital ayet sayfasının yazar metni tamamen okundu. Süyûtînin aynı on bir sayfası da kontrol edildi: 100:3–5 gövdeleri 100:2 ile aynı metni tekrar eder; 100:9–11 sayfaları müstakil tefsir gövdesi sunmaz. Tekrarlar bağımsız rivayet sayılmadı; bu dijital eksikliklerden basılı eserde yokluk sonucu çıkarılmadı. Sayfalardaki sonraki paragrafı ekle düğmesi kopya bağlantısı yardımcısıdır; eksik veya dinamik yazar metninin kanıtı sayılmadı.','',
 'Ek tefsir kontrolü Kurtubî 100:1,4,6,9,10,11; İbn Âşûr 100:1in giriş ve devam metni; Taberî ile Râzî 38:32–33 ile sınırlıdır. 100:1–11 çekirdek bölümleri tam dijital gövde denetimidir; bu ifade hiçbir yazarın basılı kitabının bütün ciltleri, farklı baskıları veya bütün klasik literatürü taranmış demek değildir. Râzînin Sâd sayfalarındaki tekrar bölüm de ayrı tarihsel tanıklık olarak sayılmadı.','',
 'Sözlük incelemesinde Mekāyîsin عدو، ضبح، غور، حبّ، حصل، جمع، كند، قبر، قدح، ربّ، صبح، صدر، شهد، شدّ، ثور، وري، وسط، علم، أنس، خير، خبر، نقع maddeleri; Müfredâtın حصل، بعثر، وري، قبر، خير، خبر، ربّ، حبب، ثور، صدر، شهد، جمع، إنس maddeleri; Sıhâhın حبب، حصل، قدح، جمع، صدر، أنس، شهد maddeleri tam olarak okundu. Lisânın كند maddesi tam; شهد maddesi ise yalnız at-koşu tanıklığı altpasajı ve sınırlı giriş düzeyinde kontrol edildi. Lisânın kalan maddesi ve indirilmiş diğer sözlük girişleri okunmuş korpus diye gösterilmedi. Köklerin ayrı başlangıçları, Râgıbın alternatif etimolojileri ve reddedilmiş açıklamalar saklandı.','',
 'İbn Hâleveyhin 1934 taramasından yalnız basılı s.178deki Şevâzzü sûreti’l-Adiyat bölümü görüntüden tamamen okundu; kitabın bütün kıraat yolları veya on kıraatin usûl/ferş külliyatı denetlenmedi. Şaz alanı yalnız bu açık sınıflaması bulunan varyantlara yazıldı. Taberîdeki 100:7 Allah adını açık eden naklin kanonikliği değerlendirilmedi. Vâhidînin no.867–868 metinleri kontrol edildi; asıl Mukatil, Hâkim, Bezzâr, İbn Ebî Hâtim, Ebûş-Şeyh ve diğer atıf yapılan erken derlemelerin tamamı bağımsız incelenmedi.','',
 'Hadis karşılaştırması Buhârî 1684/2371/6436/1130 ile Müslim 382/2564c/127a/2625c tek kayıtlarını kapsar. Sahih sınıfları bu koleksiyonların tasnifine; kenûd üçlüsünün zayıflığı İbn Kesîrin açık ravi/isnad hükmüne ve Süyûtînin açık zayıf-isnad kaydına dayanır. Ebû Ümâmenin ayrı mevkuf yoluna ve sûre fazileti nakillerine yeni bir derece verilmedi. Aynı merfû kenûd üçlüsünün tekrarları tek rapor kümesi, yalnız konaklama varyantı farklı mevkuf aktarım olarak ayrıldı.','',
 'Tanzil Uthmani v1.1in 6236 ayetlik metni değişmeden indirildi; anlam karşılaştırması özgün metnin 106 ayrı ayet atfı ve 22 seçili bağlam/ek ayet, toplam128 ayrı ayet üzerinde yapıldı. 126 Arapça aktarımın 125i normalizasyonlu alt-dizi kontrolünde eşleşti. 7:58de âyât kelimesinin hemzeyi ayrı harf veya birleşen işaretle yazma farkı kalan mekanik uyarıyı oluşturur; sözcükler elle karşılaştırıldı ve anlamlı kelime farkı saptanmadı. Bu kontrol Türkçe yorumların her birinin zorunlu tefsir olduğuna hükmetmez. Tanzil kaynağı ve indirme lisans notu araştırma kopyasında korunmuştur.','',
 'Maddi nal tarihi, bağımsız erken seriyye kronolojisi, adı verilen tek şahısların nüzul sebebi oluşu, mevkuf ve fazilet isnadlarının ayrı tahkiki bu çalışmada sonuçlandırılmadı. Dijital metinlerdeki münferit ad/yer/yazım pürüzleri başka basılı nüshalarla bütünüyle karşılaştırılmadı; onlardan yeni tarihsel sonuç çıkarılmadı. Yedi temel yazarın kontrollü pasajları dışındaki modern literatür için kapsamlı bir yokluk denetimi yapılmadı.','',
 'Yenilik bloklarında explicit doğrudan eski açıklamayı, partial önemli eski öncüllerle daha geniş proje kuruluşunu, building_blocks_only kaynaklı malzemenin burada yeni bir düzen içinde birleşmesini belirtir. Sınırlı pasaj kontrolü hiçbir yerde mutlak yokluk veya ilk kez söylenmiş olma hükmüne çevrilmedi. Özgün süreç önsözü ve kaynak sınırlamaları belge bütünlüğü için korundu; karşı deliller temel metni değiştirmeden ek katmanda gösterildi.','']
suffix='\n\n'+'\n'.join(readable(line) for line in registry)
output=prefix+body+suffix
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(output)
(W/'checked_source_catalog.json').write_text(json.dumps({'scope':'100:1–11 comprehensive; actual inspected passages only','sources':list(catalog.values()),'used_registry_ids':used_ids,'not_checked':['Complete printed volumes and alternative editions','Independent originals of Hakim/Bazzar/IbnAbiHatim and other indirectly cited report collections','Independent grade of AbuUmama mawquf report and surah merit reports','All ten-reading transmission/usul/farsh corpus','Archaeological/history survey of horseshoe materials','Downloaded dictionary entries outside the exact listed inspected selection']},ensure_ascii=False,indent=2)+'\n')
(W/'annotation_manifest.json').write_text(json.dumps({'base_file':str(BASE),'output_file':str(OUT),'annotations':annotations},ensure_ascii=False,indent=2)+'\n')
reconstructed=output[len(prefix):len(output)-len(suffix)]
for off,inserted,index in insertions:
 assert reconstructed.count(inserted)==1
 reconstructed=reconstructed.replace(inserted,'',1)
assert reconstructed==base,'Byte-level base reconstruction differs'
audit={'base_sha256':hashlib.sha256(BASE.read_bytes()).hexdigest(),'reconstructed_sha256':hashlib.sha256(reconstructed.encode()).hexdigest(),'exact_base_bytes_after_removing_only_insertions':reconstructed.encode()==BASE.read_bytes(),'insertions_only_at_base_block_ends':True,'base_blocks':len(chunks),'annotation_count':len(annotations),'annotations_by_type':dict(Counter(d['type'] for d in annotations)),'source_registry_count':len(used_ids),'novelty_count':sum(d['type']=='novelty' for d in annotations),'matrix_prepared_before_composition':True,'scope':'surah100 only; no ayah output touched'}
(W/'preservation_audit.json').write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(audit,ensure_ascii=False,indent=2))
