"""Substantive pre-composition research matrix; this script writes no annotations."""
from pathlib import Path
import json,hashlib,re
W=Path(__file__).resolve().parent
claims=json.loads((W/'claim_map.json').read_text())
# Each cell records inspected evidence, the counter-evidence/limit, disposition and novelty boundary.
rows=[
('C01','Özgün ilk paragraf kendi denetim sürecini anlatır; adjacent ledger ve üretim istemi r13 sözlük/Kuran kısıtını doğrular.','Okurun sûrenin anlamına ilişkin açıklama beklemesiyle süreç anlatımı farklıdır. Bugünkü kapsamlı ek yetkisi eski üretim kısıtı değildir.','Korunacak; reader_note ve method_note ile katmanlar açıklanacak.','Yenilik iddiası uygulanmaz.','BASE100|LEDGER100|PROTOCOL'),
('C02','Taberî 100:1 at çoğunluğunu, İbn Mesud/İbrahim deve-hac rivayetlerini ve Ali–İbn Abbas tartışmasını verir; atı tercih eder. Zemahşerî 100:1 ve 5 masdar/hal ve isim-fiil geçişini tartışır.','Ali kıssası farklı râvi/at sayısı ayrıntıları taşır; bu incelemede bağımsız isnad tahkiki yapılmadı. 100:2–3 Taberî son tercihi ateş ve sabah hareketinde geniş kapsayıcıdır.','At baskını ana anlam olarak kalır, ciddi hac alternatifi ve gramer açıklaması eklenir.','Hayvan-efendi karşılaştırması Râzî 100:1 açık; bütün sözlük beden imgesi daha dar ölçekte proje birleşimidir.','TAB100-1|TAB100-2|TAB100-3|ZAM100-1|ZAM100-5|RAZ100-1'),
('C03','Râzî 100:1 yorulan atın sahibine itaati ile insanın Rabbine itaatsizliğini doğrudan kıyaslar. Bikāî 100:1 ve 7 niyet ve efendi hakkını işler. Maqayis q-d-h ok/ince atı, sh-d-d koşu/bağı kaydeder.','Her aile sözü 100’deki fiilin bağlamsal karşılığı değildir; binicinin yanı, yarış tanıklığı ve göğüs sözleri birlikte bir klasik ayet şerhi olarak gösterilemez.','Doğrudan klasik karşılaştırma ayrı, sözlükten oluşturulan geniş at-bedeni ağı ayrı sınıflandırılacak.','Ana itaat kıyası explicit; birleşik beden ağı partial.','RAZ100-1|BIQ100-1|BIQ100-7|MAQ-qdh|MAQ-shdd'),
('C04','Tanzil 38:31–33 ve 3:14; Taberî 38:32 hayrı at/mal sayar; 38:33 kesme ve sevgiyle elle sıvazlama rivayetlerini verir ve ikincisini seçer. Râzî 38:32–33 sevgiyi Allah emrinden doğmuş kabul eden yorumu ve kesme reddini savunur.','Tek bir Süleyman okuması üzerinde sûreler arası ahlaki hüküm kurulamaz; anın uzaklaşma/kaynak anlamları ihtilaflıdır.','Doğrulanmış çapraz bağ ve yorum ihtilafı beraber eklenecek.','At-hubb-hayr-Rabb malzemesi eski; Adiyat ile bütünlükte karşılaştırma inspected 100 corpus içinde açık aynı mimari değil.','QURAN|TAB38-32|TAB38-33|RAZ38-32|RAZ38-33'),
('C05','Maqayis adw sınırı aşan hareket, gwr girme/aşağı inme; Taberî 100:3 baskın ve hac alternatifleri; Râzî 100:3 gecenin görünmezliği/sabah hazırlıksızlık gerekçesi; Müslim 382 şafak baskını ve ezan dinleme.','Udwan yakın sözcük olsa da her koşu/baskın ahlaken haksız değildir. Sûre düşman ordusu dışında sivillerin ayrıntılarını belirtmez.','Tarihsel pratik hadisi thematic/historical olarak eklenir; sahnenin uyuyan silahsız köyü tasvir sayması sınırlanır.','Özgün sabah baskını bağlamı eski; bütünüyle kıyamet provası çıkarımı ayrıca incelenecek.','MAQ-adw|MAQ-gwr|TAB100-3|RAZ100-3|MUS382'),
('C06','Taberî 100:4 bihinin yer; Râzî 100:4 yer/zaman/koşu; Zemahşerî 100:4–5 ve Beyzâvî 100:4 toz/ses. Taberî 100:5 düşman/kafir/tabur veya Müzdelife.','Cemʻ kelimesinin farklılıkları toplaması tek ayette karma sivil kalabalığı kanıtlamaz. Zemahşerî ses tartışmasındaki nakʻ/laklaka sözü Peygambere, Kurtubî 100:4 Ömere nispet edilir; bağımsız peygamber hadisi doğrulanmadı.','Toz önceliği, ciddi ses ihtimali, zamir alternatifleri ve atıf çatışması kaydedilir.','Ses ve toz klasik explicit; yağma-yemek geniş ağı malzeme düzeyindedir.','TAB100-4|TAB100-5|RAZ100-4|ZAM100-5|BAY100-4|QURT100-4|MAQ-nqa'),
('C07','Tanzil 37:177/11:81/15:83/54:38 sabah azabı, 70:43/50:44 hızlı kabir çıkışı; Bikāî 100:1 Zilzal yargısıyla bağlantıyı açık kurar.','Savaş tozu, kıyamet kabirleri ve haksız yağma aynı gerçek tarihsel olay değildir; sure raidi tek başına bütün insanlık/kıyamet öznesi yapmaz.','Çapraz benzerlikler yorum ve güçlü/çağrışımlı bağlantı düzeyiyle verilecek.','Komşu sûre yargı çerçevesi partial; ayrıntılı sabah baskını-evrensel haşir birleşimi building_blocks_only.','QURAN|BIQ100-1|BIQ100-9|RAZ100-9'),
('C08','İbn Kesîr 100:2 nalın taşa çarpması; Râzî 100:2 tabii toynak imgesini nal demirine tercih eden görüşü; Taberî 100:2 ateş, savaş, hile, dil ve pişirme anlatıları.','İbn Kesîr aynı pasajda Taberîyi toynak görüşünü seçmiş gibi özetler; gerçek Taberî sonuç paragrafı bütün ateş yakıcılarını kapsar. Material kültür ayrıntısı kesin ortak tarih bilgisi değildir.','Önemli müfessir tercih çatışması ve maddi mekanizma ihtiyatı açık eklenecek.','Ateş çıkarma temel anlamı klasik explicit, fizik açıklaması farklıdır.','KAT100-2|RAZ100-2|TAB100-2'),
('C09','Râzî 100:2 Hubahib cimriliği/yararsız ateşi; Zemahşerî 100:2 aynı adı; Râzî 100:2 fikirlerin hile ateşi, savaş ve başarılı çakmak mecazları; Beyzâvî 100:5 fikir/ilim nuru; Bikāî 100:6 iyi-kötü düşüncelerin koşup anlam yakması.','Maqayis h-b-b üç ayrı başlangıç ayırır; insanın ateşi görmesi, başarılı düşünce ve hasis kıvılcım tek zorunlu türetim değildir. Hubahib kişi menkıbesi bağımsız tarih kaydı değil.','Her klasik öncül korunur; daha geniş etik görünüm proje sentezi olarak belirtilir.','Düşünce-ateş explicit ingredients; bütün süreklilik/yanlış-ışık mimarisi partial.','RAZ100-2|BAY100-5|BIQ100-6|ZAM100-2|MAQ-hbb|SIH-hbb'),
('C10','Tanzil 36:78–80 ateşi diriliş delili bağlamına koyar; 56:71–74 ateşi yaratma/hatırlatma/rızık ve Rabb tesbihi ile bağlar. 20:10/27:7/28:29 Musa ateş-haber-yol bulma. Raghib wry gizli taş ateşi fikrini açık işler.','Musa sahnesindeki insan bilgi edinimi Allahın Habir oluşuna deneyim kökeni olarak taşınamaz. 56 pasajı tek başına ateş yalnız cehennem demek değildir.','Gerçek çapraz delil güçlü, Musa-haber-Habir hattı çağrışımlı olarak kaydedilir.','Ateş gizliliği eski; haber üzerinden birleşik sure ağı building_blocks_only.','QURAN|RAG-wry|RAZ100-11'),
('C11','Maqayis th-w-r yükselme/heyecan ve boğa; Raghib bathr 82:4 toprağı çevirme, ayrıca baath/uthira birleşim ihtimali; Taberî 100:9 kabirdeki ölüleri çıkarma; Râzî/Beyzâvî/Bikāî 100:9 mā-hum geçişi cansız halden insan haline.','b-ʿ-th-r ve th-w-r ayrı köklerdir; tarihsel birleşim bir âlimin etimolojik önerisidir. mā mutlaka hazne/mal anlamı vermez.','Kök kimliği ve imge benzerliği ayrılır; gerçek ölüler temel yorumdur.','Toprak çevirme ve bileşik kök düşüncesi partial antecedent; bütün at-tarla-kabir ekseni yine sentez.','MAQ-twr|RAG-bathr|TAB100-9|RAZ100-9|BAY100-11|BIQ100-9|QURAN'),
('C12','Raghib wry hem örtme hem taşın ardındaki ateş açıklamasını; qbr 100:9 için gerçek kabir yanında örtülü insan hallerinin açılması şeklinde alternatif mecazi yorumu kaydeder. Tanzil 5:31 gömme ve 7:57 diriliş-yağmur.','Maqayis wry ortak ölçüye indirgenmeyen kelimeler der; qbrdeki ahwal ifadesi sıradan sözlük mecazı değil alternatif doğrudan ayet tefsiridir.','Gizli ateş/gömme çıkarımı partial; hem literal hem mecazi okuma doğru kapsamlarıyla korunacak.','Klasik öncüller açık; tüm saklı-ateş/kabir-iç çıkışı ağı partial.','RAG-wry|RAG-qbr|MAQ-wry|QURAN'),
('C13','Raghib hsl DOĞRUDAN 100:10 kabuk/öz, altın/cevher, buğday/saman, hesap kalanı; Râzî ve Zemahşerî 100:10 elek/iyiyi-kötüden ayırma. Maqayis hsl altın madenden ayıklama kökenini bazı dilcilerin iddiası olarak ve eğer doğruysa der.','Eski etimoloji mutlak tarihsel köken kanıtı değil. Pasif FormII kendi başına aşamalı yavaş emek kanıtı değil; Bikāî 100:10 kolaylığı vurgular.','Tefsir öncülü explicit verilir; etimoloji, işlem temposu ve madenci kadın aile sözünden kurulma sınırlanır.','Altın/tahıl/öz ayet açıklaması explicit; belirli madenci sahnesi partial geliştirme.','RAG-hsl|RAZ100-10|ZAM100-10|MAQ-hsl|BIQ100-10'),
('C14','Raghib hbb sevgiyi kalp tanesine vurmaktan türeten açıklama verir; hsl çekirdek-kabuk doğrudan100:10; qbr örtülü insan halleri100:9.','Maqayis sevgi, tane ve küçüklüğü üç başlangıç sayar; tek etimoloji ihtilafsız değildir. İç çıkarma yalnız kötü/servet veya yalnız altın saflığı değildir.','Eski açıklamalarla projenin hubb-habb-husila birleşimi ayrılır; iki lexicographic görüş korunur.','Kalp tanesi-sevgi öncülü explicit; kapsamlı tahıl/servet/göğüs ağı partial.','RAG-hbb|RAG-hsl|RAG-qbr|MAQ-hbb|TAB100-10|RAZ100-10'),
('C15','Tanzil 3:153–154 savaş-keder, iç düşünceler ve göğüs/kalp sınanması; 3:29/47:29/86:9 açığa vurma; Müslim2564c kalp ve ameller, Müslim127a söylenmemiş/işlenmemiş iç vesvesenin affı.','Bu kontrol savaşta yaşayanların sınanması ile ölüm sonrası yargıyı aynı tarihsel sahne yapmaz; Allahın bilmesi her geçici düşüncenin cezalandırılması demek değildir.','Tematik güçlü destek ve hesap/niyet sınırı birlikte konur.','Çapraz paralel explicit metin, tek bir tarihsel sebeple bağlama yok.','QURAN|MUS2564c|MUS127a'),
('C16','Maqayis rbb bakım/onarım/süreklilik/birleşme; Raghib bulutun beslemesi. Maqayis knd kesme->nimet bağını kesme/barren earth; Taberî100:6 barren earth ve Hasan nimet unutma; Kurtubî100:6 teşekkür bağını kesme.','İnsan karşılığında Rabb kendisine kazanç sağlayan taraf gibi düşünülmemeli. Kök ailelerinin tamamı Rabb100:6ın her bağlamsal anlamı değildir.','Eski güçlü öncüller ve bütün surede ip/tarla ağının geliştirmesi ayrılacak.','Kesilmiş teşekkür bağı ve barren earth explicit; çoklu bağlantı partial.','MAQ-rbb|RAG-rbb|MAQ-knd|TAB100-6|QURT100-6'),
('C17','Raghib rbb besleyen bulut; Maqayis nqa havuz/yolcu yemeği; Qurtubi100:4 iyi killi toprak; Maqayis khbr çiftçi/ıslak toprak ile bilgi için İKİ ayrı başlangıç; Quran7:57–58 ölüm/rain/şükür,30:48 cloud stirring.','7:58 nakid n-k-d ve100:6 kenud k-n-d ayrı kök; Habir ilahi bilgi anlamındadır, çiftçi anlamından ilahi kimlik türetilemez. Habra sofra/et anlamı Maqayiste şaz sayılır.','Yararlı tarla karşılaştırması desteklenir ama bitişik harf/aile ve senkron anlamlar eşitlenmez.','Çorak insan imgesi eski; cloud-pool/farmer bütün ağı partial.','QURAN|RAG-rbb|MAQ-khbr|MAQ-nqa|QURT100-4|TAB100-6'),
('C18','Taberi100:7 tercihi Allah, Qatada açıklaması; IbnKathir insan MuhammedKaab ve Allah Qatada/Sufyan; Razi100:7 yakın zamir vs100:8 tutarlılık;100:11 Allah hep bilir, o gün mükafata vurgu; Maqayis/Raghib shd huzur/bilgi/bildirim ve göz/kalp görüsü.','İnsan tanık seçimi zorunlu değildir; Tanrı şahid okumasında insan-tanık/bilgi üçlüsünün özne çizgisi değişir. Tecrübeden bilgi kazanma Allah için açıkça reddedilir.','İhtilaf ana okuma içinde korunacak; deneyerek bilgi cümlesine doğrudan ilahi bilgi sınırı konacak.','Bilgi şahitlik ve iç bilgi eski; düzenli üçlü mimari partial.','TAB100-7|KAT100-7|RAZ100-7|RAZ100-11|MAQ-shd|RAG-shd|RAG-khbr'),
('C19','Tanzil14:34 nimet sayamama/zulm küfür,17:67 kurtulunca yüzçevirme,96:6–7 müstağnilik,82:6 keremliRabb ve7:172 self-witness/Rabb. Buhari1130 şükreden kul duası/hareketi.','7:172 başka bir ayetin ilahi-hitap sahnesidir;100:7 zamirinin insan veya Allah olduğunu bu paralel tek başına çözmez.','Nimet-şükür bağları güçlü; covenant temasını çağrışımlı seçmeli proje yorumuyla ver.','Geniş Rabb/şahitlik hattı building_blocks_only within checked core.','QURAN|BUK1130|RAZ100-7'),
('C20','Taberi100:8 hayrı mal, helal-haram ayrımına bakılmadan insan adlandırması diye açıklar. Raghib khyr bazı alimler mal çok/temiz olmalı der ve2:180 bağlamındaki şartı aktarır.','Temel Ama her mala bu ad verilmez cümlesi bütün kaynakların ittifakı veya100:8ın kesin helal servet hükmü değildir.','Açık source_note ile kuralın bazı dilciler yorumu olduğu, karşı Taberi yorumunu ver.','Yenilik yok; contextual correction constraint.','TAB100-8|RAG-khyr|QURAN'),
('C21','Taberi100:8 cimrilik vsşiddetli sevgi; IbnKathir ikisini de doğru sayar. Maqayis shdd düğüm, hbb bağlanma; Quran17:29,3:180,70:18,104:2–3 servet/bağ.','Yalnız cimri anlamı zorunlu değil. Sevginin tümünü kötü sayma, helal niyetle at/servet kullanımı Buhari2371 ile sınırlandırılır.','İki tefsir ve şiddet/bağlama-göğüste ayrıştırılma karşıtlığı sınıflandırılır.','Miser/attachment antecedent old; yumulmuş el-göğsün toplatılması ağında partial.','TAB100-8|KAT100-8|MAQ-shdd|MAQ-hbb|QURAN|BUK2371'),
('C22','Taberi100:6 marfu EbûÜmâme->CaferZubayr; IbnKathir100:6 metruk ravi ve DAIF; Suyuti100:6 zayıf isnad. Taberi aynıayrı mawquf alone-lodging variation. Lisan knd IbnSida trio için dil kökenini bilmediğini ve lirabbihiyle uyuşmadığını açık söyler.','Sözlükteki trio sahih Peygamber tefsiri diye sunulamaz; mawquf rivayet marfu zayıflığını otomatik düzeltmez. Maysir oklarının dağıtım işlevi kumarı meşrulaştırmaz (5:90).','Bir tekrar grubu olarak üçlü rivayet, ayrı mawquf varyant ve filolojik itiraz; sağlam sofra yardımı MUS2625c thematic.','Yalnız yiyen ahlak öncülü partial; kazan-kepçe-oklar/rabb/pool sistemi building_blocks_only.','TAB100-6|KAT100-6|SUY100-6|LIS-knd|MAQ-qdh|MAQ-rbb|MAQ-nqa|MUS2625c|QURAN'),
('C23','Maqayis sdr dönüş vs chest İKİ ayrı başlangıç; Raghib sdr aynı entry100:10 ve99:6; Sihahhbb deve suyla dolma; Maqayisnqa proverb cautiousbird/prudentman preferred over repeatedexperience interpretation; Quran28:23 watershepherds.','Hubb100:8 su içme değildir, chest100:10 sudan dönüş değildir. Proverb only tested experience cannot be called Maqayis priority conclusion; Allah experience issue persists.','Su hayır/sharing bağlantısı çağrışımlı; sdr iki ayrı anlam ve proverb karşı tercih açık kaydedilir.','Dönüş/göğüs yan yana eski; tüm morning-pool-judgement ağı partial.','MAQ-sdr|RAG-sdr|SIH-hbb|MAQ-nqa|QURAN'),
('C24','Taberi100:5 jamʻ militaryhost andMuzdalifa; Buhari1684 Jamʻ gerçekMuzdalifa sunrise departure. Quran11:103 witnessedday,64:9 daygathering,18:99/36:51–53 hashr.','Jamʻ100:5 evrensel hashrın tek literalreferenti değildir. Hac alternatifi ancient supports semanticassembly but adopts different opening scene.','Scalechange conditional proje nazmı; gerçek alternatif same term separatelayer.','Old assemblies explicit; universalupscaling partial.','TAB100-5|BUK1684|QURAN|BIQ100-1'),
('C25','Quran67:13–14 innerspeech/chestknowledge/create/Habir;75:13–15 human ownwitness;24:24/41:21 limbs;99:4–5 earthnews byRabb. Raghibshd sight orinsight; Razi11 knowsalways.','Aynalı benzerlik başka ayetle doğrudan S100 hakkında söylenmiş klasik şerh değildir; automatically speech means eyeseeing no.','Dilsel/thematic güçlü paraleller, proje triad repeat notsourceclaim.','Triad partial oldcomponents;67mirror building_blocks_only.','QURAN|RAG-shd|RAZ100-11|RAZ100-7'),
('C26','TAB1001–5 broadanimals andraidimages; Maqayisdbh/qdh/wry/sbh physical/figurative diversity.','Optionalmeaning layers notfour mutually literalactions allperforming atonce; oldr13 lexcheck process doesnot theologicalvalidate.','Reader orientation narrows enrichment interpretation layers beforecombinedfinalscene.','Synthesis audited in C02/C05/C08/C09.','TAB100-1|TAB100-2|TAB100-3|MAQ-dbh|MAQ-qdh|MAQ-wry|MAQ-sbh'),
('C27','Raghibhsl10010 goldore explicit; Quran9:34–35 hoardedgoldfirebody,47:37wealthreluctancereleasesgrudges;100:8–10lovemal/chest.','Chestcontents notnecessarily goldorwealth alone; hellbody9:35 foreheadflankback notchest lexicaltoken.','Intertextprecise andwholewealth-goldfire-cropchest projectpartial.','partial (gold purification old, combination inferred).','RAG-hsl|QURAN|TAB100-10'),
('C28','FullTanzil68:17–33 read: dawnharvest, nightvisitor fromRabb,exclude poor,lossandconfession,largerafterlifepunishment explicit.','Textdoesnotsay riderattack causedgardendestruction; than68cases notprove100raid havesameowners orchronology.','Powerfulthematic contrast, notdirectasbab/historicalidentity.','building_blocks_only within checked S100 passage corpus.','QURAN|RAZ100-3|RAZ100-6|BIQ100-8'),
('C29','Biqai100:6 racingthoughts,8 sensiblewealthvsunseenreligion,9 hiddenlove/deadgathering,11 innerouterallknowledge andendreturnsopeningRabb; Razi100:10–11intentionsgroundacts.','Whole outward→inward idea has substantial antecedents; newness cannot claim totalstructureunknown. Bodywateringfarmingmetalgrainlexweb broaderthanexplicitclassicalarchitecture.','Finalnazm notes partial attestation; novelty preciselylimited to combined multi-lexiconimage network.','partial; every major added synthesis gets focused novelty block, not whole volumes absence.','BIQ100-6|BIQ100-8|BIQ100-9|BIQ100-11|RAZ100-10|RAZ100-11'),
('C30','Qurtubi100:1 directlyquotesdabhburnandgraveowl/echo poetry; Zam100:5 explicitlyrejectsforelimb substitution asnotestablished; Maqayisdbh acceptsconditionalcomparison.','Graveowllore literalbelief notsupportedbyayah andnotauthenticatedrevelationtradition. Mughīrāt means raid/dawn action; unrelatedsupposedrain/provision rejected inbaseworkflow remainsrejected.','Relevantrejectedcandidateslistedwith exactclassicalantecedents, nottreatedas omittedpositiveproof.','No blanketabsenceclaims; specificsource rejection preserved.','QURT100-1|ZAM100-5|MAQ-dbh|MAQ-gwr|LEDGER100'),
]
data=[]
for c,s,o,d,n,refs in rows:
 claim=next(x for x in claims['claims'] if x['id']==c)
 data.append({**claim,'primary_support_and_early_attestation':s,'contradiction_or_limit':o,'annotation_decision':d,'novelty_disposition':n,'inspected_evidence_ids':refs.split('|'),'independent_source_count_warning':'Later quotations of the same early report are reception witnesses, not independent historical attestations.' if c in ['C02','C22'] else 'Source independence assessed locally.'})
for r in data:
 if r['id']=='C03':
  r['primary_support_and_early_attestation']+=' Sonraki seçili doğrulamada Raghib ins maddesinin tamamında hayvanın biniciye bakan yanı; Sihah sdr maddesinin tamamında öne çıkan at göğsü; Lisan shd yalnız at-koşu altpasajında koşunun atın yarış başarısına şahitliği gerçekten okundu.'
  r['inspected_evidence_ids']+=['RAG-ans','SIH-sdr','LIS-shd','RAG-jma','SIH-qdh']
 if r['id'] in ['C21','C22','C24']:
  r['primary_support_and_early_attestation']+=' Raghib jma maddesinin TAMAMI ayrıca okundu: servet yığma (70:18/104:2), evrensel toplanma (18:99/11:103/64:9), farklı kalabalık, koşan at, büyük kazan, yumruk ve bukağı aynı maddede açıkça yan yana gelir. Sihah jma ve qdh maddelerinin tamamı da kap/kepçe/ok/at kullanımlarını doğrular. Bu sözlüksel yan yanalığın öncüllüğü korunmalıdır.'
  r['inspected_evidence_ids']+=['RAG-jma','SIH-jma','SIH-qdh']
  r['novelty_disposition']+=' Toplama-servet-haşir sözlük karşılaştırması açık klasik malzemedir; yeni sayılan yalnız daha geniş sure birleşimidir.'
 if r['id'] in ['C06','C11','C13','C18']:
  r['inspected_evidence_ids'].append('SHAD178')
  r['primary_support_and_early_attestation']+=' Ayrıca İbn Hâleveyh Kitab al-Qiraat al-Shadhdha, 1934 basımı, basılı s.178 (PDF sıfır tabanlı sayfa190), Şevaz Sûrat al-Adiyat altbaşlığının TAMAMI görüntüden okundu: aththarna, şeddeli wasatna, bahath, hafif/etken hasala ve an/no-lam nakilleri; başlık bunları şaz okumalar olarak sınıflandırır. Adı belirsiz bir râvi dizgisi kullanılmaz.'
  r['annotation_decision']+=' Şaz sınıflaması artık birincil basılı koleksiyon altbaşlığından doğrulandığı için yalnız bu açıkça okunan varyantlarda canonical:false kullanılabilir; on kıraatin bütün usul/fersh yolları denetlenmiş sayılmaz.'
payload={'prepared_before_composition':True,'base_sha256':claims['base_sha256'],'mode':'comprehensive','target':'100:1-11','matrix_rows':data,'research_boundary':'Seven core S100 digital author-text bodies inspected at all eleven ayah URLs, with duplication/absence recorded; extra Qurtubi sections, IbnAshur opening, exact dictionary entries and specified hadith records. No complete printed-volume audit claimed.'}
(W/'evidence_matrix.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n')
out=['# S100 kaynak karşılaştırma matrisi','', 'Bu matris ekler kaleme alınmadan önce, gerçekten okunan birincil pasajlar temelinde oluşturuldu. Destek, karşı delil ve birleştirme kararları ayrıdır. Dijital ayet sayfası erişimi basılı cildin bütünüyle denetimi değildir.','']
for r in data:
 out.extend([f"## {r['id']} — temel bloklar {', '.join(map(str,r['base_blocks']))}",'',r['claim'],'',f"Destek/öncül: {r['primary_support_and_early_attestation']}",'',f"Karşı delil/sınır: {r['contradiction_or_limit']}",'',f"Karar: {r['annotation_decision']}",'',f"Yenilik: {r['novelty_disposition']}",'',f"İncelenen delil kimlikleri: {' | '.join(r['inspected_evidence_ids'])}",''])
(W/'evidence_matrix.md').write_text('\n'.join(out)+'\n')
claims['workflow_state']='claim_map_then_primary_inspection_then_substantive_evidence_matrix_complete; annotation_composition_not_started'
(W/'claim_map.json').write_text(json.dumps(claims,ensure_ascii=False,indent=2)+'\n')
print('Substantive matrix rows:',len(data),'prepared before composition: yes')
