from pathlib import Path
from collections import Counter, defaultdict
import json, re, hashlib

W=Path(__file__).parent
BASE=Path('/Volumes/aro/projects/prose_generation/_commentary/v16/out/s107/images.r13.map3.nohft.tool.tool/images.md')
OUT=Path('/Volumes/aro/projects/prose_generation/enrichment/v1/out/107/107_enriched.astra-max.md')
assert (W/'evidence_matrix.json').exists(), 'Evidence matrix must precede composition'
counts=Counter(); insert=defaultdict(list); annotations=[]
codes={'reader_note':'READ','tafsir':'TAF','asbab':'ASB','hadith':'HAD','qiraat':'QIR','revelation_history':'REV','historical_context':'HIS','semantic_history':'SEM','nazm':'NAZ','cross_quran':'QUR','method_note':'MET','novelty':'NOV','modern_scholarship':'MOD','source_note':'SRC'}
def add(p,t,ay,role,rel,prose,source,**kw):
 counts[t]+=1
 a={'id':f'S107-{codes[t]}-{counts[t]:03d}','type':t,'tradition':'project','ayah':ay,'role':role,'relation':rel,'status':'explicit','priority':'extended','audience':'advanced','prose':prose,'source':source}
 a.update(kw); insert[p].append(a); annotations.append(a); return a['id']
def nov(p,ay,att,checked,prose,source,**kw):
 return add(p,'novelty',ay,'novelty_assessment','comparative',prose,source,status='interpretive',priority='research',audience='research',classical_attestation=att,checked_sources=checked,**kw)

add(0,'reader_note','107:1-7','reader_orientation','methodological','Bu metinde ana anlatı olduğu gibi korunmuştur. Ek kayıtlar dört ayrı düzeyi görünür kılar: âyetin bağlamdaki anlamı, nakledilmiş yorum, sözlükteki anlam ailesi ve bu projenin kurduğu bağlantı. Bir kelimenin akrabaları aynı âyette birlikte söylenmiş sayılmaz. Hadislerde doğrudan açıklama ile konu benzerliği; yenilik değerlendirmesinde açık öncül ile ayrı yapıtaşları birbirinden ayrılır.','BASE-107|AUDIT-107',priority='core',audience='general')
add(0,'reader_note','107:1-7','reader_orientation','structural','Sûrenin yedi âyeti birlikte okunur: hesabı yalanlama, yetimi itme, yoksulun yiyeceğine teşvik etmeme; ardından namaza karşı kayıtsızlık, gösteriş ve yardımı esirgeme. Dördüncü âyetteki tehdit, onu izleyen nitelemelerden koparılarak bütün namaz kılanlara yöneltilemez. Buradaki sözlük imgeleri bu açık akışın çevresinde durur.','QUR-AR|TAB-107',priority='core',audience='general',source_ref='107:1–7; Taberî 107:4–7')

add(2,'tafsir','107:1','anchor','direct_tafsir','Taberî, dîni burada Allah’ın karşılık vermesi ve hesap görmesi olarak açıklar; İbn Abbas’tan Allah’ın hükmü, İbn Cüreyc’den hesap açıklamasını aktarır. Râzî, İslâm anlamını da kaydeder, fakat hesabı yalanlamayı bağlama daha uygun bulur. Böylece açılıştaki soru, yalnız bir inanç cümlesini değil, onun davranışta açığa çıkan sonucunu gösterir.','TAB-107|RAZ-107',tradition='rivayet',priority='core',audience='general',source_ref='Taberî 107:1; Râzî 107:1, mesele 4')
add(2,'tafsir','107:1','clarification','grammatical','Râzî, soruyu şaşırtma ve dikkat çekme işleviyle okur; hitabın Peygamber’e yönelmesi yanında her akıllı muhataba açılmasını da mümkün görür. Bikāî’nin haber ver anlamındaki açıklaması ve Râgıb’ın رأي maddesindeki dikkat formülü, ana metnin okuru sahneye çağıran sesine açık öncüllerdir.','RAZ-107|BIQ-107|RAG-LEX',tradition='dirayet',source_ref='Râzî 107:1, mesele 2; Bikāî 107:1; Râgıb, رأي')
add(2,'modern_scholarship','107:1-3','disagreement','grammatical','İbn Âşûr, görmeyi burada tek nesne alan gözle görme olarak çözümler: inkârcıların bilinen davranışları göz önündeymiş gibi sunulur. Ayrıca muzari fiillerde alışkanlık ve tekrar vurgusu bulur. Bu, dikkat çağrısını destekler; fakat fiilin zorunlu olarak iç görü anlamına geçtiği iddiasını sınırlar. Ana metindeki ahlâkî görme, bu dilbilgisel tercihin üzerine kurulmuş okuma olarak kalır.','ASH-107',tradition='dirayet',status='interpretive',source_ref='et-Tahrîr ve’t-tenvîr, 107:1, soru ve الرؤية بصرية paragrafları')
add(2,'revelation_history','107:1-7','chronology','historical','Mekkî, Medenî ve bölünmüş iniş görüşleri birlikte korunmalıdır. Kurtubî sûrenin başında Mekkî ve Medenî nakilleri verir. İbn Âşûr ilk üç âyetin Mekke’de, kalanların Medine’de indiği görüşünü daha görünür bulur; bu tercih, son kısmı münafıklar hakkında okuma ile bağlantılıdır. Onun on yedinci sûre, Tekâsür’den sonra Kâfirûn’dan önce kaydı ise açıkça sûrenin Mekkî sayılması koşuluna bağlıdır; kesin tarih değildir.','QURT-107|ASH-107',tradition='historical',status='disputed',historicity='contested',priority='core',audience='general',source_ref='Kurtubî 107:1 sûre girişi; İbn Âşûr 107:1 sûre girişi')
add(2,'asbab','107:1-3','asbab_context','asbab','Vâhidî, Mukātil ve Kelbî’ye nispetle Âs b. Vâil’i; İbn Cüreyc’e nispetle et isteyen yetimi değnekle uzaklaştıran Ebû Süfyân’ı anar. Râzî ayrıca Velîd b. Mugīre, Ebû Cehil ve adı verilmeyen bir münafık hakkındaki açıklamaları sıralar. Bunlar tek bir kesin olayın bağımsız doğrulamaları değildir. Okunan metinlerdeki nispetler aktarılır; burada bütün isnadları yeniden incelenmiş, tarihî öznesi belirlenmiş bir haber bulunduğu ileri sürülmez.','WAH-ASB-107|RAZ-107',tradition='rivayet',status='reported',historicity='uncertain',priority='core',audience='general',source_ref='Vâhidî, Esbâbü’n-nüzûl, 107:1–2; Râzî 107:1, mesele 3')
add(2,'source_note','107:1-3','source_criticism','historical','Ebû Süfyân anlatısında Vâhidî ve Râzî haftada iki deve kesildiğini söylerken İbn Âşûr haftada bir deve der. Bu küçük fark bile sonraki anlatımları ayrı şahitler gibi toplamamayı gerektirir. Sebep belirli bir kişiyle ilgili kabul edilse dahi İbn Âşûr, ifadenin kapsamının o kişiye kapanmadığını özellikle belirtir.','WAH-ASB-107|RAZ-107|ASH-107',status='reported',priority='research',audience='research',source_ref='Vâhidî 107:1–2; Râzî 107:1 mesele 3; İbn Âşûr 107:1 son paragraflar')
add(2,'qiraat','107:1','clarification','grammatical','Uleymî’nin on okuyucuyu esas alan aktarımında Nâfi‘ ve Ebû Ca‘fer ikinci hemzeyi kolaylaştırır, Kisâî onu düşürür, diğerleri tahkikle okur. Bu seslendirme ayrılığı sorunun temel işlevini değiştirmez. Zemahşerî’nin hemzesiz biçime dilsel tercih bakımından mesafeli durması, Kisâî’nin nakledilmiş okuyuşunu yok sayma gerekçesi yapılamaz. İbnü’l-Cezerî’nin en-Neşr’i bu çalışmada doğrudan incelenmemiştir; burada doğrulanan metin Uleymî’dir.','ULA-107|KASH-107',tradition='dirayet',canonical=True,priority='research',audience='research',source_ref='Fethu’r-rahmân, 107:1; el-Keşşâf 107:1')
add(2,'qiraat','107:1','early_attestation','grammatical','Taberî, İbn Mes‘ûd’a nispetle bâ olmadan يُكَذِّبُ الدِّينَ biçimini; Zemahşerî ve Râzî ise أَرَأَيْتَكَ biçimini kaydeder. Bunlar müfessirlerin aktardığı sahâbe okuyuşu kayıtları olarak sunulur. Her birinin ayrı isnadı ve kıraat kitaplarındaki teknik tasnifi burada doğrulanmadığından kanonik yahut şâz etiketi eklenmemiş, ana metnin Hafs lafzı değiştirilmemiştir.','TAB-107|KASH-107|RAZ-107',tradition='rivayet',status='reported',priority='research',audience='research',source_ref='Taberî, Zemahşerî ve Râzî 107:1')

add(3,'tafsir','107:6','clarification','grammatical','Zemahşerî ve Râzî, gösterişte iki yönü açıkça anlatır: kişi amelini insanlara gösterir, onlar da beğeni ve övgülerini ona gösterir. Dolayısıyla karşılıklı görünme düşüncesinin klasik dayanağı vardır. Bununla birlikte ana metindeki تَراءى örneği başka bir fiil kalıbıdır; يُراءون kelimesinin kendi başına ayna, karşılıklı bakış yahut fiziksel bir yansıma anlattığı söylenemez.','KASH-107|RAZ-107|SIH-LEX',tradition='dirayet',source_ref='Zemahşerî 107:6; Râzî 107:6 son soru-cevap; Cevherî رأى')
add(3,'method_note','107:1-7','constraint','structural','Gösteriş âyeti sûrenin altıncı âyetidir; son sözü yedinci âyette yardımı esirgeme söyler. Bu yüzden ana metindeki görmeyle kapanış ifadesi, iki görme kelimesi arasındaki bir çerçeve olarak anlaşılmalıdır. Sûrenin gerçek bitişini dışarıda bırakan tam bir ilk-son sözcük halkası değildir.','QUR-AR',priority='core',audience='general')
N_mirror=nov(3,'107:1|107:6-7','partial','Zemahşerî 107:1 ve 107:6 karşılıklı gösterme açıklaması|Râzî 107:1 mesele 2 ve 107:6 son soru-cevap|Beydâvî 107:6|Cevherî رأى, ayna ve تراءى alt açıklamaları|Râgıb رأي, ayna tanımı','Çift yönlü gösterme klasik açıklamada açıktır; ayna tutma ve aynada görüntü ise sözlükte ayrı örneklerdir. Bu araçları açılıştaki dikkat çağrısı ile birleştiren ayna sahnesi, belirtilen tefsir pasajlarında açıkça bulunmadı. Yenilik iddiası yalnız bu birleşime aittir; iki taraflı gösteriş fikrine ait değildir.','KASH-107|RAZ-107|BAY-107|SIH-LEX|RAG-LEX',connection='resonant')
add(4,'method_note','107:1-7','methodological_note','lexical','Bir sözlük maddesi, aynı kökten türemiş kelimeler yanında ayrı köken önerilerini, deyimleri, seslenişleri ve kıyas dışı biçimleri de barındırabilir. Bu ek katmanda Mekāyîs’in kök için koyduğu sınır önceliklidir. Özellikle dipteki zemin, ev rafı ve ateş anlatılarında sözlükte yan yana bulunma ile ortak etimoloji aynı şey sayılmayacaktır.','MQ-LEX|AUDIT-107',priority='core',audience='general',source_ref='Mekāyîs: حضض، سهو، صلو')
add(5,'tafsir','107:6','constraint','direct_tafsir','Râzî, inancını gizleyen münafık ile ibadetini olduğundan daha huşûlu gösteren kişiyi ayırır; herkesin önünde ibadet etmek tek başına riyâ değildir. Zemahşerî de farzların görünür oluşunu ve başkalarına örnek olmak amacıyla yapılan açıklığı ayrı tutar. Kınanan şey, insanların beğenisini ibadetin maksadı haline getirmektir. Bu ayrım, başkasının niyetini yalnız dış görünüşten kesinleştirmeyi sınırlar.','RAZ-107|KASH-107',tradition='dirayet',priority='core',audience='general',source_ref='Râzî ve Zemahşerî 107:6')
add(5,'hadith','107:6','corroboration','thematic','Müslim 2985’te Ebû Hüreyre’den gelen kudsî hadis, Allah için yapılan işe başka bir ortak katma yönelişini reddeder; Müslim 2986’daki İbn Abbas rivayeti ise duyurmak ve göstermek amacıyla yapılan ameli uyarının konusu yapar. İkisi de Sahîh-i Müslim’dedir. Bunlar 107:6’nın iniş sebebi yahut doğrudan âyet açıklaması olarak değil, niyet eksenini destekleyen hadisler olarak kullanılır.','MUS-2985|MUS-2986',tradition='hadith',hadith_grade='sahih',audience='general',source_ref='Sahîh-i Müslim 2985, 2986')
add(5,'hadith','107:6','constraint','thematic','Ebû Zer’in, hayırlı iş yapıp insanlar tarafından övülen kimseyi sorması üzerine verilen cevap, bu övgüyü mümine gelen peşin bir müjde olarak niteler. Müslim 2642a, her beğenilmenin riyâ sayılmadığını gösterir. Övgüyü amaçlayarak amel etmekle, hayırlı amelden sonra kendiliğinden gelen övgü aynı durum değildir.','MUS-2642A',tradition='hadith',hadith_grade='sahih',audience='general')
add(6,'tafsir','107:5-7','anchor','direct_tafsir','Taberî, İbn Abbas ve Mücâhid’den insanların yanında namaz kılıp yalnızken bırakma açıklamalarını aktarır. Süyûtî’nin Zeyd b. Eslem’den verdiği açıklamada ise görünür namaz ile gizlenebilen zekât karşılaşır. Râzî bu bağı açık bir terslik olarak kurar: Allah’a yönelmesi gereken amel insanlara sergilenirken insanların hakkı onlardan saklanmaktadır.','TAB-107|SUY-107|RAZ-107',tradition='rivayet',priority='core',audience='general',source_ref='Taberî 107:5; Süyûtî 107:7 Zeyd b. Eslem; Râzî 107:7 son الملاءمة açıklaması')
N_visible=nov(6,'107:5-7','explicit','Râzî 107:7, الصلاة لي والماعون للخلق ile başlayan uygunluk açıklaması|Süyûtî 107:7, Zeyd b. Eslem’in görünür namaz ve gizli zekât açıklaması|Taberî 107:5, İbn Abbas ve Mücâhid nakilleri','Görünen namaz ile esirgenen yardımın birbirini açıklaması projenin ilk kez bulduğu bir karşıtlık değildir. Râzî iki yönü tek cümlede birleştirir; Süyûtî’nin nakli de görünürlük ayrımını taşır. Ana metnin seyirci ve eşik dili bu açık klasik öncülün edebî genişletilmesidir.','RAZ-107|SUY-107|TAB-107',connection='direct')
add(7,'cross_quran','107:1|107:6','intertext','comparative','Nisâ 4:142, namazda gösterişi aynı fiille anlattığı için en doğrudan paraleldir. Alak 96:9–14, görme sorusu, namazı engelleme ve Allah’ın görmesini bir araya getirir; fakat oradaki engellenen namaz kılan ile Mâûn’daki gösteriş yapan aynı rol değildir. Şuarâ 26:218–219 ilâhî görmeye, İnsan 76:8–9 ve Leyl 92:19–20 ise karşılık beklemeden vermeye karşı sahneler sunar.','QUR-AR',status='interpretive',connection='strong',source_ref='4:142; 96:6–14; 26:218–219; 76:8–9; 92:19–20')
N_seeing=nov(7,'107:1-7','building_blocks_only','Râgıb رأي, أَرَأَيْتَ ve 96:9 örneği|Taberî 107:1 ve 107:6|Zemahşerî 107:1 ve 107:6|Râzî 107:1 mesele 2 ve 107:6|Bikāî 107:1 ve 107:6','Görme, ilâhî denetim, gösteriş ve karşılıksız verme âyetlerde açıkça bulunur. Alak, Şuarâ, Nisâ, İnsan ve Leyl’i Mâûn’un tek bir bakış haritasında buluşturan birleşim belirtilen pasajlarda açık biçimde görülmedi. Bu sonuç yalnız okunan pasajlar içindir; söz konusu diğer sûrelerin bütün tefsirleri taranmış değildir.','QUR-AR|RAG-LEX|TAB-107|KASH-107|RAZ-107|BIQ-107',connection='strong')

add(10,'semantic_history','107:1|107:6','semantic_range','lexical','Râgıb’ın كذب maddesinde boyayla süslü dokumaya benzetilmiş kumaş, haliyle yalan söyleyen bir örnek olarak yer alır; yalanın söz kadar davranışla da kurulabildiği açıklanır. Bu, kumaş imgesinin sözlük dayanağıdır. Ancak كذّابة adlı nesne, 107:1’deki يُكذّب fiilinin çevirisi değildir; kumaşın üretim tekniğine dair ana metindeki ayrıntılı karşılaştırma da sözlük cümlesini genişletir.','RAG-LEX',tradition='dirayet',source_ref='el-Müfredât, كذب; الكذابة ثوب alt örneği')
add(10,'tafsir','107:1|107:4-6','corroboration','direct_tafsir','Râzî, namaz kötülükten alıkoyuyorsa yetimi iten kişinin namazının neden bunu yapmadığını sorar. Cevabı, burada namazın riyâ ve kayıtsızlıktan yapılmış bir görünüşe dönüşmesidir. Ana metindeki yüzeyi doğru, içi boş ibadet karşıtlığının tefsirde açık bir dayanağı böylece bulunur; kumaş benzetmesi ise Râzî’nin cümlesinde geçmez.','RAZ-107',tradition='dirayet',source_ref='107:4–5 ortak açıklama, mesele 1 ikinci vech; 29:45 atfı')
N_cloth=nov(10,'107:1|107:4-6','partial','Râgıb كذب, fiille yalan ve boyalı kumaş paragrafları|Râzî 107:4–5 mesele 1 ikinci vech|Zemahşerî 107:5–6|Beydâvî 107:5–6','Yüzey ile iç arasındaki bozulma ve gösterişten yapılmış namaz eski açıklamalardır; boyalı kumaş da eski bir sözlük örneğidir. Bu ikisini Mâûn’da aynı kumaş sahnesine yerleştiren bağlantı belirtilen tefsir pasajlarında görülmedi. Dolayısıyla öncüller korunarak yalnız birleşimin proje sentezi olduğu söylenebilir.','RAG-LEX|RAZ-107|KASH-107|BAY-107',connection='resonant')
add(11,'source_note','107:1|107:5-6','source_criticism','lexical','İbn Fâris, saldırıya yönelip geri durmayı كذب ailesinde açıklar; devenin süt beklentisini boşa çıkarmasına dair açıklamayı ise aktarıldığına işaret ederek verir ve üzerinde durulması gerektiğini söyler. Bu ihtiyat silinmemelidir. Râgıb’daki görünür gebelik ve bekleneni vermeyen süt örnekleri, sûrede bir deve yahut koşucu bulunduğunu göstermez.','MQ-LEX|RAG-LEX',source_ref='Mekāyîs كذب, زعموا ve وفيه نظر kayıtları; Müfredât كذب ve رأي')
N_runner=nov(11,'107:1|107:5-6','building_blocks_only','İbn Fâris كذب, yarım kalan saldırı ve süt örnekleri|Râgıb كذب ve رأي, süt ve gebelik örnekleri|Taberî 107:5|Râzî 107:4–5 mesele 2–3','Kesilen hareket, boşa çıkan beklenti ve görünür doğruluk sözlükte ayrı yapıtaşlarıdır. Bunların seyirci gidince duran ibadetle ve geciken iyilikle tek bir koşu anlatısında birleştirilmesi belirtilen sûre açıklamalarında bulunmadı. Bağlantı, etimolojik bir zorunluluk veya olay rivayeti değil, sınırlı bir benzetmedir.','MQ-LEX|RAG-LEX|TAB-107|RAZ-107',connection='resonant')
add(12,'semantic_history','107:1','constraint','lexical','Ezherî, دين maddesinde yemin edenin niyetini esas alma anlamındaki deyimi İbnü’l-A‘râbî’den aktarır. Bu, hukuk dilinde belli bir kullanımdır; بِالدِّين ifadesinin bağlamdaki hesabı yalanlama anlamını niyet okuma şeklinde değiştirmez. Ayrıca böyle bir deyimden başkalarının gizli inancını kesin olarak bildiğimiz sonucu çıkmaz.','TAH-LEX|TAB-107',tradition='dirayet',source_ref='Tehzîbü’l-luga دين, دينت الحالف alt açıklaması; Taberî 107:1')
nov(12,'107:1|107:6','building_blocks_only','Ezherî دين, dinte’l-hâlif açıklaması|Taberî 107:1|Râzî 107:1 mesele 4 ve 107:6 münafık/mürâî ayrımı','Yemindeki niyet deyimi ile Mâûn’un hesap ve gösteriş eleştirisini doğrudan bağlayan açıklama bu pasajlarda görülmedi. Sözlük örneği içtenlik meselesini düşündürebilir; âyetin dîn kelimesinin özel hukuk anlamına geldiğini kanıtlamaz.','TAH-LEX|TAB-107|RAZ-107',connection='resonant')
add(13,'tafsir','107:4-6','disagreement','direct_tafsir','Taberî’de namazı vaktinden sonraya bırakma, yalnızken terk etme ve kılsa da kılmasa da aldırmama açıklamaları bulunur. Kendi tercihi bu kayıtsızlığın farklı biçimlerini içine alan geniş okumadır. İbn Kesîr de vakit, şartlar ve huşû bakımından ihmal ihtimallerini toplar. Böylece kınama, yalnız tek bir dalgınlık ânına ya da tek bir tarihî gruba kolayca indirgenmez.','TAB-107|IK-107',tradition='rivayet',priority='core',audience='general',source_ref='Taberî 107:5, ihtilaf ve tercih; İbn Kesîr 107:5')
add(13,'tafsir','107:5','disagreement','grammatical','Zemahşerî ve Beydâvî, namazın içinde meydana gelen sehiv ile namaza karşı kayıtsızlık arasındaki عَنْ / فِي ayrımını vurgular. Râzî ise عَنْ ifadesinden mutlak namaz terkini çıkarmanın, bu kişilerin namaz kılanlar diye adlandırılmasıyla gerilim taşıdığını tartışır; dıştan eda ile içten boşluk ve süreklilik cevaplarını verir. Edat farkı açıklayıcıdır, fakat bütün yorum ihtilafını tek başına bitirmez.','KASH-107|BAY-107|RAZ-107',tradition='dirayet',status='disputed',priority='core',audience='general',source_ref='Zemahşerî ve Beydâvî 107:5; Râzî 107:4–5 mesele 2–3')
add(13,'hadith','107:5','constraint','thematic','İbn Mes‘ûd’un Müslim 572a rivayetinde Peygamber, insan olarak unutabileceğini söyler, hatırlatılmasını ister ve sehiv secdesi yapar. Bu sahih haber, namazda istemeden unutmayı ahlâkî kayıtsızlıkla bir tutmayı engeller. Âyetin doğrudan açıklaması olarak değil, yorumun sınırını gösteren bağımsız bir namaz rivayeti olarak kullanılır.','MUS-572A',tradition='hadith',hadith_grade='sahih',priority='core',audience='general')
add(13,'hadith','107:5-6','corroboration','thematic','Enes’in Müslim 622 rivayeti, güneş batmaya yaklaşıncaya kadar bekleyip dört rekâtı aceleyle kılan ve Allah’ı pek az anan kimsenin namazını eleştirir. Sahih olan bu metin, dikkatsizliğin iradî ve sürekli biçimini görünür kılar. Hadisin kendi lafzında Mâûn’a atıf yoktur; doğrudan sûre tefsiri diye sunulmaz.','MUS-622',tradition='hadith',hadith_grade='sahih',audience='general')
add(13,'source_note','107:5','source_criticism','direct_hadith_tafsir','Sa‘d b. Ebî Vakkās’a dayanan vakti geciktirme açıklamasının Peygamber’e yükseltilmiş biçimi ile sahâbî sözü olarak duran biçimi ayrılmalıdır. Süyûtî, Hâkim ve Beyhakī’nin mevkuf biçimi daha doğru bulduğunu aktarır; İbn Kesîr de yükseltme yolunun eleştirisini verir. Ümit ve korku taşımadan kılma açıklamasını Peygamber’e nispet eden Ebû Berze rivayeti ise İbn Kesîr’de zayıf râvi ve adı bilinmeyen şeyh sebebiyle eleştirilir.','SUY-107|IK-107|TAB-107',tradition='hadith',status='disputed',hadith_grade='not_assessed',priority='research',audience='research',source_ref='Taberî 107:5; Süyûtî 107:5; İbn Kesîr 107:6 içindeki ilgili iki rivayetin tenkidi')
nov(13,'107:5','explicit','Zemahşerî 107:5 عَنْ / فِي sorusu|Beydâvî 107:5|Râzî 107:4–5 mesele 2–3|Taberî 107:5 tercih paragrafı','Namazdan gaflet ile namaz içindeki sehiv ayrımı açık klasik öncüle sahiptir. Projenin kesilen koşu ve boyalı kumaşı bu ayrımın çevresine yerleştirmesi yenidir denebilecek bileşim düzeyindedir; edat ayrımı başlı başına yeni bir buluş değildir. Râzî’nin itirazları da klasik geleneğin tek sesli olmadığını gösterir.','KASH-107|BAY-107|RAZ-107|TAB-107',connection='direct')
add(14,'cross_quran','107:1|107:4-6','corroboration','comparative','Bakara 2:264’te gösteriş için verilen sadaka, yağmurun örtüsünü sıyırdığı kaya benzetmesiyle birlikte gelir; bu, görünüş ile dayanıklılık karşıtlığına açık bir Kur’an örneğidir. Buna karşılık 53:33–34’te az verip kesilme, 70:23 ve 34’te namazda devam ve koruma, 98:5’te ihlâs, namaz ve zekât birlikte bulunur. Bunlar ana imgeyi aydınlatır; kumaş veya koşucunun Mâûn’daki örtük kelime anlamı olduğunu göstermez.','QUR-AR',status='interpretive',connection='strong',source_ref='2:264; 53:33–34; 70:23,34; 98:5')

add(17,'semantic_history','107:2','semantic_range','lexical','Mekāyîs, يُتم ailesini tek kalma ekseninde kurar. Ezherî insanlarda baba, hayvanlarda anne kaybını ayırır; el-Mufaddal’ın gaflet, Ebû Amr’ın gecikme açıklamalarını ve tek inci örneğini ayrıca aktarır. Bunlar eşdeğer tanımlar yahut İbn Fâris’in tek bir türetimi değildir. Yetimin korunmaya muhtaç oluşu bağlamda esastır; her yetimin ağır hareketli veya fark edilmez olduğu ileri sürülemez.','MQ-LEX|TAH-LEX',tradition='dirayet',priority='core',audience='general',source_ref='Mekāyîs يتم; Tehzîbü’l-luga يتم, PageV14P241')
add(17,'historical_context','107:2','historical_context','historical','Taberî, yetimi hakkından veya yiyeceğinden itme açıklamalarını nakleder. Kurtubî bunu küçüklerin mirastan dışlanması anlatısıyla ilişkilendirir. Burada doğrulanan, tefsirin kaydettiği bu toplumsal yorumdur; bütün İslâm öncesi ailelerde tek bir miras düzeni bulunduğuna dair bağımsız tarih araştırması yapılmış değildir. Çocuğun hem bedeni hem hakkı bakımından korunmasızlığı, şiddetin kapsamını genişletir.','TAB-107|QURT-107',tradition='historical',status='reported',historicity='uncertain',source_ref='Taberî ve Kurtubî 107:2')
add(17,'hadith','107:2','contrast','thematic','Sehl b. Sa‘d’ın Buhârî 6005 rivayetinde yetimi gözeten kişi, cennette Peygamber’e yakınlıkla anılır. Bu sahih haber, itip uzaklaştırmanın karşısına sürekli himayeyi koyar. Sûrenin doğrudan tefsiri veya yetimlik kelimesinin etimolojisine delil değildir.','BUK-6005',tradition='hadith',hadith_grade='sahih',audience='general')
N_orphan=nov(17,'107:2|107:5','building_blocks_only','İbn Fâris يتم|Ezherî يتم, el-Mufaddal ve Ebû Amr nakilleri|Taberî 107:2 ve 107:5|Râzî 107:3 yetim açıklaması ve 107:4–5 mesele 1','Yetimliği gaflet yahut gecikmeyle açıklayan eski sözlük görüşleri vardır. Bunları namazdan gaflet ile aynı unutma sahnesinde buluşturan özel bağ, belirtilen sûre pasajlarında açıkça bulunmadı. Allah’ın emrine ve yaratılanlara karşı iki eksenli kusur ise Râzî’de zaten açıktır; bu geniş ahlâkî birlik projeye mal edilemez.','MQ-LEX|TAH-LEX|TAB-107|RAZ-107',connection='resonant')
add(18,'source_note','107:2|107:5-6','constraint','lexical','İbn Fâris, Süha’nın silikliği sebebiyle سهو ailesine bağlanmasını mümkün görür; kesin bir türetim hükmü vermez. Aynı maddede başkasının sürçmelerini büyütmeden geçme anlamındaki müsâhât da vardır. Bu olumlu göz yumma ile korunmasız insanı görmezden gelme, yöneldikleri nesne bakımından ayrılır. Yıldız, sûrede geçen bir nesne değildir.','MQ-LEX',source_ref='Mekāyîs سهو, السها محتمل ve المساهاة açıklamaları')
N_suha=nov(18,'107:1-2|107:5-6','building_blocks_only','İbn Fâris سهو, yıldız ve müsâhât alt açıklamaları|Taberî 107:1–7|İbn Kesîr 107:1–7|Süyûtî 107:1–7|Zemahşerî 107:1–7|Râzî 107:1–7|Beydâvî 107:1–7|Bikāî 107:1–7|Kurtubî 107:1–7','Silik yıldız, küçük kusuru bağışlayarak geçme ve namazdan gaflet ayrı kaynak parçalarıdır. Süha’yı görünmeyen yetim ile görünmek isteyen riyakârın arasına yerleştiren birleşim okunan sûre açıklamalarında bulunmadı. Bu, sınırlı külliyat için bir yokluk sonucudur; bütün klasik literatürde bulunmadığı iddiası değildir. Üstelik sözlükteki kök bağlantısı da ihtimalli olduğundan imge ikincil kalır.','MQ-LEX|TAB-107|IK-107|SUY-107|KASH-107|RAZ-107|BAY-107|BIQ-107|QURT-107',connection='speculative')
add(19,'source_note','107:3','clarification','direct_tafsir','Üçüncü âyet yoksulun yiyeceğini açıkça adlandırır: طَعَامِ الْمِسْكِينِ. Ana metindeki yemeğin ağza alınmaması, âyetin bunu söylemediği biçiminde okunmamalıdır; eksiklik, tasvir edilen kişinin doyurmaya teşvik etmemesindedir. Metnin kendi söylediği ile kişinin yapmadığı eylem ayrı tutulur.','QUR-AR|TAB-107',priority='core',audience='general',source_ref='107:3; Taberî 107:3')
add(19,'hadith','107:2-3','corroboration','thematic','Müslim 1039a’daki Ebû Hüreyre rivayeti, gerçek ihtiyaç sahibinin her zaman kapı kapı dolaşıp istemediğini; bazen fark edilmediği için kendisine yardım da ulaşmadığını belirtir. Bu sahih hadis fark etme sorumluluğunu güçlendirir. Yıldız benzetmesini yahut yetim kelimesinin kökenini doğrulamaz; ihtiyaç ile görünür talep arasındaki farkı açıklar.','MUS-1039A',tradition='hadith',hadith_grade='sahih',audience='general')
add(20,'cross_quran','107:2|107:5|107:7','constraint','comparative','Zâriyât 51:11’de غمرة içinde sâhûn oluş, bağlamda şaşkınlık ve gaflet halini anlatır; gerçek bir su kütlesinde bulunmayı gerektirmez. Duhâ 93:6 ve 9 yetimin barındırılması ile ezilmemesini doğrudan bir araya getirir. Tevbe 9:67’de kapalı eller ve unutma aynı tasvirde bulunur. Bunların ilkinde su imgesini, son ikisinde sosyal davranışı öne çıkarma farklı güçte bağlantılardır.','QUR-AR',status='interpretive',connection='resonant',source_ref='51:10–11; 93:6,9; 9:67')
nov(20,'107:2|107:5|107:7','building_blocks_only','Taberî 107:2,5,7|Râzî 107:3 yetim ve 107:4–5 gaflet açıklamaları|Bikāî 107:2,5,7|İbn Fâris سهو','Gaflet, kapalı el ve yetime sığınak sağlama Kur’an’da ayrı bağlamlarda açıktır. Bunları gamranın su çağrışımıyla birlikte Mâûn’un tek bir ihmal manzarasına dönüştüren okuma belirtilen pasajlarda bulunmadı. Duhâ, Zâriyât ve Tevbe’nin bütün klasik açıklamaları için ayrıca tarama yapıldığı ileri sürülmez.','QUR-AR|TAB-107|RAZ-107|BIQ-107|MQ-LEX',connection='resonant')

add(23,'tafsir','107:2','anchor','direct_tafsir','Taberî’de yetimi sertlikle uzaklaştırma, hakkını vermeme ve doyurmama açıklamaları birlikte yer alır. Râzî, incitici davranışın maddî hakkı esirgemeye veya yardımı kabalıkla reddetmeye dönüşebildiğini tartışır. Bu doğrudan anlam, aynı ses ailesindeki teşvik seslerinden önce gelir: âyetin fiili yetimi kaldırmak değil, onu itip kakmaktır.','TAB-107|RAZ-107',tradition='dirayet',priority='core',audience='general',source_ref='Taberî 107:2; Râzî 107:3 sayfasının başındaki 107:2 tartışması')
add(23,'qiraat','107:2','semantic_range','grammatical','Râzî, şeddesiz يَدَع biçimini terk etmek; يدعو şeklinde aktardığı davet okuyuşunu ise yetimi gösteriş veya hizmet maksadıyla çağırmak yönünde yorumlayan nakilleri verir. Bu kayıtlar müfessirin bildirdiği alternatiflerdir. Okuyucu isnadı ve teknik kıraat tasnifi burada ayrıca doğrulanmadığından bunlardan metne eşdeğer kanonik seçenekler üretilmez; ana metindeki يَدُعّ korunur.','RAZ-107',tradition='rivayet',status='reported',priority='research',audience='research',source_ref='Râzî 107:3 sayfası, 107:2 fiiline ilişkin okuyuş açıklamaları')
add(23,'method_note','107:2','rejected_candidate','lexical','Ezherî, tökezleyene دع دع denmesini kalkıp toparlanması için bir sesleniş olarak kaydeder. Ancak İbn Fâris, çoban ve tökezleyenle ilgili bu seslenişlerin düzenli kök kıyasına pek elvermediğini açıkça söyler. Bu nedenle iten el ile kaldıran ses arasında edebî karşıtlık kurulabilir; âyet fiilinin iki zıt anlamı aynı anda taşıdığı savı reddedilir.','TAH-LEX|MQ-LEX',connection='rejected',source_ref='Tehzîb دع; Mekāyîs دعع, seslerin kıyas dışılığı açıklaması')
add(24,'method_note','107:3','rejected_candidate','lexical','Mekāyîs, حضض maddesinde teşvik ile alçak zemin için iki ayrı asıl belirtir; ayrıca Halîl’den, sürme ve yürütme bağlamında حث kullanıldığı, حض kullanımının bundan ayrıldığı kaydını verir. Dolayısıyla dipte duran insanı yukarı itme sahnesi tek bir etimolojinin sonucu sayılamaz. Ana metindeki mekânsal karşıtlık, bu açık sözlük ayrımı bilinerek kurulmuş bir imge olarak okunmalıdır.','MQ-LEX',connection='rejected',priority='core',audience='general',source_ref='Mekāyîs حضض, أصلان ve حض/حث ayrımı')
add(24,'tafsir','107:3','clarification','grammatical','Râzî, yiyeceğin yoksula izafetini onun hakkının gözetilmesine bağlar; teşvikin kişinin kendisine veya başkalarına yönelik anlaşılmasını da tartışır. Bikāî de ihtiyaç sahibine ulaşması gereken geçim payını vurgular. Böylece mesele yalnız eliyle vermemek değil, başkalarını iyiliğe çağırmaktan da kaçınmaktır.','RAZ-107|BIQ-107',tradition='dirayet',priority='core',audience='general',source_ref='Râzî 107:3, طعام المسكين ve ولا يحض açıklamaları; Bikāî 107:3')
add(25,'method_note','107:2-3|107:7','constraint','lexical','Miskînin سكن ailesiyle bağı, ihtiyaç yüzünden güçsüz düşmeyi düşündürebilir; her yoksulun bedenen hareketsiz olduğu anlamına gelmez. Benzer biçimde منع ailesindeki korunmuş yer, aynı engellemenin herkese aynı ahlâkî değeri taşıdığını göstermez. Değer, kimin hangi haktan ve hangi zarardan korunduğuna göre belirlenir.','MQ-LEX|TAB-107',connection='resonant',source_ref='Mekāyîs سكن ve منع; Taberî 107:2–3,7')
N_hands=nov(25,'107:2-3|107:7','building_blocks_only','Ezherî دع, tökezleyene sesleniş|İbn Fâris دعع، حضض، سكن، منع|Taberî 107:2–3 ve 107:7|Râzî 107:3, itme ve teşvik açıklamaları','İten, kaldıran, teşvik eden ve koruyan hareketleri tek el sahnesinde toplamak proje sentezidir. İtmenin âyetteki anlamı eski ve doğrudandır; fakat olumlu sesleniş, dipteki zemin ve koruyucu engel ayrı yapıtaşlarıdır. Mekāyîs’in iki asıl ve kıyas dışı ses ayrımları, bu birleşimin etimolojik kanıt diye sunulmasını engeller.','TAH-LEX|MQ-LEX|TAB-107|RAZ-107',connection='resonant')
add(26,'tafsir','107:3','constraint','direct_tafsir','Râzî, teşvik etmemenin her koşulda aynı hükme taşınmasına itiraz eder: güç yetirememe, sözün yarar vermemesi veya zarar doğurması gibi durumlar ayrılmalıdır. Sûrenin devamlılık gösteren kayıtsız kişi tasviri, tek bir sessizlikten herkesin inancını hükme bağlama izni vermez.','RAZ-107',tradition='dirayet',priority='core',audience='general',source_ref='107:3, teşvik etmemenin hükmüne ilişkin itiraz ve cevap')
add(26,'hadith','107:2-3','contrast','thematic','Buhârî 5353’te Ebû Hüreyre’den nakledilen sahih hadis, dulun ve yoksulun geçimi için çalışanı Allah yolunda mücadele eden yahut gece ibadet edip gündüz oruç tutan kimseye benzetir. Böylece sosyal bakım ile ibadetin değeri aynı cümlede buluşur. Benzetme, namazın hukukî yükümlülüğünün sosyal hizmetle yer değiştirmesi demek değildir.','BUK-5353',tradition='hadith',hadith_grade='sahih',audience='general')
add(27,'cross_quran','107:2-3','intertext','comparative','Yetimin itilmesi ile cehenneme itilme bağı yalnız projenin çağrışımı değildir: Râzî, يَدُعّ fiilini açıklarken Tûr 52:13’ü açıkça getirir; Ezherî de iki yeri aynı maddede yan yana anar. Fecr 89:17–18 yetim ve yiyeceğe teşviki birlikte, Beled 90:15–17 ise yetim, yoksul ve merhamet tavsiyesini birlikte verir. Kalem’deki bahçe sahiplerinin yoksulu dışarıda bırakması bu halkaya eklenen ayrı bir Kur’an sahnesidir.','QUR-AR|RAZ-107|TAH-LEX',status='interpretive',connection='strong',source_ref='Râzî 107:3 başı; Tehzîb دع; 52:13–14; 89:17–18; 90:15–17; 68:17,23–24')
N_push=nov(27,'107:2-3|107:7','partial','Râzî 107:3, 52:13 ve merhamet/sabır tavsiyesi bağlantıları|Ezherî دع, 52:13 ile 107:2|Bikāî 107:2–3|Kurtubî 107:3, 69:34 ve 36:47 atıfları','İtilme karşılığı ve teşvik-merhamet ilişkisi açık klasik öncüle sahiptir. Fecr, Kalem’in bahçesi, Beled’in yokuşu ve koruyucu elin aynı hareket haritasına yerleştirilmesi bu öncülleri genişletir. Yenilik, belirtilen eski bağları silerek bütün karşılıklılığı projeye mal etmekte değil, daha geniş düzenlemededir.','RAZ-107|TAH-LEX|BIQ-107|QURT-107|QUR-AR',connection='strong')

add(30,'semantic_history','107:2-3|107:5-7','semantic_range','lexical','Ezherî’nin دع maddesi küçük çocukları, tökezleyenin kaldırılmasını ve yiyecekle doldurulmuş kabı ayrı kullanımlar halinde içerir. Mekāyîs’in سكن maddesinde ev halkı, barınma ve ocak ateşi bulunur. Fakat İbn Fâris, سهوة adlı ev bölümünü سهو kökünün düzenli açıklamasından ayrılan bir kullanım sayar. Böylece sözlük, ev çevresini kurmaya malzeme verirken kendi içindeki bağların hepsini eşit güçte kabul etmez.','TAH-LEX|MQ-LEX',tradition='dirayet',source_ref='Tehzîb دع, الدُّعاع ve دعدع جفنته; Mekāyîs سكن ve سهو, شذ عن هذا الباب')
add(31,'tafsir','107:7','semantic_range','direct_tafsir','Mâûnun tek bir geleneksel karşılığı yoktur. Taberî, Ali ve İbn Ömer’den zekât; İbn Mes‘ûd’dan kap, balta ve kova gibi ödünçler; Muhammed b. Kâ‘b’dan genel iyilik açıklamalarını aktarır. Su ve mal anlamlarını da kaydederek yarar sağlayan yardımın geniş anlamını tercih eder. Bu görüşler aynı şeyin eksiksiz eşanlamlıları değil, kelimenin kapsamına dair farklı vurgulardır.','TAB-107',tradition='rivayet',priority='core',audience='general',source_ref='107:7, zekât, ev eşyası, genel iyilik rivayetleri ve son tercih')
add(31,'tafsir','107:7','historical_development','direct_tafsir','İbn Kesîr, İkrime’nin mâûnun en üstünü zekât, en küçük örnekleri elek, kova ve iğne açıklamasını birleştirici bulur. Râzî zekât, küçük yardımlar, su ve itaat anlamlarını sıralayıp yapılması kolay bütün itaate açılan yorumu tercih eder. Kurtubî ise çok sayıda görüşü korur. Sonraki açıklamalar bazen kapsamı daraltmak yerine, erken örnekleri dereceli bir bütün halinde toplar.','IK-107|RAZ-107|QURT-107',tradition='dirayet',source_ref='İbn Kesîr 107:7, İkrime açıklaması; Râzî 107:7 dört görüş ve tercih; Kurtubî 107:7 görüşler')
add(31,'tafsir','107:7','early_attestation','direct_tafsir','Ebû Dâvûd 1657’de İbn Mes‘ûd, Resûlullah döneminde mâûnu kova ve tencere ödüncü olarak saydıklarını söyler. Sayfada Elbânî’nin hasen değerlendirmesi açıkça yer alır. Bu, sahâbînin dönem içi anlam tanıklığıdır; Peygamber’in mâûnu bizzat bu iki nesneyle sınırlayan bir açıklama yaptığı şeklinde yeniden yazılmamalıdır.','AD-1657',tradition='rivayet',status='reported',hadith_grade='hasan',priority='core',audience='general',transmitter='Abdullah b. Mes‘ûd',source_ref='Sünen Ebî Dâvûd 1657, Hukūk al-māl babı')
add(31,'historical_context','107:7','historical_context','historical','Râzî, komşunun tandırda ekmek pişirmesi ve eşyasını kısa süreliğine bırakması gibi somut yardımları örnekler; hatta ödünç vermek üzere komşunun ihtiyaç duyacağı eşyayı bulundurmayı bir fazilet sayar. İbn Kesîr’in ödünç açıklamasında ise eşyanın kendisi korunup geri verilir. Bunlar ev araçları yorumunun maddî içeriğidir; sûrede tek bir evin envanteri anlatılıyor demek değildir.','RAZ-107|IK-107',tradition='historical',historicity='not_applicable',source_ref='Râzî 107:7 ikinci görüş; İbn Kesîr 107:7, ما ينتفع به ويستعان به مع بقاء عينه')
add(31,'method_note','107:7','constraint','historical','Küçük yardımın maliyetinin az oluşu, cimriliğin ağırlığını gösteren yorumdur; her ödüncün risksiz veya maliyetsiz olduğunu bildiren hesap değildir. Kurtubî ve Râzî, zorunlu haklarla faziletli yardımları aynı düzeyde tutmaz. Zekât, zaruret halindeki yardım ve alışılmış eşya ödüncü arasındaki farklar silinerek tek bir hukukî yükümlülük listesi çıkarılmamalıdır.','QURT-107|RAZ-107',priority='core',audience='general',source_ref='Kurtubî 107:7 son hukukî ayrımlar; Râzî 107:7 ikinci görüş ve fazilet açıklaması')
add(31,'asbab','107:7','asbab_context','asbab','Süyûtî, İbn Merdûye’ye nispetle, Müslümanların münafıklardan eşya isteyip geri çevrilmesiyle bu âyetin inişini bağlayan İbn Mes‘ûd haberini aktarır. Bu, sırf mâûn kelimesinin açıklanmasından farklı bir sebep iddiasıdır. İbn Merdûye’nin asıl metni ve bu yolun sıhhat değerlendirmesi bağımsız olarak doğrulanmadığından tarihî olay kesinleşmiş sayılmaz.','SUY-107',tradition='rivayet',status='reported',historicity='uncertain',hadith_grade='not_assessed',priority='research',audience='research',source_ref='107:7, وأخرج ابن مردويه عن ابن مسعود ile başlayan eşya isteme haberi')
add(31,'source_note','107:7','source_criticism','direct_hadith_tafsir','İbn Kesîr, Kurre b. Da‘mûs üzerinden taş, demir ve suyun mâûn olarak açıklanmasını içeren haberi çok garip bulur; Peygamber’e nispetini münker sayar ve isnadda tanınmayan kimseler bulunduğunu belirtir. Burada bu haber nesne listesini genişleten sağlam bir Peygamber açıklaması olarak kullanılmaz. Tekrarlanmış olması sıhhatini artıran bağımsız tanıklar bulunduğunu göstermez.','IK-107',tradition='hadith',status='weak',hadith_grade='not_assessed',priority='research',audience='research',source_ref='107:7, Kurre b. Da‘mûs haberi sonrası وهذا غريب جدا değerlendirmesi')
add(32,'method_note','107:2-3|107:7','constraint','lexical','Kabı dolduracak biçimde silkeleme örneği sözlükte vardır; çocuğun itilmesi ile dolu kabın sunulması arasındaki karşıtlık bundan sonra kurulan okumadır. Ana metindeki tok sofra, bir nüzul rivayetinden çıkarılmış gerçek ev sahnesi değildir. Bu ayrım, maddî ayrıntının anlatıya canlılık vermesini korurken ona tarihî tanıklık ağırlığı yüklemeyi önler.','TAH-LEX|MQ-LEX',connection='resonant',source_ref='Tehzîb دع, dolu çanak ve ölçek; Mekāyîs دعع, hareket açıklaması')
N_house=nov(33,'107:2-3|107:5-7','building_blocks_only','Ezherî دع, küçük çocuklar ve dolu kap|İbn Fâris سكن ve سهو, ev halkı ve kıyas dışı sahve|Taberî 107:7 eşya görüşü|İbn Kesîr 107:7 ödünç|Râzî 107:7 komşu tandırı ve eşya bırakma|Bikāî 107:2–7','Ev araçları ve komşuluk yardımları eski tefsirde açıkça vardır; çocuk, sığınak, raf/ev bölümü, dolu kap ve ocak ise sözlükte ayrı dayanaklara sahiptir. Bunların sûrenin bütün kelimelerini dolaşan tek ev planında birleşmesi belirtilen pasajlarda görülmedi. Sentezin yeni sayılabilecek yanı bütün bu parçaları aynı evde buluşturmasıdır; ev eşyası yorumunu bulmuş olması değildir.','TAH-LEX|MQ-LEX|TAB-107|IK-107|RAZ-107|BIQ-107',connection='resonant')
add(34,'cross_quran','107:2-3|107:7','intertext','comparative','Kehf 18:77’de istenen misafirlik reddedilir; 18:82’de onarılan duvarın iki yetimin malını koruduğu açıklanır. Dolayısıyla esirgenen sofra ile korunan yetim hakkının aynı anlatıda bulunması doğrudan metinsel dayanaktır. Bununla birlikte oradaki kulun eylemi, kendi iradesiyle kurulmuş sıradan bir borç ödeştirmesine indirgenmez. Yûsuf’taki ölçünün engellenmesi ve Mutaffifîn’de ölçüde eksiltme ise bu sahneye eklenen farklı bağlamlardır.','QUR-AR',status='interpretive',connection='strong',source_ref='18:77,82; 12:63; 83:1–3; 4:8')
nov(34,'107:2-3|107:7','building_blocks_only','Râzî 107:7 komşu yardımları|Taberî 107:2–3 ve 107:7|Bikāî 107:2–3 ve 107:7|Kur’an 18:77,82; 12:63; 83:1–3; 4:8 metinleri','Kehf’in reddedilen konukluğu ve yetim duvarı Kur’an’ın kendi anlatısında birleşir. Bu anlatıyı Mâûn’un ev, ölçü ve yiyecek ağına yerleştiren bağlantı belirtilen Mâûn tefsiri pasajlarında bulunmadı. Kehf, Yûsuf ve Mutaffifîn tefsirlerinin tamamı ayrıca incelenmediği için o alanlardaki klasik öncül durumu not_checked olarak kalır.','QUR-AR|RAZ-107|TAB-107|BIQ-107',connection='strong',note='Dış sûrelerin tam tefsir külliyatı: not_checked')

add(37,'semantic_history','107:3|107:7','semantic_range','lexical','Mekāyîs’in معن maddesinde kolaylıkla akma ve suyun akışı bulunur; طعم maddesi ise su için kullanılan tadıp içme fiilini Bakara 2:249 ile gösterir. Ancak معن maddesinde bu çalışmada okunan pasaj, mâûn kelimesini ayrıca tanımlamaz. Mâûn için su karşılığının doğrudan tanıkları Taberî ve Râzî’nin 107:7 açıklamalarıdır. İki farklı kaynağın katkısı birbirine yüklenmemelidir.','MQ-LEX|TAB-107|RAZ-107|QUR-AR',tradition='dirayet',source_ref='Mekāyîs معن ve طعم; Taberî 107:7 şiir ve su; Râzî 107:7 üçüncü görüş; 2:249')
add(37,'tafsir','107:7','disagreement','lexical','Ma‘înin معن yahut عين ile türetilmesi klasik kaynaklarda tartışmalıdır. Vâhidî, 23:50’de Ferrâ’nın iki ihtimali de verdiğini; Zeccâc ve İbn Kuteybe’nin göz önünde olan suyu anlatan عين türetimini tercih ettiğini; Ebû Ali el-Fârisî’nin ise akma ve kolay boyun eğme anlamıyla معن türetimini savunduğunu aktarır. Su ağı bu ihtilafın bir tarafına yaslanır; kesinleşmiş tek kök açıklaması gibi sunulamaz.','WAH-BAS-2350',tradition='dirayet',status='disputed',priority='core',audience='general',source_ref='el-Basît 23:50, واختلفوا في اشتقاق معين ile başlayan bölüm')
add(37,'tafsir','107:7','early_attestation','lexical','Aynı Vâhidî pasajında Ebû Ali üzerinden kolayca verilen şeyler, suyun akış yerleri ve hakkı kabul edip teslim etmek birlikte açıklanır; mâûn için su, ot, ateş ve zekât örnekleri sayılır. Bu nedenle su ile kolay yardım ve hakkı yerine getirme arasındaki köprü yalnız bu projede kurulmuş değildir. Burada okunan, Vâhidî’nin aktardığı metindir; Ebû Ali’nin el-İğfâl nüshası ayrıca incelenmemiştir.','WAH-BAS-2350',tradition='dirayet',source_ref='el-Basît 23:50, واختار أبو علي القول الثاني paragrafı ve devamı')
add(38,'hadith','107:3|107:7','corroboration','thematic','Buhârî 2353’te Ebû Hüreyre’den gelen sahih hadis, fazla suyu esirgeyerek otlağa erişimi engellemeyi yasaklar. Bu metin suyun tutulmasının başkalarının geçimini de kesebildiğine güçlü bir örnektir. Hükmün lafzındaki fazla su kaydı korunmalıdır; bütün su mülkiyetini aynı şekilde açıklayan genel bir formüle çevrilmez ve Mâûn’un doğrudan tefsiri sayılmaz.','BUK-2353',tradition='hadith',hadith_grade='sahih',audience='general')
N_water=nov(38,'107:3|107:7','partial','Taberî 107:7 su ve genel yarar açıklamaları|Râzî 107:7 su ve kolay itaat görüşleri|Vâhidî el-Basît 23:50, ma‘în türetimi ihtilafı ve Ebû Ali’nin akış/hak/mâûn açıklaması|İbn Fâris معن ve طعم','Su, kolay yardım, otlak ve hakkı kolayca teslim etme arasında açık klasik bağlar vardır; bunları ayrı ve ilişkisiz parçalar gibi göstermek yeniliği abartır. Mâûn’daki evden kıyıya uzanan kesilmiş akış sahnesi ise bu öncüllerin proje düzenlemesidir. Kök ihtilafı sebebiyle bu sahne, âyetin zorunlu açıklaması olarak kabul edilmez.','TAB-107|RAZ-107|WAH-BAS-2350|MQ-LEX',connection='resonant')
add(39,'cross_quran','107:1-2|107:7','intertext','comparative','Mülk 67:30’da أَرَأَيْتُمْ sorusu ile مَاءٍ مَعِينٍ aynı âyettedir; Mü’minûn 23:50 barınma, yerleşme ve suyu, Duhâ 93:6 yetim ile barındırmayı birleştirir. Bu açık kelime ortaklıkları karşılaştırmaya izin verir. Fakat Mâûn’daki mâûn ile bu âyetlerdeki ma‘în aynı kelime değildir; ortak kök kabulü tartışmalı, bütün sahnenin birleştirilmesi yorum düzeyindedir.','QUR-AR|WAH-BAS-2350',status='interpretive',connection='resonant',source_ref='67:30; 23:50; 93:6; Vâhidî el-Basît 23:50 son su açıklamaları')
N_shelter=nov(39,'107:1-2|107:7','partial','Vâhidî el-Basît 23:50, ma‘în tartışması ve 67:30 nakli|Taberî 107:7|Râzî 107:7 üçüncü görüş|Bikāî 107:1–2 ve 107:7','23:50 ile 67:30’un su kelimesi çevresinde birlikte okunması Vâhidî’de zaten vardır. Duhâ’daki yetim-sığınak ilişkisi de Kur’an’da açıktır. Bunları Mâûn’un ilk bakışından son yardımına uzanan barınak-su çerçevesine yerleştiren bütünleşik düzen, belirtilen pasajlarda görülmedi. Bu dar yenilik tespiti, ma‘în etimolojisinin tartışmalı oluşunu kaldırmaz.','WAH-BAS-2350|TAB-107|RAZ-107|BIQ-107|QUR-AR',connection='resonant')

add(42,'source_note','107:4-5','constraint','lexical','Burada önemli bir sözlük sınırı vardır: İbn Fâris صلو maddesinde ateş/ısı ile ibadet için iki ayrı asıl bildirir. Ayrıca kaynak hazırlığının kök kimliği kaydında صلي ateş kolu namazın doğrudan kökü değil, yankı kolu olarak işaretlenmiştir. Bu nedenle ana metindeki aynı kök ifadesi, ortak anlamdan türeme ispatı olarak kabul edilemez. Namazı yakmak veya ateşle doğrultmak diye çevirmek kaynakların desteklemediği bir sonuç olur.','MQ-LEX|BASE-LEX-107',priority='core',audience='general',source_ref='Mekāyîs صلو, أصلان; özgün surah.r2/dictionary.md kök kimliği ve ECHO ص ل ي kaydı')
add(42,'method_note','107:4-5','rejected_candidate','lexical','Ateşte eğri dalı düzeltme örneği, ateş kolunun sözlükteki kullanımını açıklar. Bundan namaz kelimesinin tarihsel olarak böyle bir işlemden doğduğunu ya da sûrenin ateş ayinini anlattığını çıkarmak reddedilir. Ocak, ısı ve ibadet arasındaki yakın sesli imgeler ancak bağlamı değiştirmeyen bir karşılaştırma olarak tutulabilir.','MQ-LEX|QUR-AR',connection='rejected',source_ref='Mekāyîs صلو; 107:4–7')
add(43,'tafsir','107:4-7','clarification','structural','Râzî, yetime merhamette kusur ile Allah’ın emrine saygıda kusuru aynı akışın iki yanı olarak açıklar. Veyl tehdidinin ağırlığı bu birleşimle belirginleşir. Namaz kılanlar sözünden sonra gelen gaflet, gösteriş ve mâûnu esirgeme nitelemeleri birlikte okunmalıdır; kelimenin tek başına yeraltındaki belirli bir vadiyi kesin biçimde adlandırdığına dair ayrıca doğrulanmış bir hadis bu çalışmada kullanılmamıştır.','RAZ-107|TAB-107',tradition='dirayet',priority='core',audience='general',source_ref='Râzî 107:4–5 mesele 1; Taberî 107:4–7')
add(43,'hadith','107:3|107:7','source_criticism','thematic','Âişe’ye nispet edilen su, tuz ve ateşi esirgememe rivayeti İbn Mâce 2474’te bulunur; erişilen kayıtta Dârüsselâm değerlendirmesi zayıftır. Kurtubî de aktardığı bu ailedeki haberin isnadına ihtiyat koyar. Bu metin, ocak ve paylaşma temasının rivayet geleneğinde karşılaşıldığını gösterir; ayrıntılı sevap vaatleri veya bütün yorum ağı için sahih dayanak diye kullanılamaz.','IM-2474|QURT-107',tradition='hadith',status='weak',hadith_grade='daif',priority='research',audience='research',source_ref='Sünen İbn Mâce 2474; Kurtubî 107:7 su/tuz/ateş hadisi ve إسناده لين kaydı')
N_fire=nov(43,'107:3-7','building_blocks_only','İbn Fâris صلو, iki asıl ve ateşte dal düzeltme; سكن, ocak ateşi|Taberî 107:4–7|İbn Kesîr 107:4–7|Zemahşerî 107:4–7|Râzî 107:4–7|Beydâvî 107:4–7|Bikāî 107:4–7|Kurtubî 107:7, su/tuz/ateş ve isnad ihtiyatı','Ev ocağı, paylaşılmayan ateş ve hesabın ateşi ayrı kaynak parçalarıdır. Namazın çevresinde bu üç ateşi tek mimaride buluşturan anlatı okunan pasajlarda bulunmadı. Üstelik Mekāyîs ibadet ile ateşi iki asıl olarak ayırır: ağ, bu ayrımı aşan etimolojik delil değil, ikincil bir proje benzetmesidir.','MQ-LEX|TAB-107|IK-107|KASH-107|RAZ-107|BAY-107|BIQ-107|QURT-107',connection='speculative')
add(44,'cross_quran','107:1-3|107:7','corroboration','comparative','Hâkka 69:34’ün yoksulun yiyeceğine teşvik etmeme cümlesi Mâûn 107:3 ile aynıdır; Kurtubî bu bağı açıkça gösterir. Nisâ 4:10 ise özellikle yetim malını haksız yiyenleri ateşle karşılaştırır. Mutaffifîn 83:10–17’de hesap gününü yalanlama ve ateş, Kāf 50:24–25’te hayrı engelleme ve cehennem buluşur. Bu güçlü tematik bağlar, namaz kelimesine ateş anlamı yüklemeye ihtiyaç duymaz.','QUR-AR|QURT-107',status='interpretive',connection='strong',source_ref='69:30–34; 4:10; 83:10–17; 50:24–25; Kurtubî 107:3')
N_judgment=nov(44,'107:1-3|107:7','partial','Kurtubî 107:3, Hâkka 69:34 atfı|Râzî 107:4–5 mesele 1, veyl ve Mutaffifîn bağı|Ezherî دع, Tûr 52:13|Taberî 107:1–7|Bikāî 107:1–7','Yoksulu doyurmaya teşvik etmeme ile ahiret karşılığı arasındaki bağlantı klasik açıklamada açıktır; itilme ve veyl bağları da eskidir. Hâkka, Mutaffifîn, Nisâ ve Kāf’ı Mâûn’un ocak anlatısında birlikte düzenlemek projeye ait daha geniş bir karşılaştırmadır. Açık öncüller ile bu genişletme ayrı tutulmalıdır.','QURT-107|RAZ-107|TAH-LEX|TAB-107|BIQ-107|QUR-AR',connection='strong')

add(47,'semantic_history','107:1','semantic_range','lexical','Mekāyîs, دين ailesini boyun eğme ve alçalma ortak ekseninde açıklar; hesap ve karşılık yanında borç ilişkisini de verir. Böylece dîn/deyn yakınlığı gerçek bir sözlük dayanağına sahiptir. Yine de Taberî ve Râzî’nin 107:1 için esas aldığı hesap ve karşılık anlamı, burada ticari borç diye çevrilemez. Sözlük ailesi, âyetin tek anlamını bütün aileye genişletme yetkisi vermez.','MQ-LEX|TAB-107|RAZ-107',tradition='dirayet',priority='core',audience='general',source_ref='Mekāyîs دين; Taberî 107:1; Râzî 107:1 mesele 4')
add(47,'source_note','107:1','constraint','lexical','كَذَبَ عَلَيْكَ biçimindeki teşvik deyimi sözlükte kayıtlıdır; fakat İbn Fâris bunun açıklanmasının güçlüğünü ve kullanım çevresinin artık tam bilinmediğini özellikle söyler. Bu donmuş deyim, âyetteki يُكَذِّبُ بِالدِّين terkibinin yükümlülük anlamına geldiği sonucunu vermez. Ana metnin borç ve yükümlülük karşılaştırması, farklı yapıların birbirine çevrilmesine dayandırılamaz.','MQ-LEX|RAG-LEX',source_ref='Mekāyîs كذب, كذب عليك ve ما أحسب ملخص açıklaması; Müfredât كذب')
add(48,'semantic_history','107:7','historical_development','lexical','Kurtubî, mâûnun câhiliye dilinde yararlı armağan veya menfaat, İslâm’da ise zekât için kullanımını aktaran açıklamayı verir; aynı maddede su, genel hak ve ödünç eşya gibi başka anlamlar da yaşamaya devam eder. Bu nedenle ilk anlamın bütünüyle kaybolup yalnız zekât anlamının kaldığı doğrusal bir tarih kurulamaz. Erken nakiller zaten birden çok yorumu birlikte taşır.','QURT-107|TAB-107',tradition='historical',status='reported',source_ref='Kurtubî 107:7, câhiliye/İslâm kullanımı; Taberî 107:7 rivayet kümeleri')
add(48,'tafsir','107:7','disagreement','lexical','Râzî, mâûnu kolayca itaat etme anlamında da açıklar; Vâhidî’nin 23:50 aktarımı hakkı kabul ederek vermeyi aynı معن çevresinde ele alır. Buna karşılık Kurtubî, kelimeyi معونة ve yardım kökü üzerinden açıklayan başka bir türetimi de kaydeder. Bu seçenekler, hem su hem borç ağının tek ve tartışmasız bir kök tarihi üzerine kurulmadığını gösterir.','RAZ-107|WAH-BAS-2350|QURT-107',tradition='dirayet',status='disputed',source_ref='Râzî 107:7 dördüncü görüş; Vâhidî el-Basît 23:50 Ebû Ali pasajı; Kurtubî 107:7 türetim açıklamaları')
add(48,'reader_note','107:7','reader_orientation','historical','Ödünç verilen kap geri döner; zekât verilen malın mülkiyeti ise alıcıya geçer. Bu yüzden ana metindeki küçük borç dili, her mâûn örneğinin para borcu olduğunu söylemez. Buradaki ortak eksen, kime ait hangi hakkın ve hangi yararın esirgendiğidir.','IK-107|RAZ-107',priority='core',audience='general',source_ref='İbn Kesîr 107:7 ödünç tanımı; Râzî 107:7 zekât ve araç gereç ayrımı')
N_debt=nov(48,'107:1|107:7','partial','İbn Fâris دين, borç ve karşılık; كذب, yükümlülük deyimi|Râzî 107:7 dördüncü görüş ve Allah/yaratılmış hakları açıklaması|Vâhidî el-Basît 23:50 hakkı kabul etme ve mâûn|Kurtubî 107:7 türetim ve tarihsel kullanım','Dîn ile deyn ailesi, mâûnun itaat anlamı ve Allah’a/insanlara düşen hakların ters çevrilmesi klasik kaynaklarda mevcuttur. Ana metnin aynı hesap defterinde toplanan kökler anlatısı bunları genişletir; bütünüyle öncülsüz değildir. Yenilik, belirtilen pasajlarda aynı borç defteri imgesiyle bulunmayan düzenlemededir; âyetin hesabını para borcuna indirgemekte değildir.','MQ-LEX|RAZ-107|WAH-BAS-2350|QURT-107',connection='resonant')
add(49,'cross_quran','107:1|107:4-7','contrast','structural','Meâric 70:19–35, hayır gelince esirgeyen insanı anlatır, ardından namaz kılanları istisna eder; namazda devam ve namazı koruma arasında maldaki belirli hak ile hesap gününü doğrulamayı sıralar. Mâûn’daki esirgeme, namaz, hak ve hesabı yalanlama düğümlerinin güçlü karşı sahnesidir. Bu benzerlik, iki pasajın bütün unsurlarıyla aynı ölçüde kurulmuş bir halka olduğu anlamına gelmez.','QUR-AR',status='interpretive',connection='strong',source_ref='70:19–35; 107:1–7')
add(49,'hadith','107:1|107:4-7','contrast','thematic','Buhârî 1397’de Ebû Hüreyre’nin naklettiği bedevîye verilen cevap, Allah’a ortak koşmadan kulluğu, farz namazı, zekâtı ve Ramazan orucunu birlikte anar. Hadis, hesabı gözeten ibadet ile malî yükümlülüğün olumlu beraberliğini gösterir. Sûrenin iniş zamanı veya mâûn kelimesinin yalnız zekât olması için doğrudan delil değildir.','BUK-1397',tradition='hadith',hadith_grade='sahih',audience='general')
N_maarij=nov(49,'107:1|107:4-7','building_blocks_only','Taberî 107:1 ve 107:4–7|İbn Kesîr 107:4–7|Zemahşerî 107:5–7|Râzî 107:4–7|Beydâvî 107:5–7|Bikāî 107:1–7|Kur’an 70:19–35','Meâric’teki devamlı namaz, maldaki hak ve hesap gününü doğrulama; Mâûn’daki karşı niteliklerle güçlü biçimde karşılaştırılabilir. Bu bütün düzeni Mâûn’un tersine çevrilmiş karşı tablosu olarak açıklayan pasaj, belirtilen Mâûn tefsirlerinde görülmedi. Meâric’in kendi tefsirlerinin tamamı taranmış değildir; bu kapsamda yokluk iddiası kurulmaz.','TAB-107|IK-107|KASH-107|RAZ-107|BAY-107|BIQ-107|QUR-AR',connection='strong',note='Meâric tefsirlerinin bütünü: not_checked')

add(52,'semantic_history','107:4-5','clarification','lexical','Salâtın dua anlamı klasik sözlükte açıktır; fakat her geçtiği yerde aynı anlamı taşımaz. Tevbe 9:103’te Peygamber’in sadaka getirenler için dua etmesi, Mâûn’da ise kişinin kendi namazı söz konusudur. Bir kullanımın diğerini aydınlatması, Mâûn’daki ritüel namazı yalnız başkasına iyi dilekte bulunma şeklinde çevirmeyi gerektirmez.','MQ-LEX|QUR-AR|TAB-107',tradition='dirayet',priority='core',audience='general',source_ref='Mekāyîs صلو; 9:103; Taberî 107:4–5')
add(53,'hadith','107:4|107:7','corroboration','thematic','Abdullah b. Ebî Evfâ’nın Buhârî 1497 rivayetinde Peygamber, sadaka getiren topluluklara dua eder; babasının getirdiği sadaka için de ailesine dua ettiği aktarılır. Bu sahih haber sadaka ile duanın somut beraberliğini doğrular. Tevbe 9:103’ün çevresine uygun bir uygulamadır; Mâûn’a doğrudan yapılmış Peygamber açıklaması değildir.','BUK-1497|QUR-AR',tradition='hadith',hadith_grade='sahih',audience='general',source_ref='Buhârî 1497; 9:103')
add(53,'cross_quran','107:2-5|107:7','constraint','comparative','Tevbe 9:102–104’te kusurunu kabul edenler, sadakayla arınma, Peygamber’in onlar için duası ve Allah’ın tövbeyi kabulü aynı yakın bağlamdadır. Duanın seken oluşu bu belirli muhatap ilişkisine aittir. Buradan Mâûn için sadaka, dua ve toplumsal huzur arasında karşılaştırma kurulabilir; bütün namazların başkasına verilmiş huzur diye tanımlandığı sonucu çıkarılamaz.','QUR-AR|BUK-1497',status='interpretive',connection='strong',source_ref='9:102–104')
N_outward=nov(54,'107:2-7','partial','İbn Fâris صلو, dua/ibadet ve سكن, huzur|Râzî 107:7, Allah’a ait ibadet ve insanlara ait hakkın tersliği|Taberî 107:4–7|Bikāî 107:3–7|Buhârî 1497|Kur’an 9:102–104','Sadaka ile duanın birlikte oluşu, salâtın dua anlamı ve ibadet ile insan hakkının ayrılmaması eski dayanaklara sahiptir. Tevbe’deki sadaka–dua–seken sırasını Mâûn’da kesilen dışa açılma çevrimi olarak düzenlemek belirtilen sûre açıklamalarında görülmedi. Sentez kısmen öncüllüdür; namazın ritüel anlamını veya 9:103’ün özel muhatabını kaldırmaz.','MQ-LEX|RAZ-107|TAB-107|BIQ-107|BUK-1497|QUR-AR',connection='strong')
add(55,'cross_quran','107:2-7','intertext','comparative','Ankebût 29:45 ile Mâûn’daki kötü davranışın yan yana sorulması Râzî’de açıktır. Diğer karşı sahnelerin muhatapları farklıdır: 11:87 Şuayb’ın toplumu, 2:83 İsrailoğulları ahdi, 19:31 İsa’nın bildirimi, 9:54 isteksiz ibadet ve infak, 19:59 namazı zayi eden sonraki nesillerdir. Bu farklı sahneler ibadet ve mal ahlâkının beraberliğini destekler; aynı tarihî olay veya tek bir hukuk düzenlemesi değildir.','QUR-AR|RAZ-107',status='interpretive',connection='strong',source_ref='Râzî 107:4–5 mesele 1; 11:87; 2:83; 19:31,59; 9:54; 29:45')
nov(55,'107:2-7','partial','Râzî 107:4–5 mesele 1, 29:45 sorusu|Taberî 107:2–7|Bikāî 107:1–7|Kur’an 11:87; 2:83; 19:31,59; 9:54; 29:45','Namazın kötülüğü engellemesi ile Mâûn’un eleştirisi arasındaki bağ Râzî’de açık bir öncüldür. Şuayb, İsrailoğulları, İsa ve Tevbe bağlamlarını aynı dışa açılan namaz haritasında toplamak belirtilen pasajlarda görülmeyen daha geniş bir karşılaştırmadır. Bu dış sûrelerin bütün yorumları ayrıca incelenmediği için onların geleneği hakkında mutlak yenilik hükmü kurulmaz.','RAZ-107|TAB-107|BIQ-107|QUR-AR',connection='strong')

add(58,'method_note','107:1-2|107:5-6','interpretive_consequence','comparative',f'Buradaki buluşmanın katmanları eşit değildir: dikkat ve gösteriş ayrımı doğrudan tefsir desteğine sahiptir; ayna bağlantısı {N_mirror}, Süha ile görünmeyen ihtiyaç bağlantısı {N_suha}, Alak çevresindeki karşılaştırma ise {N_seeing} kaydında sınırlandırılmıştır. Yeni bir delil eklemeden aynı bağı tekrar kesinleştirmek, çağrışımın kanıt ağırlığını artırmaz.','AUDIT-107|RAZ-107|MQ-LEX',status='interpretive',priority='research',audience='research')
add(59,'method_note','107:2-5','constraint','comparative',f'İtme ile ateşe itilmenin açık öncülü {N_push}; namazın ses ailesi ile ateşin birleştirilmesinin sınırı {N_fire} kaydındadır. Birinci bağdaki güçlü Kur’an desteği ikinci bağdaki kök ihtilafını çözmez. Hâkka’nın yoksul yiyeceği cümlesi, bu iki farklı delil türünü karıştırmadan güçlü karşılık duygusunu taşır.','QUR-AR|RAZ-107|MQ-LEX',status='interpretive',priority='research',audience='research')
add(60,'cross_quran','107:1|107:3-5','constraint','comparative','Müddessir 74:42–46’da namaz kılanlardan olmama, yoksulu doyurmama, bâtıla dalanlarla birlikte dalma ve hesap gününü yalanlama aynı cevapta sıralanır. Mâûn’la ortak düğümleri belirgindir. Fakat 74:43’te namazın yokluğu, 107:4–6’da dıştan namazla birlikte kusur anlatılır; ayrıca خوض ile سهو aynı kök değildir. Bu farklar korununca karşı sahne daha isabetli okunur.','QUR-AR',status='interpretive',connection='strong',priority='core',audience='general',source_ref='74:42–46; 107:1–6')
N_mudd=nov(60,'107:1|107:3-6','building_blocks_only','Taberî 107:1–7|İbn Kesîr 107:1–7|Süyûtî 107:1–7|Zemahşerî 107:1–7|Râzî 107:1–7|Beydâvî 107:1–7|Bikāî 107:1–7|Kurtubî 107:1–7|Kur’an 74:42–46','Müddessir’de namaz, yoksul, hesap ve boş uğraşın aynı konuşmada buluşması Kur’an’da açıktır. Bunun Mâûn’un tüm ağının âhiretten verilen cevabı olarak düzenlenişi, okunan sûre açıklamalarında açıkça bulunmadı. Müddessir’in kendi tefsir külliyatı bu denetimin dışında kaldığından o alandaki öncüller için sonuç not_checked durumundadır.','QUR-AR|TAB-107|IK-107|SUY-107|KASH-107|RAZ-107|BAY-107|BIQ-107|QURT-107',connection='strong',note='Müddessir tefsirlerinin bütünü: not_checked')
nov(61,'107:1-3|107:7','partial','Râzî 107:7 ev yardımları, su, itaat ve haklar|Vâhidî el-Basît 23:50 su/kolay verme/hakkı kabul etme|Ezherî دع, küçük çocuklar ve dolu kap|İbn Fâris سكن، معن، دين، منع',f'Ev, su ve borç arasında burada kurulan birleşim, {N_house}, {N_water} ve {N_debt} kayıtlarının üzerine oturur. Özellikle su–kolay yardım–hak ilişkisi Vâhidî’de zaten birleşiktir. Çocuk, dolu kap ve koruyucu engelin bunlara eklenip tek bir geçim çevresi oluşturması belirtilen pasajlarda bulunmayan proje düzenlemesidir; eski bağlantılar yeniden icat edilmiş sayılmaz.','RAZ-107|WAH-BAS-2350|TAH-LEX|MQ-LEX',connection='resonant')
nov(62,'107:1|107:4-7','partial','Râzî 107:4–7, kulluk ve yaratılmışa şefkat ile hakların tersliği|Bikāî 107:1 ve 107:7, başlangıç-son ilişkisi|Kur’an 70:19–35 ve 9:102–104|Buhârî 1497',f'Meâric’in olumlu namaz dizisi ({N_maarij}) ile Tevbe’nin sadaka ve dua sahnesini ({N_outward}) Mâûn çevresinde tek çevrim yapmak bu projenin birleşimidir. Namaz ile yardım arasındaki ahlâkî birlik ise Râzî’de, sadaka ve dua uygulaması hadiste açıktır. Aynı tasarımı belirtilen klasik pasajlarda görmemek, bütün malzemenin yeni olduğunu söylemeye yetmez.','RAZ-107|BIQ-107|QUR-AR|BUK-1497',connection='strong')
add(63,'nazm','107:1-7','nazm','structural','Bikāî, Kureyş sûresindeki evin Rabbine kulluk emrini ve açlıktan doyurulma nimetini Mâûn’un inkâr ve yardımı esirgeme eleştirisine bağlar. Sûrenin sonunda da hesabı yalanlama ile hakkı vermemeyi yeniden buluşturur. Böylece ilk âyet ile son âyet arasında ahlâkî bütünlük kurmanın açık bir klasik öncülü vardır; bu yapı yalnız kelimelerin uzak sözlük akrabalarından çıkarılmaz.','BIQ-107|QUR-AR',tradition='nazm',status='interpretive',priority='core',audience='general',source_ref='Bikāî 107:1 sûre girişi ve 107:7 başlangıca dönüş; 106:3–4')
add(63,'nazm','107:1-7','contrast','structural','Râzî, Kevser 108:1’in girişindeki ilk latifede dört karşıtlık kurar: cimriliğin karşısında bol veriş; namaz ihmali karşısında namaz emri; riyâ karşısında Rab için oluş; mâûnu esirgeme karşısında kurban ve yedirme. Bikāî de en küçük yardımın esirgenmesi ile Kevser’in bolluğunu karşılaştırır. Bu komşuluk, sûrenin yapısının klasik yorumda da ibadet ve verme ekseninde okunduğunu gösterir.','RAZ-108-OPEN|BIQ-108',tradition='nazm',status='interpretive',source_ref='Râzî 108:1 yalnız girişin ilk لطيفة bölümü; Bikāî 108:1 giriş')
add(63,'method_note','107:1-7','constraint','structural','Edebî bütünlük, bütün âyetlerin aynı anda ve aynı kişi hakkında indiğini ispatlamaz. Mekkî, Medenî ve bölünmüş iniş nakilleri, sûreyi son biçimiyle birlikte okuma imkânından ayrı bir tarih sorusudur. İlk bölümdeki tekil kişi ile son bölümdeki çoğul nitelikleri tek bir kesin biyografiye çevirmek için ayrıca delil gerekir.','QUR-AR|QURT-107|ASH-107|BIQ-107',priority='core',audience='general')
N_ring=nov(63,'107:1-7','partial','Bikāî 107:1 ve 107:7, sûre amacı ve başlangıca dönüş|Râzî 107:4–5 mesele 1 ve 107:7 hakların tersliği|Râzî 108:1 girişte ilk latife|Bikāî 108:1 giriş','Hesabı yalanlamadan yardımı esirgemeye uzanan birlik, kulluk ile yaratılmışlara şefkatin ayrılmazlığı ve Kureyş–Mâûn–Kevser komşuluğu klasik kaynaklarda açıktır. Ayna, kumaş, Süha, ev, su, ateş ve borç imgelerini bu yapıya birlikte yerleştiren geniş örgü belirtilen pasajlarda bulunmadı. Bu örgü kısmen eski bağlantılara dayanan proje sentezidir; sûreye ait tek zorunlu mimari veya kesin nüzul planı değildir.','BIQ-107|RAZ-107|RAZ-108-OPEN|BIQ-108',connection='resonant')
add(63,'source_note','107:1-7','source_criticism','methodological','Bikāî’nin sûre sonundaki kelime sayısı ile sonraki tarih arasında kurduğu sayısal yorum, bağımsız tarihsel doğrulama yapılmadığı için burada kronoloji delili olarak kullanılmadı. Bazı tefsirlerin sonundaki sûreyi okuyana özel bağışlanma rivayetleri de bağımsız sıhhat incelemesi tamamlanmadığından kanıt katmanına alınmadı. Kaynakta bulunma ile güvenilirliği doğrulanmış olma ayrı kayıtlardır.','BIQ-107|KASH-107|BAY-107|RAZ-107',status='not_assessed',priority='research',audience='research',source_ref='Bikāî 107:7 sayısal tarih yorumu; Zemahşerî, Beydâvî ve Râzî 107:7 son fazilet rivayetleri')
add(63,'source_note','107:1-7','source_criticism','methodological','Yenilik denetiminin çekirdeği, Taberî, İbn Kesîr, Süyûtî, Zemahşerî, Râzî, Beydâvî, Bikāî ve Kurtubî’nin aşağıda belirtilen 107:1–7 metinleridir; bu metinler bütünüyle okunmuştur. Râzî’de 4 ve 5 sayfaları aynı açıklamayı tekrar eder, 2. âyetin tartışması 3. âyet sayfasına taşar; Beydâvî 4 ve Süyûtî 3 sayfalarında ayrı açıklama yoktur. Sayfa etiketi tek başına inceleme kapsamı sayılmamıştır.','AUDIT-107|TAB-107|IK-107|SUY-107|KASH-107|RAZ-107|BAY-107|BIQ-107|QURT-107',priority='research',audience='research')
add(63,'source_note','107:1-7','source_criticism','methodological','Sözlük denetimi adı verilen maddelerle sınırlıdır; indirilen bütün Mekāyîs kitabı baştan sona taranmış değildir. Râzî’nin Kevser açıklamasında yalnız girişin ilk latifesi kullanılmıştır. Vâhidî’nin aktardığı Ebû Ali ve Uleymî’nin dayandığı en-Neşr, asıl kitaplarından ayrıca denetlenmemiştir. Tam basılı ciltler, yazmalar, bütün isnad yolları ve belirtilmeyen diğer sûre tefsirleri için durum not_checked olarak kalır.','AUDIT-107|MQ-LEX|WAH-BAS-2350|ULA-107|RAZ-108-OPEN',priority='research',audience='research')

registry={
 'QUR-AR':'Kur’an Arapça metni. Ana anlatıdaki âyet başvuruları ile yakın bağlam ve komşu sûreler için toplam 125 âyet satırı doğrudan okundu; başlıca ilave bağlamlar 9:102–104, 52:13–14, 69:30–34, 70:19–35, 74:42–46, 96:6–14 ve 106–108. Kaynak: [/Volumes/aro/projects/quran-data/data/text/quran-uthmani.tsv](/Volumes/aro/projects/quran-data/data/text/quran-uthmani.tsv); [seçilmiş Arapça satırlar](/Volumes/aro/projects/prose_generation/enrichment/v1/work/107_astra_max/sources/quran_selected.json). Türkçe açıklamalar bu çalışmanın kısa anlam aktarımlarıdır.',
 'TAB-107':'Taberî, Câmiʿu’l-beyân, 107:1–7; yedi ayrı sayfanın açıklamaları bütünüyle okundu. [107:1](https://quran.ksu.edu.sa/tafseer/tabary/sura107-aya1.html), [107:7](https://quran.ksu.edu.sa/tafseer/tabary/sura107-aya7.html). Erken isimlere nispet edilen sözler, Taberî’nin aktardığı rivayetlerdir; bağımsız isnad tashihi yapıldığı anlamına gelmez.',
 'IK-107':'İbn Kesîr, Tefsîrü’l-Kurʾâni’l-ʿazîm, 107:1–7; yedi sayfanın açıklamaları bütünüyle okundu. [107:1](https://quran.ksu.edu.sa/tafseer/katheer/sura107-aya1.html), [107:6](https://quran.ksu.edu.sa/tafseer/katheer/sura107-aya6.html), [107:7](https://quran.ksu.edu.sa/tafseer/katheer/sura107-aya7.html). 107:6 sayfasındaki Ebû Berze ve Sa‘d yollarına, 107:7’deki Kurre b. Da‘mûs haberine konan tenkitler özellikle ayırt edildi.',
 'SUY-107':'Süyûtî, ed-Dürrü’l-mensûr, 107:1–7; erişilen bütün açıklamalar okundu. [107:1](https://quran-tafsir.net/seoty/sura107-aya1.html), [107:5](https://quran-tafsir.net/seoty/sura107-aya5.html), [107:7](https://quran-tafsir.net/seoty/sura107-aya7.html). 107:3 sayfasında ayrı yorum yoktur. Başka kitaplara yaptığı nispetler, o kitapların asılları ayrıca açılmış gibi gösterilmedi.',
 'KASH-107':'Zemahşerî, el-Keşşâf, 107:1–7; yedi sayfanın açıklamaları bütünüyle okundu. [107:1](https://quran-tafsir.net/zamakhshary/sura107-aya1.html), [107:5](https://quran-tafsir.net/zamakhshary/sura107-aya5.html), [107:6](https://quran-tafsir.net/zamakhshary/sura107-aya6.html), [107:7](https://quran-tafsir.net/zamakhshary/sura107-aya7.html). Sondaki fazilet haberi sıhhat delili yapılmadı.',
 'RAZ-107':'Fahreddin er-Râzî, Mefâtîhu’l-gayb, 107:1–7; erişilen metnin tamamı okundu. [107:1](https://quran-tafsir.net/alrazy/sura107-aya1.html), [107:3](https://quran-tafsir.net/alrazy/sura107-aya3.html), [107:4](https://quran-tafsir.net/alrazy/sura107-aya4.html), [107:6](https://quran-tafsir.net/alrazy/sura107-aya6.html), [107:7](https://quran-tafsir.net/alrazy/sura107-aya7.html). 107:2 yorumu 3. âyet sayfasında sürer; 4 ve 5 sayfaları, başlıktaki âyet dışında aynı açıklamayı içerir. Bu kayıt bu gerçek bölümlemeye göre kullanıldı.',
 'BAY-107':'Beydâvî, Envârü’t-tenzîl, 107:1–7; erişilen bütün açıklamalar okundu. [107:1](https://quran-tafsir.net/baidawy/sura107-aya1.html), [107:5](https://quran-tafsir.net/baidawy/sura107-aya5.html), [107:7](https://quran-tafsir.net/baidawy/sura107-aya7.html). 107:4 sayfasında ayrı açıklama yoktur. Sondaki fazilet haberine bağımsız derece verilmedi.',
 'BIQ-107':'Bikāî, Nazmü’d-dürer, 107:1–7; yedi sayfanın açıklamaları, sûre girişi ve sonundaki sayısal yorum dahil bütünüyle okundu. [107:1](https://quran-tafsir.net/beqaay/sura107-aya1.html), [107:7](https://quran-tafsir.net/beqaay/sura107-aya7.html). Edebî münasebet kullanıldı; sayısal tarih yorumu doğrulanmış kronoloji sayılmadı.',
 'QURT-107':'Kurtubî, el-Câmiʿ li-ahkâmi’l-Kurʾân, 107:1–7; sûre girişi ve yedi âyet açıklaması bütünüyle okundu. [107:1](https://quran.ksu.edu.sa/tafseer/qortobi/sura107-aya1.html), [107:3](https://quran.ksu.edu.sa/tafseer/qortobi/sura107-aya3.html), [107:7](https://quran.ksu.edu.sa/tafseer/qortobi/sura107-aya7.html). Mâûn görüşleri, hukuki ayrımlar ve su/tuz/ateş rivayetindeki isnad ihtiyatı ayrı izlendi.',
 'WAH-ASB-107':'Vâhidî, Esbâbü’n-nüzûl, [107:1–2 için görünen bütün pasaj](https://quranpedia.net/surah/1/107/book/2919). Mukātil/Kelbî ve İbn Cüreyc nispetli anlatımlar okundu; kitabın tamamı veya bütün isnad yolları incelenmedi.',
 'WAH-BAS-2350':'Vâhidî, el-Basît, [23:50 açıklamasının tamamı](https://tafsir.app/albaseet/23/50). Özellikle ma‘în türetiminde Ferrâ, Zeccâc, İbn Kuteybe ve Ebû Ali el-Fârisî görüşleri, hakkı kabul etme ve mâûn bağlantısı okundu. Köşeli parantezli modern neşir notları, Vâhidî’nin kendi sözüyle karıştırılmadı; el-İğfâl ve diğer atıf verilen kitaplar ayrıca incelenmiş değildir.',
 'ULA-107':'Mücîrüddin el-Uleymî, Fethu’r-rahmân fî tefsîri’l-Kurʾân, [107. sûrenin gösterilen metni](https://quranpedia.net/surah/1/107/book/557). Sûre girişi, 1–7 açıklamaları ve hukukî sonuçları içeren bütün görünen pasaj okundu; bu çalışmada esas kullanılan kısım 107:1 kıraat bilgisidir. Dipnotta anılan en-Neşr doğrudan kontrol edilmedi.',
 'ASH-107':'Muhammed Tâhir İbn Âşûr, et-Tahrîr ve’t-tenvîr, [107:1 sayfasındaki sûre girişi ve ilk âyet açıklaması](https://quran-tafsir.net/ashour/sura107-aya1.html). Bu pasaj bütünüyle okundu; 107:2–7 için İbn Âşûr’un bütün metninin denetlendiği iddia edilmez. Modern tefsir katmanıdır.',
 'BAGH-107-1':'Begavî, Meʿâlimü’t-tenzîl, [107:1](https://quran.ksu.edu.sa/tafseer/baghawy/sura107-aya1.html). Yalnız sûre girişi ve ilk âyete ait kısa metin okundu; çekirdek yenilik külliyatına tam sûre olarak eklenmedi.',
 'RAZ-108-OPEN':'Râzî, Mefâtîhu’l-gayb, [108:1 açıklamasının açılışı](https://quran-tafsir.net/alrazy/sura108-aya1.html). Açılışın ilk iki latifesi ve izleyen bölümün başlangıcı görüldü; bu dosyada yalnız ilk latifenin Mâûn–Kevser arasında kurduğu dört karşıtlık kullanılır. Sayfanın tamamı okunmuş değildir.',
 'BIQ-108':'Bikāî, Nazmü’d-dürer, [108:1](https://quran-tafsir.net/beqaay/sura108-aya1.html); erişilen açıklama bütünüyle okundu. Diğer Kevser âyetlerinin açıklamaları bu kapsamda değildir.',
 'MQ-LEX':'İbn Fâris, Muʿcemü Mekāyîsi’l-luga. Doğrudan okunan maddeler: رأي، كذب، يتم، حضض، دعع، دين، سكن، طعم، منع، صلو، سهو، معن. İlk on madde, proje veri deposundaki birincil metin aktarımından; سهو ve معن ise [OpenITI metninden](https://raw.githubusercontent.com/OpenITI/0400AH/master/data/0395IbnFarisQazwini/0395IbnFarisQazwini.MucjamMaqayis/0395IbnFarisQazwini.MucjamMaqayis.JK008008-ara1) okundu. صلو ayrıca [İslâmweb’deki birincil metinle](https://www.islamweb.net/ar/library/content/124/2430/باب-الصاد-واللام-وما-يثلثهما) karşılaştırıldı. سهو: c. 3, s. 107; معن: c. 5, s. 335; صلو: c. 3, s. 300–301 biçimindeki aktarım işaretleri korundu. Bunlar basılı nüshanın bağımsız sayfa görüntüsü denetimi değildir.',
 'RAG-LEX':'Râgıb el-İsfahânî, el-Müfredât: رأي ve كذب maddeleri bütünüyle okundu. Kaynak, proje veri deposundaki Arapça birincil metin aktarımıdır; ayna, gebeliğin görünmesi, fiille yalan ve boyalı kumaş örnekleri bu maddelerdedir. Kayıt kimlikleri: mufradat 619 ve 1279. [Kaynak bilgili yerel metin dizini](/Volumes/aro/projects/prose_generation/enrichment/v1/work/107_astra_max/sources/lexicon_entries.json).',
 'TAH-LEX':'Ezherî, Tehzîbü’l-luga: يتم، دع، دين maddeleri bütünüyle okundu. Birincil metin aktarımının kayıtları sırasıyla 8231, 52, 8018; sayfa işaretleri c. 14 s. 241, c. 1 s. 70–71, c. 14 s. 128–130. İçlerinde nakledilen dilcilerin görüşleri Ezherî’nin aktarımı düzeyinde kullanılır. [Kaynak bilgileri](/Volumes/aro/projects/prose_generation/enrichment/v1/work/107_astra_max/sources/lexicon_entries.json).',
 'SIH-LEX':'Cevherî, es-Sıhâh: رأى maddesi bütünüyle okundu; ayna tutma, görüntü, karşılıklı görme ve hemze kullanımları. Birincil metin aktarımı, kayıt 5330, c. 6 s. 2347–2349 işaretleri. [Yerel doğrulanan metin](/Volumes/aro/projects/prose_generation/enrichment/v1/work/107_astra_max/sources/lex_sihah_رءي_5330.txt).',
 'BASE-107':'Değiştirilmeden korunan özgün Türkçe ana metin: [images.md](/Volumes/aro/projects/prose_generation/_commentary/v16/out/s107/images.r13.map3.nohft.tool.tool/images.md). Özgün kaynak satırları ve satır içi etiketler eklerin kaynak kayıtlarından ayrıdır; eski üretim kısıtları eklenen kanıt katmanlarına taşınmamıştır.',
 'BASE-LEX-107':'Özgün üretim sözlük kapsamı: [surah.r2/dictionary.md](/Volumes/aro/projects/prose_generation/_commentary/v16/work/s107/surah.r2/dictionary.md); doğrudan kök ile ECHO kolu ayrımı için kullanıldı. Bu hazırlık kaydı birincil sözlüğün yerine geçirilmez.',
 'AUDIT-107':'Bu bağımsız varyantın [iddia haritası](/Volumes/aro/projects/prose_generation/enrichment/v1/work/107_astra_max/claim_map.json), açıklama yazımından önce tamamlanan [kanıt matrisi](/Volumes/aro/projects/prose_generation/enrichment/v1/work/107_astra_max/evidence_matrix.md), [kaynak indirme kaydı](/Volumes/aro/projects/prose_generation/enrichment/v1/work/107_astra_max/sources/download_manifest.json) ve [yapı denetimi](/Volumes/aro/projects/prose_generation/enrichment/v1/work/107_astra_max/worker_structural_audit.json). Yöntem: [Tafsir_Comprehensive_Annotation_Instructions.md](/Volumes/aro/projects/prose_generation/enrichment/v1/Tafsir_Comprehensive_Annotation_Instructions.md). Bunlar araştırma izidir; tarihî iddialara bağımsız tanık değildir.'
}
hadiths=[
 ('MUS-2985','Müslim','2985','https://sunnah.com/muslim:2985','Ebû Hüreyre; amele ortak katma','sahih','Sahîh-i Müslim kaydı'),
 ('MUS-2986','Müslim','2986','https://sunnah.com/muslim:2986','İbn Abbas; duyurma ve gösteriş','sahih','Sahîh-i Müslim kaydı'),
 ('MUS-2642A','Müslim','2642a','https://sunnah.com/muslim:2642a','Ebû Zer; hayırlı amelden sonra gelen övgü','sahih','Sahîh-i Müslim kaydı'),
 ('MUS-572A','Müslim','572a','https://sunnah.com/muslim:572a','İbn Mes‘ûd; insanî unutma ve sehiv secdesi','sahih','Sahîh-i Müslim kaydı'),
 ('MUS-622','Müslim','622','https://sunnah.com/muslim:622','Enes; güneşin batışına kadar erteleme ve acele namaz','sahih','Sahîh-i Müslim kaydı'),
 ('MUS-1039A','Müslim','1039a','https://sunnah.com/muslim:1039a','Ebû Hüreyre; fark edilmeyen, istemeyen ihtiyaç sahibi','sahih','Sahîh-i Müslim kaydı'),
 ('BUK-6005','Buhârî','6005','https://sunnah.com/bukhari:6005','Sehl b. Sa‘d; yetimi gözetme','sahih','Sahîh-i Buhârî kaydı'),
 ('BUK-5353','Buhârî','5353','https://sunnah.com/bukhari:5353','Ebû Hüreyre; dul ve yoksulun geçimi için çalışma','sahih','Sahîh-i Buhârî kaydı'),
 ('BUK-2353','Buhârî','2353','https://sunnah.com/bukhari:2353','Ebû Hüreyre; fazla suyu esirgemekle otlağı engelleme','sahih','Sahîh-i Buhârî kaydı'),
 ('BUK-1397','Buhârî','1397','https://sunnah.com/bukhari:1397','Ebû Hüreyre; bedevîye namaz, zekât ve kulluk cevabı','sahih','Sahîh-i Buhârî kaydı'),
 ('BUK-1497','Buhârî','1497','https://sunnah.com/bukhari:1497','Abdullah b. Ebî Evfâ; sadaka getirene Peygamber’in duası','sahih','Sahîh-i Buhârî kaydı'),
 ('AD-1657','Ebû Dâvûd','1657','https://sunnah.com/abudawud:1657','İbn Mes‘ûd; mâûn için kova ve tencere ödüncü tanıklığı','hasan','Erişilen sayfada Elbânî: hasen'),
 ('IM-2474','İbn Mâce','2474','https://sunnah.com/ibnmajah:2474','Âişe’ye nispetli su, tuz ve ateş rivayeti','daif','Erişilen sayfada Dârüsselâm: zayıf')
]
for sid,author,num,url,topic,grade,basis in hadiths:
 registry[sid]=f'{author}, [{num}]({url}); {topic}. Arapça rivayet ve numara doğrudan kontrol edildi. Derece dayanağı: {basis}. Türkçe açıklama kısa anlam aktarımıdır; web sayfasının İngilizce tercümesi aktarılmamıştır.'

enum_keys={'type','tradition','role','relation','status','priority','audience','connection','confidence','historicity','hadith_grade','classical_attestation'}
def serialize(a):
 def value(k,v):
  if isinstance(v,bool):return str(v).lower()
  if k in enum_keys:return v
  return json.dumps(v,ensure_ascii=False)
 return '{'+', '.join(k+':'+value(k,v) for k,v in a.items())+'}'
text=BASE.read_text()
chunks=re.split(r'\n\s*\n',text.strip())
assert len(chunks)==63
parts=['<!-- comprehensive-annotation: canonical-v1; target:107:1-7; language:tr; independent-variant:astra-max; date:2026-10-02 -->']
parts.extend(serialize(a) for a in insert[0])
for p,chunk in enumerate(chunks,1):
 parts.append(chunk)
 parts.extend(serialize(a) for a in insert[p])
used={s for a in annotations for s in a['source'].split('|')}
assert used <= registry.keys(),sorted(used-registry.keys())
parts.append('## Kaynak kayıtları')
parts.extend('- **'+sid+'** — '+entry for sid,entry in registry.items())
parts.append('### Kaynak-eleştiri ve tarama sınırı')
parts.append('Denetim 2 Ekim 2026 tarihinde bu dosyaya özgü olarak yapıldı. Çekirdek sekiz tefsirin belirtilen Mâûn pasajları, ayrıca Vâhidî’nin 107:1–2 ve 23:50 açıklamaları, Uleymî’nin gösterilen 107 metni, İbn Âşûr’un sûre girişi/107:1 açıklaması, Begavî 107:1 ve Bikāî 108:1 okundu. Râzî 108:1 için kapsam yalnız kayıtlı açılış bölümleridir. Basılı eserlerin tamamının, başka sûrelerin tüm tefsirlerinin veya yazma varyantlarının denetlendiği iddia edilmez. Bağımsız olarak açılmayan ilk kaynaklar, yalnız aktaran müellifin tanıklığı düzeyinde tutuldu.')
parts.append('Hadislerde sahih etiketi doğrulanan Sahîhayn kayıtlarına; hasen ve zayıf etiketleri ise belirtilen değerlendirme sahibine dayanır. Sonraki tefsirlerdeki tekrar yeni ve bağımsız isnad sayılmadı. Peygamber’e nispeti tartışmalı doğrudan tefsir haberleri, sahâbî açıklamaları ve tematik hadisler ayrıldı. Sözlük aktarımında madde sınırları ve kayıt kimlikleri korundu; metin neşrinin sayfa işaretleri basılı nüsha görüntüsü denetimi gibi sunulmadı.')
parts.append('Yenilik sonuçları yalnız her kayıtta adı ve bölümü gösterilen okuma alanı için geçerlidir. Açık öncül, kısmi öncül, ayrı yapıtaşları ve denetlenmemiş alanlar farklı tutuldu. S107_comprehensive_reference_v2.md bulunmadığından içeriği varsayılmadı; yazılı kanonik protokol izlendi. Özgün r13 ana metni ve bitişik üretim kayıtları kullanıldı; diğer bağımsız varyantların sonuçları veya araştırmaları kullanılmadı.')
output='\n\n'.join(parts)+'\n'
OUT.write_text(output)
(W/'annotations.json').write_text(json.dumps([{'after_base_block':p,**a} for p,items in insert.items() for a in items],ensure_ascii=False,indent=2)+'\n')
(W/'source_records.json').write_text(json.dumps(registry,ensure_ascii=False,indent=2)+'\n')
(W/'hadith_verification.json').write_text(json.dumps([dict(zip(['id','collection','number','url','topic','grade','grade_basis'],h)) for h in hadiths],ensure_ascii=False,indent=2)+'\n')
report={'output':str(OUT),'annotations':len(annotations),'by_type':dict(sorted(counts.items())),'registry_count':len(registry),'base_sha256':hashlib.sha256(BASE.read_bytes()).hexdigest(),'matrix_sha256':hashlib.sha256((W/'evidence_matrix.json').read_bytes()).hexdigest(),'base_blocks':len(chunks),'bytes':len(output.encode())}
(W/'build_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(report,ensure_ascii=False,indent=2))
