from pathlib import Path
import json, hashlib

W = Path(__file__).parent
claims = json.loads((W / 'claim_map.json').read_text())['claims']
# Substantive research decisions, completed before final annotation composition.
# Tuple: support; contradiction/constraint; early attestation; later development;
# hadith relationship; historical scope; novelty conclusion; confidence.
rows = [
('Tabari 107:1 حساب/جزاء; Razi 107:1 mesele 2 question of astonishment; Biqai 107:1 attention; Raghib رأي attention formula', 'IbnAshur 107:1 calls seeing visual, one-object construction; do not claim only inner seeing', 'Tabari reports IbnAbbas حكم الله and IbnJurayj الحساب without a new independent grade', 'Razi general audience alongside Prophet; IbnAshur present tense repeated character', 'none directly', 'named referents uncertain; general address remains', 'explicit for attention; interpretive emphasis on ethical seeing', 'high'),
('Zamakhshari 107:6; Razi 107:6 work shown for returned praise; Jawhari رأى mirror/holding mirror; Raghib رأي mirror', 'تَراءى form VI is not يُراءون form III; participation is rhetorical motive, not automatic two equal lookers; verse 6 is penultimate, not last', 'IbnFaris رأي and Jawhari separate lexical mirror attestations', 'Razi distinction munafiq/murai and Zam public worship exception', 'Muslim2985/2986 thematic; Muslim2642a unsolicited praise counterexample', 'no archaeological mirror practice asserted', 'partial: two-sided display explicit; literal mirror with107:1 not found in inspected107:1/6 sections', 'high'),
('Tabari107:5 IbnAbbas/Mujahid private neglect; Razi107:7 final suitability passage inversion of God/people owed acts; Suyuti107:7 Zayd bAslam visible prayer/hidden zakat', 'Cannot infer every public prayer insincere or every isolated person abandons prayer', 'early reports in Tabari, Zayd bAslam through Suyuti', 'Razi explicit unity is major predecessor', 'Muslim622 thematic hypocrisy of prayer; not verse-specific prophetic tafsir', 'nifaq reading does not settle Medinan chronology', 'explicit visible worship/hidden help inversion', 'high'),
('Q96:6–14,26:218–219,4:142,4:38,76:8–9,92:19–20 exact Arabic inspected', 'Allah seeing and human spectators differ; Q96 prayer is restrained by another,107 prayer-doer displays; no causal revelation connection proved', 'Raghib رأي quotes96:9 attention separately', 'no combined Alak-to-mirror reading found in core107:1/6 passages', 'Muslim2985 corroborates sincerity, not cross-surah intent', 'no sequence dating inferred', 'building_blocks_only for integrated Quran montage', 'medium'),
('Raghib كذب cloth painted like decorated textile lies by its state; Razi107:4–5 m1 prayer manufactured from riya and sahw; Q2:264,63:4,2:177', 'cloth noun not107 verb meaning; Raghib does not specify all fabric-making details of base', 'Raghib material metaphor independent of107', 'Razi counterfeit prayer explicit partial antecedent', 'Muslim2985 thematic', 'no claim everyday seventh-century audience saw this cloth', 'partial: false outward prayer old; cloth107 junction not found in inspected core', 'high'),
('IbnFaris كذب stopped attack; Raghib كذب milk disappointing expectation, رأي pregnancy showing; Q53:33–34 giving stops', 'IbnFaris says milk account زعموا وفيه نظر; lexical image cannot become actual revelation event', 'separate lexicon entries', 'Tabari107:5 persistent negligence, not runner/camel connection', 'Muslim572a prevents equating transient lapse and condemnation', 'no historical camel incident', 'building_blocks_only', 'medium'),
('Tahdhib دين: dayyantu alhalif niyyah; IbnFaris دين submission, recompense; Tabari107:1 reckoning', 'technical legal intention expression not meaning of بالدين; no authorization to claim unknown hearts', 'IbnArabi through Tahdhib, source layered', 'Razi107:1 Islam/recompense alternatives', 'none direct', 'sourced oath idiom only; no actual trial reconstructed', 'building_blocks_only for oath-to-sincerity bridge', 'high'),
('Tabari107:5 delay, omit alone, indifference and broad choice; Zam107:5 an/fi; Baydawi107:5; Razi107:4–5 m2–3', 'Razi challenges reading an as total abandonment if named prayer-doers, responds outward only/persistence; normal involuntary forgetfulness not equivalent', 'Saad report time-neglect stronger mawquf according Suyuti/IbnKathir', 'IbnKathir107:5 broad conditions/khushu; Razi safeguards from equating every sin and disbelief', 'Muslim572a sahih ordinary sehiv; Muslim622 sahih deliberate delay; AbuBarza direct tafsir weak per IbnKathir', 'public/private practice reported not universal biography', 'explicit basic distinction; preserve internal disagreement', 'high'),
('IbnFaris يتم solitary; Tahdhib يتم humans father vs animals mother, Mufaddal ghafla/AbuAmr slowness accounts, isolated pearl', 'IbnFaris does not derive orphan from ghafla; alternative lexicographer proposals not synonyms for every orphan', 'multiple named lexical accounts, not one consensus', 'Tabari107:2 protection/food; Qurtubi107:2 inheritance exclusion report', 'Bukhari6005 orphan care thematic sahih', 'loss of father and property guardianship context; no blanket picture of all preIslamic families', 'building_blocks_only for orphan/prayer forgetting analogy', 'high'),
('IbnFaris سهو: forgetfulness/stillness, musahat overlook faults; Suha star possible member; Muslim1039a unseen nonbegging needy thematic', 'Maqayis says Suha محتمل; sky not in107; charitable overlook versus harmful neglect different objects', 'primary lexicon explicitly qualifies the etymology', 'no star107 linkage in eight complete107 corpora', 'Muslim1039a strong thematic, not star allegory', 'no star-watching custom reconstructed', 'building_blocks_only, combination speculative/resonant', 'high'),
('Q51:10–11 sahun in gamra;93:6/9 shelter/orphan;9:67 closed hands and forgetting', 'gamra can be figurative heedlessness, not actual pool in51:11;107 no body of water', 'Quran exact wording', 'no joint Suha-water reading found core107:2/5/7', 'Muslim1039a complementary', 'none', 'building_blocks_only', 'medium'),
('Tabari107:2 pushing from right/food; Tahdhib دعع falling-child encouragement and dependents; IbnFaris منع withholding/fortification; Razi107:3 on107:2 push52:13', 'IbnFaris حضض TWO originals urge versus lower ground, حث for driving not حض; IbnFaris دعع says cries do not form regular root analogy', 'lexical proverbs and concrete push sense separate', 'Biqai107:2–3 aggression/withheld mercy pairing', 'Bukhari6005/5353 thematic care', 'no inference miskin physically immobile always', 'partial push reciprocity; building_blocks_only hands/low-ground integration; reject unified derivation', 'high'),
('Razi107:3 taam possessive as poor right; self/others urging; Biqai107:3 due sustenance; Tabari107:3 failure encouragement', 'Razi recognizes inability/advice ineffective/risk; silence alone does not certify disbelief; food IS mentioned107:3 (base ambiguous false wording)', 'reports early feeding failure', 'Razi/Biqai rights and agency articulation', 'Bukhari5353 social service like worship thematic', 'right language not full adjudication of individual property obligation', 'explicit', 'high'),
('Razi107:3 explicitly cites52:13 push; Q89:17–18 adjacent orphan/feeding, Q68:17/23–24 exclusion,90:15–17 mercy; Q4:37 bidding stinginess', 'retributive echo not identity of all persons or proof every lexeme is inserted hidden meaning', 'Quran parallels; Tahdhib دعع also juxtaposes107:2/52:13', 'Razi107:3 mercy/patience90:17,103:3', 'none direct', 'garden story not Maun sabab', 'partial: push and exhortation links explicit; full network project', 'high'),
('Tahdhib دعع little dependents/shaken filled bowl; IbnFaris سكن household/hearth; Maqayis سهو sahwa porch; maun tools classical consensus of one branch', 'IbnFaris sahwa porch شذ عن هذا الباب; lexical inventory not assertion all meanings activated107; shelf detail not independently newly verified', 'lexical material separate; IbnMasud vessels in AbuDawud1657', 'Razi107:7 oven/neighbor storage vivid material examples', 'AbuDawud1657 hasan Albani companion reading', 'loans/neighbor oven verified interpretive exempla; not actual house photographed', 'building_blocks_only complete home; explicit tool practice', 'high'),
('Tabari107:7 zakat Ali/IbnUmar, tools IbnMasud, good Muhammad bKab, money SaibnMusayyab/Zuhri, water poetry; own all useful help; Razi/Qurtubi multiple senses', 'avoid one uniform traditional sense; etymology mauna/awn alternative Qurtubi107:7; generic preIslamic gift→Islam zakat not exhaustive historical law', 'earliest reported voices remain distinct from collector and chain certainty', 'Ikrima largest zakat/smallest needle in IbnKathir; Qurtubi 12 views', 'AbuDawud1657 direct companion-era attestation not prophetic speech', 'common lending and due dues both possible', 'explicit semantic plurality', 'high'),
('IbnKathir107:7 lending substance retained/returned; Razi107:7 oven/storage/needle and virtue lending; Qurtubi necessity distinctions', 'tiny cost is rhetorical typicality not universal financial fact; necessity and harmless voluntary loans not one legal class', 'IbnMasud concrete bucket/pot', 'Razi extended social practice; Qurtubi legal nuance', 'AbuDawud1657 hasan', 'do not impose contemporary legal advice', 'explicit practice; project cost arithmetic limited', 'high'),
('Q18:77 refusal of hospitality and18:82 orphan-owned wall; Q4:8 share/words; Q12:63 blocked measure;83:1–3 weights', 'Q18 merciful servant acts by disclosed divine instruction; no lexical root identity of all scenes; their own tafsir sections not checked', 'Quran exact contexts', 'Razi107:7 hospitality tools adds only partial general support', 'none', 'no claim one historical incident', 'building_blocks_only; outside-sura tafsirs not_checked', 'medium'),
('Maqayis معن flowing water/easy passage; Tabari107:7 rainwater; Wahidi alBasit23:50 Fara derivations and AbuAli m-n plus maun water/fire/grass/zakat, giving rights; Maqayis طعم cites2:249 water', 'Zajjaj and IbnQutayba in Wahidi prefer عين visible water; AbuAli rejects that with qualified analogy; Maqayis معن does not itself include maaun lemma', 'classical lexical and exegetical water-rights ingredients explicitly combined before project', 'Razi107:7 water view; Qurtubi107:7 alternative mauna origin', 'Bukhari2353 surplus water denial prevents pasture, thematic sahih', 'actual irrigation regime not reconstructed', 'partial/explicit for water-rights connection, project107 scene broader', 'high'),
('Q67:30 araaytum and main;23:50 shelter/main;93:6 orphan/shelter; Wahidi23:50 cross-references67:30', '107 and67 have different word forms; m-n attribution conditional; shelter verse about Mary/Jesus not orphan label for Jesus', 'Wahidi already connects23:50 and67:30 water philology', 'no three-surah plus107 full shelter ring core107 corpus', 'Bukhari2353 thematic only', 'no geographical identity inferred for23:50 disputed location', 'partial', 'high'),
('IbnFaris صلو two originals fire versus worship; سكن fire/household; Q69:31/34 punishment vs hunger;4:10 wrongful orphan property into fire', 'Original dictionary marks صلي ECHO not identity; Maqayis explicitly separates two originals. Reject derivation prayer literally burning/wood straightening', 'lexical sound/family proximity only', 'no prayer etymology from fire in core107:4–7 passages', 'IbnMajah2474 water/salt/fire weak; not proof sacred hearth etymology', 'no fire ritual ancestry asserted', 'building_blocks_only for hearth synthesis, rejected derivational identity', 'high'),
('Tabari107:4; Razi107:4–5 m1 wail great threat, relative clauses specify prayer-doers', 'do not quote107:4 detached to condemn prayer; wail specific valley report not established independently', 'received thematic threat', 'Razi says omission service Creator plus mercy creatures', 'Muslim572a supports constraint', 'none', 'explicit', 'high'),
('Q69:34 exactly107:3; Q83 denial day/fire;4:10 orphan wealth/fire;50:24–25 prevent good;74:43–46 prayer/food/false talk/account', '74 no prayer vs107 demonstrative prayer different; khawd not sahw root; none establish word salat means fire', 'Qurtubi107:3 explicitly69:34', 'Razi107:4 cites wail83:1 and punishment parallels', 'none direct', 'descriptions of judgment not dating', 'partial for69/Qurtubi, building_blocks_only for full74 assembly', 'high'),
('Maqayis دين submission/recompense/debt; Razi107:7 obedience alternative; Wahidi23:50 conceding rights; Tahdhib دين oath; Maqayis كذب kadhaba alayka urging', 'din107 reckoning not commercial debt; maun loan generally ariya not money deyn; IbnFaris admits obscurity urging idiom; no invented historical stage chronology', 'early separate senses preserved', 'Razi107:7 rights to God/creatures explicit ethical accounting antecedent', 'Bukhari1397 prayer/zakat account-positive thematic', 'distinguish gift, zakat, ariya, monetary debt', 'partial', 'high'),
('Q70:19–35 prayer encloses known financial right, affirmation account vs withholding; Q1:4/82:9/41:6–7/17:26/51:19', 'Maun structure seven vs long list70; omitted virtues in70 remain, no literal exact chiasm proven', 'Quran direct lexical overlaps', 'no whole Maun70 reversal found read core107 passages', 'Bukhari1397 obligatory prayer/zakat positive thematic', 'no detailed zakat rates dated to107', 'building_blocks_only for comparative architecture', 'high'),
('Q9:103 exact charity/purification/Prophet prayer/comfort; Bukhari1497 IbnAbiAwfa confirms received gifts followed by prayer; Maqayis صلو dua and سكن comfort', '9:103 addressee Prophet, salat there supplication for givers while107 ritual; cannot erase ritual by external social effect', 'sahih narrated practice independent of107', 'Razi107:7 inversion God/people claim direct predecessor but not9:103 loop', 'Bukhari1497 sahih thematic not direct107 tafsir', 'institutional receiving alms explicit; no full economy inferred', 'partial', 'high'),
('Q11:87 critique prayer/property;2:83 BaniIsrael pact,19:31 Jesus prayer/zakat,9:54 reluctant worship/giving,29:45 ethical effect,19:59 waste prayer', 'different addressees/covenant settings not single legislative episode; ritual cannot reduce to social service', 'Quran', 'Razi107:4–5 m1 explicitly invokes29:45', 'Bukhari5353 charitable service analogized ritual without identity', 'separate prophet contexts retained', 'partial with29:45 explicit', 'high'),
('Biqai107:1 Quraish worship feeding/security;107:7 returns beginning and predicts abundant Kawthar; Razi108:1 FIRST latifa four oppositions', 'Biqai numerological word count history not verified; literary unity does not prove one occasion or same historical referent', 'no independent earliest date claimed', 'classical nazm explicit, broad network new only arrangement', 'none direct', 'Makkī/Madanī reports contested', 'partial final ring, explicit neighbor sequence', 'high'),
('Qurtubi107:1 Mekki/Medeni traditions; IbnAshur107:1 introduction split3/4 and conditional17th; Wahidi Asbab107:1–2 AsbWail vs AbuSufyan; Razi107:1 multiple persons', 'not harmonizable one biography without new evidence; IbnAshur says one camel/week vs Wahidi/Razi two, source variation not certainty; no complete sanad regrading', 'Muqatil/Kalbi and IbnJurayj as attributed by Wahidi, earliest surviving checked source not original voices books', 'Razi alternatives; IbnAshur split preference is modern tafsir judgment', 'Suyuti107:7 borrowing hypocrites sabab from IbnMardawayh not independently graded', 'uncertain/contested', 'not_applicable', 'high'),
('Ulaymi Fath107:1 Nafi/AbuJafar ease, Kisai delete, others full; IbnAshur Warsh local transmission; Tabari107:1 IbnMasud no ba; Zam107:1 araytaka; Razi107:3 yadau/yaduu reports', 'Zam grammatical dislike deleted hamza not reason to deny received canonical reading; companions variants not silently normalized to Hafs; formal status of no-ba/yadau not independently checked', 'named reading reports', 'ten-reader account in Ulaymi verified actual excerpt, Nashr book not directly inspected', 'not hadith', 'transmission scope no manuscript claims', 'not_applicable', 'high'),
('Verified primary collections Muslim2985,2986,622,572a,2642a,1039a; Bukhari6005,5353,1397,2353,1497; AbuDawud1657; IbnMajah2474', 'direct107:5 raised Saad report disputed; AbuBarza weak per IbnKathir and Suyuti; Qurra107:7 marfu munkar per IbnKathir; no inferred grades from later quotation', 'companion maun usage distinguished from Prophet quote', 'later repetition not independent witnesses; virtue-of-surah closing reports not graded and not evidence', 'primary thematic vs direct/companion labels mandatory', 'source does not become sabab merely shares imagery', 'not_applicable', 'high'),
]
assert len(rows)==len(claims)==31
names=['supporting_sources','contradicting_sources','early_attestation','later_development','hadith_relation','historical_context','novelty_status','confidence']
matrix=[]
for c,row in zip(claims,rows):
 matrix.append({**c,**dict(zip(names,row))})
corpus={
 'completed_before_annotation_composition':True,
 'core_fully_read':['Tabari107:1–7','IbnKathir107:1–7','Suyuti107:1–7','Zamakhshari107:1–7','Razi107:1–7','Baydawi107:1–7','Biqai107:1–7','Qurtubi107:1–7'],
 'segmentation':'Razi4/5 bodies identical apart from displayed verse; aya2 discussion continues3. Baydawi4 and Suyuti3 have verse-only pages. Claims concern actual fetched commentary, not printed volume completion.',
 'additional_fully_read':['IbnAshur107:1 introduction/commentary','Baghawi107:1','Ulaymi107 complete displayed passage incl107:1–7','WahidiAsbab107:1–2','WahidiBasit23:50','Biqai108:1'],
 'additional_partial':['Razi108:1 opening two lataif plus beginning subsequent discussion; only first latifa used'],
 'lexicon_entries_fully_read':['Maqayis رأي كذب يتم حضض دعع دين سكن طعم منع صلو سهو معن','Raghib رأي كذب','Tahdhib يتم دعع دين','Jawhari رأى'],
 'quran_entries_read':len(json.loads((W/'sources/quran_selected.json').read_text())),
 'not_checked':['whole printed volumes','original manuscripts','complete independent rijal/isnad audit','Nashr primary volume (only Ulaymi report)','AbuAliIghfal primary volume (only Wahidi quotation)','outside-surah tafsirs except named passages','the absent S107_comprehensive_reference_v2.md','competing agent outputs/research'],
 'claims':matrix
}
(W/'evidence_matrix.json').write_text(json.dumps(corpus,ensure_ascii=False,indent=2)+'\n')
md=['# S107 Astra/MAX evidence decisions before composition','',corpus['segmentation'],'']
for r in matrix:
 md += ['## '+r['id']+' — '+r['claim'],'']
 md += ['- **'+k+'**: '+r[k] for k in names]+['']
(W/'evidence_matrix.md').write_text('\n'.join(md)+'\n')
print(json.dumps({'claims':len(matrix),'before_composition':True,'sha256':hashlib.sha256((W/'evidence_matrix.json').read_bytes()).hexdigest()}))
