# My research judgements for 103:3 (ehlikitap). build_verdicts.py only formats these into verdicts.jsonl.

A = 'S103-'

# accepted discovery connections: cid -> (paragraph, annotation id, reason)
ACC = {
 'BC-7ad8cc305ae2e3ad36d4': (1, 'TEV-MTF-001', "Ps 15:2 (opened) is the answer to 15:1's entrance question: a short list of acts (walking blameless, doing righteousness, speaking truth). Placed after Ps 14:3's universal verdict it gives the same order as 103:2-3 (universal sentence, then a group defined by a few acts); used at ¶1 as a structural parallel, not as a source."),
 'BC-0728b02c5703a4c2ff76': (2, 'TEV-MTF-002', "Mal 3:16 defines the group to be spared by reciprocal speech (nidberu ... ish et-re'ehu, a reciprocal niphal) and a book of remembrance; this matches ¶2's point that the last two verbs are reciprocal and define the excepted group."),
 'BC-b3282cfa5eb85dd2e851': (2, 'TEV-MTF-002', "Mal 3:18 completes the scene of 3:16: on the day the righteous are distinguished from the wicked. Cited in the ¶2 block as the outcome of the reciprocal speech; it supplies the separation element of the exception."),
 'BC-6e20d3a9f1028967af00': (2, 'TEV-MTF-002', "Avot 3:2 (SEFARIA, opened) explicitly reads Mal 3:16 as two people with words of Torah between them, with the Shekhinah present: a rabbinic reading that makes reciprocal speech of teaching the point. Included in the ¶2 Malachi block."),
 'BC-0e71bbe796c545e7e926': (2, 'INC-MTF-001', "1 Thess 1:3 (opened) characterizes a community by a compact formula: work of faith, labor of love, endurance of hope. Faith, work and endurance co-occur as a short defining list like 103:3's four verbs; the block notes the difference (love and hope instead of reciprocal counsel)."),
 'BC-f5ecdd7825cc15debed7': (2, 'INC-MTF-001', "Same verse and same point as the companion reading: the faith/work/endurance triad as a defining community formula, placed at ¶2 (four verbs)."),
 'BC-df474d09ed6cdc7f80d4': (3, 'INC-KRA-001', "Rom 4:5 (opened) explicitly reckons faith as righteousness to the one who does not work; set against Jas 2:24 it shows the NT's two emphases on faith and works, while 103:3 lists both verbs side by side. Placed at ¶3 where the faith-and-deeds formula is discussed; no adjudication."),
 'BC-df5b44704a06bd5464f7': (3, 'INC-KRA-001', "Jas 2:24 (opened) says a person is justified by works and not by faith alone; it is the second pole of the ¶3 contrast block with Rom 4:5."),
 'BC-0a1fa3670a7abf0369c1': (4, 'TEV-SYD-001', "Isa 7:9 (opened) plays ta'aminu (believe, hiphil) against te'amenu (be made firm, niphal): believing and being secure in one root, which is exactly ¶4's claim that the Arabic verb carries entering security. Motif reading is carried by the soydas block."),
 'BC-318d3f8a2d4c39a0425f': (4, 'TEV-SYD-001', "Wordplay check: the WLC verse has both forms of the root (תַאֲמִינוּ / תֵאָמֵנוּ); the basis is sound correspondence only, as the block states."),
 'BC-9d047c91b8f68f5f4bf8': (4, 'TEV-SYD-001', "Same verse; the two forms of אמן establish belief/firmness in one root. Accepted into the ¶4 soydas block with the basis marked (sound correspondence, no lexicon note)."),
 'BC-178480c63832e62653d3': (6, 'TEV-SYD-002', "Gen 15:6 (opened, וְהֶאֱמִן) with Gen 15:1 ('do not fear, I am your shield'): Abraham, removal of fear and believing in one scene, matching ¶6 (Abraham, security and iman). The block notes the difference of setting."),
 'BC-7ff8444c96543ab5f2b2': (6, 'TEV-SYD-002', "Hebrew he'emin in Gen 15:6 is the hiphil of אמן; used in the ¶6 block with the basis marked."),
 'BC-9456085c1188c63b8fb4': (6, 'TEV-SYD-002', "Same verse and root; accepted into the ¶6 block (Abraham's belief after the promise of protection)."),
 'BC-5a3331792d7ef3b42606': (7, 'TEV-SYD-003', "Exod 17:12 (opened): Aaron and Hur hold Moses' heavy hands; the block uses the scene for emunah as steadiness through the day. The support detail is carried in the ¶7 block rather than at ¶32."),
 'BC-3e0e0a6fd47043be8162': (7, 'TEV-SYD-003', "Exod 17:12 has אֱמוּנָה meaning steady hands until sunset: the firmness sense of the root, matching ¶7's emun (reliability proven along the road)."),
 'BC-d63523f1d53bcbfc2a95': (7, 'TEV-SYD-003', "Same verse; emunah = steadiness, accepted into the ¶7 soydas block with Dan 6:5 for the Aramaic 'trustworthy'."),
 'BC-78573c6fcac493050145': (7, 'TEV-SYD-003', "Companions holding Moses' arms until evening; mentioned in the ¶7 block as the setting of emunah. Its guarantor reading (¶32) is not developed separately to avoid a repeat."),
 'BC-ef847d9b0cc7e607a6ec': (9, 'TEV-KRA-001', "Gen 37:31 (opened): the brothers dip Joseph's tunic in goat's blood, the same false evidence as 12:18's dam kadhib; cited in the ¶9 counter-narrative block."),
 'BC-596c5e55f50c11c29c2c': (9, 'TEV-KRA-001', "Gen 37:33 (opened): Jacob recognizes the tunic and accepts the report ('a wild beast devoured him'), whereas in ¶9 Jacob withholds trust and chooses sabr. The difference is the point of the block."),
 'BC-15bf0d942d3df7c0dc01': (9, 'TEV-KRA-001', "Gen 45:26 (opened) uses לֹא־הֶאֱמִין לָהֶם for Jacob's disbelief of the true report: the same root as iman, applied to the brothers' word, reversed relative to the Qur'anic scene. Part of the ¶9 block."),
 'BC-0ff3609434f4184056b6': (10, 'TEV-SYD-005', "Eccl 1:3 (opened) uses עָמָל for toil and asks about yitron (gain): the Hebrew word's range is burdensome toil, unlike ¶10's intentional amal; accepted as the soydas block's main witness."),
 'BC-a1b51ca6df6929ecfb5f': (10, 'TEV-SYD-005', "Eccl 2:11 (opened) concludes 'there is no gain under the sun' for all his amal: cited in the ¶10 block as Qohelet's answer."),
 'BC-a8d552042c32e8319a60': (10, 'TEV-SYD-005', "Eccl 4:9 (opened): two have a good wage in their amal; the one place in the book where toil yields reward is joint labour, cited in the ¶10 block."),
 'BC-37b992490a6c400caa25': (10, 'TEV-SYD-005', "Eccl 4:10 (opened): if one falls the other lifts him; cited with 4:9 in the ¶10 block as the reciprocal condition of the good wage."),
 'BC-75391b4f7ae98ac4acaa': (11, 'TEV-MTF-003', "Avot 2:15 (SEFARIA, opened): R. Tarfon's day short / work much / wage great / master pressing; a pre-Qur'anic day-work-wage image matching ¶11's afternoon wage scene and the worker's word."),
 'BC-79aff752b70d7f4c1345': (11, 'TEV-MTF-003', "Avot 2:16 (opened): 'faithful (ne'eman) is your employer to pay the wage of your labour'; cited in the ¶11 block, also showing the amn root for reliability."),
 'BC-15f2f6b9b00b3d52ca7c': (11, 'TEV-MTF-003', "Deut 24:15 (opened): pay the poor labourer's wage on his day before the sun sets; work, wage and day's end, cited in the ¶11 block."),
 'BC-7b6a9dec8c79a17a2e43': (11, 'TEV-MTF-003', "Same verse and point (wage due before sunset); accepted into the ¶11 block."),
 'BC-3340da416b685c1cdaa8': (11, 'INC-MTF-002', "Matt 20:8 (opened): at evening the vineyard owner has the workers paid; a parable scene of evening wages matching ¶11."),
 'BC-aed1d4286ca8dd695814': (11, 'INC-MTF-002', "Same verse; evening wages to labourers, accepted into the ¶11 block."),
 'BC-6d44104119e87a37cc06': (11, 'INC-MTF-002', "Matt 20:12 (opened): those who bore the day's burden are made equal to one-hour workers; the block notes how the parable breaks the measured-wage expectation."),
 'BC-f3c86888e724a2f1e770': (11, 'INC-MTF-002', "Matt 20:15 (opened): the owner grounds the equal pay in his goodness; cited in the ¶11 block."),
 'BC-47c4077b464b8596ea4d': (12, 'INC-KRA-002', "1 Cor 3:15 (opened): if a work burns the worker suffers loss (ζημιωθήσεται) yet himself is saved; shares ¶12's 'loss attached to work' but differs on the person's fate, so a counter-narrative block."),
 'BC-12d77d71b65b81374216': (14, 'TEV-MTF-004', "Mishnah Peah 1:1 (opened): deeds whose fruits one eats now while the principal (qeren) remains for the world to come; a capital image for lasting deeds matching ¶14 (eroding capital vs. lasting salihat)."),
 'BC-81dd57a019f777054e4e': (14, 'TEV-MTF-004', "Same mishnah; the list includes making peace between people; accepted into the ¶14 block."),
 'BC-841109ac2441c39b91bd': (14, 'INC-MTF-003', "1 Cor 3:14 (opened): if the work built remains, the builder receives a wage; lasting work tied to reward, matching ¶14."),
 'BC-f90ad6c515ea8f6caaf5': (14, 'INC-MTF-003', "1 Cor 3:13 (opened): the day will reveal and test each one's work; cited in the ¶14 block as the setting of 3:14."),
 'BC-68f4b4596893e55d2e08': (19, 'INC-MTF-004', "Heb 10:24 (opened): consider one another (ἀλλήλους) to provoke love and good works; reciprocal exhortation joined to good works, matching ¶19's reciprocal form."),
 'BC-0ea9d4d1963113542721': (19, 'INC-MTF-004', "Same verse and point; accepted into the ¶19 block."),
 'BC-5ef1e9b34e081ad322c5': (19, 'INC-MTF-004', "Heb 10:25 (opened): not forsaking the assembly, encouraging one another as the day approaches; cited in the ¶19 block."),
 'BC-b780e4aa61d77ee39840': (19, 'INC-MTF-004', "Same verse; mutual encouragement as the day nears; accepted into the ¶19 block."),
 'BC-f68cabe3b00d1d6fe35c': (20, 'TEV-PRL-001', "Gen 18:19 (opened): Abraham chosen so that he will command (יְצַוֶּה) his sons and household after him to keep the way and do righteousness; same figure and act as 2:132 cited at ¶20."),
 'BC-f5e1ca91adc26eaf9ee8': (20, 'TEV-YGL-001', "Gen 49:29 (opened): Jacob's charge before death concerns burial with his fathers; cited in the ¶20 block to show Genesis lacks the question of 2:133, which Pesachim 56a supplies."),
 'BC-efd8d740595f115f928a': (22, 'TEV-MTF-005', "Zech 8:16 (opened): 'speak truth each man to his neighbour' (emet, ish et-re'ehu), truth handed reciprocally, matching ¶22; the block adds that emet belongs to the amn root."),
 'BC-7453c9208406e428238c': (22, 'TEV-MTF-005', "Same verse; the reciprocal truth command is used in the ¶22 block. The judging-for-peace clause is not developed."),
 'BC-5e12796c305ee337968e': (22, 'INC-MTF-005', "Eph 4:25 (opened) takes Zechariah's command and grounds it in 'we are members of one another'; accepted at ¶22 as the Christian reuse."),
 'BC-8d3a1076c6901a43ee0c': (22, 'INC-MTF-005', "Same verse and point; accepted into the ¶22 block."),
 'BC-a360c4db699bd7d3926d': (26, 'INC-MTF-006', "2 Tim 2:24 (opened): the Lord's servant must not quarrel, being forbearing (ἀνεξίκακον); matches ¶26 (haqq made the object of counsel, not quarrel)."),
 'BC-4665af3778822b4f0e94': (26, 'INC-MTF-006', "2 Tim 2:25 (opened): gentle correction of opponents toward knowledge of truth; completes the ¶26 block."),
 'BC-3d00a3f9240a44c5b794': (26, 'TEV-KRA-002', "Avot 5:17 (opened): a dispute for the sake of Heaven endures (Hillel and Shammai), one not for Heaven does not (Korah); evidence that complicates ¶26's opposition of quarrel and counsel; reported without adjudicating."),
 'BC-b65ebedbd4efa0701bc2': (27, 'INC-MTF-007', "Rom 2:6 (opened): God will repay each according to his works; matches ¶27 (the day confronting each person with his work)."),
 'BC-5650485a40d4706cecad': (27, 'INC-MTF-007', "Same verse; accepted into the ¶27 block."),
 'BC-686e1f8910ee7341ab06': (27, 'INC-MTF-007', "Rom 2:7 (opened): 'by endurance in good work' (καθʼ ὑπομονὴν ἔργου ἀγαθοῦ); joins endurance and good work in the judgment scene; cited in the ¶27 block."),
 'BC-a5ffa48c17bd6cb5b882': (27, 'INC-MTF-007', "Same verse; accepted into the ¶27 block."),
 'BC-f6a5639bc49c4dde4c80': (27, 'INC-MTF-007', "Rom 2:8 (opened): those who disobey the truth and obey injustice receive wrath; adds the truth element to the ¶27 block."),
 'BC-f2f489390f0e52da1e92': (29, 'TEV-SYD-009', "Gen 16:2 (opened): עֲצָרַנִי, 'the LORD has restrained me', restraint by another; with Prov 25:28's self-restraint it shows both directions named in ¶29."),
 'BC-713b1557d787483dd627': (29, 'TEV-SYD-009', "Same verse, ʿṣr soydas reading; accepted into the ¶29 block with the basis marked (sound correspondence only)."),
 'BC-3c5523e252da07fd9bb1': (30, 'TEV-MTF-006', "Prov 29:11 (opened): the fool lets out all his spirit, the wise holds it back; the stopper/vessel image of ¶30 as behaviour."),
 'BC-f8cc665bf5ffe29b79b7': (30, 'TEV-KRA-003', "Exod 9:11 (opened) with 8:15: Egypt's magicians concede 'the finger of God' but do not believe, and cannot stand before Moses; the Qur'anic magicians of 7:124-126 (¶30) believe and pray for patience. Difference recorded as counter-narrative."),
 'BC-a998b06a7ebd7774844b': (32, 'TEV-MTF-007', "Gen 43:9 (opened): Judah becomes surety (אֶעֶרְבֶנּוּ) for Benjamin; the guarantor image of ¶32 enacted in narrative."),
 'BC-99ae6fce542ccd7884fe': (32, 'TEV-MTF-007', "Gen 44:33 (opened): Judah offers to remain as slave in the boy's place, paying the surety; cited in the ¶32 block."),
 'BC-7deca6e804e919e3b318': (32, 'INC-MTF-008', "Gal 6:2 (opened): bear one another's burdens; reciprocal bearing matches ¶32 (one holds in place of another)."),
 'BC-688f4397f1fcb6d86fcd': (32, 'INC-MTF-008', "Same verse; accepted into the ¶32 block."),
 'BC-586c31ea269a1af450b8': (32, 'INC-MTF-008', "Gal 6:1 (opened): restore a transgressor gently and watch yourself; cited in the ¶32 block to show that bearing is joined to counsel."),
 'BC-8b95ba8ec2517681c237': (32, 'INC-MTF-008', "Same verse; accepted into the ¶32 block as context of 6:2."),
 'BC-e22c55a0360fe9b7f17b': (35, 'TEV-SYD-010', "Gen 41:49 (opened): וַיִּצְבֹּר, Joseph heaps grain until counting stops 'for it was without number'; Hebrew ṣbr = heap only, sharing the unweighed-heap sense of ¶35 and not the patience sense."),
 'BC-26e31057ddc2566ff2b4': (36, 'TEV-MTF-008', "Hab 2:3 (opened): wait for the vision, it will surely come and not lie; waiting grounded in the sureness of the promise, matching ¶36 (40:55)."),
 'BC-7f911ffbc4d38ca1844d': (36, 'TEV-MTF-008', "Same verse; accepted into the ¶36 block."),
 'BC-be8da0f73611b0c3a1b4': (36, 'TEV-MTF-008', "Hab 2:4 (opened): the righteous lives by his emunah, next to the waiting command; cited in the ¶36 block."),
 'BC-3e6082987087bccfade6': (36, 'TEV-MTF-008', "Hab 2:4 emunah is from אמן; the block names the root of the word carrying the waiting (basis: sound correspondence)."),
 'BC-ca591a0943a0dfbe5020': (36, 'TEV-MTF-008', "Same verse and root reading; accepted into the ¶36 block."),
 'BC-6e593efb60837ed788f6': (36, 'INC-YGL-001', "Heb 10:36 (opened): 'you need endurance' to receive the promise; Hebrews then cites Habakkuk (10:37-38). Christian reading of the Hab parallel joining endurance and faith, at ¶36."),
 'BC-071f95aef4b6e90b8f87': (36, 'INC-YGL-001', "Same verse; accepted into the ¶36 block."),
 'BC-ccac9679598d59f0312d': (36, 'INC-YGL-001', "Heb 10:38 (opened): 'my righteous one shall live by faith', applying Hab 2:4; cited in the ¶36 block."),
 'BC-da8c0474dc5f679657cd': (38, 'TEV-MTF-009', "Prov 25:21 (opened): feed a hungry enemy; answering hostility with good, matching ¶38 (41:34)."),
 'BC-cd88969cba37ad9d9164': (38, 'TEV-MTF-009', "Same verse; accepted into the ¶38 block."),
 'BC-32ea521f5bc77b850798': (38, 'TEV-MTF-009', "Prov 25:22 (opened): coals on his head and the LORD will repay; the block notes the disputed sense and that the text does not say the enemy becomes a friend."),
 'BC-5e79ee89071566bfad88': (38, 'INC-MTF-009', "Rom 12:20 (opened) quotes Prov 25:21-22; cited in the ¶38 block."),
 'BC-98026b7e71171282e7df': (38, 'INC-MTF-009', "Same verse; accepted into the ¶38 block."),
 'BC-33d45ad2dd53c8236366': (38, 'INC-MTF-009', "Rom 12:21 (opened): overcome evil with good; the same movement as 41:34's repelling evil with what is better (¶38)."),
 'BC-64dfc5b67c9494c267c7': (38, 'INC-MTF-009', "Same verse; accepted into the ¶38 block."),
 'BC-c563e42382d31d54cf62': (38, 'INC-MTF-009', "Rom 12:12 (opened): enduring in affliction (τῇ θλίψει ὑπομένοντες) in the same exhortation chain; cited in the ¶38 block for the patience link of 41:35."),
}

# rejected discovery refs (default reason for every cid of the ref)
REJ = {
 'SBLGNT:1Cor.12.25': "Opened. Members caring for one another in the body image; keyword-only: mutual care. ¶32's guarantor point is carried by Gal 6:2 and Gen 43-44.",
 'SBLGNT:1Cor.12.26': "Opened. Shared suffering and honour of members; keyword-only: solidarity. No shared counsel, truth or patience formula.",
 'SBLGNT:1Cor.13.6': "Opened. Love rejoices with the truth; keyword-only: truth. No reciprocal counsel of truth.",
 'SBLGNT:1Cor.13.7': "Opened. Love bears and endures all things; keyword-only: endurance. Not the reciprocal patience of the ayah.",
 'SBLGNT:1Cor.15.58': "Opened. Labour in the Lord not in vain; keyword-only: work not lost. The lasting-work point is carried by 1 Cor 3:14 and Peah 1:1.",
 'SBLGNT:1Cor.3.6': "Opened. Planting and watering by different workers; keyword-only: plants. ¶17's image is joined vegetation, not successive cultivation.",
 'SBLGNT:1Cor.3.8': "Opened. Each receives wage by his labour; the wage point at ¶11 is carried by Matt 20 and Avot 2:15; adds no new element.",
 'SBLGNT:1Cor.3.9': "Opened. God's field and building; keyword-only: field/building metaphor.",
 'SBLGNT:1Cor.9.10': "Opened. Ploughman works in hope of a share; keyword-only: worker's share.",
 'SBLGNT:1Cor.9.25': "Opened. Athlete's self-control for a crown; keyword-only: self-control. Not the commentary's restraint images.",
 'SBLGNT:1Cor.9.9': "Opened. Do not muzzle the threshing ox; keyword-only: working animal. ¶24's load image concerns capacity, not wages.",
 'SBLGNT:1John.3.17': "Opened. Closing one's heart to a needy brother; broad ethical theme without the haqq-as-due formula.",
 'SBLGNT:1John.3.18': "Opened. Love in deed and truth; keyword-only: deed and truth. Not reciprocal counsel.",
 'SBLGNT:1John.3.23': "Opened. Believe and love one another; keyword-only: faith plus reciprocity; the faith-work catalogue point is carried by 1 Thess 1:3.",
 'SBLGNT:1Pet.2.20': "Opened. Enduring suffering for doing good; keyword-only: endurance. The cost-of-truth point is not this verse's subject.",
 'SBLGNT:1Pet.3.15': "Opened. Answer for one's hope with gentleness; keyword-only: gentle speech. ¶26's quarrel/counsel point is carried by 2 Tim 2:24-25.",
 'SBLGNT:1Pet.3.20': "Opened. Few (eight souls) saved through water; broad theme of a saved few; no exception formula or deed list.",
 'SBLGNT:1Pet.3.9': "Opened. Bless instead of returning insult; duplicates the ¶38 point carried by Rom 12:21 and Prov 25:21.",
 'SBLGNT:1Pet.4.19': "Opened. Entrust soul to the Creator while doing good; keyword-only: trust and good. No shared image.",
 'SBLGNT:1Thess.5.11': "Opened. Encourage and build up one another; reciprocal exhortation, but the ¶19 point is carried by Heb 10:24-25, which also joins good works; one block per point.",
 'SBLGNT:1Thess.5.14': "Opened. Admonish, encourage, help, be patient with all; a list of community duties; the reciprocal-counsel point is carried by Heb 10:24-25 and the catalogue by 1 Thess 1:3.",
 'SBLGNT:1Tim.6.11': "Opened. Pursue righteousness, faith, love, endurance; virtue list without reciprocity; catalogue point carried by 1 Thess 1:3.",
 'SBLGNT:1Tim.6.18': "Opened. Rich to do good and share; keyword-only: good works.",
 'SBLGNT:1Tim.6.19': "Opened. Treasure as foundation for the future; the lasting-capital point is carried by Peah 1:1.",
 'SBLGNT:2Cor.4.16': "Opened. Inner man renewed daily; keyword-only: daily renewal.",
 'SBLGNT:2Cor.4.17': "Opened. Momentary affliction, eternal weight of glory; broad theme.",
 'SBLGNT:2Cor.4.18': "Opened. Seen things temporary, unseen eternal; broad theme of permanence.",
 'SBLGNT:2Cor.4.7': "Opened. Treasure in clay vessels; the vessel image differs: fragile container of divine power, not a stopper keeping contents in.",
 'SBLGNT:2Cor.4.8': "Opened. Afflicted but not crushed; keyword-only: endurance under pressure.",
 'SBLGNT:2Cor.4.9': "Opened. Struck down but not destroyed; keyword-only: endurance.",
 'SBLGNT:2Cor.5.10': "Opened. Each receives for deeds at Christ's judgment seat; the repayment-by-works formula is carried at ¶27 by Rom 2:6-8.",
 'SBLGNT:2Cor.8.13': "Opened. Relief of others without your affliction; keyword-only: fair burden.",
 'SBLGNT:2Cor.8.14': "Opened. Abundance supplying another's want; keyword-only: mutual supply.",
 'SBLGNT:2John.1.4': "Opened. Children walking in truth; keyword-only: truth.",
 'SBLGNT:2John.1.5': "Opened. Love one another as old command; keyword-only: reciprocal love.",
 'SBLGNT:2John.1.6': "Opened. Love is walking by the commands; keyword-only: command.",
 'SBLGNT:2Pet.1.5': "Opened. Add virtue to faith; virtue chain; catalogue point carried by 1 Thess 1:3.",
 'SBLGNT:2Pet.1.6': "Opened. Self-control then endurance; virtue chain; no reciprocity or truth counsel.",
 'SBLGNT:2Pet.1.7': "Opened. Brotherly affection and love; end of the virtue chain; keyword-only.",
 'SBLGNT:2Pet.2.17': "Opened. Waterless springs, storm-driven mists; image of false teachers; ¶17's cloud is a surah-level image, not this ayah's.",
 'SBLGNT:2Thess.1.3': "Opened. Faith grows and love for one another increases; keyword-only: faith and reciprocity.",
 'SBLGNT:2Thess.1.4': "Opened. Endurance and faith in persecution; keyword-only: endurance and faith.",
 'SBLGNT:2Tim.1.14': "Opened. Guard the good deposit; keyword-only: deposit/trust.",
 'SBLGNT:2Tim.2.2': "Opened. Entrust what you heard to faithful men to teach others; transmission theme; ¶18-20's generational point is carried by Gen 18:19.",
 'SBLGNT:2Tim.3.10': "Opened. Paul's teaching, faith, patience, love, endurance; virtue list; no new element beyond 1 Thess 1:3.",
 'SBLGNT:2Tim.4.2': "Opened. Reprove, rebuke, exhort with all patience; truth-then-patience is close, but ¶26 already carries 2 Tim 2:24-25 from the same letter; one block per point.",
 'SBLGNT:2Tim.4.3': "Opened. People heaping up teachers for their desires; keyword-only: transmission of error (¶21 is about 51:53).",
 'SBLGNT:2Tim.4.7': "Opened. Fought the fight, kept the faith; keyword-only.",
 'SBLGNT:2Tim.4.8': "Opened. Crown of righteousness on that day; keyword-only: reward on the day.",
 'SBLGNT:3John.1.3': "Opened. Brothers testify to your truth; keyword-only: truth.",
 'SBLGNT:3John.1.5': "Opened. Faithful work for brothers and strangers; keyword-only: faithful work.",
 'SBLGNT:Acts.2.42': "Opened. Teaching and fellowship; broad communal theme.",
 'SBLGNT:Acts.2.44': "Opened. Believers had all things common; broad communal theme; ¶17's image is not property sharing.",
 'SBLGNT:Acts.2.45': "Opened. Distribution by need; broad theme; haqq as due share at ¶23 is lexical, carried by Lev 10:13.",
 'SBLGNT:Acts.4.32': "Opened. One heart and soul, all things common; broad communal theme.",
 'SBLGNT:Acts.4.34': "Opened. No needy among them; broad communal theme.",
 'SBLGNT:Acts.4.35': "Opened. Distribution according to need; broad theme.",
 'SBLGNT:Col.1.10': "Opened. Bearing fruit in every good work; keyword-only: fruit/good work.",
 'SBLGNT:Col.1.11': "Opened. Strength for endurance and patience; keyword-only: endurance.",
 'SBLGNT:Col.3.13': "Opened. Bear with and forgive one another; reciprocal forbearance close to ¶32, but Gal 6:2 carries the bearing point; one block per point.",
 'SBLGNT:Col.3.16': "Opened. Teaching and admonishing one another; reciprocal admonition, but the ¶19 reciprocal point is carried by Heb 10:24-25.",
 'SBLGNT:Eph.2.10': "Opened. Created for good works; keyword-only: good works.",
 'SBLGNT:Eph.2.8': "Opened. Saved by grace through faith; the faith/works contrast at ¶3 is carried by Rom 4:5 and Jas 2:24; duplicate.",
 'SBLGNT:Eph.2.9': "Opened. Not from works; same contrast already carried at ¶3 by Rom 4:5; duplicate.",
 'SBLGNT:Eph.4.14': "Opened. Tossed by winds of teaching; keyword-only: wind/scattering.",
 'SBLGNT:Eph.4.15': "Opened. Speaking truth in love, growing into the head; close to ¶22 but Eph 4:25 from the same chapter carries the reciprocal truth point.",
 'SBLGNT:Eph.4.16': "Opened. Body joined and knit by every joint; joining image, but ¶16-17's image is vegetation; the reciprocity point is carried by Eph 4:25.",
 'SBLGNT:Eph.4.2': "Opened. Patience, bearing with one another in love; reciprocal forbearance, covered by Gal 6:2 at ¶32.",
 'SBLGNT:Eph.6.14': "Opened. Belt of truth in the armour; keyword-only: truth as equipment; ¶24's banner is not this image.",
 'SBLGNT:Gal.5.22': "Opened. Fruit of the Spirit list; virtue list without the ayah's structure.",
 'SBLGNT:Gal.5.6': "Opened. Faith working through love; faith/action link carried by the ¶3 block.",
 'SBLGNT:Gal.6.9': "Opened. Do not tire of doing good; harvest in season; keyword-only: perseverance.",
 'SBLGNT:Heb.10.23': "Opened. Hold fast the confession; the promiser is faithful; close to ¶36 but Heb 10:36-38 carries the point.",
 'SBLGNT:Heb.11.1': "Opened. Faith as assurance of things hoped; definition of faith without the security image of ¶4.",
 'SBLGNT:Heb.11.17': "Opened. Abraham offered Isaac by faith; keyword-only: faith tested.",
 'SBLGNT:Heb.11.22': "Opened. Joseph's dying instruction about his bones; deathbed theme, but ¶20's Jacob scene is carried by Pesachim 56a.",
 'SBLGNT:Heb.11.8': "Opened. Abraham obeyed by faith; keyword-only.",
 'SBLGNT:Heb.12.1': "Opened. Run the race with endurance; keyword-only: endurance.",
 'SBLGNT:Heb.12.11': "Opened. Discipline painful now, fruit later; resembles ¶31's bitter medicine, but the subject is discipline, not patience; the medicine image is not shared (no healing word in this verse).",
 'SBLGNT:Heb.12.2': "Opened. Jesus endured the cross for joy set before him; christological, broad theme of endurance.",
 'SBLGNT:Heb.3.13': "Opened. Exhort one another daily lest hardened; reciprocal exhortation already carried by Heb 10:24-25; one block per point.",
 'SBLGNT:Heb.4.12': "Opened. Word sharper than a sword; the spear image at ¶25 concerns 21:18 and the root's 'unswerving thrust'; image of weapon only, no shared formula for this ayah.",
 'SBLGNT:Heb.6.10': "Opened. God does not forget your work and love; keyword-only.",
 'SBLGNT:Heb.6.11': "Opened. Diligence to the end; keyword-only.",
 'SBLGNT:Heb.6.12': "Opened. Inherit promises through faith and patience; close but ¶36 uses Heb 10:36-38 which quotes Habakkuk; duplicate point.",
 'SBLGNT:Heb.6.18': "Opened. Fled for refuge to hold hope; keyword-only: refuge.",
 'SBLGNT:Heb.6.19': "Opened. Hope as anchor; image differs from stopper/stone.",
 'SBLGNT:Jas.1.22': "Opened. Doers of the word; keyword-only: doing.",
 'SBLGNT:Jas.1.3': "Opened. Testing of faith produces endurance; keyword-only.",
 'SBLGNT:Jas.1.4': "Opened. Let endurance have its perfect work; keyword-only.",
 'SBLGNT:Jas.2.17': "Opened. Faith without works is dead; the James pole of ¶3 is represented by Jas 2:24; duplicate.",
 'SBLGNT:Jas.2.22': "Opened. Faith worked with works; same James argument as 2:24 used at ¶3; duplicate.",
 'SBLGNT:Jas.3.17': "Opened. Wisdom from above peaceable and full of good fruits; keyword-only.",
 'SBLGNT:Jas.3.18': "Opened. Fruit of righteousness sown in peace; keyword-only: fruit/peace.",
 'SBLGNT:Jas.5.10': "Opened. Prophets as examples of suffering and patience; keyword-only: patience of speakers.",
 'SBLGNT:Jas.5.11': "Opened. Endurance of Job; patience theme; no shared formula with this ayah.",
 'SBLGNT:Jas.5.19': "Opened. Bringing back one who wanders from the truth; close to counsel in truth but not reciprocal; secondary.",
 'SBLGNT:Jas.5.20': "Opened. Turning a sinner saves a soul; secondary to 5:19.",
 'SBLGNT:Jas.5.4': "Opened. Withheld wages cry out; wage theme; ¶11 point carried by Deut 24:15 and Matt 20.",
 'SBLGNT:Jas.5.7': "Opened. Patient like a farmer waiting for rain; patience image differs from the commentary's restraint/stopper images.",
 'SBLGNT:Jas.5.8': "Opened. Be patient, establish hearts; keyword-only.",
 'SBLGNT:John.15.12': "Opened. Love one another; keyword-only: reciprocity.",
 'SBLGNT:John.15.4': "Opened. Branch bears fruit only remaining in the vine; attachment to a source, not mutual joining of plants as in ¶17.",
 'SBLGNT:John.15.5': "Opened. Same vine image; not mutual joining.",
 'SBLGNT:Jude.1.12': "Opened. Waterless clouds; cloud image belongs to the surah-level ¶17 note; no bearing on this ayah's words.",
 'SBLGNT:Luke.21.19': "Opened. By endurance gain your lives; keyword-only: endurance and gain.",
 'SBLGNT:Luke.6.35': "Opened. Love enemies, lend expecting nothing; ¶38 point carried by Rom 12:21.",
 'SBLGNT:Luke.6.38': "Opened. Good measure pressed down, running over; but the verse keeps measure-for-measure, unlike ¶35's unweighed heap and wage without reckoning; not used.",
 'SBLGNT:Luke.8.13': "Opened. Rocky ground believes for a while; keyword-only: faith without root.",
 'SBLGNT:Luke.8.14': "Opened. Riches choke the word; keyword-only.",
 'SBLGNT:Luke.8.15': "Opened. Hold the word fast and bear fruit with endurance; close but a broad parable theme; no reciprocity.",
 'SBLGNT:Mark.8.35': "Opened. Losing life to save it; belongs to 103:2's loss (khusr) rather than this ayah.",
 'SBLGNT:Mark.8.36': "Opened. Gain the world and forfeit the soul (ζημιωθῆναι); a loss formula for 103:2, not for 103:3's exception.",
 'SBLGNT:Matt.10.22': "Opened. The one who endures to the end will be saved; keyword-only: endurance.",
 'SBLGNT:Matt.11.28': "Opened. Rest for the burdened; keyword-only: burden.",
 'SBLGNT:Matt.11.30': "Opened. Easy yoke, light burden; ¶24's capacity point concerns 6:152; no shared formula beyond 'burden'.",
 'SBLGNT:Matt.16.27': "Opened. Repay each according to conduct; formula carried at ¶27 by Rom 2:6.",
 'SBLGNT:Matt.18.15': "Opened. Reprove a brother privately to gain him; mutual correction theme; ¶19/¶26 points carried elsewhere.",
 'SBLGNT:Matt.18.16': "Opened. Two or three witnesses; keyword-only.",
 'SBLGNT:Matt.20.13': "Opened. 'Did you not agree for a denarius?'; context of the parable; the ¶11 block cites 20:8, 20:12 and 20:15; no independent addition.",
 'SBLGNT:Matt.24.12': "Opened. Love grows cold; keyword-only.",
 'SBLGNT:Matt.24.13': "Opened. Endure to the end; keyword-only.",
 'SBLGNT:Matt.25.35': "Opened. Feeding the hungry at judgment; broad ethical theme.",
 'SBLGNT:Matt.25.40': "Opened. Done to the least, done to me; broad ethical theme.",
 'SBLGNT:Matt.5.16': "Opened. Good works seen by others; keyword-only.",
 'SBLGNT:Matt.5.44': "Opened. Love enemies; ¶38 point carried by Rom 12:21 and Prov 25:21.",
 'SBLGNT:Matt.6.12': "Opened. Forgive debts as we forgive debtors; keyword-only: debt; ¶23's haqq-as-debt point is lexical.",
 'SBLGNT:Matt.6.20': "Opened. Treasure in heaven; lasting-capital point carried by Peah 1:1.",
 'SBLGNT:Matt.6.4': "Opened. Father repays secret alms; keyword-only: reward.",
 'SBLGNT:Matt.7.21': "Opened. Doing the Father's will; keyword-only: doing.",
 'SBLGNT:Matt.7.24': "Opened. House on rock; image of building, not the commentary's well wall; keyword-only.",
 'SBLGNT:Matt.7.25': "Opened. House stands in storm; same.",
 'SBLGNT:Matt.7.26': "Opened. House on sand; same.",
 'SBLGNT:Phil.4.9': "Opened. Practise what you learned; keyword-only.",
 'SBLGNT:Rev.12.11': "Opened. Conquered by testimony unto death; keyword-only.",
 'SBLGNT:Rev.14.12': "Opened. Endurance of saints keeping commands and faith; a catalogue resembling ¶2, but 1 Thess 1:3 carries the catalogue point; duplicate.",
 'SBLGNT:Rev.2.10': "Opened. Faithful unto death; keyword-only.",
 'SBLGNT:Rev.2.19': "Opened. Works, love, faith, service, endurance; catalogue duplicate of 1 Thess 1:3.",
 'SBLGNT:Rev.2.2': "Opened. Works, labour, endurance; catalogue duplicate of 1 Thess 1:3.",
 'SBLGNT:Rev.2.3': "Opened. Endurance for my name; keyword-only.",
 'SBLGNT:Rev.2.4': "Opened. Left first love; not about persistence in wrong (¶34).",
 'SBLGNT:Rev.20.12': "Opened. Dead judged by books according to works; formula carried at ¶27 by Rom 2:6.",
 'SBLGNT:Rev.22.12': "Opened. Repay each according to work; same formula, duplicate.",
 'SBLGNT:Rev.3.19': "Opened. Those I love I reprove; keyword-only.",
 'SBLGNT:Rom.13.8': "Opened. Owe no one anything except love; keyword-only: debt.",
 'SBLGNT:Rom.15.1': "Opened. Strong bear the weaknesses of the weak; bearing point carried by Gal 6:2.",
 'SBLGNT:Rom.2.5': "Opened. Hardness storing up wrath; context of 2:6-8; the ¶27 block cites 2:6-8; no independent addition.",
 'SBLGNT:Rom.4.4': "Opened. Wage reckoned as debt, not grace; context of 4:5 at ¶3; no independent addition.",
 'SBLGNT:Rom.5.3': "Opened. Affliction produces endurance; keyword-only.",
 'SBLGNT:Rom.5.4': "Opened. Endurance produces character; keyword-only.",
 'SBLGNT:Rom.5.5': "Opened. Love poured into hearts; the 'pour patience' image of 7:126 is not shared (different subject).",
 'SBLGNT:Rom.8.25': "Opened. Wait with endurance for unseen hope; keyword-only.",
 'SBLGNT:Titus.2.2': "Opened. Sound in faith, love, endurance; virtue list duplicate.",
 'WLC:1Kgs.18.45': "Opened. Clouds and great rain; cloud image belongs to the surah-level note at ¶17; no bearing on this ayah.",
 'WLC:1Kgs.8.35': "Opened. בְּהֵעָצֵר שָׁמַיִם, heavens shut; ʿṣr in the sense 'shut up (rain)'; a real use of the root but a sense the page does not develop; the ʿṣr block uses Gen 16:2 and Prov 25:28.",
 'WLC:1Sam.17.47': "Opened. The battle is the LORD's; the Goliath scene is mentioned only in passing at ¶30 (2:250); no prayer for patience in 1 Sam 17.",
 'WLC:1Sam.17.49': "Opened. David's stone strikes Goliath; same scene, passing mention only.",
 'WLC:2Chr.20.20': "Opened. הַאֲמִינוּ ... וְתֵאָמֵנוּ ... וְהַצְלִיחוּ: echoes Isa 7:9 and adds ṣlḥ 'prosper'; the believe/firm wordplay is carried by Isa 7:9 (the earlier, primary text); ṣlḥ here is the success sense, not ¶13's 'sound/fit'.",
 'WLC:Amos.8.5': "Opened. Merchants shrink the ephah and falsify scales; the market-loss image belongs to 103:2 (¶23 says so explicitly).",
 'WLC:Dan.5.27': "Opened. תְּקִילְתָּה בְמֹאזַנְיָא וְהִשְׁתְּכַחַתְּ חַסִּיר: Aramaic ḥsr 'found lacking' on the scales; a genuine use, but the khusr root belongs to 103:2's page; here only cross-referenced at ¶12/¶23; not used.",
 'WLC:Dan.6.4': "Opened. Verse-numbering error: WLC Dan 6:4 (Daniel distinguished by an excellent spirit) lacks the root; the 'faithful' (מְהֵימַן) clause is in WLC 6:5 (KJV 6:4), which was opened and used in the ¶7 block.",
 'WLC:Deut.15.10': "Opened. Give without a grudging heart; broad ethical theme.",
 'WLC:Deut.15.8': "Opened. Open hand, lend for his lack (מַחְסֹרוֹ); keyword-only: lack/need.",
 'WLC:Deut.19.15': "Opened. Two or three witnesses; keyword-only.",
 'WLC:Deut.2.7': "Opened. 'You lacked nothing' (לֹא חָסַרְתָּ): ḥsr 'lack'; a use of the root but on this page the khusr root is only cross-referenced; no shared image.",
 'WLC:Deut.30.14': "Opened. The word near, in mouth and heart, to do it; keyword-only: word to be done.",
 'WLC:Deut.31.12': "Opened. Assemble all to hear and learn; broad theme of instruction.",
 'WLC:Deut.31.13': "Opened. Children learn to fear; broad theme.",
 'WLC:Deut.32.47': "Opened. Not an empty word, it is your life; keyword-only.",
 'WLC:Deut.4.8': "Opened. חֻקִּים וּמִשְׁפָּטִים צַדִּיקִם, righteous statutes; ḥq here is 'statute', not the 'due share' sense the ¶23 block uses; the statute sense is noted in the root verdict.",
 'WLC:Deut.6.7': "Opened. Teach them to your sons; generational transmission carried at ¶20 by Gen 18:19.",
 'WLC:Eccl.11.6': "Opened. Sow morning and evening; keyword-only: morning/evening.",
 'WLC:Eccl.12.14': "Opened. God brings every deed into judgment; formula carried at ¶27 by Rom 2:6-8.",
 'WLC:Eccl.2.22': "Opened. What has a man of all his toil (עֲמָלוֹ); same question as 1:3, which the ¶10 block cites; duplicate.",
 'WLC:Eccl.3.7': "Opened. Time to be silent and to speak; keyword-only.",
 'WLC:Eccl.4.11': "Opened. Two lie together and are warm; cold image of ¶31 is about patience in hardship, not shared warmth; secondary to 4:9-10.",
 'WLC:Eccl.4.12': "Opened. Threefold cord not quickly broken; joining image, secondary to 4:9-10 which the ¶10 block cites.",
 'WLC:Eccl.9.10': "Opened. Work with might, no work in Sheol; keyword-only.",
 'WLC:Exod.14.31': "Opened. וַיַּאֲמִינוּ בַּיהוָה וּבְמֹשֶׁה: belief after seeing; a use of the root, but the belief/security point is carried by Isa 7:9 and Gen 15; duplicate.",
 'WLC:Exod.18.18': "Opened. The task too heavy for you alone; burden-sharing theme; not the guarantor image.",
 'WLC:Exod.18.20': "Opened. Teach them the statutes (הַחֻקִּים) and the work they must do; ḥq as statute, not the due-share sense; noted in the root verdict.",
 'WLC:Exod.18.21': "Opened. Choose capable men, men of truth; keyword-only.",
 'WLC:Exod.18.22': "Opened. They shall bear the burden with you; burden-sharing theme, carried by Gal 6:2.",
 'WLC:Ezek.18.21': "Opened. The wicked who turns shall live; the commentary's point on past-tense verbs is grammatical, not about repentance; no shared formula.",
 'WLC:Ezek.18.24': "Opened. The righteous who turns away; same; no shared formula.",
 'WLC:Ezek.3.17': "Opened. Watchman who warns; keyword-only: warning.",
 'WLC:Ezek.3.18': "Opened. Failure to warn; keyword-only.",
 'WLC:Ezek.3.19': "Opened. Warning saves the warner; keyword-only.",
 'WLC:Ezra.6.14': "Opened. Aramaic מַצְלְחִין 'prospering' in building; ṣlḥ success sense; the ¶13 block uses Jer 13:7 and Ezek 15:4 where the sense is 'fit for use'.",
 'WLC:Ezra.7.10': "Opened. Ezra studies, does and teaches statute; keyword-only.",
 'WLC:Gen.31.40': "Opened. Jacob's labour in heat and frost; keyword-only: cold/labour.",
 'WLC:Gen.33.4': "Opened. Esau embraces Jacob; reconciliation theme; no repelling of evil with good in the verse.",
 'WLC:Gen.45.27': "Opened. Jacob sees the wagons and revives; context of 45:26; no independent addition.",
 'WLC:Gen.50.25': "Opened. Joseph's oath about his bones; deathbed theme; ¶20's point carried by Gen 18:19 and Pesachim 56a.",
 'WLC:Gen.6.9': "Opened. Noah righteous in his generation; broad theme of a righteous exception.",
 'WLC:Gen.7.23': "Opened. Only Noah and those with him remained (אַךְ־נֹחַ); an exception within universal destruction, but narrative rather than a defining list; ¶1's structure is carried by Ps 14-15.",
 'WLC:Hab.3.16': "Opened. Wait quietly for the day of distress; keyword-only.",
 'WLC:Hab.3.17': "Opened. Fig and vine fail; keyword-only.",
 'WLC:Hab.3.18': "Opened. Yet I rejoice in the LORD; keyword-only.",
 'WLC:Hab.3.19': "Opened. Feet like a deer's; keyword-only.",
 'WLC:Isa.1.17': "Opened. Learn to do good, seek justice; broad ethical theme.",
 'WLC:Isa.26.3': "Opened. The verse uses בָּטוּחַ (bṭḥ 'trust'), not the amn root; the soydas claim fails on the text; motif (steadfast mind, peace) is broad.",
 'WLC:Isa.26.4': "Opened. Trust in the LORD, everlasting rock; keyword-only: rock.",
 'WLC:Isa.28.16': "Opened. הַמַּאֲמִין לֹא יָחִישׁ 'the believer will not hasten': a genuine amn use joined to non-panic; the belief/firmness point is carried by Isa 7:9; secondary.",
 'WLC:Isa.30.15': "Opened. In quietness and trust (בִטְחָה) your strength; bṭḥ, not amn; keyword-only.",
 'WLC:Isa.33.22': "Opened. מְחֹקְקֵנוּ 'our lawgiver'; ḥqq as decree; not the due-share sense.",
 'WLC:Isa.40.31': "Opened. Those who wait renew strength; keyword-only: waiting.",
 'WLC:Isa.42.3': "Opened. Bruised reed not broken; keyword-only.",
 'WLC:Isa.42.4': "Opened. Not faint until justice is set; keyword-only.",
 'WLC:Isa.50.4': "Opened. A word to sustain the weary; keyword-only.",
 'WLC:Isa.51.7': "Opened. Do not fear reproach; keyword-only.",
 'WLC:Isa.55.10': "Opened. Rain makes the earth sprout; surah-level rain/vegetation image, not this ayah.",
 'WLC:Isa.55.11': "Opened. The word accomplishes its purpose (וְהִצְלִיחַ); ṣlḥ success sense; keyword-only.",
 'WLC:Isa.58.11': "Opened. Watered garden; keyword-only.",
 'WLC:Isa.58.12': "Opened. Repairer of the breach; keyword-only.",
 'WLC:Isa.58.6': "Opened. The chosen fast looses bonds; ¶29's fasting note is a lexical aside; no shared formula.",
 'WLC:Isa.58.7': "Opened. Share bread with the hungry; broad ethical theme.",
 'WLC:Isa.59.6': "Opened. Webs not garments; ¶22's woven-cloth example is lexical; keyword-only.",
 'WLC:Jer.17.10': "Opened. Gives each according to his ways; formula carried at ¶27.",
 'WLC:Jer.17.7': "Opened. Blessed who trusts (יִבְטַח, bṭḥ) the LORD; not the amn root; broad theme.",
 'WLC:Jer.17.8': "Opened. Tree by water in drought; plant image differs from joined vegetation.",
 'WLC:Jer.6.14': "Opened. Peace, peace, when there is no peace; keyword-only.",
 'WLC:Job.19.23': "Opened. וְיֻחָקוּ 'be inscribed': ḥqq 'engrave', the root's base sense; noted in the root verdict, not used.",
 'WLC:Job.2.10': "Opened. Receive good and evil without sinning with lips; patience theme, broad.",
 'WLC:Job.27.16': "Opened. יִצְבֹּר כֶּעָפָר כָּסֶף: ṣbr 'heap up' silver; same heap sense as Gen 41:49, which carries the point; duplicate.",
 'WLC:Job.8.14': "Opened. Trust a spider's house; keyword-only.",
 'WLC:Job.8.15': "Opened. Leans on his house, it will not stand; keyword-only.",
 'WLC:Josh.1.8': "Opened. תַּצְלִיחַ אֶת־דְּרָכֶךָ 'make your way prosper': ṣlḥ success sense, not 'sound/fit'.",
 'WLC:Lam.3.25': "Opened. Good to those who wait; keyword-only.",
 'WLC:Lam.3.26': "Opened. Wait quietly; keyword-only.",
 'WLC:Lev.19.13': "Opened. Wage not kept overnight; same point as Deut 24:15, which the ¶11 block cites; duplicate.",
 'WLC:Lev.19.17': "Opened. Reprove your neighbour; mutual correction duty, but ¶19/¶22 carry reciprocity with Heb 10:24-25 and Zech 8:16; secondary.",
 'WLC:Lev.19.18': "Opened. Love your neighbour; broad theme.",
 'WLC:Mal.3.17': "Opened. They shall be mine on the day; context of 3:16-18; the ¶2 block cites 3:16 and 3:18; no independent addition.",
 'WLC:Mic.6.8': "Opened. Do justice, love kindness, walk humbly: a short list of what is required; close to ¶2's catalogue, but Ps 15 and 1 Thess 1:3 carry the point; secondary.",
 'WLC:Num.11.17': "Opened. Elders bear the burden with Moses; burden-sharing theme carried by Gal 6:2.",
 'WLC:Prov.11.1': "Opened. False balance an abomination; market image belongs to 103:2.",
 'WLC:Prov.11.15': "Opened. Surety for a stranger brings harm; a wisdom caution on suretyship, not about community solidarity; does not bear on ¶32's metaphor.",
 'WLC:Prov.11.24': "Opened. Withholding leads to want (לְמַחְסוֹר); ḥsr 'need'; khusr root only cross-referenced on this page.",
 'WLC:Prov.14.5': "Opened. Faithful witness (עֵד אֱמוּנִים) does not lie; amn use; the truth/amn link is carried by Zech 8:16.",
 'WLC:Prov.15.1': "Opened. Soft answer turns away wrath; ¶26 point carried by 2 Tim 2:24-25.",
 'WLC:Prov.16.26': "Opened. The labourer's appetite labours for him (עָמֵל עָמְלָה); ʿml as toil for need; the ¶10 block uses Qohelet.",
 'WLC:Prov.16.32': "Opened. Ruling one's spirit; close to ¶28-30, but Prov 25:28 and 29:11 carry the restraint point; secondary.",
 'WLC:Prov.17.17': "Opened. A brother born for adversity; keyword-only.",
 'WLC:Prov.19.17': "Opened. Lending to the LORD; keyword-only: loan/repayment.",
 'WLC:Prov.20.10': "Opened. Diverse weights; market image for 103:2.",
 'WLC:Prov.24.12': "Opened. Repays man according to his work; formula carried at ¶27.",
 'WLC:Prov.25.14': "Opened. Clouds without rain; surah-level cloud image.",
 'WLC:Prov.25.15': "Opened. Patience persuades a ruler; keyword-only.",
 'WLC:Prov.27.17': "Opened. Iron sharpens iron, man his neighbour: reciprocal improvement; close to ¶19, but Heb 10:24-25 carries the reciprocal point; secondary.",
 'WLC:Prov.27.5': "Opened. Open rebuke better than hidden love; keyword-only.",
 'WLC:Prov.27.6': "Opened. Faithful (נֶאֱמָנִים) are a friend's wounds; amn use; keyword-only.",
 'WLC:Prov.27.9': "Opened. A friend's counsel sweet; keyword-only.",
 'WLC:Prov.28.27': "Opened. Giver to the poor will not lack (אֵין מַחְסוֹר); ḥsr only cross-referenced on this page.",
 'WLC:Prov.3.23': "Opened. Walk securely without stumbling; keyword-only.",
 'WLC:Prov.3.27': "Opened. Do not withhold good from its owner (מִבְּעָלָיו); 'due to its owner' is close to haqq as due, but the ¶23 block uses the ḥq root itself; secondary.",
 'WLC:Prov.3.28': "Opened. Do not delay the neighbour; keyword-only.",
 'WLC:Prov.3.3': "Opened. Bind kindness and truth (אֱמֶת) on your neck; amn use; the emet point is carried by Zech 8:16.",
 'WLC:Prov.31.21': "Opened. Household not afraid of snow; keyword-only: cold.",
 'WLC:Prov.8.29': "Opened. בְּשׂוּמוֹ לַיָּם חֻקּוֹ: ḥq as boundary set for the sea; a real sense of the root (limit), noted in the root verdict; ¶22's door-socket image is not a boundary.",
 'WLC:Ps.1.2': "Opened. Meditation day and night; keyword-only.",
 'WLC:Ps.1.3': "Opened. Tree by streams; כֹל אֲשֶׁר יַעֲשֶׂה יַצְלִיחַ: ṣlḥ 'prosper' (success sense); tree image differs from joined vegetation.",
 'WLC:Ps.1.4': "Opened. Chaff driven by wind; ¶14's chaff belongs to 18:45; secondary.",
 'WLC:Ps.106.30': "Opened. וַתֵּעָצַר הַמַּגֵּפָה 'the plague was stayed'; ʿṣr 'stop'; not self-restraint.",
 'WLC:Ps.112.7': "Opened. Firm heart trusting (bṭḥ); keyword-only.",
 'WLC:Ps.112.9': "Opened. Righteousness endures forever; keyword-only.",
 'WLC:Ps.118.27': "Opened. Bind the festal offering with cords; ¶29's maṣbūra is a lexical aside; keyword-only: bound animal.",
 'WLC:Ps.119.160': "Opened. Sum of your word is truth (אֱמֶת); emet point carried by Zech 8:16.",
 'WLC:Ps.119.30': "Opened. Way of faithfulness (אֱמוּנָה) chosen; amn use; keyword-only.",
 'WLC:Ps.119.5': "Opened. Keep your statutes (חֻקֶּיךָ); ḥq as statute; not the due sense.",
 'WLC:Ps.119.86': "Opened. All your commands are faithfulness (אֱמוּנָה); amn use; keyword-only.",
 'WLC:Ps.119.90': "Opened. Your faithfulness to all generations; amn use; keyword-only.",
 'WLC:Ps.125.1': "Opened. Those who trust (bṭḥ) like Mount Zion; mountain image of ¶31 is lexical; keyword-only.",
 'WLC:Ps.127.1': "Opened. Builders labour (עָמְלוּ) in vain; ʿml toil; the ¶10 block uses Qohelet.",
 'WLC:Ps.133.1': "Opened. Brothers dwelling together; broad unity theme.",
 'WLC:Ps.133.3': "Opened. Dew and commanded blessing; keyword-only.",
 'WLC:Ps.141.3': "Opened. Guard on the mouth, door of the lips; restraint of speech is close to ¶30's stopper, but Prov 29:11 carries it; secondary.",
 'WLC:Ps.23.1': "Opened. לֹא אֶחְסָר 'I shall not lack'; ḥsr use; khusr only cross-referenced here.",
 'WLC:Ps.23.2': "Opened. Verse-boundary error: WLC Ps 23:2 has no ḥsr (it is in 23:1); green pastures image is broad.",
 'WLC:Ps.27.13': "Opened. הֶאֱמַנְתִּי 'I believed I would see the goodness'; amn use; secondary to Isa 7:9.",
 'WLC:Ps.27.14': "Opened. Wait and be strong; keyword-only.",
 'WLC:Ps.33.4': "Opened. All his work in faithfulness (בֶּאֱמוּנָה); amn use; keyword-only.",
 'WLC:Ps.37.3': "Opened. Trust (bṭḥ) and do good; not the amn root; keyword-only.",
 'WLC:Ps.37.7': "Opened. Be still and wait; keyword-only.",
 'WLC:Ps.39.7': "Opened. יִצְבֹּר וְלֹא־יֵדַע מִי־אֹסְפָם, heaps up not knowing who gathers; ṣbr heap sense, duplicate of Gen 41:49.",
 'WLC:Ps.46.2': "Opened. God our refuge; keyword-only: refuge.",
 'WLC:Ps.46.3': "Opened. We will not fear though the earth change; keyword-only.",
 'WLC:Ps.60.6': "Opened. Banner given to those who fear you, because of truth (קֹשֶׁט); ¶24's banner (haqiqa) is lexical; the verse's sense of qošeṭ is disputed; not used.",
 'WLC:Ps.78.6': "Opened. Next generation to tell their children; transmission theme carried by Gen 18:19.",
 'WLC:Ps.90.17': "Opened. Establish the work of our hands; close to ¶14's lasting work, but Peah 1:1 and 1 Cor 3:14 carry the point; secondary.",
 'WLC:Zech.7.9': "Opened. True judgment and kindness each to his brother; reciprocity with truth, but Zech 8:16 states it more directly; duplicate.",
 'WLC:Zech.8.17': "Opened. Do not devise evil against a neighbour; context of 8:16; no independent addition.",
 'WLC:Zech.8.19': "Opened. Love truth and peace; keyword-only.",
 'WLC:Exod.9.11': None,
}

SEF = {  # discovery ref -> (status, locator, reason)
 'Mishnah Avot 1:1': ('rejected', 'SEFARIA:Pirkei_Avot.1.1', "Opened (Sefaria). Chain of transmission from Moses to the Great Assembly; transmission theme; ¶20 is about a dying father's charge, carried by Gen 18:19 and Pesachim 56a."),
 'Mishnah Avot 1:12': ('rejected', 'SEFARIA:Pirkei_Avot.1.12', "Opened. Hillel: love and pursue peace, draw people to Torah; broad ethical theme."),
 'Mishnah Avot 1:14': ('rejected', 'SEFARIA:Pirkei_Avot.1.14', "Opened. 'If I am only for myself, what am I'; keyword-only: beyond the individual."),
 'Mishnah Avot 1:17': ('rejected', 'SEFARIA:Pirkei_Avot.1.17', "Opened. Action, not study, is the main thing; keyword-only: deed."),
 'Mishnah Avot 1:2': ('rejected', 'SEFARIA:Pirkei_Avot.1.2', "Opened. World stands on Torah, worship, acts of kindness; a triad, but not a definition of the saved; keyword-only."),
 'Mishnah Avot 1:6': ('rejected', 'SEFARIA:Pirkei_Avot.1.6', "Opened. Acquire a teacher and a companion; keyword-only: companionship."),
 'Mishnah Avot 4:16': ('rejected', 'SEFARIA:Pirkei_Avot.4.16', "Opened. This world a vestibule; keyword-only."),
 'Mishnah Avot 4:2': ('rejected', 'SEFARIA:Pirkei_Avot.4.2', "Opened. The reward of a mitzvah is a mitzvah; keyword-only: reward."),
 'Bava Metzia 30b': ('rejected', 'SEFARIA:Bava_Metzia.30b', "Opened (first portion; lost-property laws). The readers' point (Jerusalem destroyed for judging by strict law) concerns legal strictness, not mutual counsel of haqq; no shared formula."),
 'Makkot 24a': ('rejected', 'SEFARIA:Makkot.24a', "Opened (full). R. Simlai's reductions of the 613 commandments (Ps 15 eleven, Micah three, Habakkuk one: 'the righteous lives by his emunah'). Useful reception context for Ps 15 and Hab 2:4, but adds no claim specific to this page beyond the ¶1 and ¶36 blocks; not used."),
 'Rosh Hashanah 29a': ('rejected', 'SEFARIA:Rosh_Hashanah.29a', "Opened. The mishnah asks whether Moses' hands made war and answers that Israel looked upward; it does not bear on emunah as steadiness or on communal support; not used."),
 'Shabbat 127a': ('rejected', 'SEFARIA:Shabbat.127a', "Opened (full). The six things whose fruits are eaten now with principal remaining, and the citation of Mishnah Peah 1:1; duplicate of Peah 1:1 used at ¶14."),
 'Shabbat 31a': ('rejected', 'SEFARIA:Shabbat.31a', "Opened (first portion: Hillel's patience with the provoker). Golden-rule summary is a general ethical maxim, not reciprocal counsel; keyword-only."),
 "Ta'anit 23a": ('rejected', 'SEFARIA:Taanit.23a', "Opened (first portion: rains in season, Honi). Planting for the next generation is a plant theme without the joined-vegetation image; keyword-only."),
 'Sirach 2:2': ('rejected', 'SEFARIA:Ben_Sira.2.2', "Opened. The Hebrew shown is bracketed, an editorial reconstruction, not a manuscript witness; content (steady heart in calamity) is a broad patience theme."),
 'Sirach 2:4': ('rejected', 'SEFARIA:Ben_Sira.2.4', "Opened. Bracketed reconstructed Hebrew; 'be long of spirit in your breaking' is a broad patience theme."),
 'Sirach 2:6': ('rejected', 'SEFARIA:Ben_Sira.2.6', "Opened. Bracketed reconstructed Hebrew (הַאֲמֵן בּוֹ); a use of the amn root but not a manuscript text; trust/hope theme already carried."),
 'Sirach 4:28': ('rejected', 'SEFARIA:Ben_Sira.4.28', "Opened. Numbering mismatch: the Sefaria verse at this locator says 'do not sit with an unjust judge'; the readers' 'strive for truth unto death' saying is not in this segment; rejected on textual grounds."),
 'Sirach 6:14': ('rejected', 'SEFARIA:Ben_Sira.6.14', "Opened. A faithful friend (אוֹהֵב אֱמוּנָה) is a strong shelter; amn use; keyword-only."),
 'Sirach 6:16': ('rejected', 'SEFARIA:Ben_Sira.6.16', "Opened. A faithful friend is a bundle of life; the 'medicine' wording is the Greek/Syriac, not this Hebrew; keyword-only."),
 'Wisdom of Solomon 2:19': ('rejected', 'SEFARIA:The_Wisdom_of_Solomon.2.19', "Opened. A modern Hebrew rendering of a Greek book (translated witness); testing the righteous by insult; broad theme."),
 'Wisdom of Solomon 3:5': ('rejected', 'SEFARIA:The_Wisdom_of_Solomon.3.5', "Opened. Translated witness; disciplined a little, great good; broad theme."),
 'Wisdom of Solomon 3:6': ('rejected', 'SEFARIA:The_Wisdom_of_Solomon.3.6', "Opened. Translated witness; tried like gold in the furnace; broad theme."),
 'Wisdom of Solomon 3:9': ('rejected', 'SEFARIA:The_Wisdom_of_Solomon.3.9', "Opened. Translated witness; those who trust will understand truth; keyword-only: trust/truth."),
}

ACC_SEF = {  # accepted discovery refs on Sefaria: cid -> locator
 'BC-6e20d3a9f1028967af00': 'SEFARIA:Pirkei_Avot.3.2',
 'BC-75391b4f7ae98ac4acaa': 'SEFARIA:Pirkei_Avot.2.15',
 'BC-79aff752b70d7f4c1345': 'SEFARIA:Pirkei_Avot.2.16',
 'BC-3d00a3f9240a44c5b794': 'SEFARIA:Pirkei_Avot.5.17',
 'BC-12d77d71b65b81374216': 'SEFARIA:Mishnah_Peah.1.1',
 'BC-81dd57a019f777054e4e': 'SEFARIA:Mishnah_Peah.1.1',
}

CID_REJ = {  # per-cid rejections that differ from the ref default
 'BC-2b52c56386ae0e9ad999': ('SEFARIA:Pirkei_Avot.2.16', "Opened. Luna's reading (patience: not free to desist from the work) is not used; the ¶11 block cites 2:16 for the faithful employer who pays the wage (sol's connection); patience point not developed here."),
}

UNAVAILABLE = {
 '1 Clement 34:2': "Not in the intertext corpus (prefetch gap); the worker-and-bread comparison could not be checked.",
 '1 Clement 38.1-2': "Not in the corpus (prefetch gap); 'strong care for the weak' could not be checked.",
 '1 Clement 38:2': "Not in the corpus (prefetch gap); could not be checked.",
 'Didache 1:3': "Not in the corpus (prefetch gap); could not be checked.",
 'Didache 4.1': "Not in the corpus (prefetch gap); could not be checked.",
 'Didache 4.2': "Not in the corpus (prefetch gap); could not be checked.",
 'Ignatius, Letter to Polycarp 1:2': "Not in the corpus (prefetch gap); could not be checked.",
 'Ignatius, Letter to Polycarp 3:1': "Not in the corpus (prefetch gap); could not be checked.",
 'Justin Martyr, First Apology 67': "Not in the corpus (prefetch gap); could not be checked.",
 'Shepherd of Hermas, Mandate 5.1': "Not in the corpus (prefetch gap); could not be checked.",
 'Tertullian, Apology 39': "Not in the corpus (prefetch gap); could not be checked.",
 '1 Maccabees 2:50': "Not in the corpus (prefetch gap); Mattathias' deathbed charge could not be checked; relevant to ¶20 if available.",
 '2 Maccabees 7:2': "Not in the corpus (prefetch gap); could not be checked.",
 'Sirach 29:15': "Not in the corpus at this numbering (prefetch gap); the guarantor saying could not be checked; relevant to ¶32 if available.",
 'Targum Onkelos on Genesis 15:6': "Not in the corpus (prefetch gap); the Memra rendering of Gen 15:6 could not be checked.",
}

# own research and context lookups: ref -> (status, paragraph or None, annotation or None, reason)
RESEARCH = {
 'WLC:Ps.14.3': ('accepted', 1, 'TEV-MTF-001', "Own research. 'None does good, not even one': the universal verdict on bnei adam that precedes Ps 15's list; used at ¶1."),
 'WLC:Ps.15.1': ('accepted', 1, 'TEV-MTF-001', "Own research. The entrance question 'who may dwell in your tent', answered by 15:2's list; used at ¶1."),
 'WLC:Ps.14.2': ('rejected', None, None, "Context for 14:3 (the LORD looks down on mankind); no independent addition."),
 'WLC:Ps.14.5': ('rejected', None, None, "Context: 'God is with the righteous generation'; shows Ps 14 also names a group, noted implicitly; no independent addition."),
 'WLC:Gen.15.1': ('accepted', 6, 'TEV-SYD-002', "Own research. 'Do not fear, Abram, I am your shield' precedes 15:6's belief; fear removed and belief in one scene; used at ¶6."),
 'WLC:Dan.6.5': ('accepted', 7, 'TEV-SYD-003', "Own research (resolving the Dan 6:4 numbering). Aramaic דִּי־מְהֵימַן הוּא, no fault found because he was trustworthy; used at ¶7."),
 'WLC:Gen.37.35': ('accepted', 9, 'TEV-KRA-001', "Own research. Jacob refuses to be comforted; the opposite of ¶9's sabr jamil; used in the counter-narrative block."),
 'WLC:Gen.37.34': ('rejected', None, None, "Context: Jacob tears his clothes and mourns; covered by 37:35; no independent addition."),
 'WLC:Deut.27.15': ('accepted', 9, 'TEV-SYD-004', "Own research. The people answer 'amen' to each curse; amen as response formula; used at ¶9."),
 'WLC:Jer.28.6': ('accepted', 9, 'TEV-SYD-004', "Own research. 'Amen, so may the LORD do' (אָמֵן כֵּן יַעֲשֶׂה): amen glossed by 'so'; matches ¶9's 'so be it'."),
 'WLC:Jer.13.7': ('accepted', 13, 'TEV-SYD-006', "Own research (hebrew.py root צלח). נִשְׁחַת ... לֹא יִצְלַח לַכֹּל: ruined, good for nothing; ṣlḥ as 'fit/useful' against corruption, matching ¶13."),
 'WLC:Ezek.15.4': ('accepted', 13, 'TEV-SYD-006', "Own research. הֲיִצְלַח לִמְלָאכָה 'is it fit for any work?' of burnt vine wood; ṣlḥ as usefulness for work; used at ¶13."),
 'WLC:Jer.13.10': ('rejected', None, None, "Context: application of the ruined loincloth to the people; repeats 13:7's phrase; no independent addition."),
 'WLC:Ezek.15.5': ('rejected', None, None, "Context of 15:4 (not used for work even when whole); no independent addition."),
 'WLC:Isa.38.1': ('accepted', 18, 'TEV-SYD-007', "Own research. צַו לְבֵיתֶךָ כִּי מֵת אַתָּה: ṣwh for the dying man's charge to his house; parallels ¶18's wasiyya; root link proposed from knowledge, marked unverified in the block."),
 'WLC:Gen.49.33': ('accepted', 18, 'TEV-SYD-007', "Own research. Jacob finishes charging (לְצַוֺּת) his sons and dies; deathbed ṣwh; used at ¶18."),
 'SEFARIA:Pesachim.56a': ('accepted', 20, 'TEV-YGL-001', "Own research (opened, full relevant portion). Resh Lakish: dying Jacob fears a defect in his sons, they answer with the Shema; the Jewish parallel to 2:133 cited at ¶20; Bavli roughly contemporary with the Qur'an."),
 'SEFARIA:Targum_Jonathan_on_Genesis.49.2': ('unavailable', None, None, "Requested for the Shema deathbed scene in the Targum; NOT FOUND in the corpus."),
 'WLC:Lev.10.13': ('accepted', 23, 'TEV-SYD-008', "Own research (hebrew.py root חקק; BDB ḥōq 'a statute or due'). חָקְךָ וְחָק־בָּנֶיךָ 'your due and your sons' due'; due-share sense matching ¶23."),
 'WLC:Prov.30.8': ('accepted', 23, 'TEV-SYD-008', "Own research. לֶחֶם חֻקִּי 'my allotted bread'; ḥq as portion; used at ¶23."),
 'WLC:Prov.25.28': ('accepted', 29, 'TEV-SYD-009', "Own research (hebrew.py root עצר; BDB maʿṣār 'restraint, control', Pr 25:28). A man without restraint over his spirit is a breached city; self-restraint, matching ¶29."),
 'WLC:Exod.8.15': ('accepted', 30, 'TEV-KRA-003', "Own research (WLC numbering = KJV 8:19). Magicians: 'it is the finger of God', Pharaoh does not listen; no belief or patience prayer; used in the ¶30 counter-narrative."),
 'WLC:Gen.44.32': ('accepted', 32, 'TEV-MTF-007', "Own research. 'Your servant became surety (עָרַב) for the boy'; links 43:9 to 44:33; used at ¶32."),
 'SBLGNT:Heb.10.37': ('accepted', 36, 'INC-YGL-001', "Own research. 'The coming one will come and not delay', the Habakkuk wording Hebrews uses between 10:36 and 10:38; used at ¶36."),
 'CORPUSCORANICUM:103:1-3:kommentar': ('rejected', None, None, "Context: Corpus Coranicum editors call v.3 a short virtue catalogue, possibly a later addition, and discuss the market reading of 'asr (Robinson); no Jewish or Christian intertext is attached to 103:3; informs the catalogue framing but not cited."),
}
