import csv, json, collections
csv.field_size_limit(10**9)
CALL = '/Volumes/aro/projects/prose_generation/enrichment/bible/work/s103/ehlikitap.103_1.opus.high.a2'
TSV = '/Volumes/aro/projects/prose_generation/enrichment/bible/work/s103/discovery/s103-20261009/103_1.merged.tsv'

ann = {}
for line in open(CALL + '/annotations.jsonl', encoding='utf-8'):
    if line.strip():
        r = json.loads(line)
        ann[r['id']] = r

def srcs(aid):
    return [s for s in ann[aid]['kaynak'].split('|') if s != 'hafiza']

A = lambda k: 'S103-' + k

# ---- judgement table (my decisions): ref -> (status, reason, paragraphs, evidence, [annotation ids])
# A = accepted, R = rejected, U = unavailable, Q = unresolved
J = {}
def acc(ref, aids, paras, reason, ev=None):
    J[ref] = ('accepted', reason, paras, ev or [ref], [A(a) for a in aids])
def rej(ref, reason, paras=None, ev=None, aids=None):
    J[ref] = ('rejected', reason, paras or [], ev if ev is not None else [ref], [A(a) for a in (aids or [])])
def una(ref, reason):
    J[ref] = ('unavailable', reason, [], [], [])
def unr(ref, reason, aids=None):
    J[ref] = ('unresolved', reason, [], [], [A(a) for a in (aids or [])])

# Non-corpus discovery refs
una('Didache 1:5', 'Didache is not in the intertext corpus (prefetch gap); the not-asking-back of gifts against ¶14 cannot be checked here.')
una('Didache 4:5', 'Didache is not in the corpus (prefetch gap); the open/closed hand point for ¶14 is carried by Deut 15:7-8 instead.')
una('Didache 8:3', 'Didache is not in the corpus (prefetch gap); thrice-daily Lord\'s Prayer cannot be verified; it also fixes no afternoon hour.')
unr('Gregory of Tours, Glory of the Martyrs 1.95', 'Seven Sleepers of Ephesus: the expected Christian parallel to the cave story cited in ¶19, but Gregory of Tours is not in the corpus; kept only as a memory source note (hafiza, unverified).', ['INC-KNT-001'])
unr('Gregory of Tours, Glory of the Martyrs 94', 'Same Ephesus sleepers legend, different numbering of Gregory\'s work; text absent from the corpus; covered only by the memory source note.', ['INC-KNT-001'])
una('Protevangelium of James 8', 'Not in the corpus (prefetch gap); in any case Mary leaving the temple at twelve concerns purity, not the protective keeping of ¶15.')
una('Tertullian, On Prayer 25', 'Tertullian is not in the corpus (prefetch gap); the third/sixth/ninth-hour pattern is attested here instead by Acts 3:1 and 10:30.')
una('1 Maccabees 2:31', '1 Maccabees is not in the corpus (SEFARIA lookup NOT FOUND); wilderness hiding places cannot be checked.')
una('1 Maccabees 2:38', '1 Maccabees is not in the corpus (SEFARIA lookup NOT FOUND); the failed Sabbath refuge cannot be checked.')
una('Tobit 4:9', 'Tobit 4:9 not in the corpus (SEFARIA:Book_of_Tobit.4.9 NOT FOUND).')
rej('Tobit 4:7', 'The fetched Sefaria witness of Tobit 4:7 is a Hebrew recension about Tobit\'s deposited silver, not the alms saying the reader cited; textual mismatch, and alms-giving is only a broad theme here.', ev=['SEFARIA:Book_of_Tobit.4.7'])
rej('Sirach 4:31', 'The Hebrew Ben Sira text at SEFARIA:Ben_Sira.4.31 reads a warning against boastful tongue and slackness, not the open-to-receive/closed-to-give hand of the Greek numbering; witness/numbering mismatch; the hand image is given by Deut 15:7-8.', [14], ['SEFARIA:Ben_Sira.4.31'])
rej('Wisdom of Solomon 3:6', 'keyword-only: testing/refining like gold; no shared image with pressing, time or refuge on this page.', ev=['SEFARIA:The_Wisdom_of_Solomon.3.6'])
acc('Babylonian Talmud, Ta\'anit 23a', ['TEV-MTF-014'], [19], 'Prefetch listed a gap but SEFARIA:Taanit.23a is in the corpus: Honi sleeps seventy years hidden by a rock enclosure and wakes to a generation that does not recognise him; shared motif of long protected sleep and waking into a changed age (¶19).', ['SEFARIA:Taanit.23a'])
acc('Babylonian Talmud, Berakhot 26b', ['TEV-YGL-001'], [2], 'Berakhot 26b says Isaac instituted the minha (afternoon) prayer, reading Gen 24:63 lifnot erev as prayer; Jewish counterpart of a prayer tied to the late part of the day (¶2).', ['SEFARIA:Berakhot.26b'])
acc('Berakhot 26b', ['TEV-YGL-001'], [2], 'Same passage (SEFARIA:Berakhot.26b): Isaac instituted minha from Gen 24:63; supports the afternoon-prayer sense discussed in ¶2.', ['SEFARIA:Berakhot.26b'])
rej('Genesis Rabbah 89:1', None)  # placeholder replaced below
acc('Genesis Rabbah 89:1', ['TEV-YGL-002'], [11], 'Bereshit Rabbah 89:1 reads Job 28:3 as God fixing in advance how many years Joseph would spend in prison darkness; matches ¶11 prison measured by a span.', ['SEFARIA:Bereshit_Rabbah.89.1'])
acc('Genesis Rabbah 89:3', ['TEV-YGL-003'], [12], 'Bereshit Rabbah 89:3: two years were added to Joseph because he said remember me and mention me; a second reason (so Pharaoh would dream) is also given; explains the prolonged wait of ¶12.', ['SEFARIA:Bereshit_Rabbah.89.3'])
acc('Mishnah Avot 2:15', ['TEV-MTF-002'], [5], 'R. Tarfon: the day is short, the work much, the master presses (doheq); shares ¶5\'s late-day narrowing of time for unfinished work.', ['SEFARIA:Pirkei_Avot.2.15'])
rej('Mishnah Avot 2:16', 'Not your duty to finish the work: a sequel to 2:15 about obligation and reward; adds nothing to the late-hour image beyond 2:15.', [5], ['SEFARIA:Pirkei_Avot.2.16'])
rej('Mishnah Avot 3:16', 'Open shop and ledger with collectors: a judgment/credit image; the page has no ledger or credit claim; keyword-only: reckoning.', ev=['SEFARIA:Pirkei_Avot.3.16'])
rej('Mishnah Avot 4:16', 'This world as vestibule: broad eschatological theme; keyword-only: preparation before the end.', ev=['SEFARIA:Pirkei_Avot.4.16'])
rej('Mishnah Avot 4:17', 'One hour of repentance and good deeds better than the world to come: relevant to 103:3 good works, not to an image of ¶1-22 of this page.', ev=['SEFARIA:Pirkei_Avot.4.17'])
rej('Mishnah Avot 5:10', 'Four character types about mine and yours: ethical theme of sharing; the page\'s withholding image (¶14) is carried more concretely by Deut 15:7-8; keyword-only: possession.', [14], ['SEFARIA:Pirkei_Avot.5.10'])
acc('Mishnah Berakhot 4:1', ['TEV-YGL-001'], [2], 'Mishnah fixes the minha prayer until evening (R. Judah: until plag ha-minha); a prayer named for and bounded by the late afternoon, beside ¶2\'s salat al-asr.', ['SEFARIA:Mishnah_Berakhot.4.1'])

# SBLGNT
rej('SBLGNT:1Cor.15.52', 'keyword-only: the blink of an eye (en rhipe ophthalmou); Paul speaks of resurrection change, not of asr as a brief moment.', [5])
acc('SBLGNT:1Cor.7.29', ['INC-MTF-004'], [6], 'ho kairos synestalmenos: time drawn together/shortened as the end nears; shares ¶6\'s narrowing of time at the end.')
rej('SBLGNT:1Pet.1.24', 'All flesh as withering grass: the same morning-evening withering is shown with Ps 90:5-6 in the tevrat layer; no independent addition.', [6])
rej('SBLGNT:1Tim.6.18', 'Generosity exhortation; keyword-only: giving; the page\'s giving image is the pressed flow (¶8, ¶14), not wealth in good works.')
rej('SBLGNT:1Tim.6.19', 'Storing a good foundation for the future: broad theme; no shared image with the stored grain of ¶12-13.')
rej('SBLGNT:2Cor.4.17', 'Light momentary affliction producing glory: general consolation; no shared pressing image with ¶10.')
rej('SBLGNT:2Cor.4.8', 'thlibomenoi (pressed) but not crushed: keyword-only: pressure as affliction; lacks the refuge or extraction element of ¶10 and ¶18.', [18])
rej('SBLGNT:2Cor.9.10', 'Seed and bread supplied to the sower: theme of generosity\'s yield; ¶8\'s rain-chain is better shown by Isa 55:10 which 2 Cor 9:10 echoes.', [8])
rej('SBLGNT:2Cor.9.11', 'Enriched for generosity: broad theme; no shared image.')
rej('SBLGNT:2Cor.9.6', 'Sowing sparingly/bountifully: harvest proverb; no link to pressing, time or refuge on this page.')
rej('SBLGNT:2Tim.4.6', 'Life poured out as a libation: an outpouring image of martyrdom, not the pressed juice as gift of ¶8; keyword-only: pouring.')
acc('SBLGNT:Acts.10.3', ['INC-MTF-001'], [2], 'Cornelius sees the angel about the ninth hour, the hour at which he was praying (10:30); attests a late-afternoon prayer hour (¶2).')
rej('SBLGNT:Acts.10.4', 'Prayers and alms rising as a memorial: no time or pressing element relevant to this page.')
rej('SBLGNT:Eph.5.16', 'Redeeming the time: general exhortation; keyword-only: time.')
rej('SBLGNT:Gal.6.10', 'Do good while we have opportunity: general; covered more concretely by John 9:4 for ¶5.')
rej('SBLGNT:Heb.10.25', 'Encourage as the Day approaches: communal exhortation; keyword-only: nearness of the day.')
acc('SBLGNT:Heb.11.38', ['INC-MTF-009'], [19], 'The persecuted faithful wandered in deserts, mountains and caves; shares the scene of believers taking refuge in caves from a hostile people (¶19, 18:16).')
rej('SBLGNT:Heb.3.11', 'Oath excluding from rest (Ps 95:11): the parallel is the oath-verdict-exception structure of 103:1-3 as a whole, not this ayah page\'s paragraphs; better on the surah or 103:3 page.', [1])
rej('SBLGNT:Heb.3.13', 'Exhort one another while it is called Today: general urgency; keyword-only: today.')
rej('SBLGNT:Heb.3.18', 'Oath against the disobedient: belongs to the exception structure of 103:2-3, not to ¶1\'s oath by time.', [1])
rej('SBLGNT:Heb.3.19', 'Unbelief prevents entry: theme of 103:2-3 exclusion; not a paragraph of this page.')
rej('SBLGNT:Heb.4.3', 'Believers enter the rest: corresponds to the exception of 103:3, outside this page\'s paragraphs.')
rej('SBLGNT:Heb.4.7', 'A day called Today: keyword-only: today.')
acc('SBLGNT:Heb.6.18', ['INC-MTF-008'], [18], 'hoi kataphygontes kratesai: those who fled for refuge to hold fast; joins refuge and firm grasping exactly as ¶17-18 join iltija and imtisak.')
rej('SBLGNT:Heb.6.7', 'Land drinking rain and bearing useful growth: the rain-to-yield chain of ¶8 is given by Eccl 11:3 and Isa 55:10; no independent addition.', [8])
rej('SBLGNT:Heb.6.8', 'Land bearing thorns ends in burning: a judgment of barrenness, not the old man\'s burned garden of ¶21-22; keyword-only: burning.')
rej('SBLGNT:Jas.1.3', 'Testing produces endurance: keyword-only: patience (sabr belongs to 103:3).')
rej('SBLGNT:Jas.4.13', 'Traders planning a year of profit: the page does not make the market reading its claim; keyword-only: gain.')
rej('SBLGNT:Jas.5.2', 'Rotting riches: general theme; no shared image.')
rej('SBLGNT:Jas.5.3', 'Corroded treasure as witness: general theme; no shared image.')
rej('SBLGNT:Jas.5.5', 'Luxury before the day of slaughter: general warning; no shared image.')
rej('SBLGNT:Jas.5.7', 'The farmer waits patiently for early and late rain: keyword-only: patience/harvest; ¶13 does not turn on rain-waiting.')
rej('SBLGNT:John.11.9', 'Twelve hours of daylight: covered by John 9:4 (work before night) for ¶5.', [5])
rej('SBLGNT:John.12.24', 'Grain dying to bear fruit: no shared image with the grain kept in its husk (¶12, ¶15); keyword-only: grain.')
rej('SBLGNT:John.12.3', 'House filled with the ointment\'s fragrance: the trailing-scent point of ¶22 is given by 2 Cor 2:14-15 and Eccl 7:1; this anointing scene adds no independent point.', [22])
rej('SBLGNT:John.15.2', 'Pruning fruitful branches: keyword-only: fruit.')
rej('SBLGNT:John.15.6', 'Withered branch burned: keyword-only: withering/burning; not the whirlwind-fire garden of ¶21.')
rej('SBLGNT:John.15.8', 'Fruit as discipleship: keyword-only: fruit.')
acc('SBLGNT:Luke.12.18', ['INC-MTF-7'.replace('7','007')], [16], 'Rich man pulls down barns to gather all his grain; part of the stored-and-lost harvest scene matched with ¶16.')
rej('SBLGNT:Luke.13.25', 'Householder shuts the door on late-comers: same point as Matt 25:10-12 already used for ¶5.', [5])
rej('SBLGNT:Luke.13.7', 'Three years seeking fruit: the granted-respite image overlaps the 2 Pet 3:9 block on ¶6; no independent addition.', [6])
rej('SBLGNT:Luke.13.9', 'Fruit or cutting down: see Luke 13:7; overlapping.')
acc('SBLGNT:Luke.16.24', ['INC-MTF-005'], [9], 'Rich man asks that Lazarus dip his finger in water and cool his tongue: thirst-dried tongue and the denied sip, the two images of ¶9.')
rej('SBLGNT:Luke.16.25', 'Reversal of fortunes after death: concerns the loss of 103:2, not a paragraph image here.')
acc('SBLGNT:Luke.16.26', ['INC-MTF-005'], [9], 'The fixed chasm makes the requested sip impossible; completes the no-rescuing-sip image of ¶9.')
rej('SBLGNT:Luke.16.9', 'Make friends by mammon: keyword-only: wealth.')
rej('SBLGNT:Luke.19.13', 'Trade until I come: keyword-only: trade; no paragraph claim.')
rej('SBLGNT:Mark.11.20', 'Fig tree withered by morning: keyword-only: withering overnight; ¶16\'s overnight ruin is matched more closely by Luke 12:20.', [16])
rej('SBLGNT:Mark.13.35', 'Evening, midnight, cockcrow, morning: night watches of vigilance, not the asr or the day\'s edges of ¶4.', [4])
rej('SBLGNT:Mark.14.9', 'Deed remembered wherever preached: memory theme; the fragrance trace of ¶22 is given by 2 Cor 2:14-15.', [22])
rej('SBLGNT:Matt.20.12', 'One hour versus the day\'s burden: context within Matt 20 already represented by 20:6-9.', [5])
acc('SBLGNT:Matt.20.6', ['INC-MTF-002'], [5], 'The householder hires idle workers about the eleventh hour, the late part of the day; shares ¶5\'s late hour.')
acc('SBLGNT:Matt.20.8', ['INC-MTF-002'], [5], 'opsias genomenes: when evening came wages were paid; evening as reckoning time, set beside Robinson\'s reading reported by Corpus Coranicum.')
acc('SBLGNT:Matt.20.9', ['INC-MTF-002'], [5], 'Eleventh-hour workers receive a full denarius: a counter-scene to belatedness as loss (¶5); kept as karsit function.')
rej('SBLGNT:Matt.21.34', 'Tenants withholding fruit at harvest time: a different scene (rejected messengers); keyword-only: withheld fruit.')
rej('SBLGNT:Matt.21.41', 'Vineyard given to tenants who render fruit in season: keyword-only: fruit in season.')
rej('SBLGNT:Matt.25.13', 'Unknown day and hour: general vigilance; covered by 25:10-12.')
rej('SBLGNT:Matt.25.27', 'Money with interest: keyword-only: gain.')
rej('SBLGNT:Matt.25.29', 'Taken from the one who has not: keyword-only: loss.')
rej('SBLGNT:Matt.6.19', 'Earthly treasure exposed to moth and theft: broad theme; ¶13 speaks of grain protected in its husk, not heavenly treasure.')
rej('SBLGNT:Matt.6.20', 'Heavenly treasure: broad theme; no shared image.')
rej('SBLGNT:Phil.4.18', 'Gift as fragrant offering: joins gift and fragrance, which this page does not join; keyword-only.')
rej('SBLGNT:Rev.14.19', 'Earth\'s vintage thrown into the winepress of wrath: same judgment image as Joel 4:13 used in the tevrat block on ¶10; an incil block would repeat the point.', [10])
rej('SBLGNT:Rev.14.7', 'Hour of judgment has come: keyword-only: hour.')
rej('SBLGNT:Rev.18.17', 'Wealth laid waste in one hour: imperial judgment on Babylon, not a lifetime\'s yield lost (¶22); keyword-only: one hour.')
rej('SBLGNT:Rev.6.15', 'Kings hide in caves from the Lamb: caves as hiding from God; contrast is general and adds no element to ¶19\'s prayer in the refuge.', [19])
rej('SBLGNT:Rev.6.16', 'Asking rocks to hide them: see Rev 6:15.', [19])

# WLC
rej('WLC:1Kgs.17.13', 'Widow gives the last cake first: generosity under scarcity; keyword-only: giving.')
rej('WLC:1Kgs.17.16', 'Flour and oil do not fail: keyword-only: provision in drought.')
rej('WLC:1Kgs.18.44', 'Small cloud; contains ya\'atsorkha ha-geshem (lest the rain stop you) but the cloud-to-rain point of ¶8 is carried by Deut 11:17 and Eccl 11:3; no independent addition.', [8])
rej('WLC:1Kgs.18.45', 'Heavens darken with clouds and wind, great rain: drought-breaking narrative; no shared pressing image.', [8])
rej('WLC:1Kgs.19.9', 'Elijah lodges in a cave: refuge in a cave is given by Ps 142:1,6 with prayer; this verse adds no prayer or time element.', [19])
rej('WLC:1Kgs.21.3', 'Naboth keeps his ancestral land: keyword-only: retaining.')
rej('WLC:1Sam.21.8', None)
acc('WLC:1Sam.21.8', ['TEV-SYD-003'], [14], 'ne\'tsar lifne YHWH: Doeg detained before the LORD; the Hebrew root\'s detaining sense matches ¶14\'s asr = habs, ma asaraka.')
acc('WLC:2Chr.7.13', ['TEV-SYD-001'], [8], 'he e\'etsor ha-shamayim ve-lo yihye matar: the root used of heaven withholding rain; reverse of the pressed rain clouds of ¶8.')
rej('WLC:2Kgs.4.24', 'al ta\'atsar li lirkov: do not slow down the riding; the root is present (the wording finding is a segmentation artefact) but the sense hinder adds nothing beyond 1 Sam 21:8.', [14])
rej('WLC:2Kgs.4.4', 'Closed door and pouring oil: keyword-only: closing/pouring.')
rej('WLC:2Kgs.4.7', 'Sell oil, pay debt: keyword-only: provision.')
rej('WLC:Amos.4.7', 'Rain withheld (mana\'ti) three months before harvest: different verb; the withheld-rain point is given by Deut 11:17 with the cognate root.', [8])
rej('WLC:Amos.8.4', 'Those who trample the needy: social-justice theme; ¶16\'s exclusion of the poor is matched by Deut 24:19-21.', [16])
rej('WLC:Amos.8.5', 'Merchants impatient for new moon/sabbath to end: keyword-only: waiting for sacred time to pass.')
rej('WLC:Amos.8.6', 'Buying the poor for silver: social-justice theme; no shared image.')
rej('WLC:Amos.8.9', 'Sun set at noon: darkening at midday as judgment; no asr or day-edge claim of this page.')
rej('WLC:Amos.9.13', 'Ploughman overtakes reaper, treader overtakes sower: abundance image without pressing-as-gift or calendar claim of ¶13; keyword-only: treading grapes.')
rej('WLC:Dan.12.12', 'Blessed is he who waits 1335 days: keyword-only: waiting.')
rej('WLC:Dan.6.10', 'Textual: WLC Dan 6:10 is the king signing the decree (MT numbering); the thrice-daily prayer is WLC Dan 6:11, which was opened and also rejected (three times, not the two day-edges of ¶4).', [4])
rej('WLC:Deut.15.10', 'Give without a grudging heart: covered by 15:7-8 in the ¶14 block.', [14])
rej('WLC:Deut.15.14', 'Furnish the freed slave from threshing floor and winepress (yeqev): giving from the press, but the ¶14 hand image is already given by 15:7-8; adds the press only as a keyword.', [14])
rej('WLC:Deut.24.13', 'Return the pledge cloak at sunset: sunset as deadline, but no asr image; keyword-only: sunset.')
rej('WLC:Deut.24.15', 'Pay the wage before sunset: day-end reckoning, but the evening wage scene is represented by Matt 20:8; no independent addition.', [5])
acc('WLC:Deut.24.19', ['TEV-MTF-011'], [16], 'Forgotten sheaf left for stranger, orphan, widow: harvest with the poor\'s share, the reverse of the garden owners\' oath to exclude the poor (¶16).')
acc('WLC:Deut.24.21', ['TEV-MTF-011'], [16], 'Grapes not gleaned a second time, left for the poor: the vineyard counterpart of 24:19 for ¶16.')
rej('WLC:Deut.32.1', 'Heaven and earth summoned to hear: a witness formula, not an oath by a created thing; keyword-only.', [1])
rej('WLC:Eccl.11.6', 'Sow in the morning, do not rest at evening: day-edge work advice; covered by John 9:4 and Avot 2:15 for ¶5.', [5])
acc('WLC:Eccl.12.1', ['TEV-MTF-017'], [22], 'Remember your Creator before the evil days and unwanted years of old age; opens the old-age-as-darkening passage used for ¶22.')
acc('WLC:Eccl.7.1', ['TEV-MTF-18'.replace('18', '018')], [22], 'tov shem mi-shemen tov: good name better than fine oil, with the day of death; the trace left behind measured by fragrance (¶22).')
rej('WLC:Eccl.8.8', 'No one rules the wind or the day of death: keyword-only: wind/death.')
rej('WLC:Eccl.9.10', 'Do what you can, for there is no work in Sheol: same point as John 9:4 on ¶5; no independent addition.', [5])
rej('WLC:Exod.15.25', 'Bitter water made sweet: keyword-only: bitterness (sabr as bitter aloe in ¶10 is a different image).', [10])
rej('WLC:Exod.16.20', 'Kept manna spoils: keyword-only: keeping.')
rej('WLC:Exod.16.24', 'Manna kept for Sabbath does not spoil: keyword-only: keeping.')
acc('WLC:Exod.29.39', ['TEV-MTF-001'], [4], 'Daily lamb in the morning and the second ben ha-arbayim: a dual time-word for the day\'s closing edge and worship tied to the two ends of the day (¶4).')
acc('WLC:Ezek.19.12', ['TEV-MTF-016'], [21], 'Vine plucked up, the east wind dried its fruit, fire consumed its rods: vine, wind and fire ending the yield, as in 2:266 (¶21).')
acc('WLC:Ezek.19.14', ['TEV-MTF-016'], [21], 'Fire went out from its branch and devoured its fruit: completes the vine-wind-fire image for ¶21.')
acc('WLC:Gen.16.2', ['TEV-SYD-003'], [14], 'atsarani YHWH mi-ledet: the LORD has restrained me from bearing; the root\'s withholding range for ¶14.')
rej('WLC:Gen.20.18', 'Wombs closed: same withholding sense as Gen 16:2 (used); the link to the girl kept at menarche (¶15) is keyword-only: closing.', [15])
acc('WLC:Gen.24.63', ['TEV-YGL-001'], [2], 'Isaac went out lasuah ba-sadeh lifnot arev; Berakhot 26b reads this as the institution of the afternoon prayer (¶2).')
acc('WLC:Gen.40.13', ['TEV-PRL-001'], [11], 'Within three days Pharaoh will restore the cupbearer: the rescue of the dreamer that ¶11 links to asr as manjat.')
acc('WLC:Gen.40.15', ['TEV-PRL-001'], [11], 'Joseph: I was stolen and have done nothing to be put in the pit; innocence in prison, as in ¶11.')
rej('WLC:Gen.40.19', 'The baker\'s fate: ¶11 discusses only the cupbearer; context only.', [11])
acc('WLC:Gen.41.14', None, None, None) if False else None
rej('WLC:Gen.41.14', 'Joseph brought hastily out of the pit: context for the release; no independent addition to ¶12.', [12])
acc('WLC:Gen.41.29', ['TEV-KRA-002'], [13], 'Seven years of great plenty announced: first half of the Genesis calendar compared in ¶13.')
acc('WLC:Gen.41.30', ['TEV-KRA-002'], [13], 'Seven famine years follow: Genesis ends the forecast with famine, no year of relief and pressing (¶13).')
rej('WLC:Gen.41.31', 'Plenty forgotten in famine: context of 41:30; no independent addition.', [13])
acc('WLC:Gen.41.35', ['TEV-KRA-002'], [13], 'Grain heaped (ve-yitsberu) in cities under Pharaoh\'s hand: storage in cities, not in the ear as in 12:47 (¶13). Its tsavar is also cited in the elenen block, which is linked by the rejected Gen 41:49 soydas connections.')
acc('WLC:Gen.41.36', ['TEV-KRA-002'], [13], 'Food as a deposit for the seven famine years: the reserve plan compared in ¶13.')
rej('WLC:Gen.41.47', 'Land produced by handfuls: context of the plenty; no independent addition.', [13])
acc('WLC:Gen.41.48', ['TEV-KRA-002'], [13], 'Joseph gathered food and put it in the cities: storage location differs from the Qur\'anic leave-it-in-the-ear (¶12-13).')
acc('WLC:Gen.41.5', ['TEV-PRL-002'], [12], 'Seven full ears on one stalk: Pharaoh\'s dream shared with 12:43 (¶12).')
acc('WLC:Gen.41.6', ['TEV-PRL-002'], [12], 'Seven thin ears blasted by the east wind: the dry ears of 12:43 (¶12).')
acc('WLC:Gen.41.9', ['TEV-PRL-002'], [12], 'Cupbearer: I remember my faults today; the delayed remembering of ¶12 (12:45).')
acc('WLC:Gen.45.6', ['TEV-KRA-002'], [13], 'Five more years without ploughing or harvest: Genesis\' calendar ends in famine, without the year of relief and pressing of 12:49 (¶13).')
rej('WLC:Gen.41.56', 'Joseph opens the stores: context of distribution; no independent addition to ¶13.', [13])
rej('WLC:Gen.6.14', 'Ark compartments: keyword-only: enclosure/refuge.')
rej('WLC:Gen.7.16', 'The LORD shut him in: refuge enclosure without the prayer/time element of ¶19; keyword-only: shut in.', [19])
rej('WLC:Gen.8.13', 'Dated drying of the flood: keyword-only: time in a shelter.')
rej('WLC:Gen.8.2', 'Rain restrained (yikkale) after the flood: different root; the withheld-rain point uses Deut 11:17.', [8])
rej('WLC:Hag.1.10', 'Heavens withhold dew (kal\'u): different root; covered by Deut 11:17.', [8])
rej('WLC:Hag.1.6', 'Wages into a bag with holes: keyword-only: bag; the page\'s bag is the grape-press bag of ¶7.', [7])
rej('WLC:Hos.8.7', 'Sow wind, reap whirlwind (sufa): keyword-only: whirlwind; no garden/fire scene.', [20])
rej('WLC:Isa.16.10', 'No treader treads in the presses: cessation of joy; keyword-only: winepress.', [7])
acc('WLC:Isa.17.13', ['TEV-MTF-015'], [20], 'Peoples chased like chaff before wind and like a whirling thing before the storm: the wind that whirls and drives, beside Song 4:16\'s scent-bearing wind (¶20).')
rej('WLC:Isa.2.19', 'Men enter caves for fear of the LORD: caves as hiding from God; general contrast without the prayer-in-refuge element of ¶19.', [19])
rej('WLC:Isa.27.3', 'The LORD guards and waters his vineyard: keyword-only: vineyard/protection.')
rej('WLC:Isa.5.2', 'Vineyard with a hewn wine vat that yields wild grapes: a parable of moral failure; the page\'s garden (¶21-22) is lost by wind and fire, not by bad fruit; keyword-only: vineyard/vat.', [21])
rej('WLC:Isa.5.5', 'Vineyard hedge removed: see Isa 5:2.')
rej('WLC:Isa.5.6', 'Clouds commanded not to rain on the vineyard: withheld rain with a different verb; covered by Deut 11:17.', [8])
rej('WLC:Isa.5.7', 'Vineyard as Israel, justice expected: allegorical key of Isa 5; not a claim of this page.')
acc('WLC:Isa.55.10', ['TEV-MTF-006'], [8], 'Rain and snow water the earth, make it bring forth and sprout, giving seed and bread: the rain-to-yield chain named in ¶8.')
rej('WLC:Isa.59.17', 'Righteousness as breastplate: keyword-only: armour (¶17 maasir).', [17])
acc('WLC:Isa.63.3', ['TEV-MTF-009'], [10], 'The LORD treads the winepress alone, peoples trodden: judgment as pressing, the contrasting image beside ¶10.')
acc('WLC:Isa.65.8', ['TEV-MTF-005'], [8], 'Do not destroy the cluster, for a blessing is in it: the juice within the grape as blessing, close to pressed juice as image of good in ¶8.')
rej('WLC:Isa.66.9', 'Shall I cause to bring forth and restrain (ve-atsarti)? Root present; same withholding sense as Gen 16:2; no independent addition.', [14])
acc('WLC:Jer.6.4', ['TEV-MTF-003'], [5], 'Woe, the day has turned, the evening shadows lengthen: late afternoon as time running out (¶5).')
rej('WLC:Job.1.19', 'Great wind kills Job\'s children in the house: the wind destroys the children, whereas 2:266 destroys the garden while the children are weak; different scene.', [21])
rej('WLC:Job.14.5', 'Fixed limit of human days: broad theme; covered by Ps 90.', [6])
rej('WLC:Job.14.6', 'Like a hireling until his day ends: day-labourer image overlaps Avot 2:15 and Matt 20 on ¶5.', [5])
acc('WLC:Job.24.11', ['TEV-MTF-007'], [9], 'They tread winepresses and suffer thirst: pressing and thirst in one scene, beside ¶9\'s dried tongue.')
rej('WLC:Job.27.16', 'yitsbor ka-afar kasef: heaps up silver like dust; tsavar heap only, a false friend for sabr; no addition beyond the elenen block.', [10])
rej('WLC:Job.38.37', 'Who can tip the water-jars of heaven: cloud-as-vessel image, but Eccl 11:3 states the filling and emptying more directly; no independent addition.', [8])
rej('WLC:Job.38.38', 'Dust fused into clods: keyword-only: dust.')
rej('WLC:Job.7.6', 'Days swifter than a shuttle: broad transience theme; keyword-only.')
rej('WLC:Joel.1.14', 'Call a solemn assembly (atsara): the assembly sense of the root has no counterpart in the Arabic senses this page develops; false friend.', [14])
rej('WLC:Joel.2.15', 'Call an assembly (atsara): see Joel 1:14; false friend for this page.', [14])
rej('WLC:Joel.2.24', 'Vats overflow with wine and oil: abundance after rain; overlapping Isa 65:8/Isa 55:10; no independent addition.', [8])
acc('WLC:Joel.4.13', ['TEV-MTF-009'], [10], 'The press is full, the vats overflow, for their wickedness is great: humans pressed as grapes at the end, the contrasting image for ¶10.')
rej('WLC:Jonah.4.6', 'A plant shades Jonah: keyword-only: shelter.')
acc('WLC:Judg.13.15', ['TEV-SYD-003'], [14], 'na\'tsera na otakh: let us detain you (for a meal); the root is present (the wording finding reflects a prefix segmentation); detaining sense for ¶14.')
rej('WLC:Judg.6.11', 'Gideon threshes wheat in a winepress to hide it: hiding grain, but not the husk-protection of ¶12/¶15; keyword-only: winepress.')
rej('WLC:Lev.15.19', 'Menstrual impurity for seven days: purity law; ¶15 speaks of keeping the girl protected, not impurity; keyword-only: menstruation.', [15])
rej('WLC:Lev.19.13', 'Wage not kept overnight: day-end payment; represented by Matt 20:8.', [5])
rej('WLC:Lev.23.36', 'atseret: the closing festival assembly; the root\'s assembly sense is a false friend for the senses of this page (no pressing, refuge or time-edge sense).', [14])
rej('WLC:Mal.3.10', 'Windows of heaven opened to pour blessing: tithing promise; keyword-only: pouring blessing.')
rej('WLC:Mal.3.11', 'Devourer rebuked, vine not barren: keyword-only: vine protected.')
rej('WLC:Nah.1.3', 'His way in whirlwind and storm, clouds the dust of his feet: theophany; dust/whirlwind image without the garden or scent element of ¶20; Isa 17:13 used instead.', [20])
rej('WLC:Num.14.23', 'Oath excluding the generation from the land: belongs to the oath-exception structure of 103:1-3 as a whole (surah or 103:3 page).', [1])
rej('WLC:Num.14.24', 'Caleb as the exception: corresponds to 103:3, outside this page.')
rej('WLC:Num.17.13', 'va-te\'atsar ha-magefa: the plague was stopped; root present, sense halting, no independent addition to ¶14.', [14])
rej('WLC:Num.27.7', 'Daughters inherit: keyword-only: inheritance.')
rej('WLC:Num.35.25', 'City of refuge until the high priest\'s death: refuge bound to a lifespan, but no shared prayer, sleep or grip element with ¶17-19; keyword-only: refuge.', [17])
rej('WLC:Prov.10.25', 'As the whirlwind passes the wicked is gone: proverb; keyword-only: whirlwind.')
acc('WLC:Prov.11.24', ['TEV-MTF-010'], [14], 'One scatters yet increases; one withholds and comes to want: the outcome of the gripping versus open hand (¶14).')
rej('WLC:Prov.11.25', 'The generous soul is enriched: overlapping 11:24; no independent addition.', [14])
acc('WLC:Prov.11.26', ['TEV-MTF-010'], [14], 'Who withholds grain, the people curse him: withholding produce, the stinginess of ¶14.')
rej('WLC:Prov.14.26', 'Children have a refuge: keyword-only: refuge.')
rej('WLC:Prov.3.27', 'Do not withhold good: overlapping Deut 15:7-8.', [14])
rej('WLC:Prov.3.28', 'Do not delay giving until tomorrow: keyword-only: delay.')
rej('WLC:Prov.30.4', 'Who gathered wind in his fists, bound waters in a garment: grip of wind and water, but a cosmic riddle; no claim of this page.')
rej('WLC:Ps.1.3', 'Tree yielding fruit in season: keyword-only: fruit.')
rej('WLC:Ps.1.4', 'Chaff driven by wind: keyword-only: wind.')
acc('WLC:Ps.102.12', ['TEV-MTF-003'], [5], 'yamay ke-tsel natuy: my days like a lengthening shadow; life measured by the late-afternoon shadow (¶5).')
rej('WLC:Ps.104.23', 'Man goes to his labour until evening: covered by Avot 2:15 and Jer 6:4 for ¶5.', [5])
acc('WLC:Ps.105.18', ['TEV-YGL-002'], [11], 'Joseph\'s feet hurt with fetters: the confinement whose term 105:19 sets (¶11).')
acc('WLC:Ps.105.19', ['TEV-YGL-002'], [11], 'ad et bo devaro: until the time his word came; the prison measured by a time (¶11).')
rej('WLC:Ps.126.5', 'Sow in tears, reap in joy: keyword-only: harvest after hardship.')
rej('WLC:Ps.141.3', 'Textual: WLC Ps 141:3 is set a guard over my mouth; the incense/evening offering is 141:2 (opened, rejected separately).', [2, 20])
acc('WLC:Ps.142.6', ['TEV-MTF-013'], [19], 'atta mahsi: you are my refuge, in the psalm headed as a prayer in the cave (¶19).')
rej('WLC:Ps.144.4', 'Days like a passing shadow: same image as Ps 102:12, which is used.', [5])
rej('WLC:Ps.39.6', 'Handbreadth of days: broad transience theme; covered by Ps 90.', [6])
rej('WLC:Ps.39.7', 'yitsbor: heaps up without knowing who gathers; tsavar heap only, false friend for sabr.', [10])
acc('WLC:Ps.46.2', ['TEV-MTF-012'], [18], 'God our refuge, help in tsarot (straits, root tsrr tightness): refuge for the pressed, as in ¶18.')
rej('WLC:Ps.55.18', 'Evening, morning and noon: three stations, not the two day-edges of ¶4; no independent addition beyond Exod 29:39.', [4])
rej('WLC:Ps.65.11', 'Rain softens furrows: rain-chain covered by Isa 55:10.', [8])
rej('WLC:Ps.65.12', 'Year crowned with goodness: keyword-only: good year.')
rej('WLC:Ps.90.10', 'Seventy or eighty years pass swiftly: general; the Ps 90 block uses 90:4-6,12.', [6])
rej('WLC:Ps.90.11', 'Textual: 90:11 asks who knows the power of your anger; the seventy-years statement is 90:10.', [6])
acc('WLC:Ps.90.12', ['TEV-MTF-004'], [6], 'Teach us to number our days: the given span to be counted, as with 35:37 in ¶6.')
acc('WLC:Ps.90.4', ['TEV-MTF-004'], [6], 'A thousand years like yesterday when past: time shrinking when seen from its end (¶6).')
acc('WLC:Ps.90.5', ['TEV-MTF-004'], [6], 'Swept away as a sleep, in the morning like grass: the morning half of the morning/evening life image (¶6, 79:46).')
rej('WLC:Ps.90.7', 'Textual: 90:7 is consumed by your anger; the morning-flourish/evening-wither line is 90:6, opened and used instead.', [6])
rej('WLC:Ps.92.15', 'Fruitful in old age: keyword-only: old age.')
rej('WLC:Ps.92.3', 'Morning and nights praise: pair formula, but adds nothing beyond Exod 29:39 for ¶4.', [4])
rej('WLC:Ps.95.11', 'Oath that they shall not enter my rest: oath-exception structure belongs to the surah or 103:3 page.', [1])
rej('WLC:Ruth.2.12', 'Refuge under his wings: keyword-only: refuge.')
rej('WLC:Ruth.2.15', 'Ruth gleans among sheaves: narrative instance of the gleaning law; Deut 24:19-21 carries the point for ¶16.', [16])
rej('WLC:Ruth.2.16', 'Extra stalks left for Ruth: see Ruth 2:15.', [16])
acc('WLC:Song.4.16', ['TEV-MTF-015'], [20], 'Awake north wind, blow on my garden that its spices flow: wind carrying fragrance, the scent pole of ¶20.')
rej('WLC:Zech.10.1', 'Ask rain in the season of latter rain: keyword-only: rain clouds.')

# Per-connection overrides (same ref, different reasons)
OV = {}
def ov(cid, status, reason, paras, aids, ev=None):
    OV[cid] = (status, reason, paras, ev, [A(a) for a in aids])

# 2Cor.2.14 / 2.15 (four ids) all accepted
for cid, r in [('BC-aecdd94515d03ab85726', 'osmen tes gnoseos phanerounti en panti topo: fragrance spread wherever the apostles go; scent left behind movement (¶22).'),
               ('BC-d7e591f1d9a546a46775', 'Fragrance of knowing Christ made perceptible through his messengers: a sweet trace left by those who pass (¶22).'),
               ('BC-2c660aedae69689c879a', 'Christou euodia among the saved and the perishing: one aroma, two ends; set beside the dust-or-scent contrast of ¶22.'),
               ('BC-77e24f7a66634db018cd', 'The community as the aroma of Christ: a person\'s fragrant trace (¶22).')]:
    ov(cid, 'accepted', r, [22], ['INC-MTF-010'])
ov('BC-661de42652d09f94df3d', 'accepted', '2 Pet 3:8 applies Ps 90:4\'s thousand years as a day to the asked-about coming of the Lord; Christian reading of Ps 90 for ¶6.', [6], ['INC-YGL-001'])
ov('BC-7bf5a2f79c62a5193fd4', 'accepted', 'One day as a thousand years: the time-scale reversal; placed on ¶6 (not on the cave sleepers of ¶19, where it would be keyword-only).', [6], ['INC-YGL-001'])
ov('BC-a6e447d7dece0e237e20', 'accepted', 'The Lord is not slow but patient, wanting all to reach repentance: remaining time as respite (¶6, 35:37).', [6], ['INC-YGL-001'])
ov('BC-8492885f5c13c6f38405', 'rejected', 'Reading Joseph\'s delayed relief and the sleepers\' interval as purposive waiting: not what 2 Pet 3:9 addresses; keyword-only: delay.', [12, 19], [])
ov('BC-22c52cefdce464a7cef6', 'accepted', 'Peter and John go to the temple at the ninth hour, the hour of prayer: a prayer hour in the late afternoon (¶2).', [2], ['INC-MTF-001'])
ov('BC-0ad5e283c08ac20a4627', 'accepted', 'The ninth hour explicitly called the hour of prayer (¶2).', [2], ['INC-MTF-001'])
ov('BC-2fa20dbe51a6b7f65822', 'rejected', 'Shield of faith quenching fiery darts: keyword-only: armour/protection (¶17 maasir).', [17], [], ['SBLGNT:Eph.6.16'])
ov('BC-943d666bf0b9cf1dde27', 'rejected', 'Shield against flaming darts: keyword-only: armour and fire; no shared scene with ¶17 or ¶21.', [17], [], ['SBLGNT:Eph.6.16'])
ov('BC-576b95ca19adbb4feaf4', 'rejected', 'Do not tire of doing good, harvest in due season: keyword-only: patience/harvest.', [13], [], ['SBLGNT:Gal.6.9'])
ov('BC-fe4bb594846398bdfdc9', 'rejected', 'Harvest in due season if we do not give up: general exhortation; keyword-only.', [13], [], ['SBLGNT:Gal.6.9'])
ov('BC-62158a6e4efae873a26f', 'rejected', 'Life a vapour appearing briefly: broad transience theme; Ps 90 carries ¶6 concretely.', [6], [], ['SBLGNT:Jas.4.14'])
ov('BC-10715db0007202f5fc62', 'rejected', 'Tomorrow unknown, life a vapour: keyword-only: brevity.', [6], [], ['SBLGNT:Jas.4.14'])
ov('BC-eb250aa8631c05f298ba', 'rejected', 'Withheld wages of harvesters cry out: withholding from labourers; ¶14 and ¶16 are carried by Deut 15:7-8 and Deut 24:19-21; no independent addition.', [14, 16], [], ['SBLGNT:Jas.5.4'])
ov('BC-93599e2184eeae0daf03', 'rejected', 'Retained wages: see the other Jas 5:4 connection; overlapping.', [14], [], ['SBLGNT:Jas.5.4'])
ov('BC-e704cb50bfbd80e80501', 'accepted', 'Work while it is day, night comes when no one can work: the closing of the day on unfinished work (¶5).', [5], ['INC-MTF-003'])
ov('BC-9371cf6f1bf457996369', 'accepted', 'Shrinking daylight and unfinished work: same verse, same point (¶5).', [5], ['INC-MTF-003'])
ov('BC-f94f3fa710ac9425895a', 'accepted', 'This night your life is required: the stored harvest lost overnight; set on ¶16 (garden ruined while the owners sleep).', [16], ['INC-MTF-007'])
ov('BC-06777f72f2be6e570c48', 'accepted', 'Stores for many years, life required tonight: placed on ¶16.', [16], ['INC-MTF-007'])
ov('BC-7e0aeb7c0a2ac4b0bb2c', 'accepted', 'Storing for oneself, not rich toward God: the retained harvest of ¶16.', [16], ['INC-MTF-007'])
ov('BC-a0d7a5eee31d9d6afa1c', 'accepted', 'Treasure amassed for oneself: closes the stored-harvest parable used on ¶16.', [16], ['INC-MTF-007'])
ov('BC-c9f1823946e6d1bcead0', 'rejected', 'One more year for the fig tree: granted-respite point overlaps 2 Pet 3:9 on ¶6; the old owner of ¶22 has no respite scene.', [6, 22], [], ['SBLGNT:Luke.13.8'])
ov('BC-aea625d4916f050c7b66', 'rejected', 'Final productive interval: overlapping 2 Pet 3:9; no independent addition.', [6], [], ['SBLGNT:Luke.13.8'])
ov('BC-7ca2dcf6342eeb69f0a1', 'accepted', 'metron pepiesmenon: a pressed-down measure running over as gift; pressing that flows outward (¶14).', [14], ['INC-MTF-006'])
ov('BC-3b7020331075a2a8d5db', 'accepted', 'Compression making the gift overflow: same verse, same point (¶14).', [14], ['INC-MTF-006'])
ov('BC-c5e49ae5f3c7e1a6e947', 'accepted', 'Late bridesmaids find the door shut: belatedness as irreversible loss (¶5).', [5], ['INC-MTF-003'])
ov('BC-5ac2eedbfbbe92e1cf31', 'rejected', 'Shelter preserving those inside: the wedding door is not a refuge scene; keyword-only: shut door (¶19).', [19], [], ['SBLGNT:Matt.25.10'])
ov('BC-b09b3c6696740911c993', 'rejected', 'Delayed bridegroom, all sleep: sleeping waiters are not the protected long sleep of ¶19 nor the lateness of ¶5 (the late arrival is 25:10).', [5, 19], [], ['SBLGNT:Matt.25.5'])
ov('BC-b0084cf1af9a5b60efd4', 'rejected', 'Delay and sleep: see the other Matt 25:5 connection.', [5], [], ['SBLGNT:Matt.25.5'])
ov('BC-373ddaff3577cecc92b1', 'accepted', 'Angel swears that there will be no more time/delay: time as the content of an oath, set against time as the object of the oath in 103:1 (¶1).', [1], ['INC-KRA-001'])
ov('BC-987579fc5d55fd386833', 'accepted', 'Oath by the eternal creator about time: the difference from swearing by time itself (¶1).', [1], ['INC-KRA-001'])
ov('BC-48715a93a719549cb4c0', 'rejected', 'Blood from the trodden winepress: same judgment image as Joel 4:13 (tevrat block on ¶10); would repeat the point.', [10], [], ['SBLGNT:Rev.14.20'])
ov('BC-277790adee8c90e94d1b', 'rejected', 'Winepress trodden outside the city: see the other Rev 14:20 connection.', [10], [], ['SBLGNT:Rev.14.20'])
ov('BC-eb03098dc80742805361', 'accepted', 'Short day, much work, pressing master: the late-afternoon narrowing of ¶5.', [5], ['TEV-MTF-002'])
ov('BC-c70d09aee24c85941786', 'accepted', 'Late working time with a day\'s pay and a pressing master: same saying, accepted as motif on ¶5.', [5], ['TEV-MTF-002'])
ov('BC-d9696ac9e8e0a96c25ac', 'rejected', 'Prayer when heaven is shut: the prayer-time link is not made by this verse; its relevance is the root (separate soydas connection).', [2, 8], [], ['WLC:1Kgs.8.35'])
ov('BC-0c2f4bf700f5b0093d10', 'accepted', 'behe\'atser shamayim ve-lo yihye matar: heaven restrained with no rain; the cognate root\'s use opposite to the pressed rain clouds of ¶8.', [8], ['TEV-SYD-001'])
ov('BC-03746be2dfa7d8792a94', 'accepted', 'Heaven shut up (atsar) and no rain: same verse and point (¶8).', [8], ['TEV-SYD-001'])
ov('BC-ad1e64b01278cfa911d9', 'rejected', 'Oath not to forget merchants who trample the needy: the garden owners\' oath of ¶16 is matched by Deut 24:19-21; this reading of Amos 8:7 is a theme link.', [16], [], ['WLC:Amos.8.7'])
ov('BC-d091cdc8084a3b6bb3f7', 'accepted', 'The LORD swears by the pride of Jacob before a verdict: a divine oath by something named, whose referent is debated; cited in the ¶1 block on the object of divine oaths.', [1], ['TEV-KRA-001'])
ov('BC-25f799e3eaf7e8586b00', 'accepted', 'The man in linen swears by him who lives forever and gives a measured period: time as the oath\'s content, not its object (¶1).', [1], ['TEV-KRA-001'])
ov('BC-c86520951413b4395b67', 'accepted', 'Oath by the eternal one at the threshold of an end: same verse, used on ¶1.', [1], ['TEV-KRA-001'])
ov('BC-f18c535b7b158c8cc4d8', 'accepted', 've-atsar et ha-shamayim ve-lo yihye matar: the cognate root\'s withholding of rain against the pressed clouds of ¶8.', [8], ['TEV-SYD-001'])
ov('BC-c0377b4de284dd8673d1', 'accepted', 'Heaven restrained, land without yield: same verse and point (¶8).', [8], ['TEV-SYD-001'])
ov('BC-7433dcb43ed68ae134cf', 'accepted', 'lo tiqpots et yadekha: do not shut your hand against the poor; the closed grip of ¶14.', [14], ['TEV-MTF-010'])
ov('BC-6c0bf64f81f537d9352a', 'accepted', 'Shutting the hand against the poor kinsman: ¶14 (the garden owners of ¶16 are matched separately by Deut 24).', [14], ['TEV-MTF-010'])
ov('BC-b3c34db0581b5da0e6c3', 'accepted', 'patoah tiftah et yadekha: open your hand; the releasing grip of ¶14.', [14], ['TEV-MTF-010'])
ov('BC-7a003592dfa334cdb97b', 'accepted', 'Open hand to the needy: same verse and point (¶14).', [14], ['TEV-MTF-010'])
ov('BC-6a559adbe4471c86e7d1', 'accepted', 'Sun and light darken as old age comes: the evening of life of ¶22.', [22], ['TEV-MTF-017'])
ov('BC-344cfb9febba176a7eb0', 'accepted', 'Waning light and returning clouds for life\'s evening: same verse, ¶22.', [22], ['TEV-MTF-017'])
ov('BC-7c989f1429a8d3086ae5', 'rejected', 'Wombs closed linked to the girl kept at menarche (¶15): keyword-only: closing; the root\'s range is shown with Gen 16:2.', [15], [], ['WLC:Gen.20.18'])
ov('BC-0d6856eb5ff757b399aa', 'rejected', 'Wombs closed with atsar: duplicates Gen 16:2 in the ¶14 soydas block.', [14], [], ['WLC:Gen.20.18'])
ov('BC-17611fd38db9d8ad07dd', 'accepted', 'The cupbearer\'s prison dream: grapes pressed (va-eshhat) into Pharaoh\'s cup; same scene as 12:36 (¶11), with a different Hebrew verb.', [11], ['TEV-PRL-001'])
ov('BC-7f8e2b166e79b942ae93', 'accepted', 'Pressing grapes into the cup he will serve: same verse (¶11).', [11], ['TEV-PRL-001'])
ov('BC-4a701e5dddcc1962def5', 'accepted', 've-hizkartani el Par\'o: Joseph\'s request to be remembered, as in 12:42 (¶11).', [11], ['TEV-PRL-001'])
ov('BC-f4a884d4ae301ad016bb', 'accepted', 'Remember me and bring me out of this house: same verse (¶11).', [11], ['TEV-PRL-001'])
ov('BC-a32eb47a1057fa3e9028', 'accepted', 'The restored cupbearer did not remember Joseph and forgot him: as in ¶12.', [12], ['TEV-PRL-002'])
ov('BC-c072bc26d541a29b6615', 'accepted', 'Forgotten remembrance prolongs confinement: same verse (¶12).', [12], ['TEV-PRL-002'])
ov('BC-6bc8ba105f96a65bc632', 'accepted', 'miqqets shenatayim yamim: two full years before Pharaoh dreams; Genesis\' exact span against the Qur\'an\'s bid\'a sinin (¶12).', [12], ['TEV-PRL-002'])
ov('BC-8b715332fc08ea0d7a15', 'accepted', 'Two full years: same verse (¶12).', [12], ['TEV-PRL-002'])
ov('BC-0dde1c8042d47ad17ab5', 'rejected', 'Joseph heaped (va-yitsbor) grain: tsavar means heap only; the patience/bitter-extract sense of sabr is absent; false friend, kept as an elenen block.', [10], ['TEV-ELN-001'], None)
ov('BC-90043d8d186d697ceeb5', 'rejected', 'Consonantal meeting of tsavar with sabr in the storage scene: a sound match only, the senses differ; recorded in the elenen block.', [10], ['TEV-ELN-001'], None)
ov('BC-4b5778eeff046d459c37', 'accepted', 'Seven plentiful years end: part of the Genesis calendar compared in the ¶13 counter-narrative.', [13], ['TEV-KRA-002'])
ov('BC-7a66aa3cf7c2a9107a82', 'accepted', 'Completion of the plenty before scarcity: same verse (¶13).', [13], ['TEV-KRA-002'])
ov('BC-9eadbe6a06caa45ff340', 'accepted', 'Famine begins, Egypt still has bread: Genesis\' calendar continues into famine (¶13).', [13], ['TEV-KRA-002'])
ov('BC-0cec54d4ccd9c8d22b2d', 'accepted', 'Seven famine years began: same verse (¶13).', [13], ['TEV-KRA-002'])
ov('BC-3625e3b928de275b44ec', 'rejected', 'All lands come to buy grain: distribution context; the Genesis calendar point uses 41:53-54 and 45:6; no independent addition.', [13], [], ['WLC:Gen.41.57'])
ov('BC-881a1a4d3900cbcdd30a', 'rejected', 'Grain sold abroad heard as asr-gain: keyword-only: gain.', [13], [], ['WLC:Gen.41.57'])
ov('BC-ff7f0aba9090dadce7b0', 'accepted', 'Treading the winepress with stained garments: judgment as pressing, contrasting the extraction image of ¶10.', [10], ['TEV-MTF-009'])
ov('BC-9dd029e4d1b5d128f050', 'accepted', 'The speaker treads the winepress alone: same verse (¶10).', [10], ['TEV-MTF-009'])
ov('BC-b8a9bd4026e333386faa', 'rejected', 'Wind collapses the house on Job\'s children: in 2:266 the wind destroys the garden while the children are weak; different scene.', [21], [], ['WLC:Job.1.19'])
ov('BC-f8750c7d382504749303', 'rejected', 'Great wind kills the children: see the other Job 1:19 connection.', [21], [], ['WLC:Job.1.19'])
ov('BC-c10e7873eb8f9ad14ab8', 'accepted', 'hen ya\'tsor ba-mayim ve-yivashu: he holds back the waters and they dry up, sends them and they overturn the earth; holding versus releasing (¶14).', [14], ['TEV-SYD-003'])
ov('BC-9f29e6abdf8406c33558', 'accepted', 'Restraining waters dries, sending floods: same verse, holding and releasing (¶14).', [14], ['TEV-SYD-003'])
ov('BC-cb9cce4049d0549ab1c2', 'rejected', 'atseret (assembly) on the eighth day: the assembly sense is a false friend for this page.', [14], [], ['WLC:Lev.23.36'])
ov('BC-c80a6cf174aef37bfb62', 'rejected', 'Closing assembly heard as day-edge and holding together: the page develops no assembly sense; false friend.', [4], [], ['WLC:Lev.23.36'])
ov('BC-13e969627b38f3b29832', 'rejected', 'Textual: the incense and evening-offering line is Ps 141:2, not 141:3; 141:2 opened and rejected as adding nothing to the minha/ninth-hour blocks on ¶2.', [2], [], ['WLC:Ps.141.3', 'WLC:Ps.141.2'])
ov('BC-52f9a14e186ebaf70afc', 'rejected', 'Prayer rising like incense linked to scent rising (¶20): wrong verse (141:2 not 141:3) and keyword-only: rising fragrance.', [20], [], ['WLC:Ps.141.3', 'WLC:Ps.141.2'])
ov('BC-5874e93e8357490ff2d3', 'rejected', 'Evening, morning and noon prayer: three stations, not the two edges of ¶4.', [4], [], ['WLC:Ps.55.18'])
ov('BC-65790a0f0b29b61703c6', 'rejected', 'Three temporal stations: see the other Ps 55:18 connection.', [4], [], ['WLC:Ps.55.18'])
ov('BC-d2abb1f57bdfa2a25368', 'rejected', 'Boaz as near kinsman and redeemer: keyword-only: kinship (¶17 unsur).', [17], [], ['WLC:Ruth.2.20'])
ov('BC-bbaa2d41019793b3e6d3', 'rejected', 'Kinship as refuge: keyword-only.', [17], [], ['WLC:Ruth.2.20'])
ov('BC-d1cb6c98cb1f07782ae5', 'accepted', 'Winds blow on the garden so its spices flow: wind and fragrance together (¶20).', [20], ['TEV-MTF-015'])
ov('BC-2dc8d822bd06f59bdd93', 'accepted', 'Scent lifted by wind as against storm dust: same verse (¶20).', [20], ['TEV-MTF-015'])

# placeholders fixed
J['WLC:Gen.40.11'] = ('accepted', 'see overrides', [11], ['WLC:Gen.40.11'], [A('TEV-PRL-001')])
J['SBLGNT:Luke.12.19'] = ('accepted', 'Goods laid up for many years: the rich man\'s plan whose end is that night (¶16).', [16], ['SBLGNT:Luke.12.19'], [A('INC-MTF-007')])
J['SBLGNT:Luke.12.18'] = ('accepted', 'Rich man pulls down barns to gather all his grain: the stored harvest of ¶16.', [16], ['SBLGNT:Luke.12.18'], [A('INC-MTF-007')])
J['WLC:Eccl.7.1'] = ('accepted', 'tov shem mi-shemen tov: a good name better than fine oil, beside the day of death; the trace left behind measured by fragrance (¶22).', [22], ['WLC:Eccl.7.1'], [A('TEV-MTF-018')])

# ---- research (own lookups, not in the discovery list)
R = []
def res(ref, status, reason, paras, aids, ev=None):
    R.append((ref, status, reason, paras, aids, ev))
res('CORPUSCORANICUM:103:1-3:kommentar', 'accepted', 'Corpus Coranicum (Sinai) prefers Robinson\'s reading of asr as end-of-market-day reckoning and leaves Neuwirth\'s prayer-time reading open; cited in the ¶2 minha block and the ¶5 Matt 20 block.', [2, 5], ['TEV-YGL-001', 'INC-MTF-002'], ['CORPUSCORANICUM:103:1-3:kommentar'])
res('CORPUSCORANICUM:103:1:anmerkung', 'rejected', 'Editors\' note: asr probably a specific time of day rather than time in general; context for the kommentar; no Jewish or Christian text is attached (no intertext entries for 103:1).', [2], [])
res('WLC:Gen.22.16', 'accepted', 'bi nishba\'ti ne\'um YHWH: God swears by himself; the object of the divine oath differs from 103:1 (¶1).', [1], ['TEV-KRA-001'])
res('SBLGNT:Heb.6.13', 'accepted', 'Since he had no one greater to swear by, he swore by himself: the Christian reading of Gen 22:16 used on ¶1.', [1], ['INC-KRA-001'])
res('WLC:Exod.12.6', 'accepted', 'Passover lamb slaughtered ben ha-arbayim: second attestation of the dual day-edge term (¶4).', [4], ['TEV-MTF-001'])
res('SBLGNT:Acts.10.30', 'accepted', 'Cornelius: I was praying at the ninth hour in my house; the ninth-hour prayer (¶2).', [2], ['INC-MTF-001'])
res('WLC:Ps.90.6', 'accepted', 'In the morning it flourishes, in the evening it fades and withers: the morning/evening life image (¶6); the discovery cited 90:7 in error.', [6], ['TEV-MTF-004'])
res('SBLGNT:2Pet.3.4', 'accepted', 'Scoffers ask where the promise of his coming is: the asked-about Hour, answered by 3:8-9 (¶6).', [6], ['INC-YGL-001'])
res('SBLGNT:Matt.25.11', 'accepted', 'The other virgins come later and say Lord, open to us: the late arrival (¶5).', [5], ['INC-MTF-003'])
res('SBLGNT:Matt.25.12', 'accepted', 'I do not know you: the door stays shut on the late-comers (¶5).', [5], ['INC-MTF-003'])
res('WLC:Isa.41.17', 'accepted', 'leshonam ba-tsama nashatta: their tongue is parched with thirst, and the LORD will answer them; the dried tongue of ¶9.', [9], ['TEV-MTF-007'])
res('WLC:Lam.4.4', 'rejected', 'The suckling\'s tongue cleaves for thirst: same image as Isa 41:17, which is used; no independent addition.', [9], [])
res('WLC:Eccl.11.3', 'accepted', 'If the clouds are full of rain they empty it on the earth: cloud as a vessel that is emptied, beside the pressed clouds of ¶8.', [8], ['TEV-MTF-006'])
res('WLC:Job.26.8', 'rejected', 'He binds up waters in his clouds and the cloud is not split: cloud holding water; the holding point is made with the cognate root elsewhere; no independent addition.', [8], [])
res('WLC:Prov.30.33', 'accepted', 'Pressing (mits) milk brings butter, pressing the nose blood, pressing anger strife: pressure brings out what is within (¶10).', [10], ['TEV-MTF-008'])
res('WLC:Gen.40.9', 'accepted', 'The cupbearer tells his dream: a vine before him (¶11).', [11], ['TEV-PRL-001'])
res('WLC:Gen.40.10', 'accepted', 'Three branches, blossoms, clusters ripen into grapes: the dream preceding the pressing (¶11).', [11], ['TEV-PRL-001'])
res('WLC:Gen.40.12', 'rejected', 'The three branches are three days: interpretive detail; context only, 40:13 carries the outcome.', [11], [])
res('WLC:2Kgs.17.4', 'accepted', 'va-ya\'atsrehu melekh Ashshur va-ya\'asrehu bet kele: the root used for confining a prisoner; supports ¶11\'s link of holding and imprisonment.', [11], ['TEV-SYD-002'])
res('WLC:Jer.33.1', 'accepted', 'Jeremiah atsur in the court of the guard: detained/confined with the same root (¶11).', [11], ['TEV-SYD-002'])
res('WLC:Gen.39.20', 'accepted', 'Joseph put in bet ha-sohar: Genesis names Joseph\'s prison with other words, not atsar (¶11).', [11], ['TEV-SYD-002'])
res('WLC:Judg.13.16', 'accepted', 'If you detain me (ta\'tsereni) I will not eat your bread: detaining sense (¶14).', [14], ['TEV-SYD-003'])
res('WLC:Exod.8.10', 'rejected', 'Frogs heaped (va-yitsberu) in heaps: tsavar heap; confirms the false-friend judgement for sabr; no block.', [10], [])
res('WLC:Ps.142.1', 'accepted', 'Maskil of David when he was in the cave, a prayer: prayer in the cave of refuge (¶19).', [19], ['TEV-MTF-013'])
res('WLC:Ezek.19.10', 'accepted', 'Your mother was like a vine planted by waters, fruitful: the watered vine whose ruin follows (¶21).', [21], ['TEV-MTF-016'])
res('SBLGNT:Luke.12.16', 'accepted', 'The land of a rich man produced plentifully: opening of the stored-harvest parable (¶16).', [16], ['INC-MTF-007'])
res('SBLGNT:Luke.12.17', 'accepted', 'Where shall I gather my fruits: the hoarding plan (¶16).', [16], ['INC-MTF-007'])
res('SBLGNT:Matt.20.7', 'rejected', 'No one hired us; go into the vineyard: context of 20:6; no independent addition.', [5], [])
res('WLC:Ps.141.2', 'rejected', 'Prayer as incense, lifted hands as minhat arev: the evening offering bridges offering and prayer, but the ¶2 point is carried by Mishnah Berakhot 4:1 and Berakhot 26b; no independent addition.', [2], [])
res('WLC:Dan.6.11', 'rejected', 'Daniel prays three times a day toward Jerusalem: three stations, not the two edges of ¶4 or an afternoon hour (¶2).', [2, 4], [])
res('SEFARIA:Ben_Sira.4.31', 'rejected', 'Hebrew Ben Sira at this locator warns against a boastful tongue and slackness; it does not carry the open-to-receive/closed-to-give hand of the Greek numbering; witness/numbering mismatch.', [14], [])
res('SEFARIA:Berakhot.26b', 'accepted', 'Isaac instituted the minha (afternoon) prayer, reading Gen 24:63 lifnot erev as prayer; supports the ¶2 afternoon-prayer block.', [2], ['TEV-YGL-001'])
res('SEFARIA:Bereshit_Rabbah.89.1', 'accepted', 'Reads Job 28:3 as God fixing how many years Joseph would spend in prison darkness; prison measured by a span (¶11).', [11], ['TEV-YGL-002'])
res('SEFARIA:Bereshit_Rabbah.89.3', 'accepted', 'Two years added to Joseph for saying remember me and mention me, with a second reason (Pharaoh\'s dream); explains the prolonged wait of ¶12.', [12], ['TEV-YGL-003'])
res('SEFARIA:Book_of_Tobit.4.7', 'rejected', 'This Hebrew recension of Tobit 4:7 concerns Tobit\'s deposited silver, not the alms saying cited by the reader; textual mismatch.', [], [])
res('SEFARIA:Mishnah_Berakhot.4.1', 'accepted', 'Fixes the minha prayer until evening (R. Judah: until plag ha-minha); a prayer bounded by the late afternoon (¶2).', [2], ['TEV-YGL-001'])
res('SEFARIA:Pirkei_Avot.2.15', 'accepted', 'R. Tarfon: the day is short, the work much, the master presses; the late-day narrowing of ¶5.', [5], ['TEV-MTF-002'])
res('SEFARIA:Pirkei_Avot.2.16', 'rejected', 'Not your duty to finish the work: sequel to 2:15 about obligation and reward; no independent addition to ¶5.', [5], [])
res('SEFARIA:Pirkei_Avot.3.16', 'rejected', 'Open shop and ledger with collectors: credit/judgment image; the page makes no ledger claim; keyword-only: reckoning.', [], [])
res('SEFARIA:Pirkei_Avot.4.16', 'rejected', 'This world as vestibule to the world to come: broad eschatological theme; keyword-only.', [], [])
res('SEFARIA:Pirkei_Avot.4.17', 'rejected', 'One hour of repentance and good deeds: concerns the good works of 103:3, not an image of this page.', [], [])
res('SEFARIA:Pirkei_Avot.5.10', 'rejected', 'Four character types (mine and yours): sharing theme; ¶14 withholding is carried more concretely by Deut 15:7-8.', [14], [])
res('SEFARIA:Taanit.23a', 'accepted', 'Honi sleeps seventy years hidden by a rock enclosure and wakes to a generation that does not recognise him; long protected sleep (¶19).', [19], ['TEV-MTF-014'])
res('SEFARIA:The_Wisdom_of_Solomon.3.6', 'rejected', 'Righteous tested like gold in a furnace: keyword-only: testing; no shared pressing, time or refuge image.', [], [])
for ref in ['SEFARIA:Book_of_Tobit.4.9', 'SEFARIA:The_Book_of_Maccabees_I.2.31', 'SEFARIA:Ben_Sira.4.36', 'SEFARIA:Rashi_on_Exodus.12.6', 'SEFARIA:Onkelos_Genesis.40.11', 'SEFARIA:Rashi_on_Leviticus.23.36', 'SEFARIA:Rashi_on_Genesis.40.11', 'SEFARIA:Onkelos_Genesis.41.49']:
    res(ref, 'unavailable', 'corpus get returned NOT FOUND; the text is not in the local SEFARIA cache (not fetched for this page).', [], [], [])

# ---- assemble
rows = list(csv.DictReader(open(TSV, encoding='utf-8'), delimiter='\t'))
out = []
seen = set()
problems = []
for r in rows:
    ev = json.loads(r['evidence'])
    for e in ev:
        cid = e['connection_id']
        if cid in seen:
            continue
        seen.add(cid)
        ref = r['ref']
        if cid in OV:
            st, reason, paras, evd, aids = OV[cid]
            if evd is None:
                evd = J[ref][3] if ref in J else [ref]
        elif ref in J:
            st, reason, paras, evd, aids = J[ref]
        else:
            problems.append(('NO JUDGEMENT', cid, ref))
            continue
        if reason is None:
            problems.append(('NO REASON', cid, ref))
        evid = list(evd)
        paras = list(paras)
        for a in aids:
            for s in srcs(a):
                if s not in evid:
                    evid.append(s)
            if ann[a]['paragraf'] not in paras:
                paras.append(ann[a]['paragraf'])
        out.append({'connection_id': cid, 'ref': ref, 'status': st, 'reason': reason, 'paragraphs': paras, 'evidence': evid, 'annotations': aids})
for ref, st, reason, paras, aids, ev in R:
    aids = [A(a) for a in aids]
    evid = list(ev) if ev is not None else [ref]
    for a in aids:
        for s in srcs(a):
            if s not in evid:
                evid.append(s)
    out.append({'connection_id': None, 'origin': 'research', 'ref': ref, 'status': st, 'reason': reason, 'paragraphs': paras, 'evidence': evid, 'annotations': aids})

PREFETCH = '/Volumes/aro/projects/prose_generation/enrichment/bible/work/s103/discovery/s103-20261009/prefetch.json'
pf = json.load(open(PREFETCH, encoding='utf-8'))
missing_sources = list(pf['missing'])
for o in out:
    if o['status'] == 'unavailable' and not o['ref'].startswith('SEFARIA:') and o['ref'] not in missing_sources:
        missing_sources.append(o['ref'])
missing_sources += [
    'Peshitta (Syriac Old and New Testament): not in the intertext corpus; no Syriac cognate or Peshitta wording checked',
    'Patristic and Syriac homiletic texts (Jacob of Serugh, Ephrem, Gregory of Tours on the Seven Sleepers): not in the corpus',
    'Septuagint: not in the corpus; Greek of Sirach 4:31 and Tobit 4:7-9 could not be checked against the Hebrew Sefaria witnesses',
    'Targum and classical Jewish commentary (Onkelos, Rashi) on Gen 40-41, Exod 12:6, Lev 23:36: not fetched for this page (prefetch limitation: Sefaria links of WLC candidates were not fetched)',
]
not_found = [o['ref'] for o in out if o['status'] == 'unavailable' and o['ref'].startswith('SEFARIA:')]
unresolved = [o['ref'] for o in out if o['status'] == 'unresolved']
gaps = {'missing_sources': missing_sources, 'not_found': not_found, 'unresolved': unresolved,
        'notes': ['Prefetch listed Babylonian Talmud, Ta\'anit 23a as a gap, but SEFARIA:Taanit.23a is in the corpus and was used.',
                  'Prefetch resolved Sirach 4:31 and Tobit 4:7 to Hebrew Sefaria witnesses whose text at those locators does not carry the cited sayings; numbering/recension mismatch, rejected on textual grounds.',
                  'Corpus Coranicum lists no intertext entries for 103:1; only the editors\' Anmerkung and Kommentar were available.',
                  'Seven Sleepers of Ephesus parallel (¶19) kept only as a memory source note (hafiza, unverified).']}
with open(CALL + '/gaps.json', 'w', encoding='utf-8') as f:
    json.dump(gaps, f, ensure_ascii=False, indent=1)

linked = set(a for o in out for a in o['annotations'])
missing = [a for a in ann if a not in linked]
bad = [a for a in linked if a not in ann]
with open(CALL + '/verdicts.jsonl', 'w', encoding='utf-8') as f:
    for o in out:
        f.write(json.dumps(o, ensure_ascii=False) + '\n')
print('verdicts', len(out), 'connections', len(seen), 'problems', problems)
print('unlinked annotations', missing, 'unknown annotation ids', bad)
print(collections.Counter(o['status'] for o in out))
